### ISSUE TITLE
Fix unity build workflow

### ISSUE THREAD

**Issue by boscohyun** [planetarium/NineChronicles#1737]
The unity logo should not appeared at the intro scene of unity player.
This issue is occurred from https://github.com/planetarium/NineChronicles/pull/1700 I guess.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/6128868/180700163-73be0d03-dd5c-4294-80dc-08c2b576b86b.png">

**Comment by moreal** [comment]
<img width="1072" alt="image" src="https://github.com/planetarium/NineChronicles/assets/26626194/34c4db50-6ed1-4201-b9f3-7cae1568ce67">

It seems fixed 🤔
