### ISSUE TITLE
Migrate broken `AvatarState`s related with issue #1925

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles#1932]
Related with #1925 

- [x] Prepare Action hex of `MigrationAvatarState`
  - https://www.notion.so/planetarium/2022-09-15-257e4c9712f34d2dbcd9cf7165c386a6
- [x] Signing and broadcasting signed Tx to 9c main-net  w/ @longfin

**Comment by boscohyun** [comment]
@longfin This approach has been failed.

### Course

- The fields `Inventory`, `WorldInformation`, `QuestList` of the `AvatarState` are already empty in the blockchain.
- The process to migrate `AvatarState` from v1 to v2  contains set serialized `AvatarState` by `AvatarState.SerializeV2()` method to blockchain.
- So the action hex in [here](https://www.notion.so/planetarium/2022-09-15-257e4c9712f34d2dbcd9cf7165c386a6) has been failed with `NullRefereceException`.

**Comment by longfin** [comment]
We need to find the block index when that avatar's info had been broken.

**Comment by boscohyun** [comment]
We can see the last `HackAndSlash` execution was contained to 720,113 block in [9c scan](https://9cscan.com/avatar/0xCC2570cFf8aEa5F9D907552c95D452Aded8818d9).(Tue Feb 02 2021 10:22:46 GMT+0900)

The last `HackAndSlash` Tx: [hack_and_slash4](https://9cscan.com/tx/6f126fb2e0aed19edff7f728d475ec884eff041d25f0ff915828fe3f349e8dba)
  - World Id: 1
  - Stage Id: 47

**Comment by boscohyun** [comment]
### Broken `AvatarState`

| index \ address hex | AgentState / exist in blockchain | AvatarState / exist in blockchain | Inventory / exist in blockchain | WorldInfomation / exist in blockchain | QuestList / exist in blockchain | block index | tx link |
| --: | --- | --- | --- | --- | --- | --- | --- |
| 1 | f189C04126E2E708Cd7D17CD68a7B7f10Bbb6f16 / y | cc2570cff8aea5f9d907552c95d452aded8818d9 / y | 79948eabe8Dfe795F0515D0908Fd1f1dC5f3C51f / y | 13346332C92F2d4ab3E20A0876dD927BcD1d8fFe / n | d086bfd9FFBc2AcbF5BADa291CDD6b48554fbe49 / y | [4753873](https://9cscan.com/blocks/4753873) | [hack_and_slash_sweep5](1-tx-link)
| 2 | c58721640d11af1f5332be723c95ad1d83fdd05f / y | 4a3a41755Ff9dcC76D3c1cE112e18F9691A4f644 / y | a7B1f99861B856A1601736DD94d0e819a40BB0Ef / y | 39253320B1785F8b4e6971Cf6169954E30f24E25 / n | fFcA0bf395f955c3888547926685e777E9a2386A / y | [4901527](https://9cscan.com/blocks/4901527) | [claim_stake_reward][2-tx-link]
| 3 | c58721640d11af1f5332be723c95ad1d83fdd05f / y | EC19Bf2bDa7900Ba98fEa61332CE53A7c3474514 / y | 643Db06Cd8024d61042cc2cF98B7DaCefD7A7843 / y | 8661A9448beb2fF03fbAFA73dAf2E090D110881e / n | 209d2AAEE745Fea469090d4b8b6EFBE09c2cb97F / y | [4901517](https://9cscan.com/blocks/4901517) | [hack_and_slash_sweep6][3-tx-link]
| 4 | c58721640d11af1f5332be723c95ad1d83fdd05f / y | 4bC933F2C7D54445133473f33E0eC38049635710 / y | 0bc0a820f7663B938bDD279d8A0491A185694074 / y | cAf3a120b0F47F8C5d5c7262b8208527b5244F9B / n | 428cCA56b74A63e5af6E2454c88aE7de0c442856 / y | [4901520](https://9cscan.com/blocks/4901520) | [hack_and_slash_sweep6][4-tx-link]

[1-tx-link]: https://9cscan.com/tx/e5fd2957137b46fabeb19f71a395caaa5f200766f2174c2177f7b0dfb967ef32
[2-tx-link]: https://9cscan.com/tx/f62ca0d352c61afe92cf73a8d45392165b06387883353b69a0e99ed0391dcfa2
[3-tx-link]: https://9cscan.com/tx/90ae200d1768ed091816532d1c5d5cf186a0f04c448e0af60c0f11691db8f427
[4-tx-link]: https://9cscan.com/tx/7d421062f3d0e66c7cf4ad181cde1355fcad596d2dce10ff461d62b0f9b3821e

**Comment by boscohyun** [comment]
### Select snapshots for each broken `AvatarState`

| index | tx | block | snapshot |
| --: | --- | --- | --- |
| 1 | [hack_and_slash_sweep5](1-tx-link) | [4753873](https://9cscan.com/blocks/4753873)
| 2 | [claim_stake_reward][2-tx-link] | [4901527](https://9cscan.com/blocks/4901527)
| 3 | [hack_and_slash_sweep6][3-tx-link] | [4901517](https://9cscan.com/blocks/4901517)
| 4 | [hack_and_slash_sweep6][4-tx-link] | [4901520](https://9cscan.com/blocks/4901520)

[1-tx-link]: https://9cscan.com/tx/e5fd2957137b46fabeb19f71a395caaa5f200766f2174c2177f7b0dfb967ef32
[2-tx-link]: https://9cscan.com/tx/f62ca0d352c61afe92cf73a8d45392165b06387883353b69a0e99ed0391dcfa2
[3-tx-link]: https://9cscan.com/tx/90ae200d1768ed091816532d1c5d5cf186a0f04c448e0af60c0f11691db8f427
[4-tx-link]: https://9cscan.com/tx/7d421062f3d0e66c7cf4ad181cde1355fcad596d2dce10ff461d62b0f9b3821e

**Comment by boscohyun** [comment]
We published a transaction to resolve this issue.([view in 9cscan](https://9cscan.com/tx/a203b66e6bd9e662b4746044eda4c65fc64231399653a468bd1b1070eafe213f))
