### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by boscohyun** [planetarium/NineChronicles#2089]
Unity provide Apple Silicon version of Unity editor now. But NineChronicles(i.e., 9c-unity) does not supported.

- [x] Secp256K1.Net
- [ ] Shader errors

**Comment by longfin** [comment]
Glad to hear that!

@boscohyun Is there any migration guide or checklist for existing projects to support Apple Silicon?

**Comment by boscohyun** [comment]
Hm.. I could not find something like migration guide(or checklist) posted by Unity. There are just [this thread](https://forum.unity.com/threads/installing-the-native-apple-silicon-editor.1188253/) on Unity forum?
There is [a Unity building guide for OSX](https://docs.unity3d.com/Manual/macos-building.html).
And.. There is [a porting guide](https://developer.apple.com/documentation/apple-silicon/porting-your-macos-apps-to-apple-silicon) posted by Apple.

So I will just switching the target platform of my Unity editor to macOS(Apple silicon), and then troubleshooting step by step.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/6128868/199407809-0b5ceda6-f9b6-453d-9ae2-331cc055b885.png">
