### ISSUE TITLE
Unable to perform any action in game.

### ISSUE THREAD

**Issue by PoohVz** [planetarium/NineChronicles#213]
Description: This is an old issue that happens rarely sometimes, and when it happens, players can't perform any action in-game, it could be stuck at the loading screen for hours or result in error 26-28.
Normal trouble doesn't resolve the issue and sometimes it's fixed by itself after a while.

Users with the issue: 
HotSauce#0725
Kojackcheese#9718
APOLLO#8106

Logs:
From APOLLO: [logs.zip](https://github.com/planetarium/NineChronicles/files/6520287/logs.zip)

Will update more logs later when users upload it.

**Comment by PoohVz** [comment]
Mushroom | Axie.gg 🌿#9560 

[logs.zip](https://github.com/planetarium/NineChronicles/files/6527514/logs.zip)

**Comment by longfin** [comment]
> Vinje#3976
> 
> [main(2).log](https://github.com/planetarium/NineChronicles/files/6539775/main.2.log)

There is too many transaction ids that broadcasted from other node. usually, it can be a sign that the block is not being synchronized properly. I'll continue to investigate about block synchronization delaying.

**Comment by PoohVz** [comment]
YoinkedGaming#2928
[logs.zip](https://github.com/planetarium/NineChronicles/files/6589877/logs.zip)

**Comment by longfin** [comment]
We've updated [v100048](https://wiki.nine-chronicles.com/en/9C/patch-notes#v100048) to address this issue. I'll continue to monitoring timeout and block sync status.
