### ISSUE TITLE
Client stuck after entering arena preparation

### ISSUE THREAD

**Issue by osamadeep** [planetarium/NineChronicles#2145]
Hello, 
this issue reported many times and still not fixed in the OC, 

![NOWIDGES](https://user-images.githubusercontent.com/13297843/204661480-8dedff29-c6fd-40db-a610-62e0b9a3ddf6.png)

Desc:
no widges rendered and you need to close the client

Steps to get the error:
1 - enter UI_ArenaBoard
2 - select taget (Enter UI_ArenaBattlePreparation)
3 - return to UI_ArenaBoard (not attack)
4 - select attack again (Enter UI_ArenaBattlePreparation)
5 - error cause

what the problem:
the _player Spine is pointing wrong 

how to solve: 
https://github.com/planetarium/NineChronicles/blob/3cb6808bedd7e9009ea402079fddece04d34b3f5/nekoyume/Assets/_Scripts/UI/Widget/ArenaBattlePreparation.cs#L242
after prevoius line destroy the player gameobject. or set it null

Final code:

`            if (!(_player is null))
            {
                _player.gameObject.SetActive(false);
                _player = null;
            }`

**Comment by sonohoshi** [comment]
Thank you for the reporting! If you don't mind, could you upload this as a Pull Request?
