### ISSUE TITLE
Quest UI doesn't show for the new world update

### ISSUE THREAD

**Issue by PoohVz** [planetarium/NineChronicles#221]
Cleared stage 201 and unlocked a new recipe and the Quest UI should show the quest that asks you to craft the new recipe but it didn't.
![image](https://user-images.githubusercontent.com/13524523/119483436-2a1d6d80-bd7f-11eb-928b-e73634fb8899.png)

Another old bug: 
I'm level 210 and this quest is still not done yet.
![image](https://user-images.githubusercontent.com/13524523/119483794-8c766e00-bd7f-11eb-88d8-f23bf1851bab.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200502992455763) by [Unito](https://www.unito.io)

**Comment by PoohVz** [comment]
Update: The quest suddenly appear now for me
![image](https://user-images.githubusercontent.com/13524523/120076143-4d715100-c0ce-11eb-9648-f53f04605d1a.png)

**Comment by hskim881028** [comment]
https://github.com/planetarium/lib9c/pull/461
