### ISSUE TITLE
Error 14 happens after running the stage for few times.

### ISSUE THREAD

**Issue by PoohVz** [planetarium/NineChronicles#223]
User reported: torotoro#9921
Address: 0x23a70D8D60A4e3b4d8eDb6793Eb7127d49876208

He said that he cleared stage 202 for 3 times and whenever he tries stage 203, error 14 will appear.
This could happen due to reorg but he said that after restarting the game, it reverses all the way back to stage 200, and after a bit stage 202 unlock again. 
And when he tried to do stage 202 again, error 14 appears, then after a bit, he is able to join stage 202 without error.

My only explanation for this is because he tried to do stage 203 multiple times, so there are multiple nonces, and because of reorg, some of them are being shown a bit later on.
And when he tried to join stage 202 again, the error appears cuz the block that contain the error message got reorg'ed.

Not sure if I was correct so I will just provide the logs and some related txid
[main.zip](https://github.com/planetarium/NineChronicles/files/6540503/main.zip)
e9e74ea15a2bbb01c459fd1285ef0c3dde74707d7da63da798b9706c062073a2
4b89ae3d1d07c8f06d273b7c8472d690c713ec5bf023d0b3f685441bafdd561f
99155e5f77137fb73747af81bef1de757e1b37e328e78ff21d7b45e4d7af0f7e
a0cc30f0c87e0035e9737295248b8feee184863e2c8995d004f693ac44f10f1a
c09feeb6497db1e47cde53e568bc7304022fc4d21bc3b27a576c6d0345b3a773
d377e5e901ca60177cb596ef245fa42ad52223e177a1d7a0a711c8bdaf55a4df

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200503065308068) by [Unito](https://www.unito.io)

**Comment by ipdae** [comment]
Hello @PoohVz . i found `HackAndSlash4` action failed log between the block indexes 1547900 to 1547920(About 10 minutes between 11:45 pm and 54 pm KST on May 25th). I think, it seems different execution result cause of from reorg.

**Comment by PoohVz** [comment]
I was thinking it has something to do with reorg too. It's similar when you try to do arena for more than 5 times, and the error message will keep showing up for a while, until the error isn't in an orphan block anymore
