### ISSUE TITLE
Provide icon assets through GitHub Pages

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles#2262]
Currently, third-party users can use icon assets by:

 - Add `NineChronicles` repository as a submodule and extract icon from there.
   - It makes project hard to clone.
 - Fetch icon items from `https://github.com/planetarium/NineChronicles/raw/main/PATH/TO/ITEM/ICON/*.png`.
   - NineChronicles developer can break the structure. And it's hard to find where icons are.

But I think they are hard to use even though they just wanted to use only icons. So I want to suggest to provide icons through GitHub Pages (static page).

Examples:
 - Hourglass icon: `https://planetarium.github.io/NineChronicles/icons/items/400000.png`
 - ApStone icon: `https://planetarium.github.io/NineChronicles/icons/items/500000.png`

**Comment by osamadeep** [comment]
good suggestion
