### ISSUE TITLE
using AP stone for Grind after reach AP to 0

### ISSUE THREAD

**Issue by osamadeep** [planetarium/NineChronicles#2381]
![image](https://user-images.githubusercontent.com/13297843/220567458-90951cbf-f86b-4296-9b54-13c36d20abd1.png)

issue: when your action points reach 0, and try to use potions after pressing OK button, nothing happens, just the popup message hidden,

issue mainly in this method: 
https://github.com/planetarium/NineChronicles/blob/2287f31729cbbc5a5a1c70a743c8f1b341bd7292/nekoyume/Assets/_Scripts/UI/Module/GrindModule.cs#L416

**Comment by sonohoshi** [comment]
It will be fix at v100370. thx for your reporting! ref: https://github.com/planetarium/NineChronicles/pull/2374
