### ISSUE TITLE
AP potion doesn't sync properly with UI

### ISSUE THREAD

**Issue by PoohVz** [planetarium/NineChronicles#256]
Step to reproduce:

1. Use AP potion
1. The AP bar will be filled instantly
1. Wait for few minutes
1. The AP bar will be empty again.

The UI will be fixed when you restart the game, but for players who don't know about this, they will keep using another AP potion and wasting them.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200502991561614) by [Unito](https://www.unito.io)

**Comment by ipdae** [comment]
We will add a step to check the AP in the `ChargeActionPoint` as well.
