### ISSUE TITLE
User often cannot use hourglasses to speed up craft

### ISSUE THREAD

**Issue by CosminSh** [planetarium/NineChronicles#273]
The adress of the user is 0xC0bA278CB8379683E66C28928fa0Aa8bfF3D95E6 and the character is Wabbs.
I have a Leather Belt Wind that I cannot speed up - it says that the item is done but it's not appearing in the inventory. After the reset of the client, it's still crafting
I restarted the game multiple times, I cleared the cache. Same results.

I can speed up other crafts just fine, this is the only item that is not working

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200503064555568) by [Unito](https://www.unito.io)

**Comment by PoohVz** [comment]
I can't speed up my craft also, normally there will be an email straight away, but there is none
![image](https://user-images.githubusercontent.com/13524523/121424759-e724e200-c99b-11eb-9702-f7b8a51befa0.png)

**Comment by Namyujeong** [comment]
사용해야 하는 모래시계가 많은 아이템에서만(ex.챕터2에서 추가된 아이템들) 에서 주로 문제가 발생하는 것 같다는 제보가 있습니다.
https://discord.com/channels/539405872346955788/653951482395361301/856531587129671712
