### ISSUE TITLE
Sometimes Ranking page not working

### ISSUE THREAD

**Issue by PoohVz** [planetarium/NineChronicles#283]
![image](https://user-images.githubusercontent.com/13524523/121801376-318ab500-cc61-11eb-8cf6-76a9d481934a.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200503122468598) by [Unito](https://www.unito.io)

**Comment by longfin** [comment]
@PoohVz Thanks for reporting.

Is this symptom intermittent or continuous? A known problem is that the message is not displayed correctly when the backend service(https://api.9c.gg) fails. (it will be fixed on the next release)

**Comment by PoohVz** [comment]
@longfin It's working now but there is another bug that happens when I tried to open it before it done loading.
https://user-images.githubusercontent.com/13524523/122191982-701cab80-cebd-11eb-8eee-f38d42f0738b.mp4

**Comment by PoohVz** [comment]
![Uploading image.png…]()

**Comment by area363** [comment]
`Livenessprobe` for `DataProvider`(ranking) server has been added to minimize downtime.
