### ISSUE TITLE
noisy errors relied to ItemRequirementSheet

### ISSUE THREAD

**Issue by boscohyun** [planetarium/NineChronicles#3160]
<img width="932" alt="image" src="https://github.com/planetarium/NineChronicles/assets/6128868/861bf916-bb21-4dcc-abd2-94332e3cc9d1">

**Comment by tyrosine1153** [comment]
로컬 네트워크에서 제네시스 블록을 생성해 실행될 때, 현재 존재하지 않는 item id가 ItemRequirementSheet에 작성되어 이를 참조하다가 발생한것이 맞지요? 현재 메인에 적용되어 있는 테이블 시트와 Lib9c에 적용되어 있는 테이블 시트가 동기화 되지않은 상태입니다. 머지 프로세스나, 시트가 변경될 때마다 테스트가 깨지는 문제 등으로 그동안 미뤄져 왔는데 담당 기획자님께서 lib9c에 유효한 데이터로 갱신하고 프로그래머 한 명이 붙어서 사이드 이펙트 처리하면 해결이 가능한 문제일겁니다.
