### ISSUE TITLE
Refactor `ActionRenderHandler` to be compatible with Libplanet 3.6.0

### ISSUE THREAD

**Issue by greymistcube** [planetarium/NineChronicles#3271]
Todo list:

### Unmarked
- [x] RewardGold();
- [x] GameConfig();
- [x] CreateAvatar();
- [x] TransferAsset();
- [x] TransferAssets();
- [x] Stake();

### MeadPledge
- [x] RequestPledge();
- [x] ApprovePledge();

### Battle
- [x] HackAndSlash();
- [x] MimisbrunnrBattle();
- [x] HackAndSlashSweep();
- [x] HackAndSlashRandomBuff();
- [x] EventDungeonBattle();

### Craft
- [x] CombinationConsumable();
- [x] CombinationEquipment();
- [x] ItemEnhancement();
- [x] RapidCombination();
- [x] Grinding();
- [x] EventConsumableItemCrafts();
- [x] EventMaterialItemCrafts();
- [x] AuraSummon();

### Market
- [x] RegisterProduct();
- [x] CancelProductRegistration();
- [x] ReRegisterProduct();
- [x] BuyProduct();

### Consume
- [x] DailyReward();
- [x] RedeemCode();
- [x] ChargeActionPoint();
- [x] ClaimMonsterCollectionReward();
- [x] ClaimStakeReward();

### Crystal Unlocks
- [x] UnlockEquipmentRecipe();
- [x] UnlockWorld();

### Arena
- [x] InitializeArenaActions();

### World Boss
- [x] Raid();
- [x] ClaimRaidReward();

### Rune
- [x] RuneEnhancement();
- [x] UnlockRuneSlot();

### Unmarked
- [x] PetEnhancement();

### GARAGE
- [x] UnloadFromMyGarages();

### Claim Items
- [x] ClaimItems();

### Dev
- [x] Testbed();
- [x] ManipulateState();

**Comment by boscohyun** [comment]
@greymistcube @riemannulus Is this done?

**Comment by riemannulus** [comment]
Yes @boscohyun
