### ISSUE TITLE
[아레나] 동일한 점수의 유저들이 있을 경우 내 캐릭터가 동일한 점수 최상단에 출력되지 않는 현상

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#3951]

**Comment by QgamesTaekHaJang** [comment]
현재 Arena 최초 등록 시 점수가 동일한 유저가 상단에 출력되는 현상을 확인하였습니다.
이슈 되돌리겠습니다.

[테스트 환경]
Windows.v200150-150.0.0
Android.v200150-150.0.0
iOS.v150.0.0(27)


![Image](https://github.com/planetarium/NineChronicles/assets/156992678/902b9724-f71c-4adc-8252-6e3afb171009)

**Comment by sonohoshi** [comment]
흠 이거 접속하는 사람의 점수가 플레이 기록이 없어서 1000점일때만 발생하는것처럼 보이는데 혹시 다른 점수에서 발생하는지도 확인해보면 좋을 것 같습니다.

**Comment by ipdae** [comment]
코드상으로 봤을때 1000점(정확하게는 해당 시즌 아레나에 참여한적이 없는 경우)인 경우에 임시로 목록을 생성해서 더해주는 처리를 하고 있습니다. 클라이언트상에서 인덱스를 찾아다 넣는식으로 처리하면 될것같습니다.

**Comment by sonohoshi** [comment]
> 코드상으로 봤을때 1000점(정확하게는 해당 시즌 아레나에 참여한적이 없는 경우)인 경우에 임시로 목록을 생성해서 더해주는 처리를 하고 있습니다.
아 그러네요... 다른 이슈 처리하고 이것도 마저 보도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/8eb24655-0976-44ac-b7db-021040b7172f)


[테스트 환경]
Windows.v200150.v.150.0.2
Android.v200150.v.150.0.2
iOS.v150.0.2(30)
