### ISSUE TITLE
인게임 스테이킹: Action, State 핸들링 및 액션 보낼 수 있는 임시 UI 개발

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#3956]

**Comment by sonohoshi** [comment]
https://www.notion.so/planetarium/Monster-Collection-Mobile-a5d6b8d0c2fb42618059c3c08cf4a4cb

**Comment by sonohoshi** [comment]
아직 UI 시안 안나왔음

**Comment by ipdae** [comment]
프리팹연결은 후속 이슈로 처리

**Comment by sonohoshi** [comment]
이슈 진행이 여러번 밀려서 오늘자로 MVP 마무리하고 홀드, 이후 시안 나오면 UI 연결로 개발 끝내겠습니다.
