### ISSUE TITLE
도감 MVP 클라이언트

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#3972]

**Comment by tyrosine1153** [comment]
related task
https://github.com/planetarium/lib9c/issues/2336
https://github.com/planetarium/lib9c/issues/2341

**Comment by tyrosine1153** [comment]
mvp 스펙을 모두 구현했으나 몇 가지 오류가 남아있습니다.
그래서 내일까지 현재 스펙 안에서 정상 동작하도록 마무리하고 중간 리뷰를 요청할까 합니다.

**Comment by tyrosine1153** [comment]
034c78a39075056069fec155268356871435693d

**Comment by tyrosine1153** [comment]
관련 문서
기획서 : https://www.notion.so/Collection-a2cfa093044243cc8cf0d7eb7ba9d4db
개발 기록 : https://www.notion.so/planetarium/ac44708a24824d6e80f44fba1b7d6f42
