### ISSUE TITLE
[공방] 그라인드 아이템 50개 이상 등록 시 센터 메시지 내용에 10개 이상 아이템 등록 불가로 출력되는 현상

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#3990]
[공방] 그라인드 아이템 50개 이상 등록 시 센터 메시지 내용에 10개 이상 아이템 등록 불가로 출력되는 현상

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200140-130.0.1
