### ISSUE TITLE
아레나 챔피언십 참가조건 텍스트 겹침

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4023]
관련 스레드 : https://planetariumhq.slack.com/archives/C062ZS68A21/p1706145611062979

코드 수정이 필요
![Image](https://github.com/planetarium/NineChronicles/assets/63496908/69b7e07d-0012-4075-9dfa-249c6413ebc9)

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200150.v.150.0.3
Android.v200150.v.150.0.3
iOS.v150.0.3(31)


![Image](https://github.com/planetarium/NineChronicles/assets/156992678/f5a3dc08-a216-4492-9f48-2a527683d8cf)
