### ISSUE TITLE
배포시 클라이언트 진입 막기

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#4079]

**Comment by jonny-jeahyunchoi** [comment]
https://planetariumhq.slack.com/archives/C011716SDTM/p1707101134246649?thread_ts=1707100367.744179&cid=C011716SDTM

이미 maintenence 인자로 시스템 점검팝업 관련내용이 구현된것이있어서 해당이슈 클로즈처리하겠습니다~!
