### ISSUE TITLE
스파인 업그레이드

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#4085]
## 배경
- 현재 프로젝트에서 사용하고있는 스파인의 버전을 업그레이드합니다
- 현재 3.8 -> 업그레이드 이후 4.1 목표(최소 4.0을 타겟으로 하고 있습니다)
- 스파인 데이터 저장 형식을 json에서 bytes로 바꾸려고 합니

## 목적
- 스파인 프로젝트 상에서 그래프, x y축 분리 등 작업 편의성 증가(아우라 제작에 용이)
- 유니티 프로젝트상에서 걸리는 부하 감소
- 유니티 프로젝트의 복잡도 감소, 

## 기대 결과
- 스파인 작업 편의성이 증가합니다
- 전투에서 에너미 오브젝트 생성시 걸리는 부하가 감소합니다
- 코드에서 관리되고 있는 스파인 코드들을 별도의 패키지로 분리해서 관리함으로써, 9c저장소에 있는 코드의 양을 감소시킵니다. 그리고 이후 버전 변경시 manifest를 수정하는것으로 간편하게 진행할 수 있습니다.
 
## 작업 내용
- 프로젝트에 있던 스파인 에셋들을 버전업하고, 데이터 형식을 bytes로 변경
- 기존 3.8을 기준으로 작성된 코드 마이그레이션 작업
- 스파인 코드를 유니티 프로젝트에서 분리하고 패키지로 관리
- 월드보스 연출에서 타임라인 관련 코드 수정 

---

### 관련 이슈
- 버전업 후 기존 인게임에 적용되어있는 스파인들의 동작이 변경되지 않고 제대로 작동하는지 확인이 필요합니다

### 관련 문서
- https://ko.esotericsoftware.com/forum/d/15981-spine-unity-38-to-40-upgrade-guide

**Comment by tyrosine1153** [comment]
@eugene-doobu 이 이슈와 실제로 연결되어서 머지된 pr은 https://github.com/planetarium/NineChronicles/pull/4119 이게 맞나요?

**Comment by eugene-doobu** [comment]
> @eugene-doobu 이 이슈와 실제로 연결되어서 머지된 pr은 #4119 이게 맞나요?

넵 맞습니다. 해당 pr연결내용 추가하였습니다
