### ISSUE TITLE
8월드 더미데이터 MVP 테스트

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4088]

**Comment by jonny-jeahyunchoi** [comment]
NineChronicles\nekoyume\Assets\Resources\UI\Icons\Character에 몬스터 아이콘 추가되어야함.
![Image](https://github.com/planetarium/NineChronicles/assets/138189475/7681ae87-dce7-4fb8-baf5-1e6d556231d8)

**Comment by jonny-jeahyunchoi** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/138189475/1a111221-45e3-4759-b6ff-018653b64d20)

스킬 관련 L10N키 추가 필요 

![Image](https://github.com/planetarium/NineChronicles/assets/138189475/d2f0648b-8f38-49c1-9872-2d59d7793f29)

**Comment by jonny-jeahyunchoi** [comment]
Assets\Resources\Character\PlayerSpineTexture 신규 아머 추가될떄 컷신 리소스도 필요

**Comment by jonny-jeahyunchoi** [comment]
- [ ] 테스트로올림

**Comment by NineSyu** [comment]
2월 28일 3시 : 2차 시연
**적용 리스트**
아트 리스스 적용 필요
- [ ] 신규 장비 아이콘 리소스 (2월 21일)
- [ ] 신규 배경 (2월 26일)
- [ ] 월드맵 아이콘
- [ ] 8월드 용 스윕 프리팹
데이터 작업
- [ ] 장비 언락 레벨 적용 (레시피 소팅 순서 개선)
L10n 작업
- [ ] 장비 (장비, 장비 재료, 음식, 음식 재료)
- [ ] 월드맵 (월드, 스테이지)
- [ ] 몬스터
테스트 세팅
- [ ] 월드 언락 되기 전 상태 유지
- [ ] 모든 몬스터 체크를 위한 테스트용 데이터
- [ ] 임시 배경 적용 필요.

**Comment by jonny-jeahyunchoi** [comment]
밸런스체크는 다른 이슈들에서 팔로우되는것으로 보여서 해당이슈는 닫아두도록하겠습니다~!
