### ISSUE TITLE
SPD 소수점 제거

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4093]

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200150-150.0.0
Android.v200150-150.0.0
iOS.v150.0.0(27)


![Image](https://github.com/planetarium/NineChronicles/assets/156992678/36f30895-3c6a-4080-9aea-3d8c926b1306)
