### ISSUE TITLE
유니티 버전업데이트 이후 빌드에서 안드로이드 콘솔 리포트 문제 조사

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4094]

**Comment by jonny-jeahyunchoi** [comment]
딥링크 연결 실패, 오래된 SDK 사용 경고 문제 발생.

**Comment by jonny-jeahyunchoi** [comment]
딥링크 연결은 사용하지않던 링크가 메니페스트에 자동으로 추가되어서 발생한이슈로 메니페스트에서 관련 내용 제거시 발생하지않을것으로 예상됨

**Comment by jonny-jeahyunchoi** [comment]
https://developer.android.com/jetpack/androidx/releases/fragment?hl=ko#version_110_3 SDK는 버전을 강제로 올려야하는지 테스트해봐야함.

**Comment by jonny-jeahyunchoi** [comment]
SDK ResolverDependency수정하여 강제로변경해봤으나 제대로 적용이안되어있는것확인.
일단 8월드 mvp 작업이후로 보류

**Comment by ipdae** [comment]
@sonohoshi 님이 이어받아서 테스트진행

**Comment by sonohoshi** [comment]
sdk는 https://github.com/planetarium/NineChronicles/pull/4071/commits/9d1f3a42b32d8831481db1697d093a9b7356c174#diff-bcbe9887f7e714026bc23f5975a1b7360a31f586a1290383d1d18d6da55cc6c9R172 여기 문제같은데 뭔가 문맥이 있어서 바꾸셨겠지 싶어서... @jonny-jeahyunchoi

**Comment by jonny-jeahyunchoi** [comment]
으어 저거 왜바꿨었는지 도통기억이나지않네요ㄷㄷ 다시되돌리고 시도해보셔도될것같아요

**Comment by sonohoshi** [comment]
androidTargetVersion 세팅이 에디터에서 제대로 안되는거같길래 signing keystore랑 androidTargetVersion ci에서 세팅하도록 수정해봤고
