### ISSUE TITLE
스윕 게이지 맥스 50으로 늘리기, Repeat에서 ap 포션 쓸 수 있게 풀기

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4120]
현재 max 10으로 설정되어 있는 스윕 카운트를 50까지 늘려, tx를 줄이고 포션이 많은 유저들의 사용성을 개선합니다.

**Comment by sonohoshi** [comment]
작업할때 10개일때/50개일때 속도 벤치마킹 해보고 넣기로

**Comment by QgamesTaekHaJang** [comment]
현재 환경에서 확인 시,
Sweep의 경우 ap 포션을 20개까지 사용가능 한 것을 확인하였습니다.
Repeat의 경우 ap 포션을 사용 가능하나 1개까지 사용가능 한 것을 확인하였습니다.
관련하여 해당 수치가 확정된 수치인지 확인 부탁드리겠습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/92578289-0da9-4db9-b6cb-d36d8a17650e)

**Comment by sonohoshi** [comment]
@QgamesTaekHaJang 네 맞습니다.

**Comment by QgamesTaekHaJang** [comment]
코멘트 확인하여 이슈 종료하겠습니다.
확인 감사드립니다.
