### ISSUE TITLE
도감 MVP 150 준비 브랜치에서 비활성화시키기

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#4132]
Collection(#4025)이 150.0.0 타겟에 들어가지 못할 가능성이 있어 Collection 기능과 관련해 작업한 내용이 인게임에서는 보이지 않도록 비활성화 합니다.

**Comment by tyrosine1153** [comment]
Collection 기능이 150.0.0 rc 일정에 맞춰 준비가 되어 이 이슈는 클로즈합니다.
