### ISSUE TITLE
월드보스 전투 연출 스킵

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#4136]
## Purpose
-월드보스의 전투 연출을 스킵하는 기능을 만듭니다

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.
다만 월드 보스 전투 입장 직후에 해당 버튼이 1초 정도 동작하지 않는 것을 확인하였습니다.
해당 내용 확인 부탁드리겠습니다.
첨부드린 영상 참고 부탁드립니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)

https://github.com/planetarium/NineChronicles/assets/156992678/b2026bbb-2d1e-4880-8840-24eea77157be

**Comment by eugene-doobu** [comment]
@QgamesTaekHaJang 안녕하세요, 혹시 해당 이슈 항상 재현되는지 확인해주실 수 있나요?

**Comment by QgamesTaekHaJang** [comment]
@eugene-doobu 안녕하세요.
현재 환경에서 확인 시에는 진입 직후 0.5초 정도 버튼을 눌러도 바로 스킵되지 않는 것을 확인하였습니다.
첨부드린 영상 참고 부탁드립니다.
해당 내용 이상 없을 경우 이슈 종료 진행하겠습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
Android.v200160-.v.160.0.3
iOS.v.160.0.3(39)

https://github.com/planetarium/NineChronicles/assets/156992678/5d5be26f-b469-4bfc-bafd-eb6c39bcc70d

**Comment by Namyujeong** [comment]
이정도는 괜찮습니다.

**Comment by QgamesTaekHaJang** [comment]
코멘트 확인하여 정상 동작인 것을 확인하였습니다.
확인 감사드립니다.
이슈 종료 하겠습니다.
