### ISSUE TITLE
8월드 이펙트

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4143]

**Comment by boramqo83** [comment]
[8월드이펙트.zip](https://github.com/planetarium/NineChronicles/files/14303707/8.zip)

**Comment by boramqo83** [comment]
버프 아이콘 2종은 나오면 이 곳에 업데이트 해 두겠습니다.

**Comment by jonny-jeahyunchoi** [comment]
- [ ] 집중 - 발동이펙트, 유지되는 이펙트
- [ ] 더블어택 - 두번 타격인데 이펙트는 나눠져 있음
- [ ] 디버프 회피율 - 발동이펙트, 유지되는 이펙트, 회피에 성공했을 때 뜨는 이펙트
- [ ] HP 비례 데미지 - 발동이펙트, 타격이펙트

**Comment by jonny-jeahyunchoi** [comment]
이팩트 리소스는 저장소에 포함되어있어서 완료처리로바꿔두겠습니다.
