### ISSUE TITLE
제작 슬롯에서 펫 영역 누르면 준비중 팝업 뜨는 것 삭제해야함

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4145]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1708051747995409

**Comment by eugene-doobu** [comment]
해당 이슈에서 처리하는것으로 하고 close상태로 변경하겠습니다
https://github.com/planetarium/NineChronicles/issues/4243
