### ISSUE TITLE
스테이킹 팝업에서 아레나 리워드 보너스 나오게하기

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#4163]
![Image](https://github.com/planetarium/NineChronicles/assets/48484989/5f810656-b132-4774-91eb-63f16831e15f)

현재 Arena Reward Bonus에 해당하는 데이터가 보여지고있지 않음

**Comment by QgamesTaekHaJang** [comment]
현재 스테이킹 4단계인 계정으로 확인 진행 시 
스테이킹 팝업에서 아레나 리워드 보너스가 정상적으로 출력되는 것을 확인하였습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200150.v.150.0.1

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/31991875-3e73-499c-85ff-8ed8e312eb46)
