### ISSUE TITLE
월드 클리어 버튼 안눌러져 지는 이슈

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#4164]
슬랙 레폿된 이슈
https://planetariumhq.slack.com/archives/C062ZS68A21/p1708336707034429

**Comment by jonny-jeahyunchoi** [comment]
이거 world 8 언락하면서 보고있었는데 간헐적인이슈같습니다 prepare/150.0.x 기준브렌치에서는 발생하지않네요
