### ISSUE TITLE
월드클리어버튼 수정.

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4170]
월드 클리어 했을 때 버튼 안눌려서 재실행 해야 했습니다

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1708336707034429?thread_ts=1708336707.034429&cid=C062ZS68A21)

**Comment by eugene-doobu** [comment]
동일 이슈 같습니다
https://github.com/planetarium/NineChronicles/issues/4164

**Comment by jonny-jeahyunchoi** [comment]
지우도록하겠습니다~!
