### ISSUE TITLE
콜렉션 UI에서 재료로 들어갈 장비의 등록 가능 여부 업데이트하기

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4174]
https://planetariumhq.slack.com/archives/C011716SDTM/p1708480202923729

- [ ] 콜렉션에서 등록 가능한 "장비" 재료의 등록 가능 여부가 업데이트 되었을 때, 이를 콜렉션에서 반영해야 함

재현 방법 : 
1. 콜렉션에서 등록 가능한 장비 재료를 확인.
2. 등록 가능한 장비 재료를 강화(주재료, 부재료), 샵 판매 등 다른 액션에 넣기.
3. 콜렉션에서 등록 가능한 장비 재료가 업데이트 되었는지 확인.

\* 콜렉션 = 콜렉션 UI

**Comment by tyrosine1153** [comment]
예상 원인 :
1. RequiredBlockIndex가 조건 체크에 반영되지 않았다.
2. 장비가 등록 불가능한 상태가 될 때 Inventory가 업데이트되지 않는다. -> 콜렉션에서 등록 가능 여부를 업데이트하지 못함.

**Comment by QgamesTaekHaJang** [comment]
현재 환경에서 상점 등록, 그라인딩, 강화 시 컬렉션에서 장비 상태 정상 업데이트 되는 것을 확인하였습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200150.v.150.0.3
Android.v200150.v.150.0.3
iOS.v150.0.3(31)


https://github.com/planetarium/NineChronicles/assets/156992678/87c95050-c661-490e-8070-b29eb494aff9
