### ISSUE TITLE
[이벤트 던전] 이벤트 던전 전투 준비 화면에서 최소 요구 CP가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4180]
[테스트 환경]
Windows.v200150-150.0.0
Odin

[테스트 디바이스]
PC

[내용]
이벤트 던전 전투 준비 화면에서 최소 요구 CP가 출력되지 않는 현상
-Android, iOS 환경에서도 동일하게 확인되고 있습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.
![Image](https://github.com/planetarium/NineChronicles/assets/156992678/a49605cd-ab72-4584-b0da-2167ebe98258)

[재현스텝]
1. 메인 로비 > 어드벤쳐 진입
2. 이벤트 던전 진입하여 임의의 스테이지 진입
3. 전투 준비 화면에서 스테이지 최소 요구 CP가 출력되지 않는 것을 확인

[Should be]
스테이지 전투 준비 화면에서 최소 요구 CP가 정상적으로 출력되어야 합니다.

**Comment by jaeho0103** [comment]
required cp 는 sweep 을 실행하기 위한 spec 으로 sweep 이 없는 이벤트 던전의 경우 노출되지 않는 부분이 정상스펙범위내입니다.

**Comment by QgamesTaekHaJang** [comment]
코멘트 내용 확인하여 해당 내용 정상스펙인 것을 확인하였습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200150-150.0.0
