### ISSUE TITLE
[공방] 이벤트 아이템 레시피 제작 블록 텍스트가 사용 가능 레벨 텍스트와 겹쳐서 출력되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4184]
### APV version info

v200150

### Client version info

v150.0.0

### Device

Android, iOS

### detailed device info

Android8, iOS17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### avatar address info

0x965dd6635fedc1938c043fa8b780465cdb010da5

### What happened?

[내용]
이벤트 아이템 레시피 제작 블록 텍스트가 사용 가능 레벨 텍스트와 겹쳐서 출력되는 현상
-장비, 음식 레시피의 경우 정상적으로 출력되는 것을 확인하였습니다.
-iOS 환경에서도 동일하게 확인되고 있습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/a93886a0-e6f2-4b0a-b280-495dd60cc0fd)

### How to reproduce the issue

[재현스텝]
1. 메인 로비 > 공방 > 제작 > 이벤트 아이템 선택
2. 임의의 이벤트 레시피 선택하여 제작 블록과 사용 가능 레벨 텍스트가 겹쳐서 출력되는 것을 확인

[Should be]
제작 블록 텍스트와 사용 가능 레벨 텍스트가 겹치지 않게 정상적으로 출력되어야 합니다.

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/150.0.x
적용 브랜치 : ui/eventitem_level-edit
사용 프리퓁 : UI_Craft

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200150.v.150.0.1
iOS.v150.0.1(28)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/43c6538f-2930-44da-a383-bb58a486c5c9)
