### ISSUE TITLE
[수집] 활성화 되지 않은 항목에 보유중인 아이템의 강화레벨이 더 높은 경우 활성화 표시처럼 보이는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4191]
### APV version info

v200150

### Client version info

v150.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
활성화 되지 않은 항목에 보유중인 아이템의 강화레벨이 더 높은 경우 활성화 표시처럼 보이는 현상
-등록은 되지 않는 것을 확인하였습니다.
-PC/Android/iOS 환경에서 동일하게 확인되고 있습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/ee25313d-4f3f-4be1-a7cc-98cf92133217

### How to reproduce the issue

[재현스텝]
1. 메인 로비 > 수집 선택
2. 임의의 아직 활성화되지 않은 수집 항목 확인
3. 해당 수집 항목 등록 아이템과 동일한 강화레벨이 더 높은 아이템 보유
4. 해당 수집 항목에 딤드처리 되지 않은 것을 확인

[Should be]
보유중인 아이템의 강화레벨이 더 높은 경우 등록 가능한 아이템과 구분되게 표시되어야 합니다.

**Comment by sonohoshi** [comment]
이거 정확히 0강을 요구하는 콜렉션인데 강화가 된걸 갖고있고-
원래는 강화수치에서 빨간색으로 텍스트가 나올텐데 0강은 강화 수치 텍스트가 없으니까 이렇게 헷갈리는 상태가 된 것 같네요.
문제가 되는 것 같긴한데 기획적으로 풀어주셔야 할 것 같습니다

**Comment by tyrosine1153** [comment]
보유중인 아이템이더라도 수집 항목의 강화 레벨보다 높다면 딤드처리(미 보유 처리) 하는 것으로 정리되었습니다.

https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1708506576661369

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.
https://github.com/planetarium/NineChronicles/assets/150774808/14650bb4-9cb0-4659-8a4e-07f51201581e
[테스트 환경]
Windows.v200150.v.150.0.2
Android.v200150.v.150.0.2
iOS.v150.0.2(30)
