### ISSUE TITLE
[런처] 신규 계정 생성 화면에서 전 시즌 로고가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4192]
### APV version info

v200150

### Client version info

v150.0.0

### Device

Windows

### detailed device info

Windows 11

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
신규 계정 생성 화면에서 전 시즌 로고가 출력되는 현상
-PC 환경에서 확인되고 있습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/a88c6c32-1f09-4e1e-af42-c535b2855d92)

### How to reproduce the issue

[재현스텝]
1. 키파일이 없는 상태에서 런처 실행
2. 런처 화면에 출력되는 로고가 전 시즌 로고인 것을 확인

[Should be]
신규 게정 생성 화면에서 전 시즌 로고가 출력되지 않고 이번 시즌 로고가 출력되어야 합니다.

**Comment by boramqo83** [comment]
띠지 없는 로고가 들어가는게 좋지 않을까 의견 내봅니다.

**Comment by ipdae** [comment]
@Akamig 이거 확인 부탁드립니다.

**Comment by Akamig** [comment]
저거 시즌 바뀔때마다 들어오는 요청인데, @boramqo83 이 말씀하신것 처럼 그냥 시즌에 상관 없는 로고 리소스를 주시면 감사드리겠십니더...

**Comment by boramqo83** [comment]
@Akamig 로고 사이즈를 알려주시면 그대로 전달 드리겠습니다.

**Comment by Akamig** [comment]
@boramqo83 4096 × 2048......이긴 한데 절반정도로 줄이셔도 되겠습니다....

**Comment by boramqo83** [comment]
![01_기본로고_2048x1024_F](https://github.com/planetarium/NineChronicles/assets/102953029/3c067d7b-eec8-4563-b3b8-3aef591f4deb)
위 이미지 적용 부탁드립니다. @Akamig

**Comment by Akamig** [comment]
참고 : https://github.com/planetarium/9c-launcher/commit/2a9c318187eb955f5758b9f007f1d942a49054cc
