### ISSUE TITLE
[공방] 룬 제작 완료 시 결과 팝업이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4196]
### APV version info

v200150

### Client version info

150.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544

### What happened?

[내용]
룬 제작 완료 시 결과 팝업이 출력되지 않는 현상
- PC / AOS / iOS 모두 발생하고 있습니다.
- 첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/32bfd8ac-5d0c-453c-bebc-55b509e53f57

### How to reproduce the issue

[재현스텝]
1. 공방 > 룬 클릭
2. 룬 제작 진행
3. 룬 제작 완료 시 결과 팝업이 출력되지 않는 현상 확인

[Should be]
룬 제작 완료 시 결과 팝업이 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
현재 클라이언트 구현상 최초 룬 생성시에는 의도적으로 결과 팝업을 띄우지 않는 것으로 판단되어 확인 요청을 드리기 위해 담당자에 넣게 되었습니다 @jaeho0103 . 

관련 대화는 아래서 진행하였습니다
https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1708586099876879?thread_ts=1708583549.687329&cid=CC7BWJYTZ

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.

[테스트 환경]
Windows.v200150-150.0.0
Android.v200150-150.0.0
iOS.v150.0.0(27)

**Comment by sonohoshi** [comment]
룬 제작인지 강화인지와 관계없이 다음과 같은 결과 화면이 나오도록 수정하기로 하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/48484989/b43c0481-a33c-475d-8067-ba99126fdc9c)

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


https://github.com/planetarium/NineChronicles/assets/150774808/dc08fd2b-32c0-4971-aa74-f8555b800bfd


[테스트 환경]
Windows.v200150.v.150.0.2
Android.v200150.v.150.0.2
iOS.v150.0.2(30)
