### ISSUE TITLE
[D:CC] D:CC 메인 화면에 출력되는 고양이 캐릭터의 눈에 잘못된 이미지가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4197]
### APV version info

v200150

### Client version info

v150.0.0

### Device

Windows

### detailed device info

Windows 11

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
D:CC 메인 화면에 출력되는 고양이 캐릭터의 눈에 잘못된 이미지가 출력되는 현상
-PC 환경에서 확인되고 있습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/240b2b26-bfb8-4592-a6d7-9e66b477198e)

### How to reproduce the issue

[재현스텝]
1. 메인화면 > D:CC 진입
2. D:CC 메인 화면에 출력되는 고양이 캐릭터의 눈에 잘못된 이미지 출력되는 것을 확인

[Should be]
화면에 출력되는 캐릭터가 정상적으로 출력되어야 합니다.

**Comment by QgamesTaekHaJang** [comment]
해당 현상 발생하는 것이 확인되었습니다.
이슈 되돌리겠습니다.

[테스트 환경]
Windows.v200150.v.150.0.1


![Image](https://github.com/planetarium/NineChronicles/assets/156992678/c3afc74b-5805-4ee1-b279-81dc5701e0c9)

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/6eed6432-7bca-4187-9843-f33e6bf3f091)


[테스트 환경]
Windows.v200150.v.150.0.2
Android.v200150.v.150.0.2
iOS.v150.0.2(30)
