### ISSUE TITLE
[상점] PC 상점에서 Sell 탭에 정렬 카테고리 텍스트가 버튼 내 다른 이미지와 겹쳐서 출력되는 것을 확인

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4199]
### APV version info

v200150

### Client version info

v150.0.0

### Device

Windows

### detailed device info

Windows 11

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
PC 상점에서 Sell 탭에 정렬 카테고리 텍스트가 버튼 내 다른 이미지와 겹쳐서 출력되는 것을 확인
-"Full Costume", "PetSoulStone" 텍스트에서 확인되고 있습니다.
-PC 환경에서 확인되고 있습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/96613aa0-2648-4b38-98dd-d25c839facbd)

### How to reproduce the issue

[재현스텝]
1. PC 환경에서 메인화면 > 상점 진입
2. Sell 진입 후 정렬 카테고리 텍스트가 버튼 내 다른 이미지와 겹쳐서 출력되는 것을 확인

[Should be]
정렬 버튼에 출력되는 텍스트가 버튼 내 다른 이미지와 겹치지 않게 출력되어야 합니다.

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/150.0.x
적용 브랜치 : ui/shop_sell_text_sort-edit
사용 프리퓁 : UI_ShopSell

수정했습니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200150.v.150.0.1

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/64bfb0e8-9b15-435b-a867-4c83cf600f73)
