### ISSUE TITLE
[수집] 수집 활성화 후 보상 화면에서 클릭 시 보상 화면이 닫히지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4207]
### APV version info

v200150

### Client version info

v150.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
수집 활성화 후 보상 화면에서 클릭 시 보상 화면이 닫히지 않는 현상
-Press to continue 문구가 출력되고 있으나 클릭 시 아무 동작이 없고, 잠시 후 보상 화면이 닫힙니다.
-PC/Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/6b1ae43a-1635-4074-aa2f-0682f40735cc

### How to reproduce the issue

[재현스텝]
1. 메인화면 > 수집 진입
2. 임의의 항목 활성화하여 보상 화면 확인
3. 보상 화면에서 임의의 영역 클릭하여 보상 화면 닫히지 않는 것을 확인

[Should be]
수집 보상 화면에서 임의의 영역을 클릭할 경우 보상 화면이 정상적으로 닫혀야 합니다.

**Comment by tyrosine1153** [comment]
duplicate with https://github.com/planetarium/NineChronicles/issues/4172

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200150.v.150.0.1
Android.v200150.v.150.0.1
iOS.v150.0.1(28)

https://github.com/planetarium/NineChronicles/assets/156992678/b93df45d-a111-410b-ba8e-4d4a80aae46b
