### ISSUE TITLE
[수집] 모바일 환경에서 등록 팝업에 아이템 상세 툴팁이 우측에 출력되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4208]
### APV version info

v200150

### Client version info

v150.0.0

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
모바일 환경에서 등록 팝업에 아이템 상세 툴팁이 우측에 출력되는 현상
-Slack 답변 확인 시 팝업 좌측에 상세 툴팁이 출력되는 것이 정상인 것을 확인하였습니다.
https://planetariumhq.slack.com/archives/C011716SDTM/p1708483925437649?thread_ts=1708420940.755609&cid=C011716SDTM
-PC 버전에서는 좌측에서 출력되고 있습니다.
-Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/3882a5e2-eb7a-4ee8-b0d1-14feafcd2730)

### How to reproduce the issue

[재현스텝]
1. 메인화면 > 수집 진입
2. 임의의 항목 활성화 버튼 선택
3. 등록 팝업 에서 아이템 상세 툴팁이 우측에 출력되는 것을 확인

[Should be]
등록 팝업에서 아이템 상세 툴팁이 팝업 좌측에 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
@QgamesTaekHaJang 이 현상이 발생한 기기의 기종을 알 수 있을까요?

**Comment by tyrosine1153** [comment]
재현 불가로 다음 rc에서 확인하는 것으로 넘기겠습니다.

**Comment by QgamesTaekHaJang** [comment]
해당 현상 발생하는 것이 확인되었습니다.
이슈 되돌리겠습니다.

[테스트 환경]
Windows.v200150.v.150.0.3
Android.v200150.v.150.0.3
iOS.v150.0.3(31)

[테스트 기기]
iPhone 11 Pro Max
iPhone 12
Huawei Y7 Prime
Galaxy note 20 ultra


![Image](https://github.com/planetarium/NineChronicles/assets/156992678/835dccc7-dc77-484c-b0a5-d193605812c9)

**Comment by boramqo83** [comment]
유니티 : 시뮬레이션 돌렸을 때 문제 없이 나옵니다.
PC 메인넷 : 문제 없이 나옵니다.
안드로이드 모바일 : 위 문제 발생 합니다.
발생 원인을 찾지 못해 정민님께 담당자 넘깁니다.
