### ISSUE TITLE
[수집] 임의의 컨텐츠 진행 중 인벤토리의 컬렉션 효과 팝업을 통해 수집 화면으로 진입되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4237]
### APV version info

v200150

### Client version info

v150.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
임의의 컨텐츠 진행 중 인벤토리의 컬렉션 효과 팝업을 통해 수집 화면으로 진입되는 현상
-PC/Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/a002dbe6-551a-4158-bacc-81bbf5925773

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 어드벤쳐 진입
2. 상단의 인벤토리 버튼 선택
3. 인벤토리 팝업 우측 하단에 Collection Effect 버튼 선택 하여 수집 효과 팝업 확인
4. 수집 효과 팝업에서 Go to Collection 버튼 클릭하여 수집 화면으로 진입되는 것을 확인

[Should be]
다른 컨텐츠 진행 중에 수집 효과 팝업을 통해서 수집 화면으로 진입되지 않아야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


https://github.com/planetarium/NineChronicles/assets/150774808/49e6b202-be3c-4126-8193-d0510e922a84


[테스트 환경]
Windows.v200150.v.150.0.2
Android.v200150.v.150.0.2
iOS.v150.0.2(30)
