### ISSUE TITLE
[몬스터 컬렉션] All Rewards 탭에서 Item Rewards 항목에 루비 더스트 보상이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4242]
### APV version info

v200150

### Client version info

v150.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
All Rewards 탭에서 Item Rewards 항목에 루비 더스트 보상이 출력되지 않는 현상
-Current Rewards 탭에서 정상 출력되며 Claim 진행 시 획득이 되는 것을 확인하였습니다.
-런처의 Staking화면에서는 보상으로 루비 더스트가 출력되고 있습니다.
-PC/Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/07d9346b-cc55-4e40-82f7-96f9371a42de)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > Staking 진입
2. 몬스터 컬렉션 팝업에서 All Rewards 탭 선택
3. Item Rewards 보상 항목에 루비 더스트가 출력되지 않는 것을 확인

[Should be]
All Rewards탭 Item Rewards 보상 항목에 획득 가능한 보상이 모두 정상 출력되어야 합니다.

**Comment by sonohoshi** [comment]
이건 웹에 올라가있는 리소스 교체하면 되는 건이라서 일단 메모만 남겨둡니다.
