### ISSUE TITLE
[D:CC] 모바일 환경에서 Workshop 팝업에서 비어있는 펫을 선택할 경우 준비 안내 팝업 이후 캐릭터 선택창으로 이동하는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4243]
### APV version info

v200150

### Client version info

v150.0.1

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
모바일 환경에서 Workshop 팝업에서 비어있는 펫을 선택할 경우 준비 안내 팝업 이후 캐릭터 선택창으로 이동하는 현상
-준비 안내 팝업에서 확인 버튼을 클릭할 경우에만 발생하고 있습니다.
-Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/c4b2d630-2e82-4e47-b458-aaa5995497e9

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 상단 Workshop UI 선택
2. Workshop 팝업에서 좌측의 비어있는 펫 슬롯 선택하여 준비 안내 팝업 출력
3. 준비 안내 팝업에서 확인 버튼 클릭 시 캐릭터 선택 창으로 이동하는 것을 확인

[Should be]
준비 안내 팝업을 확인 버튼으로 닫은 후에 캐릭터 선택창으로 이동하지 않아야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/8143c10d-5262-4a57-9acd-ffd7e84610cf)


[테스트 환경]
Android.v200150.v.150.0.2
iOS.v150.0.2(30)
