### ISSUE TITLE
월드보스 시즌 시작했는데 로비에 안내 표시 안됨(flag)

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#4256]
월드보스 시즌 열렸을 때 로비에서 안내용 풍선이 보이지 않습니다.

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1708336769940389?thread_ts=1708336769.940389&cid=C062ZS68A21)

**Comment by tyrosine1153** [comment]
<img width="159" alt="image" src="https://github.com/planetarium/NineChronicles/assets/63496908/732806f2-3c53-468c-8946-776dcc10715d">
<img width="234" alt="image" src="https://github.com/planetarium/NineChronicles/assets/63496908/43253c26-d024-4425-9516-b6817ab4b7d6">

프리펩에 월드보스 안내 오브젝트가 꺼져있었습니다. 프로모션용 오브젝트는 항상 켜놓은 상태여야 정상 동작되도록 되어있어 발생한 것 같습니다.

**Comment by tyrosine1153** [comment]
150.0.4에서 수정된 것 확인
