### ISSUE TITLE
아레나 & 월드보스 시즌 오픈 안내 좀더 잘 보이게 변경

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#4257]
월드보스 시즌 열렸을 때 티켓 인디테이터 3이 안보이다가, 전투를 한번 해야 2라고 보입니다.

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1708336769940389?thread_ts=1708336769.940389&cid=C062ZS68A21)

**Comment by boramqo83** [comment]
슬랙 내용을 확인해 보니 대부분 떠야하는데 뜨지 않는 버그 잇슈인 것 같습니다. - 어싸인을 개발쪽으로 해야하는 것이 아닌지요?
그 외에 수정했으면 하는 부분이 애드벌룬 만으로는 강조가 덜 되어 보인다는 것일까요? @Namyujeong 


![Image](https://github.com/planetarium/NineChronicles/assets/102953029/e15255f8-2756-4b54-a2b5-e785073bd72a)

**Comment by Namyujeong** [comment]
@boramqo83 아까 주간미팅때 말씀드린 것처럼 진입을 유도해야 할 때의 글로벌 룰을 정리해서 UI 적용해야 한다는 차원
& 애드벌룬 프리펩 혹시 꺼져있는거면 켜야 하는거 정도 확인 차원에서 이슈 어사인 해놓은 거였습니다.
아니면 dev 로 넘기시고 글로벌 룰 적용하는건 별도 이슈 만드셔도 될듯합니다.

**Comment by boramqo83** [comment]
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=55220027
시즌 오픈에 관한 논의는 위 테스크에서 진행합니다.

인디케이터와 레드닷 문제인 것 같아 개발쪽으로 넘깁니다.
해당 테스크가 이미 있다면 삭제해 주세요. @tyrosine1153
