### ISSUE TITLE
컬렉션 스탯 효과가 스탯 UI별로 다르게 보이는 현상

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4259]
관련 슬랙 스레드 : https://planetariumhq.slack.com/archives/C011716SDTM/p1708916774296099

- 아레나 (UI_FriendInfoPopup)
  ![Image](https://github.com/planetarium/NineChronicles/assets/63496908/b813c72d-d48b-4c8d-b17d-6ae0d6f9d39a)
- 인벤토리 (UI_AvatarInfoPopup)
  ![Image](https://github.com/planetarium/NineChronicles/assets/63496908/5a81f8dc-3f07-497a-8dce-66422247633e)
- 컬렉션 내 스탯 효과
  ![Image](https://github.com/planetarium/NineChronicles/assets/63496908/0ebc2129-804e-4970-9902-45e1e5538cf6)

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.
이후 재현될 경우 새로운 이슈로 등록하겠습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200150.v.150.0.3
Android.v200150.v.150.0.3
iOS.v150.0.3(31)


![Image](https://github.com/planetarium/NineChronicles/assets/156992678/ddd558e0-8263-4f16-988d-346ee105a5b2)
