### ISSUE TITLE
[컬렉션] 컬렉션 장비, 코스튬 활성화 버튼 클릭 시 장비 등록 팝업이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4261]
### APV version info

v200150

### Client version info

v150.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### avatar address info

0x965dd6635fedc1938c043fa8b780465cdb010da5

### What happened?

[내용]
컬렉션 장비, 코스튬 활성화 버튼 클릭 시 장비 등록 팝업이 출력되지 않는 현상
-요리, 재료 아이템은 정상적으로 등록 팝업이 출력되는 것을 확인하였습니다.
-아래의 이슈와 유사한 현상입니다.
https://github.com/orgs/planetarium/projects/97/views/9?pane=issue&itemId=54412442
-PC/Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 영상 및 로그 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/bf719ffe-7c28-45e6-bd0c-4562b12da2f3

[Log_0226.zip](https://github.com/planetarium/NineChronicles/files/14399897/Log_0226.zip)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 컬렉션 진입
2. 임의의 장비, 코스튬 탭의 활성화 가능 항목에 활성화 버튼 클릭
3. 장비 등록 팝업이 출력되지 않는 것을 확인

[Should be]
활성화 가능한 아이템 항목의 활성화 버튼을 클릭할 경우 장비 등록 팝업이 정상적으로 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
- dulplicate with https://github.com/planetarium/NineChronicles/issues/4258

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200150.v.150.0.3
Android.v200150.v.150.0.3
iOS.v150.0.3(31)


https://github.com/planetarium/NineChronicles/assets/156992678/1a6a923c-03d3-43d7-8c97-aec1625af002
