### ISSUE TITLE
[D:CC] 전투 중 제작 슬롯 펫 팝업을 통해 D:CC Collection으로 이동이 가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4263]
### APV version info

v200150

### Client version info

150.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544

### What happened?

[내용]
전투 중 제작 슬롯 펫 팝업을 통해 D:CC Collection으로 이동이 가능한 현상
-아래의 이슈와 동일한 현상입니다.
https://app.asana.com/0/1141562434100787/1204476676881867/f
-PC / AOS / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/15f62936-92a9-4cc7-bbe1-e6c3c1469b68

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 월드 맵 > 임의의 스테이지 진입
2. 전투 중 공방 버튼 > 펫 버튼 클릭
3. 펫 목록을 클릭하여 D:CC Collection으로 이동하는 것을 확인

[Should be]
전투 중 제작 슬롯 펫 목록 클릭 시 시스템 메세지가 출력되며,
D:CC Collection으로 이동이 불가능해야 합니다.

**Comment by tyrosine1153** [comment]
@eugene-doobu 아래 pr 처럼 처리해주시면 됩니다
https://github.com/planetarium/NineChronicles/pull/4241

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인했습니다.


https://github.com/planetarium/NineChronicles/assets/150774808/5bf60eb8-9c10-44af-91b7-5f9ab8cc3027

[테스트 환경]
Windows.v200150.v.150.0.3
Android.v200150.v.150.0.3
iOS.v150.0.3(31)
