### ISSUE TITLE
[월드보스] 제림니르의 스킵 버튼이 설정된 언어와 다르게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4272]
### APV version info

v200150

### Client version info

150.0.0

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544

### What happened?

[내용]
제림니르의 스킵 버튼이 설정된 언어와 다르게 출력되는 현상
-AOS / iOS 모두 발생하고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

제림니르 Skip / 버튼 형태로 출력

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/ed45e33b-24b5-4a19-a305-7c72df516f96)

펜리르 스킵 / 화살표 형태로 출력

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/1da756bf-ae42-4ba3-9767-e02471df5c38)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 월드보스 진입
2. 제림니르 월드보스 입장
3. 스킵 버튼이 설정된 언어와 다르게 출력되는 현상 확인

[Should be]
제림니르의 스킵 버튼이 설정된 언어에 맞게 출력되어야 합니다.

**Comment by sonohoshi** [comment]
it resolved by @HohyunKim-kr
