### ISSUE TITLE
[컬렉션] 아이템 등록 팝업에 출력되는 장비 상세 팝업의 내용이 최상단부터 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4273]
### APV version info

v200150

### Client version info

v150.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
아이템 등록 팝업에 출력되는 장비 상세 팝업의 내용이 최상단부터 출력되지 않는 현상
-PC/Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/4f586719-5192-40f4-9d11-a9264cd6a7b7

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 컬렉션 진입
2. 임의의 활성화 가능한 항목의 활성화하기 버튼 선택하여 아이템 등록 팝업 출력
3. 아이템 등록 팝업 좌측에 출력되는 장비 상세 팝업의 내용이 중단부터 출력되는 것을 확인

[Should be]
장비 상세 팝업의 내용이 최상단 내용부터 출력되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.2
Android.v200160.v160.0.2
iOS.v160.0.2(38)
