### ISSUE TITLE
[공방] 룬 강화 시 룬 제작 완료 센터 텍스트 및 가방에 들어가는 연출이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4274]
### APV version info

v200150

### Client version info

150.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544

### What happened?

[내용]
룬 강화 시 룬 제작 완료 센터 텍스트 및 가방에 들어가는 연출이 출력되는 현상
-룬 강화 성공 / 실패 모두 발생하고 있습니다.
-PC / AOS / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/213499db-8657-4287-a3f9-709a6fd29cfb

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 공방 > 룬 탭 진입
2. 룬 레벨 업 진행
3. 룬 제작 완료 센터 텍스트 및 가방에 들어가는 연출이 출력되는 현상 확인

[Should be]
룬 강화 시 룬 제작 완료 센터 텍스트 및 가방에 들어가는 연출이 출력되지 않아야 합니다

**Comment by sonohoshi** [comment]
당시엔 가방에 들어가는것까지 의도한 연출이었던 것 같고, 룬 제작/강화를 시작하는데 완료했다는 한줄 팝업이 나오는건 이상해보여서 지워보겠습니다.

**Comment by tyrosine1153** [comment]
가방에 들어가는 연출도 룬 제작 완료 시 나오는 연출에 포함이라 지워야 할 듯 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
룬 강화 시 인벤토리로 들어가는 연출이 아직 출력되고 있습니다.
확인 부탁드립니다.


https://github.com/planetarium/NineChronicles/assets/150774808/64e1cfab-94e8-4972-bc84-8056ba41a15c


[테스트 환경]
Windows.v200160.v160.0.2

**Comment by sonohoshi** [comment]
과거 연출의 잔재로 보여 제거했고 rc2부터는 안나올 예정입니다. 다음 빌드에서 체크 부탁드리겠습니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)
