### ISSUE TITLE
[아레나] 전투 준비 화면에서 인벤토리 팝업 진입 후 나왔을 때 나의 CP 텍스트에 색상이 사라지는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4275]
### APV version info

v200150

### Client version info

v150.0.3

### Device

Windows, iOS, Android

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
전투 준비 화면에서 인벤토리 팝업 진입 후 나왔을 때 나의 CP 텍스트에 색상이 사라지는 현상
-아레나 전투 준비 화면에서만 발생하고 있습니다.
-PC/Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/c85d0cea-6b8e-4137-b405-02e9680aa48c

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 아레나 진입
2. 임의의 상대 선택하여 전투 준비 화면 진입
3. 상단 인벤토리 UI로 인벤토리 팝업 진입 후 팝업 종료
4. 나의 CP 텍스트 색상이 사라진 것을 확인

[Should be]
상대방과 나의 CP가 차이날 때 CP 텍스트에 정상적으로 색상이 표시되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.2
Android.v200160.v160.0.2
iOS.v160.0.2(38)
