### ISSUE TITLE
심사 리젝 대응을 위한 게스트 로그인 키 제공

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#4276]

**Comment by sonohoshi** [comment]
https://github.com/planetarium/NineChronicles/blob/1ca3314fde276cc0332dfb7458637e6276861958/nekoyume/Assets/_Scripts/UI/Widget/System/LoginSystem.cs#L409

**Comment by jonny-jeahyunchoi** [comment]
이거 게스트계정에 헤임달에도 아바타들만들어두면 어떨까요?

**Comment by jonny-jeahyunchoi** [comment]
라기엔 오딘으로 바꿔도 게스트로그인으로 메인화면까지넘어가지못하는군요..

**Comment by sonohoshi** [comment]
네 그냥 지금 코드가 게스트키를 쓸 수 있는 상태가 아닌것처럼 보이는데, 이걸 어떻게 피하거나 적용시킬 수 있을지 보는 중이었습니다
