### ISSUE TITLE
[컬렉션] 15스테이지 클리어 전 컬렉션 컨텐츠에 진입이 가능한 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4279]
### APV version info

v200150

### Client version info

v150.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
15스테이지 클리어 전 컬렉션 컨텐츠에 진입이 가능한 현상
-잠금 상태에서는 15스테이지 클리어 이후 해금 텍스트가 출력되는 것을 확인하였습니다.
-10스테이지 클리어 시 컬렉션 컨텐츠에 잠금이 해제되는 것을 확인하였습니다.
-PC/Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/5ffc161d-6e74-4178-a8f1-4d63d0b6f1ac)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 진입
2. 10스테이지 클리어 전 컬렉션 컨텐츠에 15 스테이지 이후 해금 표시가 출력되는 것을 확인
3. 10스테이지 클리어 후 컬렉션 컨텐츠에 진입 가능한 것을 확인

[Should be]
잠금 표시에 출력되는 해금 조건을 만족하지 못했을 경우 컨텐츠에 진입되지 않아야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.2
Android.v200160.v160.0.2
iOS.v160.0.2(38)
