### ISSUE TITLE
[UI] 이벤트 배너가 정상적으로 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4289]
### APV version info

메인넷.v200150

### Client version info

v150.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
이벤트 배너가 정상적으로 출력되지 않는 현상
-메인화면에 이벤트 배너가 출력되지 않는 것을 확인하였습니다.
-메뉴 > Notice 진입 시 일부 이벤트 이미지가 누락된 것을 확인하였습니다.
-Notice 팝업에서 Release Note 탭 선택 시 탭 이동이 되지 않는 것을 확인하였습니다.
-PC/Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/b0b08c5d-349e-48f1-9a5d-365aac60fea1

### How to reproduce the issue

[재현스텝]
1. 메인 화면 진입
2. 이벤트 배너가 메인 화면에 출력되지 않는 것을 확인
3. 메인 메뉴 > Notice 진입 하여 일부 이벤트 배너가 출력되지 않는 것을 확인

[Should be]
메인 화면에 이벤트 배너가 정상적으로 출력되어야 하며, Notice 팝업에 이벤트 이미지가 정상적으로 출력되어야 합니다.

**Comment by jaeho0103** [comment]
오프라인에서 정민님께 체크드린 부분으로
이벤트 안내 배너 혹은 릴리즈 노트 업데이트 부분에 데이터 포맷 이슈로 예측중입니다.

**Comment by tyrosine1153** [comment]
배너 이미지 업로드 시(https://github.com/planetarium/NineChronicles.LiveAssets/pull/111) 미사용 배너 이미지를 정리하던 중 Event.json에서 사용 중이던 이미지를 같이 삭제한 것 같습니다.
이미지 삭제한 커밋 revert 했고, 인게임에서 정상화된 것 확인했습니다.
cc @jaeho0103 @sonohoshi

**Comment by tyrosine1153** [comment]
재확인 요청 드립니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.
다만 현재 PC환경에서 언어설정이 English상태로 확인 시 봄맞이 이벤트의 배너에 일본어가 출력되는 것을 확인하였습니다.
해당 부분 확인 부탁드립니다.
이슈 되돌리겠습니다.

[테스트 환경]
메인넷.Windows.v200150.v.150.0.4

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/c98e5288-8c86-4f19-b817-abe0064fe543)
![Image](https://github.com/planetarium/NineChronicles/assets/156992678/80939f4a-0ce2-49d1-a94f-452ff6854ee6)
![Image](https://github.com/planetarium/NineChronicles/assets/156992678/17c440b7-22f8-4afe-8ab9-7dc3bfe34822)

**Comment by tyrosine1153** [comment]
수정해서 재요청 드립니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
메인넷.Windows.v200150.v.150.0.4

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/f3ef1ed8-044f-4d7c-bdb6-1a4b644bacc5)
