### ISSUE TITLE
[월드 보스] 월드 보스의 체력이 100 레벨 이후 2배 증가하는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4291]
### APV version info

메인넷.v200150

### Client version info

v150.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544

### What happened?

[내용]
월드 보스의 체력이 100 레벨 이후에 2배 증가하는 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

제림니르 370,843,400 (기존 185,421,700 대비 2배)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/52f27c5b-d9b8-432f-81a1-6d2742730674)

펜리르 370,843,400 (기존 185,421,700 대비 2배)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/421e26cf-f366-4425-8147-0e4db3c0781a)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 월드 보스 클릭
2. 현재 월드 보스 100 레벨 이상 도달
3. 월드보스의 체력이 100 레벨 이후에 2배 증가하는 현상 확인

[Should be]
월드 보스의 체력이 레벨과 관계없이 동일해야 합니다.

**Comment by jaeho0103** [comment]
월드 보스 체력이 100레벨부터 2배로 증가하는건
이전 업데이트에 추가된 스펙으로 정상 동작입니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200150.v150.0.4
Android.v200150.v150.0.4
iOS.v150.0.4(32)
