### ISSUE TITLE
[UI] 봄맞이 이벤트 세부 정보 보기 클릭 시 Notion 문서로 이동하는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4293]
### APV version info

메인넷.v200150

### Client version info

v150.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544

### What happened?

[내용]
봄맞이 이벤트 세부 정보 보기 클릭 시 Notion 문서로 이동하는 현상
-현재 해당 링크로 이동됩니다.
https://www.notion.so/planetarium/Spring-Event-Promo-2d00057021fc47f8a518e087523b0a38?pvs=4
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/b1d66c28-98ca-408d-85b1-1de20306f657

### How to reproduce the issue

[재현스텝]
1. 메인화면 - 이벤트 배너 클릭
2. 봄맞이 이벤트 배너 클릭
3. 세부 정보 보기 클릭 시 Notion 문서로 이동하는 현상 확인

[Should be]
봄맞이 이벤트 세부 정보 보기 클릭 시 이벤트 안내 페이지로 이동해야 합니다.
https://medium.com/nine-chronicles/9cm-spring-greeting-event-d81f56ae98c5

**Comment by jaeho0103** [comment]
수정되었습니다. 확인 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200150.v150.0.4
Android.v200150.v150.0.4
iOS.v150.0.4(32)
