### ISSUE TITLE
[UI] 릴리즈 노트 제목에서 [Release Note] 텍스트가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4295]
### APV version info

메인넷.v200150

### Client version info

v150.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544

### What happened?

[내용]
릴리즈 노트에서 [Release Note] 텍스트가 출력되지 않는 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/54e4d425-712a-4ec7-a6e7-6e0f87119cbc)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 이벤트 배너 클릭
2. Release Note 탭 클릭 시 제목에서 [Release Note] 텍스트가 출력되지 않는 현상 확인

[Should be]
릴리즈 노트 제목에서 [Release Note] 텍스트가 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
텍스트 간격을 고려해서 [Release Note] 텍스트를 표시하지 않도록 수정된 스펙입니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
메인넷.Windows.v200150.v152.0.0
메인넷.Android.v200150.v152.0.0
메인넷.iOS.v152.0.0(35)
