### ISSUE TITLE
[UI] 인트로 씬 내 캐릭터 외형이 깨진 상태로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4301]
### APV version info

메인넷.v200150

### Client version info

v150.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544

### What happened?

[내용]
인트로 씬 내 캐릭터 외형이 깨진 상태로 출력되는 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/2980e65b-1a14-4cf0-be52-ebf5c58127c7)

### How to reproduce the issue

[재현스텝]
1. 클라이언트 설치 후 진입
2. 인트로 씬 출력 시 캐릭터 외형이 깨진 상태로 출력되는 현상 확인

[Should be]
인트로 씬 내 캐릭터 외형이 정상적으로 출력되어야 합니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)

https://github.com/planetarium/NineChronicles/assets/156992678/6be50211-c248-4dd3-9f1f-b45db5d49e01
