### ISSUE TITLE
[월드 보스] 보스 정보의 공격 정보와 하단 패턴의 정보의 문구가 다른 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4306]
### APV version info

메인넷.v200150

### Client version info

v150.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
보스 정보의 공격 아이콘의 정보와 하단 패턴의 정보의 문구가 다른 현상
-일본어 환경에서도 문구가 다른 것을 확인하였습니다.
-펜리르 기준 다른 문구
  -더블 공격
-PC/Android/iOS 환경에서 확인되고 있습니다.
-첨부 드린 스크린샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/3d411e6c-a88a-4b84-9a6b-0df28b84720c)
![Image](https://github.com/planetarium/NineChronicles/assets/156992678/c74b6398-51e6-4671-8b13-a74927b51f45)

### How to reproduce the issue

[재현스텝]
#1. 기기 설정을 한국어로 변경 후 게임 실행
#2. 메인 로비 > 월드 보스 > 보스 정보 진입
#3. 공격 아이콘 클릭 시 출력되는 명칭 확인
#4. 하단 패턴 정보의 문구 확인 시 #2.번의 명칭과 다른 것을 확인

[Should be]
보스 정보의 공격 아이콘의 정보와 하단 패턴의 정보의 문구가 같아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 확인 부탁드립니다~!

**Comment by NineSyu** [comment]
다국어 번역 다시 해서 적용하였습니다.
재접속 후 확인하시면 스킬이름과 패턴이름 동일하게 표시되게 수정하였습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200240-240.0.4
iOS.v240.0.4(123)

![이슈](https://github.com/user-attachments/assets/0a913c91-c0eb-4d73-a19f-0110b7e2b769)
