### ISSUE TITLE
스테이킹 폴리싱 1차

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4311]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/c50a68c0-9e25-4297-b414-2597b951e5aa)

![Image](https://github.com/planetarium/NineChronicles/assets/102953029/72f22f63-bc26-41ad-9df7-35405604893b)

팝업에 대한 내용은 추후 재호님이 알려주시기로 했음

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/staking_polishing
사용 프리퓁 :

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/d8b0e7a4-845d-4ae8-86b0-4ee9f41c38c4)

StakingReward 루비 더스트가 들어간. 기존 보다 가로가 긴 이미지를 새로 드렸습니다.
전달 드린 이미지의 폭이 원래 사이즈로 나오도록 Set Native Size 적용 부탁드립니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/624402c6-0e8b-4027-9f50-b246658e7bfd)

스테이킹 안한 유저 NEW 마크 한 번 보여줍니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/ef625de1-771f-453e-b90b-f9f53fbefc80)

스테이킹 한 유저는 보상 받을 때까지의 시간과 레벨, 스테이킹 한 금액을 표기해 줍니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/dafe6b54-425f-4ab0-9473-a8201e464270)

스테이킹 후 받을 보상이 있을 때 이펙트와 레드닷 표기해 줍니다.

**Comment by Namyujeong** [comment]
@boramqo83 `Lv.3 5,000` 저번에 스레드에서 말씀드렸던 것처럼, 아이폰에서 보면 딱봐도 하단 바랑 간섭되는 위치거든요. 위치 등에 있어서 다시 한 번 재고 부탁드립니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/7b3b3624-8942-42dc-87c2-0bea05c247bb)

다리의 가장 위에 위치했습니다.
이 보다 더 위로 올리면... 물 위에 떠 있게 됩니다. @Namyujeong

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/d37dffec-8791-47a1-ba5e-65fcd6d452fa)

**Comment by sonohoshi** [comment]
프리팹 충돌을 고려해서 미리 development에 머지했습니다. 기능은 이제부터 다시 브랜치 만들어서 작업합니다
