### ISSUE TITLE
프롤로그 마지막 캐릭터 스파인이 깨짐

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4318]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1709364651947379

**Comment by eugene-doobu** [comment]
아래 pr에서 수정하였습니다
https://github.com/planetarium/NineChronicles/pull/4307

**Comment by tyrosine1153** [comment]
duplicated with https://github.com/planetarium/NineChronicles/issues/4301
