### ISSUE TITLE
스테이지 정보 경험치 뒤에 커서같은 것이 보임

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4326]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1709602370801289

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/stageinfo-edit
사용 프리퓁 : UI_StageInformation

구분 선 빼는 것으로 적용해 두었습니다.
