### ISSUE TITLE
적 아우라 이펙트가 뒤집혀 보임

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4337]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1709684494764069

![Image](https://github.com/planetarium/NineChronicles/assets/3654082/b000ec9a-0d09-47e4-9ba7-91aa4047dce2)

**Comment by jonny-jeahyunchoi** [comment]
https://github.com/planetarium/NineChronicles/assets/138189475/1afeb21e-8989-4496-848d-5bcdd297605b
![Image](https://github.com/planetarium/NineChronicles/assets/138189475/5977ca06-391e-4478-bfd9-431ca6532191)

**Comment by jonny-jeahyunchoi** [comment]
스프라이트 파티클의 랜더정렬이 View여서 뒤집어져도 원본그대로 보이는문제로 확인

**Comment by jonny-jeahyunchoi** [comment]
@boramqo83 관련내용 한번확인부탁드립니다~! 일단 날개표현하는 아우라는 제가 전부수정했어요~!

**Comment by boramqo83** [comment]
날개가 정상적으로 나오는지 확인해 달라는 말씀일까요?
아니면 모든 아우라 이펙트의 RenderAlignment를 local로 세팅하면 되는 걸까요?
@jonny-jeahyunchoi

**Comment by jonny-jeahyunchoi** [comment]
보통 이팩트를 뒤집어도 이미지좌우가 바뀌지않도록 RenderAlignment가 viewmode로 사용되고있었는데요 날개의경우에는 같이뒤집어져야되서 local로 바꿔야된다는내용이에요. 일단은 방법만알고계시면될것같고, 아우라 날개말고도 기존 이팩트중에 같이 뒤집혀져야하는 이팩트가있는지 체크한번부탁드린거였습니다~!

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/48627190-e945-4be3-af23-003bfbfba6fc)
