### ISSUE TITLE
스파인 교체

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4340]
https://planetariumhq.slack.com/archives/CBU2JFAF3/p1709630167530879

부모 브랜치 : development
적용 브랜치 : ui/spine-update

**Comment by boramqo83** [comment]
40100030 : 한 번도 등록한 적 없는 것이라 적용 안함(활 들고 있는 코스튬)
209002 : 8월드 몬스터는 feature/8-world-data-test브랜치에 등록

**Comment by boramqo83** [comment]
@eugene-doobu 
유진님.
요 테스크 유진님이 다른 곳에서 처리하신 것 같은데 맞는지 확인 부탁드립니다.
이미 적용된 상태라면 해당 테스크 Done으로 옮겨주세요.

**Comment by boramqo83** [comment]
아트 > In progress에 있어서 Review로 옮겼습니다.
유진님. 해당 작업 하신 것이 아니시라면 머지 부탁드려요. @eugene-doobu

**Comment by eugene-doobu** [comment]
@boramqo83 저번 제가 수정한 아틀라스랑 내용이 겹치는 부분이 있어서 제대로 적용되지 않은 부분이 있는것으로 확인되었습니다! 제가 다시 작업내용 적용하고 완료처리 해두겠습니다
