### ISSUE TITLE
인게임 스테이킹-현재 레벨에 해당하는 보상 UI 폴리싱

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#4352]

**Comment by sonohoshi** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/48484989/c754f161-b7b2-4a95-a27d-68b9770cc068)

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/4b36b41c-57f1-471c-a892-c9dea8ab9817)
