### ISSUE TITLE
클라이언트에서 클리어하지 못한 전투를 클리어한것처럼 보여주는 문제

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#4355]
https://planetariumhq.slack.com/archives/C016RR80TK9/p1709626443130329

실제로 체인상에서는 클리어하지 못했지만, 클라이언트의 전투 재연에서는 클리어되어 다음 스테이지에 도전하려다 Action단에서 실패하고 에러 팝업을 받는 것으로 보임

**Comment by sonohoshi** [comment]
이거 조사 시작해봅니다

**Comment by sonohoshi** [comment]
https://planetariumhq.slack.com/archives/CBU2JFAF3/p1711209127674459

**Comment by sonohoshi** [comment]
제보된 tx 모두 playCount가 1인것으로 보아 클라이언트단에서 전투 반복 재현으로 인한 문제는 아닌듯

**Comment by sonohoshi** [comment]
제보된 케이스 모두 공통적으로 166 스테이지를 클리어하지 못했는데 클라에서는 클리어했다고 보여주고 있는 상태

**Comment by sonohoshi** [comment]
rc 브랜치 기준 로컬 Agent에서는 Simulator의 random값까지 일치하는 상황을 확인하여... main에서 쓰던 StageSimulator에 이상이 있는지 확인할 필요가 있겠습니다

**Comment by sonohoshi** [comment]
지금 클라이언트 단에서 rc 브랜치와 main의 Simulate 상태가 크게 차이는 안나보이는데, 애시당초 client의 Simulate 방식이 HAS action의 Simulate와 차이나는 부분이 있어보여서 정리를 할 필요가 있겠고...

**Comment by sonohoshi** [comment]
https://github.com/planetarium/NineChronicles/blob/main/nekoyume/Assets/_Scripts/Extensions/ActionEvalToViewModelExtensions.cs#L30
클라이언트는 이 부분을 정리할 필요는 있겠다 정도로 마무리...
나머지 조사는 tx 리플레이 같은게 있어야 원활한 조사가 가능할 것 같습니다.

**Comment by sonohoshi** [comment]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1712118329465659?thread_ts=1712117643.493809&cid=C062ZS68A21
팀 내에서 345 스테이지를 대상으로도 발생했다는 제보

**Comment by sonohoshi** [comment]
일단 하나 잡아낸건 1회성 버프가 클라에서 써진것처럼 보여서 그런거였고요, 실제로 tx 이력을 뒤져보니까 344 스테이지에서 쓴 1회성 버프 아이디가 345 스테이지 tx에 같이 들어갔고+액션단에서는 1회성 버프를 무시했으나 클라가 혼자 1회성 버프를 사용해서 시뮬레이트를 돌린 케이스입니다.
그래서 대충...
1회성 버프가 액션단에서는 정상적으로 무시됐는지
그렇다면 클라는 왜 갑자기 1회성 버프를 썼는지
정도를 타겟으로 조사해볼 예정입니다.
별개로 repote replay를 클라에서까지 재연한 내용에 대해선 따로 기록 남겨두겠습니다

**Comment by sonohoshi** [comment]
```cs
if (eval.Action.StageBuffId.HasValue)
{
    var skill = CrystalRandomSkillState.GetSkill(
        eval.Action.StageBuffId.Value,
        tableSheets.CrystalRandomBuffSheet,
        tableSheets.SkillSheet);
    skillsOnWaveStart.Add(skill);
}
``` 찾았다 범인

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재 발생 확인되었습니다.
확인 부탁드립니다.

[테스트 환경]
메인넷.Windows.v200200-v200.1.2
![image](https://github.com/user-attachments/assets/f6703abb-e9ac-45c2-9fe9-4d56d63e8cfb)
해당 이슈 발생 당시 로그 파일 공유드립니다.
[Log.zip](https://github.com/user-attachments/files/16229569/Log.zip)

**Comment by sonohoshi** [comment]
로그 분석 시작합니다.

**Comment by sonohoshi** [comment]
https://heimdall.9cscan.com/tx/febf523a839fe42c808d8bccdff2d3ae813f4f7696a75c83d0ffeb2d7cf9d2e1
두번째 tx도 331 스테이지 시도, 성공

**Comment by sonohoshi** [comment]
https://heimdall.9cscan.com/tx/23a69ad8ac380e0dfd9b3427f11b1fe505011a1d8ebd1d002c3c3ba073f4afac

세번째 tx가 332 스테이지고...

**Comment by sonohoshi** [comment]
https://heimdall.9cscan.com/tx/ca7127b808361ec479755eb2bd756c7e1a4ea9adeeb10a39b60a533d80e535a4
네번째 tx가 333 스테이지 시도, 이게 실패로 떴고...

**Comment by sonohoshi** [comment]
로그 봤을때 332를 못깼으니 3번째 tx에서 전투 렌더가 잘못된걸로 보임

**Comment by sonohoshi** [comment]
이전처럼 랜덤버프가 섞여들어가서 렌더된 케이스는 아니고

**Comment by sonohoshi** [comment]
이게 뭐지?

**Comment by U-lis** [comment]
1. Remote replay 를 이용해서 Tx 에 특이한 점이 있는지 (평소와 다른 조건같은게 있는지) 체크
2. 발생 시 앱이 종료되는 것에 대해서는 별도 이슈로 대응
