### ISSUE TITLE
인게임 스테이킹-보상 받았을때 룬 갯수가 업데이트되지 않는듯함

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#4360]

**Comment by jaeho0103** [comment]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1709776115110659

제보내용을 일단 제목에 써주시고 체크할수 있는 기록과
예상되는 부분에 대해서는 디스크립션 이용해주시면 더 체크하기 쉽지 않을까 싶습니다.

**Comment by sonohoshi** [comment]
#4350 이슈 처리할때 같이 처리하도록 하겠습니다.

**Comment by jaeho0103** [comment]
내용 포함할 이슈에 이 부분도 체크해야한다고 커멘트 추가해주시면 좋을 것 같습니다.
