### ISSUE TITLE
Unity version up to 2021.3.37f1

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#4367]

**Comment by sonohoshi** [comment]
https://www.youtube.com/watch?v=Cx5pK7HAl0c

**Comment by ipdae** [comment]
iOS sdk랑 별개로 진행되야함

**Comment by sonohoshi** [comment]
버전 올리고 ci에서 나온 빌드로 ios에서 결제 테스트까지 성공, pc에서 전투 등 tx 정상적으로 렌더되고 처리되는 것 확인
