### ISSUE TITLE
[이벤트] 모카버스 이벤트 던전 스테이지 진행 시 간헐적으로 진행이 멈추는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4368]
### APV version info

v200152

### Client version info

v152.0.0

### Device

Windows

### detailed device info

Windows

### account address info

0xD9fCe9E571ed4bdB34D3CF46A918Eb6938571a5B

### What happened?

[내용]
모카버스 이벤트 던전 스테이지 진행 시 간헐적으로 진행이 멈추는 현상
-PC 환경에서 확인하였습니다.
-첨부 드린 영상 및 로그 파일 확인 부탁 드립니다.

[Log_0307.zip](https://github.com/planetarium/NineChronicles/files/14520778/Log_0307.zip)

https://github.com/planetarium/NineChronicles/assets/156992678/12b7b4bd-10db-4b30-96e8-e51e70eb0775

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 어드벤처 > 이벤트 던전 진입
2. 임의의 이벤트 스테이지 진행하여 진행 멈추는 현상 확인

[Should be]
전투 진행 시 멈추지않고 결과화면까지 정상적으로 진행되어야 합니다.

**Comment by ipdae** [comment]
- 전투종료후 상태업데이트때 문제가 있는것으로 예상중입니다.
- @U-lis 님 제보로는 일반스테이지에서도 발생하셨다고 합니다.
