### ISSUE TITLE
간헐적으로 전투 결과화면이 안나오고 마지막 웨이브 승리 상태에서 머뭄

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4370]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1709800244796529

**Comment by ipdae** [comment]
현재 추정되는 2가지 증상
- 전투결과창이 뜨기전
- 다음스테이지로 넘어갈때

**Comment by jonny-jeahyunchoi** [comment]
이벤트 스테이지에서 퀘스트 갱신하다가 멈추는것과 동일이슈로 확인되고 디테일한 원인 트레킹용 로그와 타임아웃 작업이 들어가있는상황이라 close처리합니다
