### ISSUE TITLE
월드보스 결과화면 표시 skip 가능하게 설정

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4376]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1706491232478909

월드보스 보상을 받을때 화면을 클릭하면 해당 연출 스킵하는 기능 추가 요청드립니다.

**Comment by eugene-doobu** [comment]
아래 pr에서 작업 진행하여 close처리 해두겠습니다
https://github.com/planetarium/NineChronicles/pull/4456
