### ISSUE TITLE
8월드 리소스 수정

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4385]
(완료)
- 배경 화면에 맞게 맞추기
- 몬스터 크기 조정
- 크리티컬 글씨 단위가 커지니 줄 바꿈 되고 있음
- 몬스터 스파인 조정 (209002, 209004, 209005, 209006, 209007)
- 죽을 때 보스가 검정으로 되지 않도록 한다. (검정색이 아닌 사라지게 처리되었음)
- 8월드 아이콘 화질 구지한 것 같은데 확인 필요(장비 아이템 샤픈 한 번씩 적용한다.) - 아트
- 맵 아이콘 붉은색으로 색 더 넣기 - 아트
- 눈 스킬 바닥 이펙트의 뎁스를 캐릭터 뒤로 해야 함 - 아트
- 스킬 수정 상미님이 내 자리에서 하신다고 했음. 그 설정은 조니님이 알려준다고 했음 - 아트

8월드 아트 수정사항 모두 완료해서 올려두었습니다.
적용 브랜치 : feature/8-world-data-test

**Comment by boramqo83** [comment]
이건 Done로 옮기겠습니다. @jonny-jeahyunchoi
