### ISSUE TITLE
빠른 퀘스트 UI 개선

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4391]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/5b1435e3-1ceb-4449-9d8c-1bd67f6b4b5f)

영역이 너무 넓어서 인게임 게이지와 겹쳐서 보여지고 있음

![Image](https://github.com/planetarium/NineChronicles/assets/102953029/d0185ba8-91d1-492c-b083-abc35f979131)

가로폭을 좁혀서 적용하자

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/quick_quest-edit240314
사용 프리퓁 : 
UI_Menu
GuidedQuestCell
GuidedQuest
UI_Battle



![Image](https://github.com/planetarium/NineChronicles/assets/102953029/5f6ffc57-af14-453e-9022-fdd47d9d85dc)



![Image](https://github.com/planetarium/NineChronicles/assets/102953029/8e411414-0577-4848-86f3-8a32cbc1f47e)

위와 같이 크기 줄여서 등록해 두었습니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/902da7f8-fe98-4b9f-b081-258fbf4da7ea)
