### ISSUE TITLE
모바일 상점 리스트의 위아래 부드럽게 빠지는 부분 Save Area 영역까지 늘어나도록 처리

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4392]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/811179ed-9936-4c22-833e-763b94b8bd0f)

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/mobile_shop_bg-edit
사용 프리퓁 :

**Comment by jonny-jeahyunchoi** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/138189475/ae67e45f-533b-45e9-9cbe-bf3710db931e)

실적용시 위치가 깨지는문제가 보입니다.

**Comment by boramqo83** [comment]
다시 확인해보겠습니다

**Comment by jonny-jeahyunchoi** [comment]
![image](https://github.com/planetarium/NineChronicles/assets/138189475/864cdcdd-58a9-453f-b9df-7e3bdb30dc2a)
좌측 카테고리에 NotchAdjuster가 빠져서 옆으로튀어나오게되는데 괜찮은건가요?

**Comment by boramqo83** [comment]
아앗. 죄송합니다.
제가 꼼꼼히 살피지 못했네요.
그것도 수정해서 다시 올리겠습니다.
혹시 ui/mobile_shop_bg-edit2 요 브랜치 머지하셨나요? @jonny-jeahyunchoi

**Comment by jonny-jeahyunchoi** [comment]
아직 머지안되었어요~!

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/68835cdb-38bc-415f-a7d9-2b8ef0ff544e)

세이프 어리어 안에 들어가지도록 수정해서 올려두었습니다.
죄송하지만 한 번 더 확인 부탁드립니다. (꾸벅) @jonny-jeahyunchoi

**Comment by jonny-jeahyunchoi** [comment]
![image](https://github.com/planetarium/NineChronicles/assets/138189475/e924e147-f842-47ac-9aef-e766c5bfc639)
수정사항항 확인했습니다~! 감사합니다~!
