### ISSUE TITLE
이펙트 작거나 안보이는 부분 수정

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4395]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/16824b6f-1ac0-49e2-a9a4-df5b37dbec2f)

스케일모드를 UI Effect로 적용시켜 주세요.
별 크게 나오는 부분을 줄여주시거나 제거해 주세요.

위 방법 말고 다른 방안이 있으면 작업 후 공유해 주세요.

**Comment by QgamesGeonPyoNoh** [comment]
현재 스테이킹 이펙트는 출력 확인되었으나, 정찰 보상 활성화 이펙트가 출력되지 않고 있습니다.
해당 현상 확인 부탁드립니다.

[테스트 환경]
Windows.v200160.v160.0.3
iOS.v160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/1659a54f-e4d4-4845-89d9-4dfeaaaa434e)

**Comment by QgamesGeonPyoNoh** [comment]
현재 정찰 보상 활성화 이펙트 확인 시, 기존에 출력되던 광원 효과가 누락되어 출력되고 있습니다.
확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/af1dad36-f17a-4d13-baa0-5ebac75f7160)

[테스트 환경]
Windows.v200160-160.0.4
Android.v200160-160.0.4
iOS.v160.0.4(41)

**Comment by sonohoshi** [comment]
#4608 과 중복으로 close해두겠습니다
