### ISSUE TITLE
[Bug]: 클라이언트 월드맵에서 스테이지 클리어 정보 갱신 문제 

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#4396]
### APV version info

v200152

### Client version info

v200152

### Device

Windows

### detailed device info

Windows11

### account address info

0x0784263E46610B5aEaA410eD84d997D50e3b8833

### What happened?

A bug happened!

![Image](https://github.com/planetarium/NineChronicles/assets/58686228/3ff9d5d6-ccdd-47c9-8f4b-077485741b1b)
![Image](https://github.com/planetarium/NineChronicles/assets/58686228/16628206-2ad0-4e2d-980e-7cab10cda9b2)

버그제보인데.. 216스테이지에서 시작해서 쭉쭉 밀었던걸로 기억하는데, 이후 월드맵으로 들어왔는데 216스테이지부터 시작 가능하고 notification은 222스테이지에 가있네요

껏다 키니까 222스테이지부터 플레이가능하긴합니다

### How to reproduce the issue

1. 잘 모르겠음. 스테이지 클리어 이후 발생

**Comment by sonohoshi** [comment]
조사 시작합니다.

**Comment by sonohoshi** [comment]
스테이지 클리어 후 결과 화면에서 스테이지 - 뒤로가기를 통해서 월드맵으로 오면 월드맵이 안꺼지고 WorldInformation도 업데이트가 안된 상태라서 그런것처럼 보이네요
