### ISSUE TITLE
아머 아이콘 바닥 흰색 들어가진 것 빼기

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4398]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/eab5786e-1e92-4958-a761-f80ddf6399f2)

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/armor_icon-edit240308
10230000
10231000
10232000
10233000
10234000

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/9fb0d6d7-853a-4839-a17f-6805108fafbf)
