### ISSUE TITLE
메인화면 브금이 아직 크리스마스 브금이 나오고 있음

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4403]
제곧내 입니다
디폴트 브금으로 변경해야 합니다

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)


https://github.com/planetarium/NineChronicles/assets/156992678/c31ce253-e79a-49a4-b87f-84d355977eb1
