### ISSUE TITLE
[refactoring] dccProfile(pfp)아이콘 관련 개선

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#4405]
### Purpose

클라이언트 리소스에서 dccProfile아이콘 분리

### Document

- dccProfile아이콘을 현재 항상 빌드에 포함되는 리소스 폴더에서 분리하여 관리합니다.
- 이를 위해 aws와 같은 외부 저장소를 사용을 고려중입니다.

### issue description

- 클라이언트 프로젝트에서 이미지 3000개를 제거합니다
- 항상 모든 프로필 이미지를 빌드에 포함하지 않습니다
- 이미지가 바뀌지 않는다고 가정하면은 dcc프로필 이미지를 로컬 디바이스에 파일로 캐싱해서 사용합니다

**Comment by jonny-jeahyunchoi** [comment]
![image](https://github.com/user-attachments/assets/14fb5eb4-9023-4769-a2d5-ecd9236c2f54)
순수 리소스 용량 33MB 정도 됨.
