### ISSUE TITLE
이벤트 던전 마지막 스테이지에서 retry 버튼이 나오지 않는 이슈

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4406]
이벤트 던전 마지막 스테이지에서 retry 버튼이 나오지 않는 이슈

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1710147566836309?thread_ts=1710147566.836309&cid=C062ZS68A21)

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 발생 확인했습니다.
이슈 되돌리겠습니다.

[테스트 환경]
Windows.v200160.v160.0.3
iOS.v160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/3c2df5a8-cab8-4b89-bbf6-c0cd6ab6fbe6)

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.4
Android.v200160-160.0.4
iOS.v160.0.4(41)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/73c109b7-8d0c-4aea-b660-d66c12253c3e)
