### ISSUE TITLE
행동력 팝업에서 UI 겹치는 현상

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4430]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/7c67ed79-f5b0-4cc3-be3e-d646eba79e36)

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/material_navigation_popup-edit
사용 프리퓁 : UI_MaterialNavigationPopup

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/c62b62af-b16c-410f-b41e-dc4e2044aaed)
