### ISSUE TITLE
[룬] 간헐적으로 아레나 스턴룬으로 전투할 경우 스턴이 풀리지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4443]
### APV version info

메인넷.v200152

### Client version info

v152.0.0

### Device

Windows

### detailed device info

Windows 11

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
간헐적으로 아레나 스턴룬으로 전투할 경우 스턴이 풀리지 않는 현상
-유저 제보 받아서 PC 환경에서 확인하였습니다.
-실제 재현해본 결과 스킬의 턴 감소 및 사용은 되었으나, 제보받은 영상 확인 시, decreases speed - hp 스킬이 사용되어 피격자의 spd가 낮아지면 스턴 스킬의 쿨타임이 돌아올때까지 턴 회복을 못하는 것으로 확인됩니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/3b69b0f6-834d-4a98-b178-05358e8cb24f

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 아레나 진입
2. 임의의 상대 선택하여 전투 준비 화면에서 스턴 룬(아레나) 장착
3. 전투 중 무한스턴이 걸리는 것을 확인

[Should be]
스킬 사용 후 전투 진행 시 스킬의 남은 턴 수가 정상적으로 감소되고 전투가 진행되어야 합니다.

**Comment by ipdae** [comment]
https://github.com/planetarium/lib9c/issues/2467 로 v160에서 해결됐습니다.
