### ISSUE TITLE
메일 보상받기 버튼 크기와 이펙트가 안맞음

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4451]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/2da8c326-8b70-4db3-aec3-e086c3bf0b08)

버튼 높이를 줄여야 할 것으로 보임

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/receive_button_effect-edit
사용 프리퓁 : MailCell

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/99d9a76c-bbfc-44ac-b49c-bb90e494be9e)
