### ISSUE TITLE
월드보스 마지막에 느리개 재생되도록 연출한 것이 이후에도 적용됨

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4470]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1710481806660099

이후에도 느리게 재생이 적용되어 보상 팝업, 킬보너스 팝업, 다음 티켓 사용, 캐릭터 아이들 애니메이션이 모두 느리게 재생됨

**Comment by eugene-doobu** [comment]
아래 이슈에서 같이 처리하겠습니다
https://github.com/planetarium/NineChronicles/issues/4892
