### ISSUE TITLE
신규 튜토리얼시 아우라 그라인딩시 바우처 메세지 남아있는 부분 삭제

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#4479]
신규 튜토리얼시 아우라 그라인딩시 바우처 메세지 남아있는 부분 삭제

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/49dcc8b9-e2b0-4884-b105-b6ec19fcd8e5)

위와 같이 나오도록 재호님께 이미지 전달 드렸습니다.

**Comment by jaeho0103** [comment]
이거 혹시 @boramqo83 님이 리소스 파일 교체해서 pr 처리해주실수 있으실까요?

**Comment by jaeho0103** [comment]
텍스트는 교체 해서 올라가 있습니다.

**Comment by boramqo83** [comment]
아하. 프리퓁 안이 이미지가 있다면 제가 처리 가능합니다.

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/160.0.x
적용 브랜치 : ui/qa_tutorial_image-edit
사용 프리퓁 :

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.6
Android.v200160-160.0.6
iOS.v160.0.6(43)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/fad873b0-e419-46c1-9a9d-81afdc7b3d85)
