### ISSUE TITLE
제작에서 컬렉션 바로가는 버튼 동작

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4480]
좌하단 컬렉션 페이지로 이동 시켜주는 버튼 적용이 안된 상태로 올라가졌습니다.

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1710726867370649?thread_ts=1710726867.370649&cid=C062ZS68A21)

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.3
iOS.v160.0.3(39)

https://github.com/planetarium/NineChronicles/assets/150774808/a331c0e7-16a3-4f4a-b42f-8fb6d8f471e0
