### ISSUE TITLE
도감에서 아이템 필요수량, 보유수량 정보표기 맞게 적용시키기

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#4481]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/02608b60-9600-43f9-ab9f-842f1a8ca649)

**Comment by ipdae** [comment]
https://github.com/planetarium/NineChronicles/pull/4474/commits/b7f5f623308f1803d6e80af6f9f651a5edd9a9b8 체리픽

**Comment by eugene-doobu** [comment]
동일내용 QA 이슈에서 처리하겠습니다
https://github.com/planetarium/NineChronicles/issues/4485
