### ISSUE TITLE
배너리소스 해상도 정상출력되지않음

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4482]
배너리소스 해상도 정상출력되지않음
https://planetariumhq.slack.com/archives/C011716SDTM/p1710729365942619

**Comment by jonny-jeahyunchoi** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/138189475/d5b2fe0d-85ab-47d6-9539-51cc20bf64f8)
에디터에서는 재현이안되나 빌드나온것으로는 재현이됨.
다운로드받는 URL이 동일하고 플랫폼분기도 따로없어서 UnityWebRequestTexture.GetTexture 스팩이 뭔가 바뀌었는지 확인해봐야함.

**Comment by boramqo83** [comment]
https://github.com/orgs/planetarium/projects/97/views/8?filterQuery=assignee%3Aboramqo83&pane=issue&itemId=56756268
위 잇슈도 같은 내용인 것 같아 연결해 둡니다.

**Comment by jonny-jeahyunchoi** [comment]
https://forum.unity.com/threads/unitywebrequesttexture-gettexture-need-mipmaps-option.1514849/
UnityWebRequestTexture.GetTexture 의 경우 자체 mipmap을 생성하여 저해상도 이미지가 나올수있는문제 확인하였습니다.
관련한 추가옵션이 아직 없기 때문에 UnityWebRequestTexture.GetTexture를 사용하지않고 이미지바이너리를 그대로 받아서 사용하는방식으로 수정합니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.3
iOS.v160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/8a6f533a-8a86-4f27-8eed-b43d97c27e2c)
