### ISSUE TITLE
[컬렉션] 우측 등록아이템 상세 정보 영역에 강화도 및 보유 수량 텍스트가 정상적으로 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4485]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
우측 등록아이템 상세 정보 영역에 강화도 및 보유 수량 텍스트가 정상적으로 출력되지 않는 현상
-목표 강화도가 없는 아이템에도 'Required level: +5' 텍스트가 표시되는 것을 확인하였습니다.
-현재 강화도가 없는 아이템에도 'Highest item level: +2' 텍스트가 표시되는 것을 확인하였습니다.
-음식/재료 아이템의 경우 보유수량 텍스트와 겹쳐서 출력되는 것을 확인하였습니다.
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/b69e4351-0a5f-45f4-96c3-a8fa610a9a17)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 컬렉션 진입
2. 임의의 도감 항목의 아이템 선택하여 우측 상세 정보 영역 출력
3. 우측 상세 정보 영역에 강화도 및 보유 수량과 관계없이 'Required level: +5','Highest item level: +2' 텍스트가 출력되는 것을 확인

[Should be]
우측 상세 정보 영역에 목표 강화도 및 보유 수량과 관련한 텍스트가 정상적으로 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/issues/4481
해당 이슈에서 처리하는것으로 하겠습니다

**Comment by eugene-doobu** [comment]
해당 pr에 수정내용 작성하였습니다. 확인시 참고 부탁드립니다. @QgamesTaekHaJang 
https://github.com/planetarium/NineChronicles/pull/4486

**Comment by QgamesTaekHaJang** [comment]
공유 감사드립니다.
이후 수정 빌드에서 해당 내용 재확인 진행하도록 하겠습니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.
다만 +0 강화 장비 및 코스튬의 경우 필요 수량 및 현재 수량이 출력되고 있는데,
해당 장비 및 코스튬을 보유하고 있음에도 보유 수량이 0으로 출력되는 것을 확인하였습니다.
해당내용 확인 부탁 드립니다.
이슈 되돌리겠습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/0335d638-e75b-4940-bf01-d0e5cb66925a)
![Image](https://github.com/planetarium/NineChronicles/assets/156992678/63e2f31e-ba91-41cf-b4b7-3f406a1ca643)

**Comment by eugene-doobu** [comment]
> 수정 내용 확인 완료되었습니다. 다만 +0 강화 장비 및 코스튬의 경우 필요 수량 및 현재 수량이 출력되고 있는데, 해당 장비 및 코스튬을 보유하고 있음에도 보유 수량이 0으로 출력되는 것을 확인하였습니다. 해당내용 확인 부탁 드립니다. 이슈 되돌리겠습니다.
> 
> [테스트 환경] Windows.v200160-.v.160.0.3 iOS.v.160.0.3(39)
> 
> ![Image](https://private-user-images.githubusercontent.com/156992678/314033939-0335d638-e75b-4940-bf01-d0e5cb66925a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTkzOTMsIm5iZiI6MTcxMDkxOTA5MywicGF0aCI6Ii8xNTY5OTI2NzgvMzE0MDMzOTM5LTAzMzVkNjM4LWU3NWItNDk0MC1iZjAxLWQwZTVjYjY2OTI1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNzE4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzI5MGZkN2FhOGMwNzE0ZjIwYTIxNmY2MTRhZWI3NTIxODJkZmZkZTAwNzE0OGFjZDY3OTAzZGViZGE0YTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GaUuL76bPAST5glG8I-TrZsN-MH_dMiloJPQ2UqCKbk) ![Image](https://private-user-images.githubusercontent.com/156992678/314033938-63e2f31e-ba91-41cf-b4b7-3f406a1ca643.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTkzOTMsIm5iZiI6MTcxMDkxOTA5MywicGF0aCI6Ii8xNTY5OTI2NzgvMzE0MDMzOTM4LTYzZTJmMzFlLWJhOTEtNDFjZi1iNGI3LTNmNDA2YTFjYTY0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNzE4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTFmZmFjMTQxM2U0Mjc5YzkyNWM3MzcyZTNlZGNmMjJhOTA2ZDQ4MDViZmI5ZGI0NTg5NmM3ZGI3MzI4NGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qI4MIMDKxL5gQUwXgrzyrLLSCRlrNEg9V9m44VXK0gg)

해당 내용 아래 PR에서 수정하였습니다! 확인시 참고 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/4572

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.4
Android.v200160-160.0.4
iOS.v160.0.4(41)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/6cd932b3-d332-4222-a967-0acfcf1849bb)
