### ISSUE TITLE
[월드보스] 월드보스 랭킹 내 본인 랭킹에서 레벨 박스가 외부로 벗어나며 태그가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4487]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0xdde23c49C0e36B5f8206Dbdac60675288484B37E

### What happened?

[내용]
월드보스 랭킹 내 본인 랭킹의 레벨 박스가 외부로 벗어나며 태그가 출력되지 않는 현상
-이전 시즌 랭킹에서도 동일하게 발생하고 있습니다.
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/f41bf913-9573-4c31-abf0-19bef61f95c8)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 월드보스 진입
2. 랭킹 버튼 클릭
3. 본인 랭킹에서 레벨 박스가 외부로 벗어나는 현상 확인
4. 본인 랭킹에서 캐릭터 태그가 출력되지 않는 현상 확인

[Should be]
월드보스 랭킹 내 본인 랭킹에서 레벨 박스가 레벨 위치에 출력되어야 합니다.
월드보스 랭킹 내 본인 랭킹에서 캐릭터 태그가 출력되어야 합니다.

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/160.0.x
적용 브랜치 : ui/qa_worldboss_mylevel_bg-edit
사용 프리퓁 :

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.3
iOS.v160.0.3(39)

![화면 캡처 2024-03-19 203353](https://github.com/planetarium/NineChronicles/assets/150774808/2b7e5de7-d260-472d-b341-e3060249aac6)
