### ISSUE TITLE
[컬렉션] 등록 조건 달성한 아이템 선택 시 우측 상세 정보 영역에 획득처가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4488]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
등록 조건 달성한 아이템 선택 시 우측 상세 정보 영역에 획득처가 출력되는 현상
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/43181f72-5f07-463f-8373-e46ad5ab0670)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 컬렉션 진입
2. 임의의 등록 조건 달성한 아이템 선택하여 우측 상세 정보 영역 출력
3. 우측 상세 정보 영역 하단에 획득처 바로가기 버튼이 출력되는 것을 확인

[Should be]
등록 조건 달성한 아이템 선택 시 우측 상세 정보 영역에 획득처 버튼이 출력되지 않아야 합니다.

**Comment by jaeho0103** [comment]
등록 조건 달성한 아이템에서도 기본 아이템 획득처를 안내해주는건 의도된 스펙입니다.

**Comment by QgamesTaekHaJang** [comment]
코멘트 확인하여 해당 내용 정상 스펙인 것을 확인하였습니다.
확인 감사드립니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)
