### ISSUE TITLE
[이벤트 던전] 이벤트 던전 내에서 이벤트 퀘스트 가이드 텍스트가 상단 정렬로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4489]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
이벤트 던전 내에서 이벤트 퀘스트 가이드 텍스트가 상단 정렬로 출력되는 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/e0375bcf-d8ea-40fd-96f3-9ecea628dcae)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 어드벤쳐 - 이벤트 던전 진입
2. 임의의 이벤트 던전 스테이지 진입
3. 던전 내에서 이벤트 퀘스트 가이드 텍스트가 상단 정렬로 출력되는 현상 확인

[Should be]
이벤트 던전 내에서 이벤트 퀘스트 가이드 텍스트가 중앙 정렬로 출력되어야 합니다.

**Comment by Namyujeong** [comment]
@boramqo83 이거 보상이 없을 때에는 위치가 어색한 것 같은데, 이벤트 퀘스트 가이드에서도 획득 재료를 보여주거나 하는게 나을거 같습니다.

**Comment by boramqo83** [comment]
![image](https://github.com/planetarium/NineChronicles/assets/102953029/58751583-c07c-4b75-b8fe-efc3c0b992f1)
활성화 상태가 아닐 때 해당 영역의 중앙에 텍스트가 배치되도록 했는데 활성 중일 때는 처리하지 못했습니다.
텍스트를 중앙으로 배치하는 방향으로 진행합니다.
기획적으로 보상을 주고자 할 경우 말씀 주시면 그 때 반영하는 것으로 진행합니다. @Namyujeong

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/160.0.x
적용 브랜치 : ui/qa_quick_quest-edit
사용 프리퓁 : UI_Menu

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.3
iOS.v160.0.3(39)

![image](https://github.com/planetarium/NineChronicles/assets/150774808/3fc9446f-a335-43e2-8782-53b8b6500de4)
