### ISSUE TITLE
[컬렉션] 임의의 아이템 'Shop (PC)' 획득처 버튼 선택 시 거래소에 해당 아이템 검색되지 않은 상태로 이동되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4490]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows

### detailed device info

Windows 11

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
임의의 아이템 획득처 버튼 선택 시 거래소에 해당 아이템 검색되지 않은 상태로 이동되는 현상
-Craft버튼의 경우 해당 아이템이 선택된 상태로 제작 화면으로 이동되는 것을 확인하였습니다.
-장비/음식/코스튬에서 동일하게 확인되었습니다.
-AP포션/모래시계의 경우 선택 시 해당 탭으로 이동하지 않는 것을 확인하였습니다.
-PC 환경에서 확인하였습니다.
-첨부 드린 영상 및 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/760596a5-4586-4309-bb33-aedb1bd5059e)

https://github.com/planetarium/NineChronicles/assets/156992678/8b1ad139-879a-40a4-a2c3-5ff928e46321

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 컬렉션 진입
2. 임의의 장비 아이템 선택하여 우측 상세 정보 영역 출력
3. 획득처 버튼에 'Shop (PC)' 버튼 클릭
4. PC 거래소 화면에서 해당 아이템 검색되지 않은 상태인 것을 확인

[Should be]
'Shop (PC)' 획득처 버튼 선택 시 해당 아이템이 검색된 상태로 이동되어야 합니다.

**Comment by jaeho0103** [comment]
해당 부분은 구현하면서 체크했을때 관련 탭이동이나 검색등을 추가해서 이동하는게
구현비용이 많이 드는 이슈로 스펙이 변경된 부분입니다. 최종 스펙은 필터를 하지 않은채
SHOP으로 이동으로 이해해주시면 감사하겠습니다,

**Comment by QgamesTaekHaJang** [comment]
코멘트 확인하여 변경된 스펙인 것을 확인하였습니다.
확인 감사드립니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)
