### ISSUE TITLE
[어드벤쳐] Sweep 264회 이후부터 애니메이션이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4491]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Sweep 264회 이후부터 애니메이션이 출력되지 않는 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/3aee2350-050a-4990-bd22-a444142cd2b3

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 어드벤처 진입
2. 임의의 스테이지 Sweep 264회 초과하여 진행
3. 264회 이후부터 애니메이션이 출력되지 않는 현상 확인

[Should be]
Sweep 264회 이후에도 애니메이션이 출력되어야 합니다.

**Comment by sonohoshi** [comment]
이거 264회 이후의 애니메이션이 안나오는게 아니라, 체인상에서 Sweep tx가 처리되길 대기하는 연출이라서 tx가 처리되면 즉시 애니메이션을 종료하고 있습니다.
애니메이션이 중단되고 보상이 바로 나오는걸 봐선 그래서 그런거같은데, 애니메이션이 중단된 이후 로딩을 이어나가는 케이스가 없다면 의도된 스펙입니다. @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
Sweep 애니메이션이 진행되는 중,
Sweep 진행 중인 스테이지 횟수 / Sweep 진행할 총 스테이지 횟수가 팝업 내에 출력되는 것을 확인하였습니다.
유저들이 확인할 때 해당 화면에서 Sweep이 끝까지 진행되지 않았다고 잘못 인지하게 될 가능성이 있다고 예상되는 부분이어서 해당 부분에 대한 확인이 필요할 것 같습니다.
해당 정보 전달 내용에 문제가 없을 경우, 상기 공유 주신 코멘트 내용 확인하여 정상 스펙으로 인지하고 이슈 종료하는 방향으로 진행하도록 하겠습니다.
확인 부탁드리겠습니다.

**Comment by sonohoshi** [comment]
네. 해당 이슈 자체는 버그가 아니라서 close하면 될 것 같고, 팀 내에서 인지를 어떻게 바꿀지 논의 후 개선 이슈를 별도로 만들도록 하겠습니다. cc @jaeho0103 @boramqo83

**Comment by QgamesGeonPyoNoh** [comment]
확인 감사드립니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160.v160.0.2
Android.v200160.v160.0.2
iOS.v160.0.2(38)
