### ISSUE TITLE
[컬렉션] 장비가 아닌 탭의 필터 버튼 기능에 사용되지 않는 항목이 기능하지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4501]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
장비가 아닌 탭의 필터 버튼 기능에 사용되지 않는 항목이 기능하지 않는 현상
-장비가 아닌 탭에서 필터 항목에 Class/Attribute/Type/Upgrade Level이 체크 가능하며, Class를 제외한 항목은 다른 탭에서 기능하지 않는 것을 확인하였습니다.
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/068650ba-dff1-4c87-abc6-4cf036e48f88

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 컬렉션 진입
2. 임의의 탭 선택하여 하단에 필터 버튼 선택
3. 필터 버튼에 Class를 제외한 임의의 항목 체크하여 필터 기능하지 않는 것을 확인

[Should be]
장비가 아닌 항목들에서 Class를 제외한 항목이 조작되지 않아야 합니다.

**Comment by eugene-doobu** [comment]
아래 pr에 수정내용 작성하였습니다. 확인시 참고 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/4536

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/25ab7dea-623b-4c4a-9d53-a4781046b0a8)
