### ISSUE TITLE
[컬렉션] 컬렉션 필터가 모바일 환경에서 번역되지 않은 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4502]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
컬렉션 필터가 모바일 환경에서 번역되지 않은 현상
-Android / iOS 모두 발생하고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/7fb842e6-83d8-48be-9e43-7f9e593a3943)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 컬렉션 클릭
2. 필터 버튼 클릭
3. 필터가 번역되지 않는 현상 확인

[Should be]
컬렉션 필터가 모바일 환경에서 한국어로 출력되어야 합니다.

**Comment by ipdae** [comment]
번역어 처리관련 확인 부탁드립니다. @eugene-doobu @NineSyu

**Comment by eugene-doobu** [comment]
아래 pr에 수정내용 작성하였습니다. 확인시 참고 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/4538

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200160.v160.0.3
iOS.v160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/4a5f2034-1570-431b-b8ea-9e8720649434)
