### ISSUE TITLE
[컬렉션] ID 정렬 시 오름차순, 내림차순으로 정렬되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4504]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
ID 정렬 시 오름차순, 내림차순으로 정렬되지 않는 현상
-등급,수량,강화 레벨의 경우 정상적으로 오름차순/내림차순으로 정렬되는 것을 확인하였습니다.
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/a20f4c5f-3ccc-4ce4-9fea-d58ce977c500

### How to reproduce the issue

[재현스텝]
1. 메인 화면 > 컬렉션 진입
2. 하단의 정렬 ID로 선택하여 정렬
3. 오름차순/내림차순 버튼 선택하여 ID 오름차순/내림차순으로 정렬되지 않는 것을 확인

[Should be]
오름차순/내림차순 버튼 선택 시 정렬 상태가 오름차순/내림차순으로 정렬되어야 합니다.

**Comment by eugene-doobu** [comment]
아래 pr에서 수정내용 작성하였습니다. 확인시 참고 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/4511
