### ISSUE TITLE
[몬스터콜렉션] 스테이킹 진행하지 않은 계정에서 스테이킹 아이콘에 New 표시가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4506]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
스테이킹 진행하지 않은 계정에서 스테이킹 아이콘에 New 표시가 출력되지 않는 현상
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/baae67d5-f14c-4eda-bb6d-b090b6b841b5)

### How to reproduce the issue

[재현스텝]
1. 스테이킹 진행하지 않은 계정으로 메인 화면 진입
2. 스테이킹 아이콘에 New 표시가 출력되지 않는 것을 확인

[Should be]
스테이킹 진행중이지 않은 계정에서 스테이킹 아이콘 확인 시 아이콘에 New 표시가 출력되어야 합니다.

**Comment by Namyujeong** [comment]
@ipdae 이 이슈는 어사인 왜 빠져있나요?

**Comment by ipdae** [comment]
@Namyujeong 해당동작이 의도된 동작이라 들어서 어사인 돌려드렸습니다. /cc @sonohoshi

**Comment by sonohoshi** [comment]
스테이킹하지 않은 계정에서는 50 NCG 이상 보유하고 있을때 New 표시가 출력되는것이 의도된 스펙입니다. 혹시 이 내용 확인 부탁드려도 될까요 @QgamesTaekHaJang

**Comment by QgamesTaekHaJang** [comment]
확인 감사드립니다.
50NCG 이상 스테이킹 하지 않은 계정에서 확인 시 New 표시가 정상적으로 출력되는 것을 확인하였습니다.
업무에 혼선을 드려 죄송합니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)
![스테이킹_new](https://github.com/planetarium/NineChronicles/assets/156992678/d483f064-b29e-44ff-9467-22cf6adf0c3b)
