### ISSUE TITLE
[이벤트 던전] 아이템 내 이벤트 던전 바로가기가 동작하지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4507]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
아이템 내 이벤트 던전 바로가기가 동작하지 않는 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/e966073d-42f9-4926-a2d5-0bdb51a23f65

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 인벤토리 클릭
2. 재료 탭 - 이벤트 던전에서 드랍되는 재료 클릭
3. 이벤트 던전 바로가기가 동작하지 않는 현상 확인

[Should be]
아이템 내 이벤트 던전 바로가기가 동작해야 합니다.

**Comment by eugene-doobu** [comment]
수정내용 아래 pr에 작성하였습니다. 확인시 참고 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/4517

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)
