### ISSUE TITLE
[몬스터콜렉션] All Rewards 탭에 출력되는 보상 테이블 이미지가 저해상도 이미지로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4508]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
All Rewards 탭에 출력되는 보상 테이블 이미지가 저해상도 이미지로 출력되는 현상
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/e97e72d8-c80f-45e2-b0bb-258ab0b4875d)

### How to reproduce the issue

[재현스텝]
1. 메인화면 > Staking 진입
2. All rewards 탭 선택하여 보상 테이블 이미지가 저해상도로 출력되는 것을 확인

[Should be]
게임 내에 출력되는 이미지의 해상도가 저해상도 이미지로 출력되지 않아야 합니다.

**Comment by boramqo83** [comment]
https://github.com/planetarium/NineChronicles/issues/4482
위 잇슈와 같은 내용이라 연결해 둡니다.
외부에서 불러오는 이미지의 경우 해상도 낮게 나오고 있는 문제

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.3
iOS.v160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/095e5ca6-ad15-4c5d-ba0d-b46ba286d463)
