### ISSUE TITLE
[UI] 거래가능 AP 포션 정보 창이 화면 밖으로 벗어나는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4509]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
거래가능 AP 포션 정보 창이 화면 밖으로 벗어나는 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/386ad378-ab88-4fef-9256-59d4c20098ca)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 인벤토리 클릭
2. 거래가능 AP 포션 클릭
3. AP 포션 정보 창이 화면 밖으로 벗어나는 현상 확인

[Should be]
거래가능 AP 포션 정보 창이 화면 밖으로 벗어나지 않아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 @NineSyu 이거 Acquisition Place가 늘어나서 생긴 사이드이팩트로보입니다. 수정방향 정리가 필요할것같습니다~!

**Comment by jaeho0103** [comment]
이벤트 스테이지로 인한 일시적인 부분이라 수정없이 가도 상관없을 것 같습니다. 다만 이거 Acqusition 이 4개면 다 동일하게 창을 벗어나는 이슈라면 대응해두는게 좋을 것 같습니다. cc @boramqo83

**Comment by boramqo83** [comment]
잇슈 확인했습니다.
이거 목록이 최대 4개까지 나온다고 생각하고 잡으면 되는 것 일까요? @jaeho0103 
![image](https://github.com/planetarium/NineChronicles/assets/102953029/d8c4e580-6bc3-4c0a-bcc9-f04729fd4f1d)
버튼과 텍스트등을 줄여서 밖으로 안나가게 수정하면 될 것 같습니다.
5개까지 나올 수 있다하면... 이런 방법으로는 해결이 안됩니다.

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/160.0.x
적용 브랜치 : ui/qu_tooltip_popup-edit
사용 프리퓁 : UI_ItemTooltip

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)
