### ISSUE TITLE
[컬렉션] 컬렉션 내 소환 바로가기의 아이콘이 계속 변경되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4510]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
컬렉션 내 소환 바로가기의 아이콘이 계속 변경되는 현상
-마지막으로 확인한 바로가기의 아이콘이 적용되고 있습니다.
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/8899e4d9-12a4-4b01-b971-59645012ea81

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 컬렉션 클릭
2. 장비 탭 - 아우라 클릭
3. 소환 바로가기 버튼의 아이콘 확인
4. 임의의 음식 클릭 후 아우라 클릭
5. 소환 바로가기의 아이콘이 계속 변경되는 현상 확인

[Should be]
컬렉션 내 소환 바로가기의 아이콘이 고정되어야 합니다.

**Comment by eugene-doobu** [comment]
수정내용 아래 pr에서 작성하였습니다. 확인시 참고 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/4516

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)
