### ISSUE TITLE
[공방] 장비 레시피의 일부 해금이 가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4512]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
장비 레시피의 일부 해금이 가능한 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/ebfe5b6b-1b30-40be-b369-60d069f6861e

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 공방 클릭
2. 제작 - 장비 클릭
3. 레시피의 일부 해금이 가능한 현상 확인

[Should be]
장비 레시피의 일부 해금은 불가능해야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 @NineSyu  이거 크리스탈 있는만큼만 해금되는것 현스팩 그대로 두어도 되는부분으로보이는데 확인부탁드립니다~!

**Comment by jaeho0103** [comment]
크리스탈이 허용하는 만큼만 최대 해금이 스펙이 맞습니다. 현상황은 스펙대로입니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인하여 변경된 스펙인 것을 확인하였습니다.
확인 감사드립니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160-.v.160.0.2
Android.v200160-.v.160.0.2
iOS.v.160.0.2(38)
