### ISSUE TITLE
[몬스터콜렉션] Migration 팝업에 안내 문구 및 변경되는 보상 내용이 정상적으로 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4513]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
Migration 팝업에 안내 문구 및 변경되는 보상 내용이 정상적으로 출력되지 않는 현상
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/fd97b6e9-68d7-49fd-9f45-034c9bd13019)

### How to reproduce the issue

[재현스텝]
1. 스테이킹 중이었던 계정으로 보상테이블 변경 이후에 메인화면 > Staking 진입
2. Migrate 버튼 클릭
3. Migration 팝업 문구가 정상적으로 출력되지 않는 것을 확인

[Should be]
Migration 팝업 내의 안내 문구 및 변경되는 보상에 대한 내용이 정상적으로 출력되어야 합니다.

**Comment by jaeho0103** [comment]
해당 부분 수정된 L10N 업데이트 되어 RC2 에서 변경 확인 가능하십니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/e6f0d3a0-fe84-4f26-97fb-8816e93285ef)
