### ISSUE TITLE
[어드벤쳐] 400스테이지 클리어 후 Sweep 진행 시 에러코드 출력되며 진행되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4515]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows

### detailed device info

Windows 11

### account address info

0xD9fCe9E571ed4bdB34D3CF46A918Eb6938571a5B

### What happened?

[내용]
400스테이지 클리어 후 Sweep 진행 시 에러코드 출력되며 진행되지 않는 현상
-400 스테이지 에서 Sweep 버튼 클릭 시 Sweep이 아닌 Repeat으로 표기되며 AP포션 최대 사용 수량이 5개까지만 적용되는 것을 확인하였습니다.
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 영상 및 로그 파일 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/d819f0db-9724-4e44-879f-7bc052e48387
[Log_0318.zip](https://github.com/planetarium/NineChronicles/files/14634253/Log_0318.zip)

### How to reproduce the issue

[재현스텝]
1. 400스테이지 클리어 후 메인화면 > 어드벤처 진입
2. 400스테이지 진입하여 Sweep 버튼 클릭
3. Sweep 팝업에서 AP 포션 최대로 설정
4. Sweep 진행하여 에러 팝업 출력되고 Sweep 진행되지 않는 것을 확인

[Should be]
Sweep 진행 시 AP 포션 수량이 20개까지 사용되며, 정상적으로 Sweep이 진행되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
```
SheetRowNotFoundException: CharacterLevelSheet: Key - 401
Nekoyume.TableData.Sheet`2[TKey,TValue].TryGetValue (TKey key, TValue& value, System.Boolean throwException) (at Assets/_Scripts/Lib9c/lib9c/Lib9c/TableData/Sheet.cs:154)
Nekoyume.Helper.AvatarStateExtensions.GetLevelAndExp (Nekoyume.Model.State.AvatarState avatarState, Nekoyume.TableData.CharacterLevelSheet characterLevelSheet, System.Int32 stageId, System.Int32 repeatCount) (at Assets/_Scripts/Lib9c/lib9c/Lib9c/Helper/AvatarStateExtensions.cs:59)
Nekoyume.UI.SweepPopup.GetEarnedExp (Nekoyume.Model.State.AvatarState avatarState, Nekoyume.TableData.StageSheet+Row row, System.Int32 apPlayCount, System.Int32 apStonePlayCount) (at Assets/_Scripts/UI/Widget/Popup/SweepPopup.cs:340)
```
이거 확인해보니 400이상의 시트값이 없어서 발생하는문제로 확인됩니다. sweep exp 계산시 달성 래밸 고려하여 계산되기 떄문에 발생하는문제로보여지고 시트추가되면해결될문제로보입니다.

**Comment by sonohoshi** [comment]
현재는 시트가 업데이트되어 문제가 발생하지 않을 것으로 보입니다. 재확인 부탁드리겠습니다. @QgamesTaekHaJang

**Comment by QgamesTaekHaJang** [comment]
코멘트 확인하였습니다.
이후 수정 빌드에서 해당 내용 재확인 진행하도록 하겠습니다.
공유 감사드립니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)

https://github.com/planetarium/NineChronicles/assets/156992678/9c3726c6-4812-470e-94c4-9415d54eb281
