### ISSUE TITLE
[NCG] Odin에서 Heimdall로 NCG 송금할 경우 Odin에서 NCG는 차감되지만 Heimdall에서 NCG 수령되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4524]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
Odin에서 Heimdall로 NCG 송금할 경우 Odin에서 NCG는 차감되지만 Heimdall에서 NCG 수령되지 않는 현상
-현재 포탈에서 Heimdall에 Voucher로 NCG변환 시도할 경우 Voucher는 차감되지만 NCG가 수령되지 않고 있습니다.
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/d8c249cd-4390-4254-83eb-242d4a5ed7bd

### How to reproduce the issue

[재현스텝]
1. Odin 환경에서 런처> Send NCG 진입
2. 임의의 Heimdall 캐릭터에 NCG 송금
3. Heimdall 캐릭터 로그인하여 NCG 수령되지 않은 것을 확인

[Should be]
Send NCG를 통해 송금할 경우 차감된 NCG 만큼 받는 대상이 NCG 수령이 되어야 합니다.

**Comment by ipdae** [comment]
#4525 와 동일하게 체인초기화가 원인으로 추정되며 조사중입니다.

**Comment by U-lis** [comment]
Odin > Heimdall 로 Tx 를 전달해주는 bridge service 가 체인 초기화 대응이 되어 있지 않아 발생한 것으로 파악됩니다.
현재 bridge service 리셋 완료했으며, Tx 가 잘 넘어가는 것 확인했습니다. 다시 한번 테스트 부탁드립니다 @QgamesTaekHaJang :pray:

**Comment by QgamesTaekHaJang** [comment]
해당 내용은 현재 환경이 아닌 다음 수정 빌드 환경에서 재확인 진행할 수 있도록 하겠습니다.
공유 감사드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.3

https://github.com/planetarium/NineChronicles/assets/150774808/a64b0df9-18f3-49bb-a9b2-94f0ad54e042

https://github.com/planetarium/NineChronicles/assets/150774808/7a2c04dd-4880-497c-b302-8571df832282
