### ISSUE TITLE
[상점] Heimdall 모바일 상점에서 구매한 상품이 지급되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4525]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Heimdall 모바일 상점에서 구매한 상품이 지급되지 않는 현상
-현재 정찰 보상 수령 시 보상이 지급되지 않는 현상도 발생하고 있습니다.
-Android / iOS 환경에서 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/2b6a30cb-7ee6-4972-a14d-41c178fb97b5

### How to reproduce the issue

[재현스텝]
1. Heimdall - 메인 화면 - 상점(Mobile) 클릭
2. 임의의 상품 구매 후 2분 간 대기
3. 구매한 상품이 지급되지 않는 현상 확인

[Should be]
Heimdall 모바일 상점에서 구매한 상품이 지급되어야 합니다.
Heimdall에서 정찰 보상이 수령되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
테스트당시 서비스가 응답이없는상태였던것같습니다 확인부탁드려요~!

**Comment by U-lis** [comment]
구매 성공까지 받았으면 API 단에서는 정상 응답을 받았는데 뒤에서 처리가 잘 안 된 것인지 확인해보겠습니다

**Comment by QgamesGeonPyoNoh** [comment]
현재 Heimdall에서 해당 현상 동일하게 발생하고 있습니다.
추가로, Odin에서도 정찰 보상 수령 시 보상이 지급되지 않는 현상 발생 확인했습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200160.v160.0.2
Android.v200160.v160.0.2
iOS.v160.0.2(38)

**Comment by U-lis** [comment]
확인해보니 Odin > Heimdall 로 구매 상품을 보내주는 bridge service 에 이슈가 있는 것이 확인되었습니다.
현재 문제 파악 및 해결 중에 있으며, 조치가 완료되는대로 안내드리겠습니다.

**Comment by U-lis** [comment]
@QgamesGeonPyoNoh 
1. IAP 구매 물품이 전달되지 않는 문제는 확인중에 있습니다. 오늘 오후 중으로 처리될 것으로 예상됩니다.
2. 정찰 보상의 경우 internal 네트워크가 재설정되면서 정찰보상 서비스와 nonce 가 맞지 않는 이슈가 있었습니다. 이는 현재 해결되었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
Odin / Heimdall 정찰 보상 수령 가능 확인 완료했습니다.
Heimdall 구매 물품 전달은 수정된 후 확인하겠습니다.

[테스트 환경]
Windows.v200160.v160.0.2
Android.v200160.v160.0.2
iOS.v160.0.2(38)

**Comment by U-lis** [comment]
@QgamesGeonPyoNoh  현재 브릿지 서비스가 다시 정상화되어 내부 테스트로 heimdall 에서 IAP 상품 구매 시 정상 지급되는 것 확인했습니다.
구매 테스트 다시 한번 진행 부탁드리겠습니다 :pray:

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200160.v160.0.3
iOS.v160.0.3(39)

Uploading 4525_Fix.mp4…
