### ISSUE TITLE
[공방] 8월드 일부 장비의 장비 스킬 텍스트에 키값이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4526]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
8월드 일부 장비의 장비 스킬 텍스트에 키값이 출력되는 현상
-수르트 아머(불), 수르트 아머(땅), 수르트 아머(노말), 수르트 벨트(물), 수르트 벨트(바람)에서 확인되고 있습니다.
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/4e8f9b5e-7532-4bae-8fc3-a0d76bb6f784)
![Image](https://github.com/planetarium/NineChronicles/assets/156992678/1ee26b3c-2bd6-4bb2-adb5-dc9eea28b4b1)

### How to reproduce the issue

[재현스텝]
1. 메인화면 > Workshop > Craft 진입
2. 확인된 8월드 장비 아이템 선택 하여 제작 레시피 확인
3. 스킬 텍스트가 키값으로 출력되는 것을 확인

[Should be]
장비 레시피에 출력되는 스킬 텍스트에 키값이 출력되지 않아야 합니다.

**Comment by NineSyu** [comment]
[https://github.com/planetarium/NineChronicles/pull/4518/files](url)
위에 PR 링크 적용 되면 해결되는 이슈입니다. PR 링크 적용 부탁드립니다.
L10n 갱신 및 신규 스킬 Name를 추가하는 PR입니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/b64118db-7d7c-4ac8-baa6-875794685e3a)
