### ISSUE TITLE
[컬렉션] 컬렉션 재료 내 Shop(Mobile) 바로가기 클릭 시 해당 아이템 탭으로 이동하지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4527]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
컬렉션 재료 내 Shop(Mobile) 바로가기 클릭 시 해당 아이템 탭으로 이동하지 않는 현상
-더스트는 Golden Dust 탭, AP포션/모래시계는 Material 탭으로 이동해야 합니다.
-Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/2ca466e9-80f1-4a02-ad53-a2dbf8e1991c

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 컬렉션 클릭
2. 재료 탭 - Golden Dust / AP포션 / 모래시계 클릭
3. Shop(Mobile) 바로가기 클릭 시 해당 아이템 탭으로 이동하지 않는 현상

[Should be]
컬렉션 재료 내 Shop(Mobile) 바로가기 클릭 시 해당 아이템이 판매되는 탭으로 이동해야 합니다.

**Comment by eugene-doobu** [comment]
바로가기 버튼은 현재 모바일 샵에서 선택한 아이템을 구매할 수 있는 탭중 가장 ID가 가장 낮은 탭으로 이동되게 설정되어있습니다. 인터널 기준 가장 처음 탭인 추천 탭에서 Golden Dust, AP포션, 모래시계등을 모두 판매하고 있어서 해당 탭으로 이동하고 있습니다. 해당 내용 @jaeho0103 님하고도 이야기 되었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
공유 감사드립니다.

이슈 종료하겠습니다.

[테스트 환경]
Android.v200160-.v160.0.3
iOS.v.160.0.3(39)
