### ISSUE TITLE
[컬렉션] 실버 / 루비 더스트 바로가기에 Shop(Mobile)이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4528]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
실버 / 루비 더스트 바로가기에 Shop(Mobile)이 출력되지 않는 현상
-Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/d2a0beb8-5108-4edd-919d-409fd0c21bb6)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 컬렉션 클릭
2. 재료 탭 - 실버 / 루비 더스트 클릭
3. Shop(Mobile)이 출력되지 않는 현상 확인

[Should be]
실버 / 루비 더스트 바로가기에 Shop(Mobile)이 출력되어야 합니다.

**Comment by jaeho0103** [comment]
모든 더스트류 상품에 Shop(mobile) 이 표시 안되고 있는데
AP포션과 모래시계또 마찬가지네요. 체크 부탁드리겠습니다. @eugene-doobu

**Comment by eugene-doobu** [comment]
레벨제한이 없는 패키지가 검색되지 않는 문제가 있어서 아래 pr에서 수정하였습니다.
확인시 아래 pr에서 수정내용 참고 부탁드립니다
https://github.com/planetarium/NineChronicles/pull/4547

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200160.v160.0.3
iOS.v160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/f2fd87d2-6ca6-4aea-a2c4-527c01741294)
