### ISSUE TITLE
[공방] 공방 팝업에서 제작중인 아이템의 필요 모래시계가 5자리를 넘어갈 경우 줄바꿈이 일어나는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4529]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
공방 팝업에서 제작중인 아이템의 필요 모래시계가 5자리를 넘어갈 경우 줄바꿈이 일어나는 현상
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/a05e0657-ce97-4dab-9631-f79a8b13d2be)

### How to reproduce the issue

[재현스텝]
1. 메인화면 > Workshop > Craft 진입
2. 임의의 장비 제작
3. 상단의 공방 UI 진입하여 제작 등록된 아이템 클릭
4. 즉시 완료에 필요한 모래시계가 5자리를 넘어갈 때 줄바꿈 되는 것을 확인

[Should be]
제작에 필요한 모래시계 수량에 줄바꿈이 일어나지 않고 버튼내에 정상 출력되어야 합니다.

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/160.0.x
적용 브랜치 : ui/qa_combination_slot_popup_button-eidt
사용 프리퓁 : UI_CombinationSlotPopup

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/01efdd39-e74d-4d51-870e-d99e46a6b042)
