### ISSUE TITLE
[어드벤처] 아바타 레벨이 400이 넘어갈 경우 어드벤처 진행 시 에러 팝업이 출력되며 게임이 종료되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4531]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### avatar address info

0x965dd6635fedc1938c043fa8b780465cdb010da5

### What happened?

[내용]
아바타 레벨이 400이 넘어갈 경우 어드벤처 진행 시 에러 팝업이 출력되며 게임이 종료되는 현상
-레벨 401 달성 시 프로필에 표시되는 경험치가 '99999'로 출력되고 있습니다.
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 영상 및 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/a39777fd-26c8-4886-8840-4b26ec7adb78)
https://github.com/planetarium/NineChronicles/assets/156992678/9dd22422-08b7-4744-86a0-c9eb4a64c5a0

### How to reproduce the issue

[재현스텝]
1. 레벨 400이 넘는 캐릭터로 메인로비 > 어드벤처 진입
2. 임의의 스테이지 진입하여 전투 진행 시도
3. 에러 팝업 출력되며 게임 종료되는 것을 확인

[Should be]
플레이어 레벨이 최대치일 때 프로필에 표시되는 경험치가 정상적으로 출력되어야 하며, 스테이지 전투가 정상적으로 진행되어야 합니다.

**Comment by NineSyu** [comment]
401레벨 이후 필요 경험치 데이터가 적용되지 않아 생기는 이슈로 보입니다.
관련한 데이터 패치테이블 진행하여 이슈 해결하겠습니다.

**Comment by NineSyu** [comment]
데이터 패치테이블 진행 쓰레드 링크 : https://planetariumhq.slack.com/archives/C011716SDTM/p1710812857498299

**Comment by jonny-jeahyunchoi** [comment]
https://github.com/planetarium/NineChronicles/issues/4515
이것도 연관이슈로보입니다~!

**Comment by QgamesTaekHaJang** [comment]
해당 내용은 현재 환경이 아닌 다음 수정 빌드 환경에서 재확인 진행할 수 있도록 하겠습니다.
공유 감사드립니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)

https://github.com/planetarium/NineChronicles/assets/156992678/3499c52b-2eb0-441b-8a18-36643df1c68e
