### ISSUE TITLE
[계정] PC 환경에서 신규계정 생성 후 이메일 연동이 되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4532]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows

### detailed device info

Windows 11

### account address info

0x2fa41855EFdA33BE86Ba4d0207A820BBCAa55A22

### What happened?

[내용]
PC 환경에서 신규계정 생성 후 이메일 연동이 되지 않는 현상
-포탈 계정 연동 Step3 페이

지에서 'Something went wrong'이 출력되며 연동이 되지 않는 것을 확인하였습니다.
-PC 환경에서 확인하였습니다.
-첨부 드린 영상 확인 부탁 드립니다.

확인 진행한 이메일: qgamesth8@gmail.com

https://github.com/planetarium/NineChronicles/assets/156992678/a0a16acf-6420-499f-a0ae-c8bd38b8fb4b

### How to reproduce the issue

[재현스텝]
1. 런처에서 신규 Key 생성
2. Patron 단계에서 Sign up for the portal 버튼 클릭하여 이메일 계정 연동 시도
3. Step3 페이지에서 'Something went wrong' 문구 출력되며 계정 연동되지 않는 것을 확인

[Should be]
신규 계정 생성 후 다른 계정과 연동되지 않은 이메일에 계정 연동 시도 시 정상적으로 연동이 되어야 합니다.

**Comment by ipdae** [comment]
@Gilhwan 인터널 네트워크의 포탈쪽 문제로 보여서 확인부탁드립니다.

**Comment by QgamesTaekHaJang** [comment]
현재 환경에서 재 확인 시 
수정 내용 확인 완료되었습니다.
이후 동일한 이슈가 발생할 경우 새로 이슈 등록할 수 있도록 하겠습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)
