### ISSUE TITLE
[시즌 패스] 시즌패스 4가 판매되고 있는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4533]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌패스 4가 판매되고 있는 현상
-프리미엄 구매 시에는 판매 기간 종료 메세지가 출력됩니다.
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/9ae11500-6c2e-4151-8362-8fa06fdd2ba5)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 시즌패스 클릭
2. 해제하기 - 프리미엄+ 구매 클릭
3. 시즌패스 4가 판매돠고 있는 현상 확인

[Should be]
시즌패스 5가 판매되어야 합니다.

**Comment by U-lis** [comment]
상황 정리해 공유드립니다 @jonny-jeahyunchoi 
1. 현재 SeasonPass 4 가 판매되는 것은 internal DB 설정 상 정상입니다.  (cc. @QgamesGeonPyoNoh)
2. 새 캐릭터로 접속했을 때 시즌4가 정상적으로 노출되며, 상품 가격도 정상적으로 22000, 44000으로 보입니다.
3. Premium 을 구매하려고 하면 `판매 기한이 지난 상품입니다` 라고 에러 메세지가 나오고 결제 프로필이 보이지 않습니다.
    1. 이 과정에서 client 에 별다른 로그는 확인되지 않았습니다. 
4. Premium All 을 구매하려고 하면 정상적으로 구매가 됩니다.
5. internal DB, internal API 응답, Google play Store 상품 설정은 모두 정상입니다.
6. @jonny-jeahyunchoi  이번에 client 에서 구매 전에 상품 구매가 가능한지 재확인하는 로직이 들어갔는데, 그쪽 영향이 아닌지 봐주실 수 있을까요? BE 쪽 데이터나 작업 필요하시면 말씀해주세요

**Comment by U-lis** [comment]
@QgamesGeonPyoNoh  시즌패스 시즌5 테스트에 대해 안내드립니다.
현재 확인 결과 시즌5를 테스트하기 위한 상품 재화가 전부 확보되지 않아서 시즌5 테스트를 바로 진행할 수 없는 상태입니다.
재화는 오늘 중으로 마련해 테스트할 수 있도록 준비 예정입니다.
다만 현재 시즌4 상품 구매가 정상적으로 되지 않는 정황이 보여 (바로 위 comment) 이를 확인한 뒤에 internal 설정 변경을 통한 시즌5 테스트를 하실 수 있을 것으로 예상됩니다.
이 스레드에서 계속 상태 업데이트 드리도록 하겠습니다.

**Comment by jonny-jeahyunchoi** [comment]
> @jonny-jeahyunchoi 이번에 client 에서 구매 전에 상품 구매가 가능한지 재확인하는 로직이 들어갔는데, 그쪽 영향이 아닌지 봐주실 수 있을까요? BE 쪽 데이터나 작업 필요하시면 말씀해주세요

이거 에러메세지뜨는상황은 말씀하신이슈가 맞는것같습니다. 한번확인해볼깨요~!\

**Comment by jonny-jeahyunchoi** [comment]
구매가능한지 여부를 체크하는것에서 product.Active 와 product.Buyable 을 둘다체크하는데요 혹시 이게 꺼질경우가 있을까요? @U-lis

**Comment by jonny-jeahyunchoi** [comment]
클라이언트 코드상으로는 상품 구매여부 체크시 문제는 없는것으로 보이나 팝업문구는 구매여부가 불가할때 뜨는내용으로 구매여부를 체크하는 상품의 Active와 Buyable이 정상적으로 세팅되지않아있는것으로 보입니다. 일단 구매가능여부가 실패할경우 추가 로그를 심어두었습니다.

**Comment by U-lis** [comment]
네 한번 확인해보도록 하겠습니다.

**Comment by U-lis** [comment]
```json
{
  "name": "SeasonPass4Premium",
  "order": 999999,
  "google_sku": "g_pkg_seasonpass4",
  "apple_sku": "a_pkg_seasonpass4",
  "is_free": false,
  "daily_limit": null,
  "weekly_limit": null,
  "account_limit": 1,
  "active": true,
  "buyable": true,
  "required_level": null,
  "purchase_count": 0,
  "rarity": "Normal",
  "size": "1x1",
  "discount": 0,
  "l10n_key": "MOBILE_SHOP_PRODUCT_SeasonPassPremium",
  "path": "shop/images/product/list/Goods_Package_02.png",
  "bg_path": "shop/images/product/list/bg_Normal_1x1.png",
  "popup_path_key": "MOBILE_SHOP_PRODUCT_SeasonPassPremium_PATH",
  "fav_list": [],
  "fungible_item_list": []
}
```
API 응답은 정상적으로 `active=true, buyable=true` 입니다.
API 서버에 남는 로그도 특이한 사항 없어서 뭐가 원인인지 잘 모르겠습니다.

**Comment by U-lis** [comment]
@jonny-jeahyunchoi 
테스트를 위해서 시즌5를 열어봤습니다.
여전히 22000원짜리 상품은 `판매 기한이 지난 상품입니다` 가 나오고, 44000원짜리 상품은 정상적으로 결제 프로필이 뜹니다.
BE 이슈로 더 의심할만한 부분은 없는데, 혹시 저 위치에 뭔가 기본값 또는 잘못된 분기 처리가 있거나 하지는 않을까요?
도저히 더 찾아볼만한 데가 없습니다 😭

**Comment by jonny-jeahyunchoi** [comment]
이거 로그확인해본결과 클라이언트에서 SeasonPass4Premium 상품 구매시도시 sku가아니라 상품이름으로 구매시도를하는부분 확인했습니다~! 수정PR 준비하겠습니다~!

**Comment by jonny-jeahyunchoi** [comment]
@QgamesGeonPyoNoh 관련 에러로그도 같이 첨부부탁드립니다~

**Comment by QgamesGeonPyoNoh** [comment]
에러 로그 공유 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/b2c78280-65c9-4153-b153-aa746c738ae6)

[에러 로그 메세지]
CheckProductAvailable Fail g_pkg_seasonpassall5 Active:True Buyable:False
NineChronicles.ExternalServices.IAPService.Runtime.<CheckProductAvailable>d__14:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(TResult)
NineChronicles.ExternalServices.IAPService.Runtime.<GetProductsAsync>d__15:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(TResult)
NineChronicles.ExternalServices.IAPService.Runtime.<ProductAsync>d__8:MoveNext()
UnityEngine.UnitySynchronizationContext:Exec()

[테스트 환경]
Android.v200160-160.0.5
iOS.v160.0.5(42)

**Comment by jonny-jeahyunchoi** [comment]
이거 로그메세지보니까 서비스에서 받은데이터에 buyable이 false로 들어와있는것같습니다. g_pkg_seasonpassall5 이랑 아바타주소 0x3146FE0E47A1998e14cd8a33640e3648A5A90276 가지고  확인부탁드려요

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈가 발생한 계정은 0xdde23c49C0e36B5f8206Dbdac60675288484B37E 입니다.
타 계정으로 확인 시 해당 이슈 발생하지 않는 것으로 확인했습니다.

**Comment by U-lis** [comment]
@QgamesGeonPyoNoh  안녕하세요 
이슈가 발생한 계정의 구매 이력을 보니 이미 동일 상품을 구매 테스트한 이력이 있습니다. 따라서 구매가 불가한 것이 정상입니다.
다만 구매 이력이 있는데 왜 premium + 활성화가 되어 있지 않은 것으로 보이고, 구매 팝업이 나왔는지에 대해서는 확인이 필요해보입니다.
후속 comment로 상황 공유드리겠습니다.

**Comment by jonny-jeahyunchoi** [comment]
이거 애초에 이미 구매한 상품인데 버튼이 활성화되어있는게 문제이고 해당상황은 같은 계정으로 동시에 여러기기에서 시즌패스에 접속한뒤 한기기에서만 결제를 진행하게되면 나머지 기기에서 구매시도시 알림뜨는것으로 확인됩니다. 일단 지금 에러알림뜨는것이 스팩이라고 보시면될것같습니다~! @QgamesGeonPyoNoh @jaeho0103

**Comment by QgamesGeonPyoNoh** [comment]
확인 감사드립니다.
계정 내 타 아바타에서 시즌패스 프리미엄을 구매한 이력이 있습니다.

현재 시즌패스 프리미엄 구매 제한의 경우 아바타 별 구매 제한인 것으로 파악하고 있습니다.
혹시 시즌패스 프리미엄 구매 제한이 계정별로 적용되는 사항일지 문의드립니다.

**Comment by U-lis** [comment]
@QgamesGeonPyoNoh 
모든 IAP 상품의 구매 이력 및 제한은 계정을 기준으로 하고 있습니다.
다만 시즌패스의 경우 아바타 개수를 고려해 최대 3번까지 구매할 수 있도록 제한하고 있습니다.
internal DB 의 값을 확인해보니 이 값이 1로 제한되어 있는 것을 확인후 수정했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200160-160.0.6
iOS.v160.0.6(43)
