### ISSUE TITLE
[튜토리얼] 방치보상 튜토리얼 진행 시 표시되는 위치가 실제 터치 가능한 위치와 다르게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4534]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
방치보상 튜토리얼 진행 시 표시되는 위치가 실제 터치 가능한 위치와 다르게 출력되는 현상
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/a54ddc78-68b7-4aef-ad88-967756b3d911

### How to reproduce the issue

[재현스텝]
1. 신규 캐릭터 생성하여 튜토리얼 진행
2. 방치보상 아이콘에 강조 표시되는 부분이 터치되는 영역과 다른 위치에 출력되는 것을 확인

[Should be]
튜토리얼 진행 시 컨텐츠 아이콘에 강조 표시되는 위치가 터지가능한 위치와 동일하게 출력되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160.v160.0.3
Android.v200160.v160.0.3
iOS.v160.0.3(39)
![4534_Fix](https://github.com/planetarium/NineChronicles/assets/150774808/090dda09-3ffe-4ce9-8c5a-7b37a062bec5)
