### ISSUE TITLE
[상점] PC 상점에 아이템 검색 영역이 동작하지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4535]
### APV version info

v200160

### Client version info

v160.0.2

### Device

Windows

### detailed device info

Windows 11

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
PC 상점에 아이템 검색 영역이 동작하지 않는 현상
-'Show only available items'텍스트가 출력되며 영역 선택 시 동작하지 않는 것을 확인하였습니다.
-PC 환경에서 확인하였습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/fd8f7bbf-b986-4c4f-aeda-60de2857f13a

### How to reproduce the issue

[재현스텝]
1. PC 환경에서 메인로비 > 상점 진입
2. 아이템 검색 영역에 'Show only available items' 텍스트 출력되는 것을 확인
3. 클릭하여 검색 기능 동작하지 않는 것을 확인

[Should be]
PC 상점에서 아이템 검색 영역이 정상적으로 동작되어야 합니다.

**Comment by eugene-doobu** [comment]
아래 pr에서 수정내역 작성하였습니다. 확인시 참고 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/4543

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-.v.160.0.3
iOS.v.160.0.3(39)

https://github.com/planetarium/NineChronicles/assets/156992678/1e0a1b5a-ecc2-4b69-913b-35a955ac1dc1
