### ISSUE TITLE
[컬렉션] 컬렉션 오름차순 / 내림차순이 반대로 적용되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4558]
### APV version info

v200160

### Client version info

v160.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
컬렉션 오름차순 / 내림차순이 반대로 적용되는 현상
-워크샵 기준 ▼ (오름차순) / ▲  (내림차순)으로 판단했습니다.
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/da8adc8b-a791-4412-a501-c0eada947def

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 컬렉션 클릭
2. 컬렉션 진입 시 ID  ▼ (오름차순) 선택 확인
3. 컬렉션이 ID 내림차순으로 정렬되어 반대로 적용되는 현상 확인
4. Grade ▲ (내림차순) 선택 시 Grade 오름차순으로 정렬되어 반대로 적용되는 현상 확인

[Should be]
컬렉션 오름차순 / 내림차순이 정상적으로 적용되어야 합니다.

**Comment by eugene-doobu** [comment]
@jaeho0103 요거 ▼ 마크가 오름차순이 맞는지 확인해주실 수 있나요?

**Comment by jaeho0103** [comment]
그러네요. 일단 워크샵에서는 저 마크를 오름으로 쓰고 있네요.

**Comment by eugene-doobu** [comment]
@jaeho0103 그럼 통일시켜서 적용시켜두겠습니다!

**Comment by jaeho0103** [comment]
네 근데 저게 내림이 맞아야 할 것 같아서 사실 워크샵이 변경되어야 하는거 아닌가 싶은데
히스토리를 모르니 맞춰두죠 ㅎㅎ

**Comment by eugene-doobu** [comment]
수정내역 아래 pr에서 진행하였습니다. craft의 정렬 아이콘을 컬랙션에 맞추는 방향으로 진행하였습니다. 확인시 참고 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/4566

**Comment by QgamesTaekHaJang** [comment]
현재 환경에서 해당 현상 수정 되어 Craft의 정렬 아이콘과 컬렉션의 정렬 아이콘이 동일하게 출력되는 것을 확인하였습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160-160.0.4
Android.v200160-160.0.4
iOS.v160.0.4(41)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/caea8b2d-30f3-4fd1-a05d-6b597c7269ef)
![Image](https://github.com/planetarium/NineChronicles/assets/156992678/7988351f-de1f-485e-ab79-ac3c6572a824)
