### ISSUE TITLE
[공방] 장비 제작 블록 40% 감소 이벤트가 적용되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4559]
### APV version info

v200160

### Client version info

v160.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
장비 제작 블록 40% 감소 이벤트가 적용되지 않는 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/51969243-39e0-4c0d-a57e-bad7b07232a9

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 공방 클릭
2. 제작 - 임의의 장비 제작 진행
3. 제작 블록 확인 시 장비 제작 블록 40% 감소 이벤트가 적용되지 않는 현상 확인

[Should be]
장비 제작 블록 40% 감소 이벤트가 적용되어야 합니다.

**Comment by jaeho0103** [comment]
장비 제작 이벤트는 40% 가 아닌 아예 변경된 수준의 조정을 하는것으로
스펙이 변경되어 금일중 업데이트 예정입니다. 관련해서는 QA문서에 내용추가해서
21일이후에 확인 요청 다시 드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
다음 수정 빌드에서 재확인 진행하도록 하겠습니다.
공유 감사드립니다.

**Comment by QgamesTaekHaJang** [comment]
@jaeho0103 
수정 내용 확인 완료되었습니다.
다만, 레전드리 등급의 장비는 무속성을 제외한 다른 속성의 장비(불, 물, 바람, 땅)가 테이블에 표기된 블록 수 보다 1블록이 더 추가되어 표시되는 것을 확인하였습니다.
해당 내용 확인 부탁 드리겠습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/20834343-91c6-4f04-84c6-9e277dbc24ea)

**Comment by jaeho0103** [comment]
아 이거 커멘트를 안드렸군요. 수정 완료했습니다. 체크 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.6
Android.v200160-160.0.6
iOS.v160.0.6(43)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/e1fede2d-86e6-4ace-807a-c0bd25155ae6)
