### ISSUE TITLE
[어드벤처] 1회성 버프의 텍스트와 아이콘이 맞지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4560]
### APV version info

v200160

### Client version info

v160.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
1회성 버프의 텍스트와 아이콘이 맞지 않는 현상
-PC / Android / iOS 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/fa378834-a255-4226-962e-23ff48c1a8f8)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 어드벤처 클릭
2. 현재 진행 중인 스테이지 클릭
3. 1회성 버프 별 조건 충족 후 뽑기 진행
4. 1회성 버프의 텍스트와 아이콘이 맞지 않는 현상 확인

[Should be]
1회성 버프의 텍스트와 아이콘이 일치해야 합니다.

**Comment by ipdae** [comment]
@NineSyu @sonohoshi 이건 혹시 번역어 문제일까요 아니면 코드에 문제가 있는걸까요? 스크린샷을 확인했을떄 올스탯은 제대로 떠있는듯해서 확인 부탁드립니다.

**Comment by sonohoshi** [comment]
아 이거 스킬 카테고리 enum이 중간에 추가되면서 리소스 매핑시켜둔 값이 한두칸씩 밀린것으로 보입니다...

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/e2b55771-1bc3-41e4-bc27-d39e568fdab7)



[테스트 환경]
Windows.v200160-160.0.4
Android.v200160-160.0.4
iOS.v160.0.4(41)
