### ISSUE TITLE
[UI] 몬스터 컬렉션 텍스트가 NEW 표시 / 스테이킹 레벨 표시에 가려지는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4563]
### APV version info

v200160

### Client version info

v160.0.3

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
몬스터 컬렉션 텍스트가 NEW 표시 / 스테이킹 레벨 표시에 가려지는 현상
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/98e60d94-c944-4b8f-963d-6f248a66f7be)
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/10e62043-5e58-4b1c-a079-6dfe161ead72)

### How to reproduce the issue

[재현스텝]
1. 50 NCG 이상 보유 / 스테이킹 하지 않은 계정으로 메인 화면 진입
2. 몬스터 컬렉션 텍스트가 NEW 표시에 가려지는 현상 확인
3. 스테이킹 진행한 계정으로 메인 화면 진입
4. 몬스터 컬렉션 텍스트가 스테이킹 레벨 표시에 가려지는 현상 확인

[Should be]
몬스터 컬렉션 텍스트가 NEW 표시 / 스테이킹 레벨 표시에 가려지지 않아야 합니다.

**Comment by sonohoshi** [comment]
@boramqo83 이거 단순 UI 레이아웃 맞추는걸로 보이는데 제가 하는게 나을까요 아님 보람님이 하시는게 나을까요?

**Comment by sonohoshi** [comment]
@boramqo83 네 맞습니당 어사인 보람님으로 돌려둘게요

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/160.0.x
적용 브랜치 : ui/monstercollection_icon-edit
사용 프리퓁 : UI_Menu, StakingBtn
![image](https://github.com/planetarium/NineChronicles/assets/102953029/082a546e-888a-412b-a419-b6a2f1b5ec36)
![image](https://github.com/planetarium/NineChronicles/assets/102953029/8aad8182-7da8-42e6-be67-1dd222ec8bfd)
텍스트가 한 줄로 들어가질 경우와 두 줄로 들어가질 경우. 모두 문제 없이 들어가지도록 처리했습니다.
![image](https://github.com/planetarium/NineChronicles/assets/102953029/46c06802-23e1-4b16-b524-cca06c89cf7f)
잠겨 있을 때 모습도 맞췄습니다.

**Comment by boramqo83** [comment]
https://github.com/planetarium/NineChronicles/pull/4578
요기에 올려두었습니다. @sonohoshi 
없는지 확인 후 머지 부탁드려요.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/cd0fcb58-f62e-4570-8e5f-870e8ee12d9d)



![Image](https://github.com/planetarium/NineChronicles/assets/150774808/a8095ffe-0feb-43ec-af2a-901e84830ac6)


[테스트 환경]
Windows.v200160-160.0.4
Android.v200160-160.0.4
iOS.v160.0.4(41)
