### ISSUE TITLE
[런처] 런처 내 스테이킹 팝업을 닫은 뒤 런처 내 버튼 클릭 불가 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4573]
### APV version info

v200160

### Client version info

v160.0.3

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
런처 내 스테이킹 팝업을 닫은 뒤 런처 내 버튼 클릭 불가 현상
-팝업 닫기 버튼 / 팝업 외부영역 클릭 모두 발생하고 있습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/9e8a131e-88bd-4d38-bf4b-0e83b0bf69b8

### How to reproduce the issue

[재현스텝]
1. 런쳐 실행 - 스테이킹 버튼 클릭
2. 스테이킹 팝업 닫기
3. 스테이킹 팝업을 닫은 뒤 런처 클릭 불가 현상 확인

[Should be]
런처 내 스테이킹 팝업을 닫은 뒤 런처 내 버튼 클릭이 가능해야 합니다.

**Comment by Akamig** [comment]
@QgamesGeonPyoNoh 
음, 현재 Windows / Mac에서 재현해본 결과 발생하지 않고 있어서, 혹시 지속적으로 재현되시는 상태이신가요?

**Comment by QgamesGeonPyoNoh** [comment]
스테이킹을 진행한 계정에서만 발생하는 현상으로 확인했습니다.
재현 영상 공유 드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/f436eb6b-8ced-4710-8a0f-a41cf769d901

[테스트 환경]
Windows.v200160-.v160.0.3

**Comment by Akamig** [comment]
아, 감사합니다. 저도 재현에 성공했습니다.

**Comment by Akamig** [comment]
일단 이 버그는 다음 조건에서 발생합니다.
- 스테이킹 존재하는 상태
- 테이블 정보에 중복된 테이블이 존재하는 경우 (현재 6,7 레벨이 한 테이블에 2개씩 존재함) 

중복인 경우가 발생하는 것 자체가 문제라서, 원래 보상 테이블을 받아오는데 사용하는 쿼리의 수정이 필요한 상태인것으로 보여집니다.

**Comment by Akamig** [comment]
현재 인터널 네트워크에서 테이블 마이그레이션 테스트를 위해 임시로 적용된 테이블로 인해 발생한 문제였고, 현재는 원복된 상태로 해당 이슈가 발생하지 않고 있습니다. 

그래서 해당 이슈가 현재 발생하지 않는 것을 확인해주시면 일단 이 이슈는 닫도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 임시로 적용된 테이블이 아직 적용되어 있는 것으로 출력되며, 이슈가 계속 발생하고 있습니다.
확인 부탁드립니다.
![image](https://github.com/planetarium/NineChronicles/assets/150774808/ddf0ac71-a41b-4cfe-b762-fccd7c0424cd)

[테스트 환경]
Windows.v200160-.v160.0.3

**Comment by Akamig** [comment]
아, 혼선을 드려서 죄송합니다. 오늘 잠시 뒤에 원복 패치가 계획되어있어서, 내일 확인해보시면 될것 같습니다.

**Comment by QgamesGeonPyoNoh** [comment]
네, 공유 감사드립니다.
명일 확인할 수 있도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
스테이킹 테이블 원복 및 해당 이슈 수정 확인되었습니다.
이슈 종료하겠습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/4968745f-7cee-45b7-9908-bba203a1780d

[테스트 환경]
Windows.v200160-160.0.3
