### ISSUE TITLE
몬스터 컬렉션 받을 보상이 없는데 이펙트 나오는 문제

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#4592]
### APV version info

200160

### Client version info

160.0.4

### Device

Windows

### account address info

.

### What happened?

스테이킹 메뉴의 이헥트가 보상을 받지 못할때도 나옴

### How to reproduce the issue

로비드가기

**Comment by jaeho0103** [comment]
정확히는 보상을 받을수 있을때 이펙트 나오다가 보상 받고나서 안꺼지던 그 이슈 맞을까요?

**Comment by sonohoshi** [comment]
아니요 그냥 항상 보상이 나오고 있습니다
