### ISSUE TITLE
[로그인] 모바일 버전 최초 진입 시 기본 플래닛이 Odin으로 선택되어 있는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4594]
### APV version info

v200160

### Client version info

v160.0.4

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모바일 버전 최초 진입 시 기본 플래닛이 Odin으로 선택되어 있는 현상
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/f03d5b9f-ab4e-4a63-8e23-156338086c54)

### How to reproduce the issue

[재현스텝]
1. 모바일 환경 최초 진입
2. Touch to Start 출력 후 화면 클릭
3. 기본 플래닛이 Odin으로 선택되어 있는 현상 확인

[Should be]
모바일 버전 최초 진입 시 기본 플래닛이 Heimdall로 선택되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
이거 심사시 게스트로그인을위하여 인터널에서만 기본 플레닛선택이 오딘으로 세팅해놓은 부분입니다. 원격으로 설정변경할수있는형태라 이슈 닫아도 될것같습니다~!

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
Android.v200160-160.0.4
iOS.v160.0.4(41)
