### ISSUE TITLE
[상점] PC 상점 내 Food - Speed 탭이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4597]
### APV version info

v200160

### Client version info

v160.0.4

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
PC 상점 내 Food - Speed 탭이 출력되지 않는 현상
-Buy 카테고리 / Sell 필터 모두 출력되지 않고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/c3201d32-070b-4159-804d-6f8796ef0b1f)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/78dc10f0-1ea6-49d0-ae87-c5f216c24fd3)

### How to reproduce the issue

[재현스텝]
1. PC 환경에서 메인 화면 - 상점 클릭
2. Buy 화면에서 Food 카테고리 클릭 시 Speed 탭이 출력되지 않는 현상 확인
3. Sell 화면에서 필터 영역 클릭 시 SPD Food가 출력되지 않는 현상 확인

[Should be]
PC 상점 내 Food - Speed 탭이 출력되어야 합니다.

**Comment by ipdae** [comment]
마켓서비스에 카테고리를 추가해야할것같습니다. 당장은 대응이 어렵기때문에 다음빌드에 반영해야할것같습니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)
![4597수정확인](https://github.com/planetarium/NineChronicles/assets/156992678/adf4b27d-c3ac-471d-b9ef-03a3b1624cd6)
