### ISSUE TITLE
[몬스터컬렉션] 런쳐 내 스테이킹 팝업에서 루비 더스트 보상이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4599]
### APV version info

v200160

### Client version info

v160.0.4

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
런쳐 내 스테이킹 팝업에서 루비 더스트 보상이 출력되지 않는 현상
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/f0809dd5-be41-4306-b3f9-39a1ef6de55f)

### How to reproduce the issue

[재현스텝]
1. 런쳐 실행 - Staking 클릭
2. 5,000 NCG 이상 단계 클릭 시 루비 더스트 보상이 출력되지 않는 현상 확인

[Should be]
런쳐 내 스테이킹 팝업에서 루비 더스트 보상이 출력되어야 합니다.

**Comment by Akamig** [comment]
요 이슈는 인터널 테이블 데이터 문제로, (루비 더스트가 왜인지 빠져있음) 메인넷에서는 다음과 같이 정상 출력됩니다.

![Image](https://github.com/planetarium/NineChronicles/assets/6278999/db300e79-d528-4a52-8003-fe177d65209d)

**Comment by Akamig** [comment]
인터널 테이블 패치로 해결될 것으로 보여서, 말씀드린뒤 @jaeho0103 님에게 넘겼습니다.

**Comment by jaeho0103** [comment]
마이그레이션 테스트를 위해 최신테이블이 V7이 아닌 V6로 셋팅되어있었어서
생긴 이슈였습니다. V7으로 수정하였고 마이그레이션시 루비더스트 정상 표시되는 부분 확인했습니다.
체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.5

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/62755ede-aaba-4daf-8d6a-bebec6006f90)
