### ISSUE TITLE
User gets the quest to craft an item that is not in the game

### ISSUE THREAD

**Issue by CosminSh** [planetarium/NineChronicles#460]
I get the quest to craft a warrior Necklace but those have been postponed from being in the game
![image](https://user-images.githubusercontent.com/85586664/123406910-1189b880-d5b4-11eb-83c7-71e11c5e4c6b.png)

Maybe the game is taking the quests from the old item release plan?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200521825478724) by [Unito](https://www.unito.io)

**Comment by Namyujeong** [comment]
@CosminSh 
Wasn't the quest cleared even after all the crafting was completed and the item was received in the inventory?
Or, have you put in crafting, but the item is still in the workshop slot and you haven't received the item?

**Comment by CosminSh** [comment]
> @CosminSh
> Wasn't the quest cleared even after all the crafting was completed and the item was received in the inventory?
> Or, have you put in crafting, but the item is still in the workshop slot and you haven't received the item?

I got the quest to craft a "Warrior Necklace" but those are not in the game yet :) 
![image](https://user-images.githubusercontent.com/85586664/123641664-27ed7980-d82b-11eb-94c0-43a78011fca7.png)

**Comment by Namyujeong** [comment]
@CosminSh Sorry, Now I totally understand what you mean. We'll check the quest table sheet. thx

**Comment by Namyujeong** [comment]
@plafina2 아직 제작이 풀리지 않은 아이템 제작 퀘스트가 노출되고 있다는 이슈입니다. 테이블 단위에서 이를 해결할 방법이 혹시 있을까요?

**Comment by Namyujeong** [comment]
It seems to be a rather low priority bug. We'll try to fix it before the end of the year.

**Comment by Namyujeong** [comment]
@CosminSh Please check if this problem disappeared at 100087.

**Comment by CosminSh** [comment]
Yes, it's ok now, I have a normal quest instead of that one
