### ISSUE TITLE
[UI] 신규 신성 등급 재료 이름 키값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4600]
### APV version info

v200160

### Client version info

v160.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신규 신성 등급 재료 이름 키값으로 출력되는 현상
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/97051ab2-62e5-434e-b091-bb30d09ff687)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 워크샵 클릭
2. 제작 - 장비 탭 내 신규 신성 장비 클릭
3. 신규 신성 등급 재료 클릭 시 이름 키값으로 출력되는 현상 확인

[Should be]
신규 신성 등급 재료 이름이 키값으로 출력되지 않아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 확인 부탁드립니다~

**Comment by jaeho0103** [comment]
네 해당 l10n 누락된 거 체크되어 https://github.com/planetarium/NineChronicles/pull/4591/files 요 pr 에서 추가되었습니다. 다음버전에서 확인 부탁드리겠습니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/17cb4bc1-b223-477c-bd1d-91583f9854d7)
