### ISSUE TITLE
[몬스터콜렉션] 스테이킹 미 진행 안내 메세지에서 staking이 staing으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4602]
### APV version info

v200160

### Client version info

v160.0.4

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
스테이킹 미 진행 안내 메세지에서 staking이 staing으로 출력되는 현상
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/73440147-eda3-4443-8eda-3b89e6a356a6)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 몬스터콜렉션 클릭
2. 스테이킹 미 진행 상태에서 Current Rewards 클릭
3. 스테이킹 미 진행 안내 메세지에서 staking이 staing으로 출력되는 현상 확인

[Should be]
스테이킹 미 진행 안내 메세지에서 staking으로 출력되어야 합니다.

**Comment by NineSyu** [comment]
https://github.com/planetarium/NineChronicles/pull/4591
위에 PR로 문제 해결하였습니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)
![4602_수정확인](https://github.com/planetarium/NineChronicles/assets/156992678/7ffcfe7a-0557-4d68-900b-60f8898e799b)
