### ISSUE TITLE
[UI] 메인 화면 내 일부 광원 효과가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4604]
### APV version info

v200160

### Client version info

v160.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
메인 화면 내 일부 광원 효과가 출력되지 않는 현상
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/4941e923-fb27-4dae-9323-83a340863a4c)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 진입
2. 워크샵 이미지 내 광원 효과가 출력되지 않는 현상 확인
3. 메인 화면 우측 상단 광원 효과가 출력되지 않는 현상 확인

[Should be]
메인 화면 내 광원 효과가 정상적으로 출력되어야 합니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)

![4604수정확인](https://github.com/planetarium/NineChronicles/assets/156992678/339bb1a1-69cf-4133-bce9-4932fc10b333)
