### ISSUE TITLE
[몬스터콜렉션] 모바일에서 몬스터콜렉션 설명 팝업이 영어로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4605]
### APV version info

v200160

### Client version info

v160.0.4

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

 0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모바일에서 몬스터콜렉션 설명 팝업이 영어로 출력되는 현상
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/46ee4621-875a-4bdb-a30f-7432994f2058)

### How to reproduce the issue

[재현스텝]
1. 모바일 환경에서 스테이킹 미 진행 계정 접속
2. 메인 화면 - 몬스터콜렉션 클릭
3. 몬스터콜렉션 팝업 출력 시 설명 팝업이 영어로 출력되는 현상 확인

[Should be]
모바일에서 몬스터콜렉션 설명 팝업이 한국어로 출력되어야 합니다.

**Comment by sonohoshi** [comment]
노운 이슈입니다. 여기까지 번역 바리에이션을 칠 비용이 없어서 전부 영어로 나오게 되어있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인하였습니다.
해당 이슈는 노운 이슈로 추적성을 위해 티켓을 남겨놓고,
번역 수정된 이후에 해당 이슈 종료처리 하는 방향으로 진행하겠습니다.
확인 감사드립니다.

[테스트 환경]
Android.v200160-160.0.4
iOS.v160.0.4(41)

**Comment by jaeho0103** [comment]
노운 이슈라기보다는 현재로서는 그냥 스펙이라고 이해해주시면 감사하겠습니다.
관련해서는 업데이트할때 따로 QA를 요청드리겠습니다. 이 이슈는 클로즈 해주셔도 좋을 것 같습니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인하였습니다.
이슈 종료하겠습니다.

[테스트 환경]
Android.v200160-160.0.4
iOS.v160.0.4(41)
