### ISSUE TITLE
[8월드] 신규 신성 등급 재료 획득처가 없는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4611]
### APV version info

v200160

### Client version info

v160.0.5

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신규 신성 등급 재료 획득처가 없는 현상
-추가로, 신성 등급 장비 크리스탈로 제작 시 신성 등급 재료를 크리스탈로 대체할 수 없다는 메세지가 출력되고 있습니다.
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/a5f94d69-42b7-4561-b410-a2134483d99c

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 월드맵 - 헬헤임 진입
2. 임의의 스테이지 클릭 시 신성 등급 재료가 출력되지 않는 현상 확인

3. 메인화면 - 워크샵 - 제작 클릭
4. 임의의 신성 장비 크리스탈로 제작 시도 시 신성 등급 재료 대체 불가 메세지 출력 확인
5. 신성 등급 재료 클릭 시 획득처가 퀘스트만 출력되는 현상 확인

[Should be]
8월드에서 신성 등급 재료의 획득이 가능해야 합니다.
신성 장비 제작 시 크리스탈로 대체가 가능해야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
CrystalMaterialCostSheet에 신규 아이템이 추가되지않은것같습니다 확인부탁드려요~! @NineSyu

**Comment by jaeho0103** [comment]
스테이지 데이터가 잘못들어가 있어서 관련 획득처도 표시가 되지 않고 있던 부분이었습니다.
데이터 수정했으니 다시 체크 부탁드리겠습니다.

**Comment by jaeho0103** [comment]
크리스탈 대체도 AP포션만으로 획득하게 했을떄의 시뮬레이션을 위해 빠져있던 부분으로
추가되었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)

https://github.com/planetarium/NineChronicles/assets/150774808/14b59f56-51b5-4f8b-a2ea-8b9a79a2980b
