### ISSUE TITLE
[8월드] 신규 재료의 이름과 설명이 일치하지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4613]
### APV version info

v200160

### Client version info

160.0.5

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신규 재료의 이름과 설명이 일치하지 않는 현상
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/754ac9ff-d585-41af-9615-d810e113600b)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 어드벤쳐 - 헬헤임 클릭
2. 임의의 스테이지 클릭
3. 신규 재료 클릭 시 이름과 설명이 일치하지 않는 현상 확인

[Should be]
신규 재료의 이름과 설명이 일치해야 합니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.6
Android.v200160-160.0.6
iOS.v160.0.6(43)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/611d8fed-7093-4d4c-8a0d-14e489f89f7e)
