### ISSUE TITLE
[8월드] 383 스테이지 보상에 수액 결정이 보상 목록에 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4614]
### APV version info

v200160

### Client version info

160.0.5

### Device

Windows, iOS, Android

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
383 스테이지 보상에 수액 결정이 보상 목록에 출력되는 현상
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/8554c741-c1da-46a2-adc7-2faa68d276bb)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 어드벤쳐 - 헬헤임 클릭
2. 383 스테이지 클릭 시  수액 결정이 보상 목록에 출력되는 현상 확인

[Should be]
383 스테이지 보상에 수액 결정이 보상 목록에 출력되지 않아야 합니다.

**Comment by jaeho0103** [comment]
스테이지 데이터가 잘못 올라가 있는 부분 수정완료했습니다. 다시 체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/5ca66e08-f123-41c7-80ab-219c34e5c447)
