### ISSUE TITLE
[몬스터콜렉션] 스테이킹 진행 중에도 NEW 표시가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4615]
### APV version info

v200160

### Client version info

160.0.5

### Device

Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
스테이킹 진행 중에도 NEW 표시가 출력되는 현상
-Android / iOS 환경에서 확인하였습니다.
-PC 환경에서는 간헐적으로 발생하고 있습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/9d611ff7-3772-4ae0-9cc6-e7bb392b3de6)

### How to reproduce the issue

[재현스텝]
1. 모바일 환경에서 스테이킹 진행 중인 계정으로 진입
2. 메인 화면 내 몬스터 콜렉션 확인 시 NEW 표시가 출력되는 현상 확인

[Should be]
스테이킹 진행 중에는 NEW 표시가 출력되지 않아야 합니다.

**Comment by boramqo83** [comment]
https://planetariumhq.slack.com/archives/CBU2JFAF3/p1711342106105519

**Comment by ipdae** [comment]
노운이슈로 남기고 v170에서 처리합니다.

**Comment by boramqo83** [comment]
https://planetariumhq.slack.com/archives/CBU2JFAF3/p1711355192565349
NEW 마크 표기를 다르게 사용하려고 합니다.
위 슬랙 내용을 참고해 주세요.
