### ISSUE TITLE
[시즌패스] 프리미엄+ 구매 시 8월드 기념 칭호 및 루비 더스트가 지급되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4616]
### APV version info

v200160

### Client version info

160.0.5

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
프리미엄+ 구매 시 8월드 기념 칭호 및 루비 더스트가 지급되지 않는 현상
-현재 칭호는 시즌 4 칭호가 지급되고 있습니다.
-Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/fb6ad491-bff8-46ff-9e2c-02a0910c4c4d)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/9d867a3c-7594-435a-9ddc-a879ea9423c4)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 시즌 패스 클릭
2. 프리미엄+ 구매 진행
3. 프리미엄+ 구매 시 8월드 기념 칭호 및 루비 더스트가 지급되지 않는 현상 확인

[Should be]
프리미엄+ 구매 시 8월드 기념 칭호 및 루비 더스트가 지급되어야 합니다.

**Comment by jaeho0103** [comment]
데이터 수정했습니다. 다시 체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 시즌패스 구매 팝업에서 칭호 아이콘 클릭 시 시즌 4 칭호가 출력되고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200160-160.0.5
iOS.v160.0.5(42)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/d04111c9-e36c-4e3b-9513-0a061f3827cb)

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 요거 확인부탁드립니다~

**Comment by U-lis** [comment]
@QgamesGeonPyoNoh cc. @jaeho0103 
내용 확인해보았습니다. 아까 시즌패스 진입 불가 이슈()를 테스트하는 과정에서 원인을 찾기 위해 internal DB 의 값을 일부만 변경한 내용이 있었는데 이것에 의한 side effect 로 확인되었습니다. 현재는 수정 완료되어 정상적으로 시즌5 칭호 (지옥의 용사) 를 확인하실 수 있습니다.
상세한 내용은 후속 comment 로 남겨두겠습니다.

**Comment by U-lis** [comment]
1. IAP 상품 table 의 구조
    - IAP 상품 중 item 의 경우 sheet ID 와 Fungible ID / Token ID 두 개의 값을 DB 에 저장하고 있습니다.
    - product API 에서는 이 값을 전부 client 에 주고 있으며, client 에서는 이 중 sheet ID 를 이용해 보상을 표기하고 있습니다.
2. 상기 이슈가 발생한 원인
    - 점심시간에 있던 시즌패스 진입 불가 이슈의 원인을 찾기 위해 의심가는 값들을 수정하던 중 DB 에서 Sheet ID 를 시즌4 보상으로 변경했었습니다.
    - client 에서 시즌5 칭호를 찾지 못하는 것이 원인일 수 있어서 이전 시즌 값으로 변경했습니다.
    - 이것이 아닌 다른 것이 원인이었고, 이 값은 이전 시즌 값으로 변경된 채로 남아있었습니다. 그래서 client 에서 이전 시즌 정보가 보이고 있었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200160-160.0.5
iOS.v160.0.5(42)

https://github.com/planetarium/NineChronicles/assets/150774808/67b4866e-2142-441f-952f-34565a3b009a
