### ISSUE TITLE
[장비] HP 비례 데미지 스킬 설명 확인 시 수치가 잘못되어 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4617]
### APV version info

v200160

### Client version info

v160.0.5

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
HP 비례 데미지 스킬 설명 확인 시 수치가 잘못되어 출력되는 현상
-실제 수치 0.8%의 100배인 80%로 출력되고 있습니다.
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/e1194b4b-0233-4002-9c18-d365d70e450d)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 워크샵 - 제작 클릭
2. HP 비례 데미지 스킬 설명 버튼 클릭
3. 데미지 수치 부분에 수치가 잘못되어 출력되는 현상 확인

[Should be]
HP 비례 데미지 스킬 설명 확인 시 수치가 정상적으로 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 실제 수치 확인부탁드립니다~

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.6
Android.v200160-160.0.6
iOS.v160.0.6(43)

https://github.com/planetarium/NineChronicles/assets/150774808/27cba59f-299c-4634-ace3-6802a1e261ea
