### ISSUE TITLE
[공방] 공방에서 신규 스킬 설명 확인 시 수치 최소-최대 범위가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4618]
### APV version info

v200160

### Client version info

160.0.5

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
공방에서 신규 스킬 설명 확인 시 수치 최소-최대 범위가 출력되지 않는 현상
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/c2067f74-3fbc-405e-9b92-9f0c3cfb46b4)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 워크샵 - 제작 클릭
2. 장비 탭에서 신규 스킬 장비 선택
3. 신규 스킬 설명 버튼 클릭 시 수치 최소-최대 범위가 출력되지 않는 현상 확인

[Should be]
공방에서 신규 스킬 설명 확인 시 수치 최소-최대 범위가 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
이거 테이블에 디스크립션 표현관련한 값들이 없느것같은데 확인부탁드립니다~! @NineSyu

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.6
Android.v200160-160.0.6
iOS.v160.0.6(43)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/5f666811-d2ef-42db-918b-96919b928313)
