### ISSUE TITLE
[룬] 룬 튜토리얼 진행 이후 인벤토리에 룬 탭 진입 시 보유하고 있지 않은 룬에 활성화 표시가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4623]
### APV version info

v200160

### Client version info

v160.0.5

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0x7d14F1721609e9B1a7dB80F750610A4FED29C143

### What happened?

[내용]
룬 튜토리얼 진행 이후 인벤토리에 룬 탭 진입 시 보유하고 있지 않은 룬에 활성화 표시가 출력되는 현상
-재진입 이후에는 정상적으로 출력되는 것을 확인하였습니다.
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 스크린 샷 확인 부탁 드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/2cff0615-863e-4ad5-a4c5-9e4569bd5dae)

### How to reproduce the issue

[재현스텝]
1. 신규 계정 생성 후 튜토리얼 진행
2. 23스테이지 클리어 후 룬 제작 튜토리얼 진행
3. 인벤토리 > 룬 진입하여 보유하고 있지 않은 룬에도 활성화 표시되는 것을 확인

[Should be]
인벤토리 룬 탭에 보유하지 않은 룬이 출력되지 않아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
일단 에디터의 튜토리얼 테스트툴로는 동일현상이 재현되지않습니다. 
동일래밸까지 아바타를 성장시켜서 최대한 실제와 가깝게 테스트해봐야할것같습니다.

**Comment by ipdae** [comment]
@QgamesTaekHaJang 혹시 PC에서 확인하셨을때 로그를 올려주실수있나요?

**Comment by eugene-doobu** [comment]
해당 이슈 확인시 룬 튜토리얼과 관련없는 이슈로 보입니다. 신규계정 생성하고 룬 튜토리얼 시작 안했는데 해당 이슈 발생했네요

**Comment by Namyujeong** [comment]
@ipdae 튜토리얼과 관계 없는 문제라면 오히려 이슈 무게가 좀 더 높아보입니다. 인벤토리 표시 초기화 관련하여 정확한 데이터를 보여줄 수 있도록 체크해보고 나가는 것이 좋을 것 같습니다.

**Comment by QgamesTaekHaJang** [comment]
다른 계정으로 재현한 로그 공유드립니다.
확인 부탁드리겠습니다.

확인 진행한 계정 주소: 0x86cF4a65290e2fb32c42558dA8A5Cc3b7c7c44D4

[Log_0325.zip](https://github.com/planetarium/NineChronicles/files/14739824/Log_0325.zip)

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.6
Android.v200160-160.0.6
iOS.v160.0.6(43)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/0c07fdcd-0796-4d1d-b603-19252900ff22)
