### ISSUE TITLE
[퀘스트] 어드벤쳐 퀘스트 클리어 보상이 증가한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4624]
### APV version info

v200160

### Client version info

160.0.5

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 퀘스트 클리어 보상이 증가한 현상
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/564c4ee1-ebc7-4945-b9fa-d98fa5dac01e)

160.0.5 인터널

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/1ce052d1-81e7-47d2-8f40-0311f5d7a47b)

152.0.0 메인넷

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 퀘스트 클릭
2. 어드벤쳐 탭 내 퀘스트 확인
3. 메인넷과 비교 시 어드벤쳐 퀘스트 클리어 보상이 증가한 현상 확인

[Should be]
어드벤쳐 퀘스트 클리어 보상이 기존과 동일해야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 @NineSyu 보상 확인 부탁드립니다~

**Comment by jaeho0103** [comment]
어드벤쳐 퀘스트 클리어 보상은 작년 11월 모바일버전 오픈시 변경되었습니다.
다만 현재 메인넷을 체크하신 계정은 그전에 만들어진 계정으로 예상되며,
신규유저들은 각 월드에 따른 클리어보상이 셋팅되어있는 부분으로 정상 스펙으로 확인됩니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160-160.0.5
Android.v200160-160.0.5
iOS.v160.0.5(42)
