### ISSUE TITLE
[어드벤쳐] 접속 후 클리어한 스테이지 Sweep 클릭 시 팝업 내 텍스트가 Repeat로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4630]
### APV version info

v200160

### Client version info

160.0.5

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
접속 후 클리어한 스테이지 Sweep 클릭 시 팝업 내 텍스트가 Repeat로 출력되는 현상
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/8714ff49-e9a9-4fa9-9efc-ccec21b6e68e

### How to reproduce the issue

[재현스텝]
1. 클라이언트 실행 - 메인 화면 - 어드벤쳐 클릭
2. 임의의 클리어한 스테이지 클릭
3. Sweep 클릭 시 팝업 내 텍스트가 Repeat로 출력되는 현상 확인

[Should be]
접속 후 클리어한 스테이지 Sweep 클릭 시 팝업 내 텍스트가 Sweep으로 출력되어야 합니다.

**Comment by QgamesTaekHaJang** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.6
Android.v200160-160.0.6
iOS.v160.0.6(43)

![Image](https://github.com/planetarium/NineChronicles/assets/156992678/15978842-e2e5-46da-87ed-b3893dae5b90)
