### ISSUE TITLE
컬렉션 폴리싱 - 장비 레시피에 관련 컬렉션 및 완료 수 표시해주기

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#4637]
Workshop - craft 왼쪽 하단 Collection 바로가기에 추가 정보 표시

입장 및 레시피 노 선택시 - 전체 collection 완성도 표시 (Completion ㅁㅁ/전체수)
레시피 선택시 - 해당 recipe 로 완성되는장비가 포함된 collection 완성도 표시 (This recipe comepletion ㅌㅌ/전체수)

@boramqo83 시안 부탁드리겠습니다.
@eugene-doobu 25일 저녁식사때 얘기한 이슈입니다. 체크 부탁드리겠습니다.

**Comment by boramqo83** [comment]
프리퓁 안에 들어가져 있습니다.
![image](https://github.com/planetarium/NineChronicles/assets/102953029/55267c5b-f381-4f93-8bd9-c2b89aa91c64)
CompletionArea 켜 주시고, 
![image](https://github.com/planetarium/NineChronicles/assets/102953029/afbe9db4-89c6-4cfc-a2ef-37f92bb78c15)
Line 높이 -5.5로 올려주세요.

**Comment by boramqo83** [comment]
각 레시피마다 필요한 컬렉션 정보 표기까지 작업해서 전달 드리는 것으로 하겠습니다.

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/craft_collection_info-add
사용 프리퓁 : UI_Craft

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/69692539-77b5-4bb6-8493-7ad52de92797)

숫자 연결 시켜 주세요.
음식, 재료, 이벤트 아이템 등 프리퓁에 넣어두었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/5f00fab8-b4f2-4e6b-8949-07a883269da7)

숫자 연결시켜 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/539131ae-83ee-433c-832e-cc044de232aa)

해당 프리퓁 수정하면서 위와 같은 문제도 해결했습니다.
