### ISSUE TITLE
[아이템] 신성 장비 툴팁 내 아포스트로피 다음에 띄어쓰기가 길게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4640]
### APV version info

v200160

### Client version info

v160.0.6

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신성 장비 툴팁 내 아포스트로피 다음에 띄어쓰기가 길게 출력되는 현상
-PC 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/a13d71e4-2989-433b-8b82-88e6a4a885ab)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 인벤토리 클릭
2. 임의의 신성 장비 클릭
3. 툴팁 확인 시 아포스트로피 다음에 띄어쓰기가 길게 출력되는 현상 확인

[Should be]
신성 장비 툴팁 내 아포스트로피 다음에 띄어쓰기가 한 칸만 출력되어야 합니다.

**Comment by NineSyu** [comment]
https://github.com/planetarium/NineChronicles/pull/4689
윗 PR링크로 이슈 해결하려고 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/af58092c-bcc0-49d8-b575-097587241eb9)

[테스트 환경]
Windows.v200170-170.0.8
