### ISSUE TITLE
[컬렉션] 수르트 검 컬렉션의 이름이 수르트의 검 그룹으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4641]
### APV version info

v200160

### Client version info

v160.0.6

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
수르트 검 컬렉션의 이름이 수르트의 검 그룹으로 출력되는 현상
-다른 부위 장비는 장비명과 동일하게 출력되고 있습니다.
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/5c00f281-05ac-4089-af3c-e60e68cbc742)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 컬렉션 클릭
2. 수르트 검 컬렉션 확인 시 컬렉션의 이름이 수르트의 검 그룹으로 출력되는 현상 확인

[Should be]
수르트 검 컬렉션의 이름이 수르트 검 그룹으로 출력되어야 합니다.

**Comment by NineSyu** [comment]
https://github.com/planetarium/NineChronicles/pull/4689
윗 PR링크로 이슈 해결하려고 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/fc39b7b4-5481-4b92-874f-44c1036919e8)

[테스트 환경]
Windows.v200170-170.0.8
Android.v200170-170.0.8
iOS.v170.0.8(57)
