### ISSUE TITLE
[공방] 노멀 속성 수르트 검의 트윈어택 효과 수치가 낮게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4642]
### APV version info

v200160

### Client version info

v160.0.6

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
노멀 속성 수르트 검의 트윈어택 효과 수치가 낮게 출력되는 현상
-물 속성 54000 ~ 90000 / 노말 속성 54000 ~ 90000 / 바람 속성 102000 ~ 170000 입니다.
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/88655230-5ae5-4455-a787-dae52e4df291)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 워크샵 클릭
2. 제작 - 장비 - 노멀 속성 수르트 검 클릭
3. 트윈어택 스킬 효과 확인 시 수치가 낮게 출력되는 현상 확인

[Should be]
노멀 속성 수르트 검의 트윈어택 효과 수치가 102000~170000으로 출력되어야 합니다.

**Comment by NineSyu** [comment]
노멀 수르트의 트윈어택 효과 수치는 물속성 검과 동일한 스킬 효과량을 가지고 있는 것이 의도한 스펙이 맞습니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160-160.0.6
Android.v200160-160.0.6
iOS.v160.0.6(43)
