### ISSUE TITLE
[그라인딩] 1회 그라인딩 이후 장비 등록 시 크리스탈 수량이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesTaekHaJang** [planetarium/NineChronicles#4644]
### APV version info

v200160

### Client version info

v160.0.6

### Device

Windows, Android, iOS

### detailed device info

Windows 11, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
1회 그라인딩 이후 장비 등록 시 크리스탈 수량이 출력되지 않는 현상
-PC/Android/iOS 환경에서 확인하였습니다.
-첨부 드린 영상 확인 부탁 드립니다.

https://github.com/planetarium/NineChronicles/assets/156992678/5a6eee2e-5d92-4288-8f21-65bfed821e03

### How to reproduce the issue

[재현스텝]
1. 메인 로비 > 공방 > Grind 진입
2. 임의의 장비 그라인딩 1회 진행
3. 임의의 장비 등록하여 분해 시 획득 크리스탈 수량이 출력되지 않는 것을 확인

[Should be]
Grind 화면에서 임의의 장비 등록 시 분해 획득 크리스탈 수량이 정상적으로 출력되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
하기 이슈 종료 처리되어 동일 이슈인 해당 이슈도 종료하겠습니다.
https://github.com/planetarium/NineChronicles/issues/5363
