### ISSUE TITLE
[공방] 신성 장비 분해 시 크리스탈이 1개만 지급되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4645]
### APV version info

v200160

### Client version info

v160.0.6

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신성 장비 분해 시 크리스탈이 1개만 지급되는 현상
-추가로, 분해 스테이킹 보너스 적용 시 우편함에서 획득한 크리스탈이 소수점으로 출력되는 현상 확인했습니다.
실제 획득한 크리스탈은 올림 처리되었습니다. 해당 현상도 확인 부탁드립니다,
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/8efdde67-b960-478f-9791-182366d030fc

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 워크샵 - 분해 클릭
2. 신성 등급 클릭 후 분해 시 크리스탈이 1개만 지급되는 현상 확인

[Should be]
신성 장비 분해 시 등급에 맞는 크리스탈이 지급되어야 합니다.

**Comment by jaeho0103** [comment]
테이블 패치로 정상 데이터 확인했습니다.
체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200160-160.0.6
Android.v200160-160.0.6
iOS.v160.0.6(43)

https://github.com/planetarium/NineChronicles/assets/150774808/0d631d03-78a7-49b7-9a1e-25a089ab8269
