### ISSUE TITLE
[상점] 무료 모험가 패키지의 이미지가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4648]
### APV version info

v200160

### Client version info

v160.0.6

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
무료 모험가 패키지의 이미지가 출력되지 않는 현상
-Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/388b124c-ab5b-459e-aba5-0e292c4f79e9)

### How to reproduce the issue

[재현스텝]
1. 메인 화면 - 상점 클릭
2. 패키지 탭 클릭
3. 무료 모험가 패키지의 이미지가 출력되지 않는 현상 확인

[Should be]
무료 모험가 패키지의 이미지가 출력되어야 합니다.

**Comment by U-lis** [comment]
이미지 path 가 잘못 되어 있어 바로잡았습니다.
![image](https://github.com/planetarium/NineChronicles/assets/3654082/e7665173-514c-47db-ac6e-94b00edfdc9e)

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200160-160.0.6
iOS.v160.0.6(43)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/63691e38-74dc-4eb7-aaca-346f56be18d1)
