### ISSUE TITLE
업그레이드 장비 리스트에서 2차 정렬 CP 내림차순으로 조정

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#4655]
업그레이드할 장비를 고를때 등급 안에서 정렬이 어떤기준인지 모르겠어서 장비마다 CP를 다 체크해서 강화할 장비를 고르는게 너무 불편해서 1차 정렬 등급, 같은 등급안에서는 CP 내림차순 으로 리스트 처리 요청드립니다.

**Comment by sonohoshi** [comment]
#5226 에서 처리하기로 하여 close합니다.
