### ISSUE TITLE
[메일] 상점 내 아이템 회수 시 Jade의 이미지가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4684]
### APV version info

v200160

### Client version info

v160.1.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
상점 내 아이템 회수 시 Jade의 이미지가 출력되지 않는 현상
-PC 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/a7704280-249e-4bc6-b89b-8beaf078357f)

### How to reproduce the issue

[재현스텝]
1. 메인 로비 > 상점 클릭
2. Sell 탭 > 임의의 등록한 아이템 회수 진행
3. 아이템 회수 시 확성기 이미지가 출력되는 현상 확인

[Should be]
상점 내 아이템 회수 시 Jade의 이미지가 출력되어야 합니다.

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.1.1
Android.v200230-230.1.1
iOS.v230.1.1(117)

![아이템 회수](https://github.com/user-attachments/assets/5f0f0e6e-03cb-48d9-ba17-1d55bf246e78)
