### ISSUE TITLE
[상점] Sell 탭 일부 필터가 작동하지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4685]
### APV version info

v200160

### Client version info

v160.1.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Sell 탭 일부 필터가 작동하지 않는 현상

-음식 필터 > 스탯 관계 없이 모든 음식이 출력됩니다.
-타이틀 / 모래시계 / AP포션 / 룬스톤 > 무기가 출력되고 있습니다.
-펫 소울 스톤 > 타이틀이 출력되고 있습니다.

-PC 환경에서 확인하였습니다.
-첨부한 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/391d1dd8-6b81-4d44-b46e-4f7f2e2fa524

### How to reproduce the issue

[재현스텝]
1. 메인 로비 > 상점 클릭
2. Sell 탭 > 임의의 아이템 등록
3. 필터 적용 시 작동하지 않는 현상 확인

[Should be]
Sell 탭 필터가 작동해야 합니다.

**Comment by ipdae** [comment]
서버와 클라이언트의 필터가 문제인것처럼 보이는데, 어디쪽에서 오작동이 있는지 조사가 필요합니다.
