### ISSUE TITLE
이벤트 던전 티켓 헤더가 일반 전투시에도 AP헤더 대신 나오는 현상

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4687]

**Comment by eugene-doobu** [comment]
지금 게임 내 컨텐츠들을 Widget이라는 UI단위로 관리하고 있는데, 여러 컨텐츠들을 동시에 활성화시킬 수 있는것이 이와 관련된 UI버그들의 원인입니다. 상단의 스태틱 UI가 가장 최근에 업데이트 요청을 한 컨텐츠와 관련된 재화를 보여주기 때문에, 현재 화면에 렌더링되고 있는 Widget UI가 Stage 전투에 관련된 것이라도 내부적으로 이벤트 던전과 관련된 호출이 생기면 상단 UI가 이벤트 티켓을 보여주는 것으로 렌더링됩니다.
