### ISSUE TITLE
[랭킹] 코스튬 착용 캐릭터의 프로필 이미지에 장비 프로필 이미지가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4695]
### APV version info

메인넷.v200160

### Client version info

v160.1.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
코스튬 착용 캐릭터의 프로필 이미지에 장비 프로필 이미지가 출력되는 현상
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/069a72ba-212a-4b54-8638-7dd1032d4f9f

### How to reproduce the issue

[재현스텝]
1. 코스튬 착용 상태
2. 메인 로비 - 랭킹 버튼 클릭
3. 코스튬 착용 캐릭터의 프로필 이미지에 장비 프로필 이미지가 출력되는 현상 확인

[Should be]
코스튬 착용 캐릭터의 프로필 이미지에 코스튬 프로필 이미지가 출력되어야 합니다.

**Comment by ipdae** [comment]
DB에 저장된 정보와 실시간 정보의 차이에 의한것으로 보입니다.
