### ISSUE TITLE
[런쳐] 런쳐 화면 하단에 Done 텍스트가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4698]
### APV version info

메인넷.v200160

### Client version info

v160.1.0

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
런쳐 화면 하단에 Done 텍스트가 출력되는 현상
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/64ec0389-34af-4965-ba18-171661b0b0f7)

### How to reproduce the issue

[재현스텝]
1. 런쳐 실행
2. 런쳐 화면 하단에 Done 텍스트가 출력되는 현상 확인

[Should be]
런쳐 화면 하단에 Done 텍스트가 출력되지 않아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@Akamig 요거 이슈 확인 부탁드립니다~!

**Comment by Akamig** [comment]
저건 상정된 정상작동입니다.

**Comment by jonny-jeahyunchoi** [comment]
확인감사합니다~!
