### ISSUE TITLE
[콘솔로그 정리] UnityEditor에서 로그를 쉽게 확인할수있는 플러그인 도입

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4704]

**Comment by eugene-doobu** [comment]
https://github.com/bbbscarter/UberLogger

**Comment by eugene-doobu** [comment]
아래 이슈 생각하며 작업하는게 좋을 것 같습니다 
https://github.com/planetarium/NineChronicles/issues/4706
