### ISSUE TITLE
이벤트 릴리즈노트 백오피스 작성을위한 문서화

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4707]
- 사용하고있는 스팩 정리
    - 파일위치 규칙이나, json 포맷
- 백엔드에 필요한 스팩
    - 추가, 목록, 제거 등등

**Comment by sonohoshi** [comment]
https://github.com/sonohoshi/md2tmp 에서 이를 관리하는 툴을 만들고있고

**Comment by sonohoshi** [comment]
과정과 툴을 만들어놨으니 not planed로 close합니다.
