### ISSUE TITLE
[펫] Select Pet 팝업에서 미보유펫 설명 텍스트(영문)가 영역 밖으로 삐져나옴

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4719]
### APV version info

메인넷.v200160

### Client version info

v160.1.0

### Device

Windows

### detailed device info

Windows 10

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
Select Pet 팝업에서 미보유펫 설명 텍스트(영문)가 영역 밖으로 삐져 나옵니다.
-Windows 환경에서 확인하였습니다.
-첨부한 스크린 샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/916640c6-db3f-4edf-a1ec-de3442a5d2c8)

### How to reproduce the issue

[재현스텝]
1. 메인 로비 > Workshop > Craft 진입 (펫 미보유 상태여야 함)
2. 제작할 장비 선택 > Select Pet 팝업에서 해당 이슈 확인 가능

[Should be]
Select Pet 팝업에서 미 보유펫 설명 텍스트(영문)가 영역을 벗어나지 않아야 합니다.

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/pet_description_list-edit
사용 프리퓁 : PetDescriptionView

**Comment by boramqo83** [comment]
추가 개발 없습니다.
