### ISSUE TITLE
Rune Level Bonus

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4720]
기획서 위치

[https://www.notion.so/planetarium/Rune-Level-Bonus-91b2940c296f427090798896a3d6be7d](https://www.notion.so/Rune-Level-Bonus-91b2940c296f427090798896a3d6be7d?pvs=21)

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/rune_level_bonus-add
사용 프리퓁 : 
UI_Rune

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/f075d18b-addd-4260-9f00-0efdfa27a31b)

리스트 영역을 줄이고 룬 레벨 보너스를 적용 시켜 주었습니다.
- 룬 레벨 보너스와 룬 스텟 보상 l10n 적용 시켜 주세요.
- 수치 연결시켜 주세요.
- 버튼 연결시켜 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/b2e10aac-4df7-4325-954f-babddd23f3d6)

1. Content 안에 RuneLevelBonusEffectCell 프리퓁 넣어주세요.
2. 현재 내 위치를 나타내는 곳에는 MyPosition 를 켜주세요.
3. Cell간 간격은 0으로 해 주세요.
4. 안에 들어갈 숫자 맞춰주세요. (기획 픽스 되었는지 문의 후 적용)
5. 언어대응 시켜 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/f9b1eb62-0562-4502-99be-081459bd2e04)

FailText는 사용하지 않습니다.
SuccessText에 '성공'이 아닌 '결과'로 텍스트가 나오도록 l10n 수정해 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/4f4b3af0-0620-478f-8fbb-235f36175abb)

1. 룬레벨 보너스가 스텟이 열리고 난 후에 등장되도록 애니메이션에 넣어두었습니다.
2. 룬레벨 보너스 텍스트 언어대응 되야 합니다.
3. 수치 연결시켜 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/b4036455-d6e5-404d-85fb-5d8aa26a335e)

CP 상승 연출
- 룬 레벨 보너스는 늘 상승하므로 CP 상승 연출은 거의 항상 뜬다고 보면 됩니다.
- 다만 룬 레벨 보너스가 너무 작게올라서 CP가 올라가지 않는 경우 요 표기는 하지 않습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/0b153c65-fcff-4fcc-b756-e6b2d56a1e1c)

1. 말풍선 안의 내용이 바뀌었습니다.
2. 업그레이드 수치 연결시켜 주세요.
3. 텍스트 언어대응시켜 주세요.
4. 캐릭터가 등장하고, 말풍선이 나오도록 해 주세요. (기존 연출을 제가 컨트롤할 수 없어 아래와 같이 만들어 두었습니다.)
- Show : 등장
- Loop :  루프 (말풍선이 사라지지 않고 계속 떠 있도록 해 주세요0

**Comment by boramqo83** [comment]
프리퓁 작업 완료 했습니다.
추가 개발 이슈 있습니다. @tyrosine1153

**Comment by boramqo83** [comment]
룬레벨 보너스 지수는 다음주 중에 해야 할 것 같습니다.
시안은 아래와 같습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/102953029/7107e397-960b-4d35-92a0-edcc0ed30c8d)

**Comment by tyrosine1153** [comment]
> ![Image](https://private-user-images.githubusercontent.com/102953029/319444922-0b153c65-fcff-4fcc-b756-e6b2d56a1e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDczNDcsIm5iZiI6MTcxMjIwNzA0NywicGF0aCI6Ii8xMDI5NTMwMjkvMzE5NDQ0OTIyLTBiMTUzYzY1LWZjZmYtNGZjYy1iNzU2LWU2YjJkNTZhMWUxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwNTA0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjJmOWFjZjBmOGViN2MwMzU4NjRmOWEzYmNkZmNiMWJjYWU3MGYzMGI1NTQ3ZjE2MmI1ZDVkZDg3YmYzNjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sgghvNgcDGCC5JpFrTiZGpHHlpby3KInKXUgi8h4cB8)
> 
> 1. 말풍선 안의 내용이 바뀌었습니다.
> 2. 업그레이드 수치 연결시켜 주세요.
> 3. 텍스트 언어대응시켜 주세요.
> 4. 캐릭터가 등장하고, 말풍선이 나오도록 해 주세요. (기존 연출을 제가 컨트롤할 수 없어 아래와 같이 만들어 두었습니다.)
> 
> * Show : 등장
> * Loop :  루프 (말풍선이 사라지지 않고 계속 떠 있도록 해 주세요0

@boramqo83 보람님 전달받은 프리펩에는 시안에서 추가해주신 RuneLevelBonus가 누락 된 것 같습니다. 확인 부탁드립니다!
![image](https://github.com/planetarium/NineChronicles/assets/63496908/b8c32c2e-adbc-47d4-9592-e824f15805a4)

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/7dd942ed-492c-40aa-b745-ed3b2052f279)

룬레벨 지수와 룬레벨 보너스 수치 변화 정보가 추가되었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/af0ac45c-3802-43d5-aa47-f489c17b709e)



결과화면에 룬 레벨 보너스 추가해 두었습니다. (<- 추가 개발 필요합니다.)

**Comment by boramqo83** [comment]
20240416 수정사항 가이드 이어서 작성합니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/a357daad-d713-447c-9dff-1692f2469961)

TextGroup_RuneStatRewards : 추가되었습니다. 수치 연결되야 합니다.
NumberText : 변경되지 않는 수치만 보여주는 룬스텟보상 숫자는 사용하지 않습니다. (삭제하셔도 됩니다.)
TextGroup_RuneLevelBonus : 룬레벨보너스 수치변경되는 정보는 보여주지 않는 것으로 수정되었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/fc4ef1ed-7bfb-4825-a632-ee8e5be8ecf3)

해당 팝업 위치 수정했습니다. 추가 개발 없습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/f7a40796-d7ae-4bf8-92bb-337f074a141c)

타이틀을 Rune Stat Rewards로 수정해 주었습니다.
수치 변경되는 내용이 룬레벨보너스가 아닌 룬스텟보상이 되도록 수정해 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/bf74c805-48e0-4488-8d81-a3e44ea87340)

인벤토리와 준비화면(어드밴처, 월드보스, 아레나)의 Collection Effect를 Stats Bonus로 수정해 주세요.
기획자한테 L10n 문의

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/c2831e6b-3119-43f9-9266-5e97a25656ef)



UI_CollectionEffectPopup 프리퓁 이름을 UI_StatsBonusPopup으로 변경했습니다.
1. 언어대응되야 합니다.
2. 수치 연결시켜 주세요.
3. 버튼 눌렀을 때 룬 화면으로 이동시켜 주세요.

**Comment by boramqo83** [comment]
24.04.19 프리퓁 수정했습니다.


![Image](https://github.com/planetarium/NineChronicles/assets/102953029/73494997-d06f-491e-9e71-ca8492ebd7b9)

룬레벨 보너스와 룬스텟 리워드를 틀 안에 넣었습니다.
