### ISSUE TITLE
[어드벤처 보스]돌파 연출관련 RnD

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4732]
로컬 에서 lib9c수정하여 커스텀 배틀로그를 만들어 연출테스트해보기

**Comment by eugene-doobu** [comment]
stage관련해서 대규모 공사가 진행중이라 지금 요거 관련해서 작업하시는게 있다면 충돌이 날 확률이 높을것같군요

**Comment by eugene-doobu** [comment]
일단 아래 pr에서 작업한 내용들이 있는데.. stage/raid/arena같은 스크립트를 한 디렉토리에 모여 관리되도록 위치를 이동시켰고 해당스크립트 상태관리 관련해서 추가적으로 수정이 있을것 같습니당
https://github.com/planetarium/NineChronicles/pull/4736

**Comment by jonny-jeahyunchoi** [comment]
이거 일단 수정사항이많아보이고 작업완료되면 머지될가능성도 높아보여서 말씀하신 PR기반으로 일단 테스팅하고있을께요~! @eugene-doobu

**Comment by jonny-jeahyunchoi** [comment]
- 몬스터 충돌박스관련해서 배속시 이슈가 발생하는 구조라고 하는데 관련 개선점있는지 같이 확인해보기

**Comment by jonny-jeahyunchoi** [comment]
CharacterBase확인결과 플레이어캐릭터와 몬스터간 OnTriggerEnter를 사용하고있어서 스피드가 올라갈경우 트리거가 통과되면서 발생하는 문제점이 있음.  CharacteBT와도 연관이있어서 바꾸기 애매한상황. 트리거 사용하지않고 동작할수있도록 구조개선해야할필요가 보임.

**Comment by jonny-jeahyunchoi** [comment]
충돌검출 방식의 타입을 변경해서 단순하게 보완하는 방법도 있음.
https://docs.unity3d.com/Manual/choose-collision-detection-mode.html
충돌 방향이 고정이니 Continuous Speculative 방식도 나쁘지않을것같음

**Comment by jonny-jeahyunchoi** [comment]
프롤로그에서 가져오는 몬스터 GameObject가 어드레서블이전 리소스로드방식이어서 문제가생길여지가있음.

**Comment by jonny-jeahyunchoi** [comment]
기존 스테이지에서 Spawn Event를가지고 몬스터를 소환하는위치와 프롤로그에서 소환하는위치의 기준점이달라서 생성위치가 꼬임.

**Comment by jonny-jeahyunchoi** [comment]
추가 진행해야하는 내용

- 배경 변환
- 돌파하는 스테이지 개수에 따른 스피드변화
- 연출에사용한 변수들 따로 빼서 직접테스트해볼수있도록 세팅
- 수정사항 정리 및 기존 구조와 분리할수있는것들 분리
