### ISSUE TITLE
[아레나] 챔피언십 조건을 충족하지 않은 캐릭터로 챔피언십 등록이 가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4738]
### APV version info

v200160

### Client version info

v160.1.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
챔피언십 조건을 충족하지 않은 캐릭터로 챔피언십 등록이 가능한 현상
-신규 캐릭터 / 승리 160회를 달성하지 않은 캐릭터 모두 발생하고 있습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/9cf313c2-3cc7-49f4-9a53-bb1c816b9ac6

-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 영상 확인 부탁드립니다.

### How to reproduce the issue

[재현스텝]
1. 챔피언십 조건 미달 캐릭터 세팅
2. 메인 로비 - 아레나 클릭
3. 챔피언십 조건을 충족하지 않은 캐릭터로 챔피언십 등록이 가능한 현상 확인

[Should be]
챔피언십 조건을 충족하지 않은 캐릭터로 챔피언십 등록이 불가능해야 합니다.

**Comment by jaeho0103** [comment]
1번의 체크가 잘못되신듯 싶습니다.
이번에는 챔피언쉽 입장조건을 특별히 0 메달 필요로 수정한 부분입니다.
현재는 조건이 모두에게 open 되어있는 상태입니다. (첫화면에서 조건 부분에 completed 로 체크되어있는 부분 확인부탁드리겠습니다.)
즉, 조건을 충족하지 않은 유저에게 등록이 가능한것은 아닌것으로 보여집니

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200160-160.1.1
Android.v200160-160.1.1
iOS.v160.1.1(45)
