### ISSUE TITLE
LiveAssetManager/PatrolReward에 재연결 시도 추가

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4753]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1712802921610499

**Comment by U-lis** [comment]
지금 상태로는 여기저기에 따로따로 timeout 을 잡아야 해서 일이 많을 것 같다
어떤 것들이 계사속 업데이트되는 것인지 골라서 작업계획을 세우는 것이 필요하다

**Comment by sonohoshi** [comment]
1. 우선 게임 시작할때 초기화 시도하는 모듈을 좀 리스트업해보고
2. 그 다음에 시도할때 재연결 시도를 할 수 있는지 모색해보는 식으로 진행하겠습니다

**Comment by sonohoshi** [comment]
외부에 의존하는 부가 서비스는 대략 다음이 있고
1. LiveAssetManager
2. PatrolRewardServiceClient
3. MarketServiceClient
4. SeasonPassServiceManager
5. IAPServiceManager
얘네들이 전부 다 Game.Start() 안에서 Initialize를 시도하고 그 이후로 안하는 형태니까 Initialize에 retry를 붙일 수 있으면 좋겠다

**Comment by sonohoshi** [comment]
구조가 통일되어있지 않아서 단순히 Retry를 억지로 붙이는건 애매해보이고...
일단 InitializeAsync 안에서 실패하면 반복을 좀 돌게 해보자

**Comment by sonohoshi** [comment]
일단 PatrolReward/MarketService는 단순 uri만 initialize 하는 애들이라서 안건드려도 되고
- LiveAssetManager
- SeasonPassServiceManager
- IAPServiceManager
이 셋이 문제인듯

**Comment by sonohoshi** [comment]
나머지 gql이나 http client를 쓰는 애들은 UI단에서 초기화를 한번만 하는 것 같은데 걔는 별개로...

**Comment by sonohoshi** [comment]
일단 LiveAssetManager랑 PatrolReward는 동적으로 재연결 할 수 있게 고쳤고
