### ISSUE TITLE
모래시계 부족 한줄팝업이 모래시계 사용 후의 데이터를 기준으로 잘못 뜨고 있음.

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#4756]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1712837556629819

**Comment by U-lis** [comment]
@jonny-jeahyunchoi ; 이전에 모래시계 사용에 있어 유사한 이슈를 수정한 적이 있어서 같이 고쳐졌을 수 있다.
development 에서 확인은 필요.

**Comment by sonohoshi** [comment]
안고쳐졌고 고치겠습니다
