### ISSUE TITLE
장비 제작 화면과 장비 상세팝업에 EXP 넣기

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4757]

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/craft_exp-add
사용 프리퓁 : UI_Craft

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/98257d3a-f358-420e-baf6-f917da999ffc)

exp 추가해 두었습니다. 장비의 경우에는 레벨은 보여주기 않고 exp가 보이도록 해 줍니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/04251965-d1dc-4841-941e-e1b1a65d8fd0)

거래가능 텍스트와 레벨 텍스트를  안에 넣어주었습니다.
가 추가되었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/c60683d2-c48b-466f-b2ca-cb3d5b6ec743)

다른 툴팁 화면에서도 거래가능 텍스트와 레벨 텍스트를 한 줄로 묶어주었습니다.

**Comment by boramqo83** [comment]
개발 필요합니다.

**Comment by eugene-doobu** [comment]
개발 작업을 위한 브랜치로 pr 타겟 브랜치를 변경해둬서 머지해두도록 하겠씁니다~
