### ISSUE TITLE
시즌패스 지난 시즌 미수령 보상 지급 변경

### ISSUE THREAD

**Issue by U-lis** [planetarium/NineChronicles#4758]
1. 지난 시즌 미수령보상 소매넣기는 없어짐
2. 일반 유저는 시즌이 종료되면 미수령 보상 소멸
    - 시즌 중 잘 가져가라고 안내
    - 시즌 막바지에 이런저런 장치로 가져가라고 안내
3. 프리미엄 유저는 시즌 종료 후 1주일간 미수령 보상 수령 가능
    - 미수령 보상 받기 버튼으로 수령
    - 1주일동안 미수령한 보상은 소멸  
---
reference: [notion](https://www.notion.so/planetarium/5725190e79c54f969838fc0714b76101?pvs=4)

**Comment by U-lis** [comment]
BE : https://github.com/planetarium/NineChronicles.SeasonPass/issues/138

**Comment by jonny-jeahyunchoi** [comment]
변경된 번역키
UI_SEASONPASS_REMAINING_TIME : 더이상 시간을 인자로 받지않음.
추가된 번역키
UI_PREV_SEASONPASS_RECEIVE : 이전 보상 수령버튼
UI_PRVE_SEASON_CLAIM_LIMIT_WARNING : 이전보상 제한시간 안내
![image](https://github.com/planetarium/NineChronicles/assets/138189475/8a52fc61-6af3-4621-a719-0bbec0da33c1)

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu
