### ISSUE TITLE
비밀키 백업 시작화면에서 지원

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#4770]
![Image](https://github.com/planetarium/NineChronicles/assets/3193043/62fdea4b-8164-4378-98e8-c596b90332da)

시작화면에서 비밀키 백업을 지원해야합니다.

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/intro_screen_backup_button-add
사용 프리퓁 : UI_IntroScreen

**Comment by boramqo83** [comment]
![image](https://github.com/planetarium/NineChronicles/assets/102953029/7037c5e6-e3af-4d93-acc3-218ff3f8bfa3)
BackupButton 버튼 추가해 두었습니다.
버튼 연결시켜 주세요.

**Comment by sonohoshi** [comment]
![image](https://github.com/planetarium/NineChronicles/assets/48484989/42d32862-03c7-4c18-b473-c8ca8683fef7)
백업이라는 번역키가 없던가...
