### ISSUE TITLE
[UI] 어드벤쳐 준비 화면에서 착용 중인 코스튬이 코스튬 슬롯에 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4773]
### APV version info

메인넷.v200160

### Client version info

v160.1.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 준비 화면에서 착용 중인 코스튬이 코스튬 슬롯에 출력되지 않는 현상
-PC / Android / iOS 환경에서 확인하였습니다.
-첨부한 스크린샷 확인 부탁드립니다.
![이슈등록](https://github.com/planetarium/NineChronicles/assets/150774808/1488537a-f36c-401c-9a3c-60318a2645d7)

### How to reproduce the issue

[재현스텝]
1. 코스튬 착용 캐릭터로 접속
2. 메인 로비 - 어드벤쳐 - 임의의 스테이지 클릭
3. 준비 화면에서 착용 중인 코스튬이 코스튬 슬롯에 출력되지 않는 현상 확인

[Should be]
어드벤쳐 준비 화면에서 착용 중인 코스튬이 코스튬 슬롯에 출력되어야 합니다.

**Comment by ipdae** [comment]
현재도 발생은 하고 있으나 우선순위가 높지않아 일단 닫아둡니다.
