### ISSUE TITLE
IceShield & FrostBite vfx 적용

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#4785]
신규 아우라 스킬인 IceShield & FrostBite vfx을 클라이언트에 적용합니다 

## Related Links

https://github.com/planetarium/lib9c/pull/2540

**Comment by ipdae** [comment]
- #4900

**Comment by eugene-doobu** [comment]
전투 시뮬레이터 관련 이슈 (필수)
https://github.com/planetarium/NineChronicles/issues/4908

연출 관련 이슈
https://github.com/planetarium/NineChronicles/issues/4900
https://github.com/planetarium/NineChronicles/issues/4902
https://github.com/planetarium/NineChronicles/issues/4904

밸런스 편의성 관련 이슈
https://github.com/planetarium/NineChronicles/issues/4899
https://github.com/planetarium/NineChronicles/issues/4898
