### ISSUE TITLE
Craft UI에서 크리스탈 장비 제작 시 텍스트 비정상, 제작 안 됨

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4799]
관련 슬랙 스레드 : https://planetariumhq.slack.com/archives/C011716SDTM/p1713777664224409?thread_ts=1713763955.040179

**Comment by eugene-doobu** [comment]
아래 이슈에서 처리하였습니다
https://github.com/planetarium/NineChronicles/pull/4798
