### ISSUE TITLE
룬 툴팁에 보이는 cp와 실제 적용된 cp가 같음

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4801]
### Should be

툴팁의 보이는 cp는 룬 자체의 cp, 실제 적용되는 cp는 스텟 이펙트(룬 레벨 보너스, 콜렉션)를 적용받아야 함

**Comment by tyrosine1153** [comment]
https://github.com/planetarium/lib9c/issues/2547 해당 이슈 해결 후 클라이언트 대응하는 것으로

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200170-170.0.4
Android.v200170-170.0.4
iOS.v170.0.4(53)

https://github.com/planetarium/NineChronicles/assets/150774808/f2bad2a2-100e-4df6-abab-186c6a24cec7
