### ISSUE TITLE
[워크샵] 장착 중인 룬 강화 완료시 CP 변화량이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4804]
### APV version info

v200170

### Client version info

v170.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
장착 중인 룬 강화 완료시 CP 변화량이 출력되지 않는 현상
-Windows / Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/0f4a0acb-9444-489d-b2ce-dc4698ac0f07

### How to reproduce the issue

[재현과정]
1. 메인 로비 - 워크샵 - 룬 클릭
2. 장착중인 룬 선택
3. 룬 강화 완료시 CP 변화량이 출력되지 않는 현상 확인

[Should be]
장착 중인 룬 강화 완료시 CP 변화량이 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
https://github.com/planetarium/lib9c/issues/2547 해당 이슈 해결 후 클라이언트 대응하는 것으로

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/8a410d1d-08da-4470-83f6-edcc6b6dd369

[테스트 환경]
Windows.v200170-170.0.3
Android.v200170-170.0.3
iOS.v170.0.3(52)
