### ISSUE TITLE
[워크샵] 룬 레벨 보너스가 실제보다 높게 적용되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4806]
### APV version info

v200170

### Client version info

v170.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
룬 레벨 보너스가 실제보다 높게 적용되는 현상
-계정 1 383레벨 (47.572%) > 414레벨 (48.998%)
-계정 2 118레벨 (35.382%) > 172레벨 (37.846%)
-Windows / Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/7529702b-24e7-45fb-82b6-df4fa024a4a2

### How to reproduce the issue

[기대결과]
1. 메인 로비 - 인벤토리 클릭
2. 임의의 룬 착용
3. 룬 레벨 보너스가 적용 확인
4. 룬 레벨 보너스가 실제보다 높게 적용되는 현상 확인

[Should be]
룬 레벨 보너스가 실제 수치와 동일하게 적용되어야 합니다.

**Comment by tyrosine1153** [comment]
콜렉션 스탯이 HP +1%인데 예상 값이 이부분도 포함해서 계산이 된 건가요?

**Comment by tyrosine1153** [comment]
이건 collection 있는 아바타

![Image](https://github.com/planetarium/NineChronicles/assets/63496908/ae0b204b-233b-4543-9202-d2281ba5aa10)

이건 collection 있는 아바타로 돌려봤습니다...

![Image](https://github.com/planetarium/NineChronicles/assets/63496908/b18b4fab-c336-447d-a4e8-6ef2f867cadc)

**Comment by QgamesGeonPyoNoh** [comment]
컬렉션 보너스 % 스탯 적용 시 예상 수치와 일치하는 것으로 확인했습니다.
확인 감사드립니다.
![image](https://github.com/planetarium/NineChronicles/assets/150774808/e3e3f751-d692-4ee2-9a09-1c106d453eff)

[테스트 환경]
Windows.v200170-170.0.2
Android.v200170-170.0.2
iOS.v170.0.2(52)
