### ISSUE TITLE
[워크샵] 장비 강화 화면에 흰색 배경 이미지가 겹쳐 나오는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4807]
### APV version info

v200170

### Client version info

v170.0.2

### Device

iOS

### detailed device info

iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
장비 강화 화면에 흰색 배경 이미지가 겹쳐 나오는 현상
-iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/08350c03-8715-434b-af2d-f933f8fc0098)

### How to reproduce the issue

[재현과정]
1. 메인 로비 - 워크샵 - 강화 클릭
2. 배경 화면에 흰색 캔버스 이미지가 겹쳐 나오는 현상 확인

[Should be]
장비 강화 화면에 흰색 배경 이미지가 출력되지 않아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@QgamesGeonPyoNoh
특정기기의 랜더링 이슈인것같아서 몇가지 테스트 요청드립니다~!

- 문제상황 발생시 로그 확인
- 동일 기기에서 라이브 버전 테스트 (160.1.0)

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 발생 시 출력된 에러 로그 공유드립니다.
-Material 'Distortion_Stencil' with Shader 'Custom/Distortion_Stencil' doesn't have a texture property '_MainTex'
UnityEngine.UI.ScrollRect:LateUpdate()

발생 기기는 iPhone 12 / 11 Pro Max 입니다.

[테스트 환경]
iOS.v170.0.2(52)

메인넷 160.1.0 버전에서는 해당 이슈 확인되지 않았습니다.

**Comment by QgamesGeonPyoNoh** [comment]
워크샵 - 제작 - 음식에서도 음식 아이콘 뒷 배경에 흰색 이미지가 출력되는 현상이 확인 되었습니다.
확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/dd7d937f-bb0f-4e1f-bdcd-819482f7b6e7)

[테스트 환경]
iOS.v170.0.2(52)

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/6b051f4f-f854-499c-b2fa-2f90970372a2)

[테스트 환경]
Windows.v200170-170.0.3
Android.v200170-170.0.3
iOS.v170.0.3(52)
