### ISSUE TITLE
[퀘스트] 장비 퀘스트 완료 시 다른 장비 퀘스트가 완료된 것으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4808]
### APV version info

v200170

### Client version info

v170.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
장비 퀘스트 완료 시 다른 장비 퀘스트가 완료된 것으로 출력되는 현상
-해당 현상 발생 시 다른 장비 퀘스트의 텍스트가 출력되지 않습니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/a59993f7-258e-40f9-b90c-6aca0455a9e5

### How to reproduce the issue

[재현과정]
1. 메인 로비 - 워크샵 - 제작 클릭
2. 제작 퀘스트에 해당되는 장비 제작
3. 퀘스트 아이콘 클릭
4. 다른 장비 퀘스트가 완료된 것으로 출력되는 현상 확인

[Should be]
장비 퀘스트 완료 시 현재 퀘스트가 완료된 것으로 출력되어야 합니다.

**Comment by ipdae** [comment]
단순 클라이언트 버그인지 https://github.com/planetarium/lib9c/pull/2525 로 인한 동작에 문제가 생긴건지 확인이 필요할 것 같습니다.

**Comment by sonohoshi** [comment]
@QgamesGeonPyoNoh 재접속해서 퀘스트 목록 확인했을때 정상적으로 원래 클리어됐어야 할 퀘스트가 완료된걸로 뜨는지, 아니면 그대로 잘못된 장비 제작 퀘스트가 완료된걸로 뜨는지 확인해주시겠어요?

**Comment by QgamesGeonPyoNoh** [comment]
재접속 시에도 잘못된 제작 퀘스트가 완료 상태로 출력되며, 일부 퀘스트의 텍스트가 출력되지 않습니다.
추가로, 해당 현상 발생 이후 일부 계정에서 장비 제작이 불가능한 현상이 확인되고 있습니다.
확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/2e2fa3aa-57ea-42e2-9b2b-f4e44e82bf6d

[테스트 환경]
Windows.v200170-170.0.2
Android.v200170-170.0.2
iOS.v170.0.2(51)

**Comment by ipdae** [comment]
lib9c의 변경이 원인으로 추정되어 어사인 가져가고 조사진행중입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 확인 완료했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/ecb733bf-241c-4b0d-a293-e593ec11abee

[테스트 환경]
Windows.v200170-170.0.4
Android.v200170-170.0.4
iOS.v170.0.4(53)
