### ISSUE TITLE
[룬] 신규 룬의 스탯이 기획서와 상이함

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4809]
### APV version info

v200170

### Client version info

v170.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신규 룬의 스탯이 기획서와 상이함
-Windows / Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/b7854f05-c05d-4216-b5d2-a7d2859c0571)

### How to reproduce the issue

[재현과정]
1. 메인 로비 - 워크샵 - 룬 클릭
2. 신규 룬 선택
3. 신규 룬의 스탯이 기획서와 상이함 확인

[Should be]
신규 룬의 스탯이 기획서와 동일해야 합니다.

**Comment by NineSyu** [comment]
정상 스펙입니다. 노션문서에 내용을 잘못 기입하여 생긴 이슈입니다.
노션 문서의 스텟 정보값 수정해서 다시 기입하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
신규 룬 스탯은 변경된 기획서와 동일한 부분 확인했습니다.
다만, 프레이야 해방 룬의 디스펠 지속시간이 7턴으로 출력되는데 기획서 상에는 10턴으로 작성되어 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200170-170.0.2
Android.v200170-170.0.2
iOS.v170.0.2(52)

**Comment by NineSyu** [comment]
넵! 내용 확인했습니다. Lv300 기준 지속시간이 10턴입니다.
100레벨 단위로 지속시간이 1턴씩 증가하는 방향으로 밸런스를 잡았습니다.
Lv.1~99 : 7턴
Lv.100~199 : 8턴
Lv.200~299 : 9턴
Lv.300 : 10턴

**Comment by QgamesGeonPyoNoh** [comment]
기획서와 스탯 일치 확인했습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200170-170.0.2
Android.v200170-170.0.2
iOS.v170.0.2(52)
