### ISSUE TITLE
[워크샵] 화웨이 기기에서 소환 진행 시 연출이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4811]
### APV version info

v200170

### Client version info

v170.0.2

### Device

Android

### detailed device info

Android 8

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
화웨이 기기에서 소환 진행 시 연출이 출력되지 않는 현상
-Android(8.1.0 / HUAWEI Y7 Prime 2019) 환경에서 확인하였습니다.
-스킵 버튼은 출력 및 동작합니다.
-해당 현상 발생 시 지속적으로 생성되는 Error 로그 공유드립니다.
-RenderTexture.Create failed: depth/stencil format unsupported - D32 SFloat S8 UInt (94). There is no compatible format on this platform or this fallback to a compatible format is disabled in the import inspector.

https://github.com/planetarium/NineChronicles/assets/150774808/aab911dd-039e-4a81-89d1-662f1d90ff21

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 워크샵
2. 소환 - 골든 아우라 혹은 골든 룬 소환
3. 화면이 암전되고 우측 상단에 스킵 버튼만 나오는 현상 확인

[Should be]
화웨이 기기에서 소환 진행 시 연출이 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
해당 이슈 수정은 하였으나, 이슈가 발생하신 기기에서 다시 확인 부탁드립니다. 수정 내역은 v170.0.2의 다음 버전에서 적용될 예정입니다.
https://github.com/planetarium/NineChronicles/pull/4812

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/059268db-201e-4d12-b3bb-c77572e2c024

[테스트 환경]
Android.v200170-170.0.3
