### ISSUE TITLE
룬 강화 시 버튼 공간에 버튼과 텍스트가 사라짐

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4817]

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/f84e87c4-b17e-4bf8-bad0-265b5a6c69df

[테스트 환경]
Windows.v200170-170.0.3
Android.v200170-170.0.3
iOS.v170.0.3(52)
