### ISSUE TITLE
[인벤토리] 인벤토리 내 룬 조각이 거래불가로 출력

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4820]
### APV version info

v200170

### Client version info

v170.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
인벤토리 내 룬 조각이 거래불가로 출력
-Windows / Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/8513bfca-ce95-447d-8557-9001bfb49aa8)

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 인벤토리 클릭
2. 룬 조각 탭 클릭
3. 신성 룬 조각을 제외한 임의의 룬 조각 클릭
4. 룬 조각이 거래불가로 출력되는 현상 확인

[Should be]
인벤토리 내 룬 조각이 거래 가능으로 출력되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
인벤토리 외 다른 컨텐츠에서도 거래불가로 출력되는 현상 발생했습니다.
확인 부탁드립니다.

1. 상점 Buy 탭 내 등록된 룬 조각
2. 상점 Sell 탭 내 보유하지 않은 룬 조각
3. 인벤토리 내 보유하지 않은 룬 조각
4. 소환 시 출력되는 룬 조각 상세정보 팝업

이상입니다.

[테스트 환경]
Windows.v200170-170.0.3
Android.v200170-170.0.3
iOS.v170.0.3(52)

**Comment by QgamesGeonPyoNoh** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/b2dd2d5a-c0f7-4711-b9fb-38bf55774d40)
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/275dfbda-6ad8-4f4f-8d37-1e76b4dac4f8)
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/f255a729-afbf-4773-8ff9-7520ec60095f)
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/c8eb07a9-8dfd-41a9-aaaa-7b6f04ac3370)

**Comment by ipdae** [comment]
유저에게 혼란을 줄수있는 이슈로 보여 P1으로 올리고 이번 빌드에서 수정되야할것같습니다. /cc @Namyujeong @jaeho0103

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200170-170.0.5
Android.v200170-170.0.5
iOS.v170.0.5(54)
