### ISSUE TITLE
모바일 환경에서 파악 안된 http client의 타임아웃으로 접속이 안되는 경우가 있어서 조사 필요함

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#4822]
https://planetariumhq.slack.com/archives/C011716SDTM/p1713834811479579

**Comment by sonohoshi** [comment]
일단 재현이 안돼서 보류합니다.

**Comment by sonohoshi** [comment]
https://planetariumhq.slack.com/archives/C011716SDTM/p1713864805151419?thread_ts=1713859774.031869&cid=C011716SDTM
발생이 좀 잦은거같아서 우선도 올려서 체크해보겠습니다.

**Comment by sonohoshi** [comment]
```cs
catch (OperationCanceledException e)
{
    if (e.CancellationToken == cancellation.Token)
    {
        _state = InitializingState.NeedInitialize;
        NcDebug.Log($"[{nameof(LiveAssetManager)}] NoticeData making failed by timeout.");
        return;
    }
}
``` 여기서 로그 찍히는거 보니까 이걸 체크해야겠는데

**Comment by jonny-jeahyunchoi** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/138189475/064005c1-0359-435f-a2f7-03b59c435a58)

코드보면 liveassetmanager는 Game.cs awake에서 비동기로 다운받고있고 실패해도 진입에는 문제없어야하더라구요
오히려 Game.cs start부분에서 keymanager 등록부분실패후 이후 진행에 로그들이 안찍히는것같아서 그쪽문제로보입니다. 
일단 그 중간에는 번역어 갱신 로드하는부분이있는데. 딱히 의심가는 코드는 없어보이는상황이네요

**Comment by jonny-jeahyunchoi** [comment]
https://github.com/planetarium/NineChronicles/blob/3fd59d49b14615f8b75d843409532273400d6758/nekoyume/Assets/_Scripts/Game/Game.cs#L308 
여기서 [KeyManager] ~ failed.keystore does not have any key로그가 찍힌뒤,  https://github.com/planetarium/NineChronicles/blob/3fd59d49b14615f8b75d843409532273400d6758/nekoyume/Assets/_Scripts/Game/Game.cs#L336 
[Game] Start()... L10nManager initialized 요로그가 찍혀야하는데 안찍혀요..

**Comment by sonohoshi** [comment]
이거 보니까 릴리즈노트 관련 로그가 아예없는데... 이거 핸들링을 하고 있는지 체크해보겠습니다

**Comment by sonohoshi** [comment]
L10nManager.AdditionalL10nTableDownload() 에서 `await client.GetAsync(url)` 을 할때, GetAsync Task가 cancel되는 바람에 try-catch가 안된 것으로 예상하여 이 부분을 @jonny-jeahyunchoi 님이 수정하시기로 했습니다.

**Comment by jonny-jeahyunchoi** [comment]
관련해서 문제구간에서 일부러 Exception을 내어서 재현성공했고, 예외처리 범위를 확장하는것으로 수정하여 고의로 Exception발생시에도 정상진입되는것 확인했습니다~!
