### ISSUE TITLE
[로그인] 비밀번호 강도 제한이 존재하지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4823]
### APV version info

v200170

### Client version info

v170.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
비밀번호 강도 제한이 존재하지 않는 현상
-Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/52eb9e47-38d5-49d7-80b0-eb653b5cddb0

### How to reproduce the issue

[재현스텝]
1. 모바일 환경 설치 후 진입
2. 로그인 - QR코드 인식 진행
3. 비밀번호 분실 - 프라이빗 키 입력
4. 새 비밀번호 입력 시 한 글자만 입력해도 적용되는 현상 확인

[Should be]
비밀번호 강도 제한이 존재해야 합니다.

**Comment by sonohoshi** [comment]
@jaeho0103 이거 한~~~참 옛날에 모바일버전 만들면서 비직관적인 로직으로 너무 깐깐하게 굴어서 빼자고 했던거같은데, 이대로여도 상관없을지 확인 한번 부탁드립니다

**Comment by jaeho0103** [comment]
비밀번호 강도 제한이 키를 만드는데 허들이 된다고 판단해 일부러 없앤 부분입니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
Android.v200170-170.0.2
iOS.v170.0.2(52)
