### ISSUE TITLE
컬렉션 등록 팝업에서 아이템 툴팁의 텍스트가 깨짐

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4828]
Tradable 텍스트
![Image](https://github.com/planetarium/NineChronicles/assets/63496908/f1ce7a0c-170b-42dc-a0c5-da6d8b599bc9)

이외의 인벤토리에서는 정상 출력 됩니다.
![Image](https://github.com/planetarium/NineChronicles/assets/63496908/7ff712e1-fec5-4c95-957c-d32593668091)

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/b2553524-53b2-4ef2-a8ea-a74bd9bd3640)


[테스트 환경]
Windows.v200170-170.0.4
Android.v200170-170.0.4
iOS.v170.0.4(53)
