### ISSUE TITLE
[UI] 롱 소드 제작 튜토리얼 진행 불가 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4832]
### APV version info

v200170

### Client version info

v170.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
롱 소드 제작 튜토리얼 진행 불가 현상
-제작 버튼 클릭 이후 부터 진행되지 않습니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/ca644e1e-ca85-4df7-98e6-f06f31973f09

### How to reproduce the issue

[재현스텝]
1. 신규 캐릭터 생성
2. 튜토리얼 진행
3. 튜토리얼따라 워크샵 - 제작 버튼 클릭
4. 이 후 튜토리얼 진행 불가 현상 확인

[Should be]
튜토리얼 진행이 가능해야 합니다.

**Comment by tyrosine1153** [comment]
테이블 패치 후 정상 동작 확인되었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/dfab941b-faae-477a-999f-d20d64b9d6bd

[테스트 환경]
Windows.v200170-170.0.3
Android.v200170-170.0.3
iOS.v170.0.3(52)
