### ISSUE TITLE
[워크샵] 제작 탭 내 선택한 장비의 옵션이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4833]
### APV version info

v200170

### Client version info

v170.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
제작 탭 내 선택한 장비의 옵션이 출력되지 않는 현상
-해당 장비 이름 및 선택 중 테두리 효과도 출력되지 않습니다.
-해당 현상이 발생하는 장비는 제작이 불가능합니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/241a8996-f14e-4d82-bed6-3cd526ca07cd

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 워크샵 - 제작 클릭
2. 롱 소드 클릭
3. 선택한 장비의 옵션이 출력되지 않는 현상 확인

[Should be]
장비 선택 시 해당 장비의 옵션 정보가 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
테이블 데이터 이슈로 확인되어 인터널에 테이블 데이터 다시 주입한 후 문제 없는것으로 확인되었습니다. 재확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/85a92372-d476-4fb4-9368-8e9c13c13000

[테스트 환경]
Windows.v200170-170.0.3
Android.v200170-170.0.3
iOS.v170.0.3(52)
