### ISSUE TITLE
[시즌 패스] 용기 경험치가 획득되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4836]
### APV version info

v200170

### Client version info

v170.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
용기 경험치가 획득되지 않는 현상
-전투를 하여 획득한 용기 경험치가 1시간이 경과하였으나 시즌 패스에 적용되지 않고 있습니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/e70643b4-0c1d-419a-8720-2faa952819e2

### How to reproduce the issue

[재현스텝]
1. 아레나, 월드 보스, 모험 전투를 진행
2. 메인 로비 - 시즌 패스
3. 용기 경험치가 추가되지 않은 현상 확인

[Should be]
전투 진행 시 시즌패스 경험치가 획득되어야 합니다.

**Comment by U-lis** [comment]
@QgamesGeonPyoNoh 확인해보니 용기 경험치를 수집하는 서버가 원인 모를 에러로 죽어있었습니다.
아침에 출근하자마자 재시작했고, 블록 다시 수집하고 있습니다.
다만 시간이 좀 오래 걸릴 수 있어서 다음 QA 요청드릴 때까지 해소가 안 되면 이전 블록은 무시하도록 조치하도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/a7fe0c2a-eeab-452c-96a3-275ed4195104

[테스트 환경]
Windows.v200170-170.0.3
Android.v200170-170.0.3
iOS.v170.0.3(52)
