### ISSUE TITLE
[월드 보스] 월드 보스 스코어가 월드 보스 로비에 반영되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4837]
### APV version info

v200170

### Client version info

v170.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
월드 보스 스코어가 월드 보스 로비에 반영되지 않는 현상
-전투 이후에도 전투 기록이 없다는 텍스트 문구가 출력되고 있습니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/22b4ed4a-cc8a-483c-bd43-6b55cadaa5c4

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 월드 보스 - 전투
2. 월드 보스 로비로 이동하여 점수 기록이 갱신되지 않은 현상 확인

[Should be]
월드 보스 공격 시 해당 스코어가 기록에 반영되어야 합니다.

**Comment by U-lis** [comment]
avatar state 를 기록하지 못해 action 로그 자체가 남지 않고 있었습니다. 수정 후 기록 잘 되는 것 확인했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


https://github.com/planetarium/NineChronicles/assets/150774808/d071aaad-b054-4d59-8419-ddd39229c357


[테스트 환경]
Windows.v200170-170.0.8
Android.v200170-170.0.8
iOS.v170.0.8(57)
