### ISSUE TITLE
[워크샵] 소환 화면에서 아우라 스킬 정보 보기 버튼이 동작하지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4838]
### APV version info

v200170

### Client version info

v170.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
소환 화면에서 아우라 스킬 정보 보기 버튼이 동작하지 않는 현상
-Windows / Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/c0630764-78d6-4e10-b36e-1364c8543788

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 아우라 탭에서 돋보기 버튼 클릭
3. 아우라 스킬 정보 보기 버튼이 동작하지 않는 현상 확인

[Should be]
소환 화면에서 아우라 스킬 정보 보기 버튼이 동작해야 합니다.

**Comment by eugene-doobu** [comment]
안녕하세요. 170.0.4 버전에서 해당 기능 문제 없는것으로 확인되었습니다. 170.0.3버전의 사이드이펙트로 일시적으로 스킬 정보가 안나온것으로 판단되어 QA로 status 변경하였습니다. 다시 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.
![image](https://github.com/planetarium/NineChronicles/assets/150774808/02052d19-cc2d-4ff0-9d3b-68c9586004c3)

[테스트 환경]
Windows.v200170-170.0.4
Android.v200170-170.0.4
iOS.v170.0.4(53)
