### ISSUE TITLE
궁수 코스튬 아이콘 등록

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4839]

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/40100030_icon-add
추가 리소스 : 40100030

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/1b8b8a47-a6ca-4388-a040-a2ff8977bc59)

이미지 추가해두었습니다.
머지 부탁드립니다. @tyrosine1153

**Comment by tyrosine1153** [comment]
https://planetariumhq.slack.com/archives/C011716SDTM/p1713943186884929?thread_ts=1713934782.671429&cid=C011716SDTM
