### ISSUE TITLE
레드 소환 

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#4841]

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/red_aura_rune-add
사용 프리퓁 : UI_Summon

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/f87229fe-2b55-4f3e-806f-7e74d541e443)

1. 언어대응 되야 합니다.
2. 언어대응 안됨. 영문으로만 나오며 각 상황에 맞는 이름 나오도록 해야 합니다.
3. 우측 내용은 기획자한테 문의 후 작업 부탁드립니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/f53dd71c-88f4-4768-9963-abc153e3b851)

텝 버튼 2종 추가되었습니다.
연결시켜 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/37468618-a35d-4458-8de7-b24e110f4d5b)

중앙 오브젝트 이미지 2종 추가되었습니다.
연결시켜 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/08c7084a-8520-4adb-bc42-5b343b272029)

우측 캐릭터 이미지 2종 추가되었습니다.
연결시켜 주세요.
레드 룬의 경우 임시 이미지 입니다. 원화 나오는데로 업데이트 예정입니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/310edd75-c307-4e7d-9d15-174d10da7a08)

배경의 경우
- 레드아우라, 레드룬 -> 첫번째 칸의 배경
- 골든아우라, 골든룬 -> 두번째 칸의 배경
- 님블아우라 -> 세번째 칸의 배경
으로 되도록 변경 부탁드립니다.

**Comment by boramqo83** [comment]
프리퓁 수정 등록해 두었습니다.
개발 부탁드립니다. @eugene-doobu

**Comment by boramqo83** [comment]
해당 브랜치에 리소스 교체해서 등록합니다.

**Comment by eugene-doobu** [comment]
@boramqo83 이슈 네임 레드 소환으로 변경하였습니다 .
