### ISSUE TITLE
[설정] 비밀번호를 설정하지 않은 계정으로 시작 화면에서 백업 가능 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4853]
### APV version info

v200170

### Client version info

v170.0.4

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
비밀번호를 설정하지 않은 계정으로 시작 화면에서 백업 가능 현상
-해당 QR코드 캡쳐 시 비밀번호 입력 없이 진행됩니다.
-Android, iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/5cd959ab-c3f5-43ec-af7f-a2e3d407f05d

### How to reproduce the issue

[재현스텝]
1. 비밀번호를 설정하지 않는 계정 세팅
2. 시작 화면 - 백업 진행
3. 비밀번호를 설정하지 않은 계정으로 시작 화면에서 백업 가능 현상 확인

[Should be]
비밀번호를 설정하지 않은 계정으로 시작 화면에서 백업이 불가능해야 합니다.

**Comment by sonohoshi** [comment]
비밀번호 설정을 하는 플로우와 QR코드 백업 플로우가 연결되어있지 않아서 일단 QR코드를 통한 백업만 넣어둔거였는데, 비밀번호 설정 플로우에 무조건 QR코드 백업 플로우를 붙여서 기존과 같이 동작하게 수정할 예정입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


https://github.com/planetarium/NineChronicles/assets/150774808/1107aca8-459d-4f66-8d07-9c2616870eea


[테스트 환경]
Android.v200170-170.0.5
iOS.v170.0.5(54)
