### ISSUE TITLE
[상점] 신규 패키지의 이미지 및 배너가 흰색으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4856]
### APV version info

v200170

### Client version info

v170.0.4

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신규 패키지의 이미지 및 배너가 흰색으로 출력되는 현상
-불의 화신 패키지 / 붉은 마녀 아이린 패키지 / 발할라의 시그룬 패키지 / 5월 데일리 패키지 I, II 이상 5개 패키지에서 발생하고 있습니다.
-Android, iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/37cf9f65-e16c-4569-9450-61613305e366

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 상점 클릭
2. 신규 패키지 확인
3. 이미지 및 배너가 흰색으로 출력되는 현상 확인

[Should be]
신규 패키지의 이미지 및 배너가 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103  이거 아직 신규패키지 이미지가 인터널 서비스에 등록안된것같은데 확인부탁드립니다~!

**Comment by jaeho0103** [comment]
네 신규 패키지는 데이터 체크를 위해 넣어둔 부분으로 아직 이미지가 안들어가있는 상황입니다.
이미지 업데이트 후 다시 체크 요청드리겠습니다.

**Comment by jaeho0103** [comment]
업데이트 완료했습니다. 체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.


https://github.com/planetarium/NineChronicles/assets/150774808/d2485fbf-7e75-4e83-85b0-a13636af02ac


[테스트 환경]
Android.v200170-170.0.8
iOS.v170.0.8(57)

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재 발생 확인했습니다.
1. 프리미엄 더스트 패키지
2. 프리미엄 룬 패키지
3. 프리미엄 제작 패키지
4. 9월 데일리 패키지 I
5. 9월 데일리 패키지 II

이상 5개의 패키지에서 발생 확인했습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200220-220.0.1
iOS.v220.0.1(102)
![이슈](https://github.com/user-attachments/assets/ea2965c4-8082-40fc-af73-dc0b3f6f9e02)

**Comment by tyrosine1153** [comment]
@jaeho0103 다시 확인 부탁드립니다.

**Comment by jaeho0103** [comment]
네 해당 패키지들은 9월 판매 패키지로 아직 이미지 업데이트 안되어있는 상태입니다.
