### ISSUE TITLE
[UI] 최초 실행 시 출력되는 배너가 흰색으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4858]
### APV version info

v200170

### Client version info

v170.0.4

### Device

Android

### detailed device info

Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
최초 실행 시 출력되는 배너가 흰색으로 출력되는 현상
-Android에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/01dd21d0-94ed-4e54-9446-5fd630f2e88f

### How to reproduce the issue

[재현스텝]
1. 설치 후 로그인 진행
2. 캐릭터 선택 후 접속 시 배너가 흰색으로 출력되는 현상 확인

[Should be]
캐릭터 선택 후 접속 시 배너가 출력되어야 합니다.

**Comment by sonohoshi** [comment]
현재 외부 리소스를 받아오는데 오래 걸리면 무시하고 진행하게 되어있어서 그런 상태고, 리소스 로드가 오래걸리는 문제 자체는 개선을 위해 찾아보고 있는 상태입니다. 노운이슈로 일단 둬야할 것 같습니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/41fb3991-9db6-4009-a71c-c7241f07176c)

[테스트 환경]
Android.v200170-170.0.5
