### ISSUE TITLE
[상점] Crystal per price 정렬에 +5강 크리스탈 제한이 정렬에 적용되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4870]
### APV version info

v200170

### Client version info

v170.0.5

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Crystal per price 정렬에 +5강 크리스탈 제한이 정렬에 적용되지 않는 현상
-Windows 환경에서 확인했습니다.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/01077/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/01077/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

장비 조건 1 | 장비 조건 2 | 크리스탈 가치 | NCG | 크리스탈/NCG
-- | -- | -- | -- | --
Wind +7 War Sword | 제한 이전 | 128,500,000 | 250 | 514,000
Wind +7 War Sword | 5강 제한 | 32,000,000 | 250 | 128,000
Fire War Sword | - | 1,000,000 | 2 | 500,000

</body>

</html>

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/df343e2f-11c6-4d2e-9eac-f55d236e3273)

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 상점 클릭
2. 정렬 기준 Crystal per price ▼로 변경
3. +6 이상 아이템 확인
4. +5강 크리스탈 제한이 정렬에 적용되지 않는 현상 확인

[Should be]
Crystal per price 정렬에 +5강 크리스탈 제한이 정렬에 적용되어야 합니다.

**Comment by tyrosine1153** [comment]
- 마켓 서비스의 lib9c 범프가 되어있지 않아 생긴 현상. 마켓 서비스 재배포 후 확인 필요.
- 금요일에 재배포 했습니다. 확인 필요합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200180-181.0.0
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/8c5dadd0-8190-4314-85eb-48e2fed953ed)
