### ISSUE TITLE
GeustButton 나오지않는문제

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#4872]

**Comment by eugene-doobu** [comment]
상태 done으로 옮기고 이슈 close해도 되지 않을까요?

**Comment by jonny-jeahyunchoi** [comment]
급하게 들어간 PR이라 사후리뷰가없어서 약간 애매한부분입니다. 작업과정에서도 추가 정리가 필요한부분이 좀있어보여서 한번 같이 확인하고 클로즈하면 좋을것같아요~!
