### ISSUE TITLE
스테이지 재도전시 아바타 연출이상 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#4875]
DCC 착용 상태로 스테이지 재도전시 DCC 가 벗셔진 뒤에 다시 입혀집니다. 그리고 뛰지 않고 끌려(?)가네요 

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1714115450218089?thread_ts=1714115450.218089&cid=C062ZS68A21)

**Comment by jonny-jeahyunchoi** [comment]
https://planetariumhq.slack.com/archives/C011716SDTM/p1729843806850889
