### ISSUE TITLE
PC버전에서 Backup 버튼 안보이게 수정 필요

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#4886]
게임 실행 화면 우상단 Backup 버튼이 나오는데 PC(Win)에선 클릭해도 동작은 안하는거같네요

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1714461185117889?thread_ts=1714461185.117889&cid=C062ZS68A21)

**Comment by jaeho0103** [comment]
@tyrosine1153 어떻게 수정하셨는지 모르겠는데 일단 윈도우 181.0.1 기준으로 켰을때 우측 상단에 backup 버튼이 표시되기는 합니다.

**Comment by tyrosine1153** [comment]
게임 실행 초기에 모바일 화면이 뜨는 것은 어쩔 수 없는데 초기 화면에는 버튼을 모두 비활성화한 상태입니다. 혹시 지금 버전에서 다시 확인해주실 수 있으신가요? 가능하시면 영상도 찍어주시면 확인이 쉬울 것 같습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.4

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/d9e3466a-dc06-4695-aa90-721b183d7865)
