### ISSUE TITLE
오딘에서 8월드에 진입했더니 스테이지 퀘스트가 보이지 않는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#4889]
오딘에서 8월드에 진입했더니 스테이지 퀘스트가 보이지 않는 현상

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1714622487768219?thread_ts=1714622487.768219&cid=C062ZS68A21)

**Comment by ipdae** [comment]
아바타의 퀘스트 업데이트는 체인에 있는 퀘스트의 총합수와 아바타가 들고있는 퀘스트의 갯수를 비교해서 처리됩니다. 중간에 퀘스트 시트의 정리가 이뤄져 이전에 생성된 아바타의 경우 퀘스트 총합수가 체인에 있는 퀘스트보다 많아서 업데이트가 이뤄지지 않는게 원인으로 보입니다. 업데이트 비교방식을 아바타가 들고있지 않은 퀘스트가 있는 경우로 변경해야할 것 같습니다.
