### ISSUE TITLE
월드보스 진행후 애니메이션 느려지는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#4892]
월드보스 진행후 애니메이션 느려지는 현상

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1714709635516099?thread_ts=1714709635.516099&cid=C062ZS68A21)

**Comment by sonohoshi** [comment]
@eugene-doobu 리뷰 남겨서 in progress로 넘겼습니당
