### ISSUE TITLE
신규 장비 그리모어, 그리모어 소환

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#4922]
작업 목록 / 상황 공유
- [x]  소환 재화 추가 (시트에 임시로 값을 추가)
    - [x]  소환 화면에서 보이는 재화 수정
        Advenced와 Normal 소환에 보이는 재화의 종류를 구분
    - [x]  인벤토리의 Material 카테고리 상단에 Dust를 고정한다.
- [x]  부적 소환 UI, 액션 작업
- [x]  신규 장비 추가에 대한 클라이언트, ui 대응
    - 시뮬레이터 추가 연출 없음 (벨트, 목걸이, 반지와 동일)
    - [x]  아바타 슬롯
    - [x]  컬렉션 필터에 대응 필요
    - [x]  강화 화면에 부적 탭 추가

**Comment by tyrosine1153** [comment]
UI 프리펩 대응 필요한 작업은 hold하고 대기합니다.

**Comment by tyrosine1153** [comment]
- UI 프리펩 대응 이슈 : https://github.com/planetarium/NineChronicles/issues/5038

**Comment by tyrosine1153** [comment]
작업 상황 녹화
https://planetariumhq.slack.com/archives/C06UMQR34GZ/p1718627298369579
