### ISSUE TITLE
Consumable 아이템 뷰 개선

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4942]
### 작업 내용
1. 아래 이미지 같이 인벤토리에서 동일한 item id를 가진 음식 아이템을 묶어서 보여주도록 수정합니다.
2. 수정시 발생하는 사이드 이펙트 파악해서 대응합니다.

![Image](https://github.com/planetarium/NineChronicles/assets/63496908/ff209b3f-a3d6-4a09-a7af-ef05ddbf2e96)

**Comment by tyrosine1153** [comment]
InventoryItem에서 Consumable을 저장할 때 최초의 Consumable만 InventoryItem의 ItemBase에 넣고 나머지는 count만 올리면, 보일 때에는 문제없음. 하지만 사용할 때가 문제인데, 갖고있는건 한 개의 Consumable에 대한 정보라서 여러개의 consumable에 대한 정보가 필요할 경우를 대비해야 함.

- 전투 준비 화면 - 슬롯에 id (not Guid)를 저장해두었다가 액션 날릴 때에만 검색해서 Guid를 가져옴
- 상점 판매

**Comment by tyrosine1153** [comment]
- 인벤토리 아이템 뷰에서 개수를 어떻게 표시할지 (장착하면 개수가 줄어드는데? 1개 이하일 경우 어떻게 표시할지)

**Comment by tyrosine1153** [comment]
https://github.com/planetarium/NineChronicles/assets/63496908/c7c9a488-1a3c-4e6f-a230-2cb70507df9d

- 전투 준비 화면
  - [ ] 같은 종류(item id)의 음식 아이템끼리 묶여서 count를 표시함
    - [ ] 장착/해제할 때마다 count가 갱신 됨
    - [ ] 음식 툴팁에 count가 뜸
  - [ ] 같은 종류의 음식을 여러개 장착 가능
    - [ ] 이러한 상태로 전투가 정상 진행됨
  - [ ] 인벤토리에서 아이템을 클릭해 툴팁을 열면 Equip 버튼이, 슬롯에서 열면 Unequip 버튼이 뜸
    - [ ] count가 0이 되면 Equip 버튼이 비활성화 됨

**Comment by tyrosine1153** [comment]
진행상황

판매 팝업에서 여러개 선택해서 보내도록 수정

![Image](https://github.com/planetarium/NineChronicles/assets/63496908/bff3b5f0-2795-44a2-97a0-3666e131e5f7)

![Image](https://github.com/planetarium/NineChronicles/assets/63496908/70a7d5fd-0660-4285-88df-da8e0756690f)

**Comment by tyrosine1153** [comment]
https://github.com/planetarium/NineChronicles/assets/63496908/9d04dc92-7127-4d79-9891-c00a13b23355

- 상점 판매
  - [x] ShopSell의 인벤토리에서 툴팁을 열었을 때 count 가 표시됨
  - [x] Consumable 아이템을 등록 시 count 선택이 가능함
  - [x] unit price(개별 가격)에 소수점 아래 값을 입력 시 등록 버튼이 비활성화 됨
  - [x] 등록 후 ShopSell의 등록한 아이템 목록에서 Consumable 아이템이 하나씩 unit price로 등록되어있는 것을 확인할 수 있음
  - [x] Consumable이 아닌 다른 아이템 종류는 위의 내용이 적용되지 않음

**Comment by tyrosine1153** [comment]
240529 기획 리뷰 cc @jaeho0103 
- [ ] 최초로 툴팁을 열 때 "Count : {}" 표시가 되지 않은 현상 수정
- [ ] Consumable의 경우 count == 1 이라도 item view에서 count text를 표시
- [ ] 상점 등록 팝업에서 unit price의 valid check 가 false라면 표시할 alert text 추가

**Comment by jaeho0103** [comment]
l10n 
개별 아이템 판매가격에 소수점이 포함되지 않아야 합니다.
The unit price should not include decimal points.

**Comment by tyrosine1153** [comment]
기획 리뷰 수정사항 모두 대응했습니다.

![image](https://github.com/planetarium/NineChronicles/assets/63496908/824de8a7-a36d-4ae5-b6b9-9bef48e6357a)
