### ISSUE TITLE
전투중 멈춤현상 조사 및 수정

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#4963]
전투중 멈춤현상 조사 및 수정합니다
안될경우 전투 타임아웃 케이스에 대해 로그를 추가합니다

**Comment by ipdae** [comment]
- 100% 발생 상황은 아님
- 돌리다보면 랜덤하게 발생함.(빈도는 꽤 높음)
- 강제로 넘어가긴함.
- 8월드에서만 발생하는것처럼 보임.

**Comment by ipdae** [comment]
- https://github.com/planetarium/NineChronicles/discussions/4639
- https://github.com/planetarium/NineChronicles/issues/4898
