### ISSUE TITLE
[K버전] Reward 버튼이 삭제되었으나 햄버거 버튼에 Red Dot이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4977]
### APV version info

K빌드_v200181

### Client version info

v181.0.0

### Device

Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Reward 버튼이 삭제되었으나 햄버거 버튼에 Red Dot이 출력되는 현상
-K버전 Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/d0f66af7-fd7b-47a2-b2ed-2b6fcc946b71

### How to reproduce the issue

[재현 스텝]
1. K버전으로 접속
2. 이벤트 배너 및 릴리즈 노트의 Red Dot 항목 확인
3. AP 자연 회복 진행
4. 햄버거 버튼에 Red Dot이 출력되는 현상 확인

[Should be]
K버전에서 햄버거 버튼에 Red Dot이 출력되지 않아야 합니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200181-181.0.4
iOS.v181.0.4(73)


https://github.com/planetarium/NineChronicles/assets/167295117/c7b07b39-b0da-4dcc-9543-6acd537bd41d

**Comment by OHHyungGeun** [comment]
해당 현상 발생 확인했습니다.
이슈 되돌리겠습니다.

[테스트 환경]
Windows.v200181-181.0.4
Android.v200181-181.0.4
iOS.v181.0.4(73)


https://github.com/planetarium/NineChronicles/assets/167295117/c32b8572-8e42-4c61-a9c5-765684092912

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200181-181.0.5
iOS.v181.0.5(74)


https://github.com/planetarium/NineChronicles/assets/150774808/e86719bc-14c9-40ee-9384-81f0d0afa567
