### ISSUE TITLE
[워크샵] 룬 화면에서 신규 룬 선택이 불가능한 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#4978]
### APV version info

v200181

### Client version info

v181.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
룬 화면에서 신규 룬 선택이 불가능한 현상
-아이콘은 보물상자 아이콘으로 출력됩니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/1552f768-6a17-4d83-9c49-7910edf0af96)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬
2. 룬 목록 상단에 보물상자 아이콘 출력 확인
3. 보물상자 아이콘 클릭 시 선택되지 않는 현상 확인

[Should be]
룬 목록에 신규 룬 아이콘이 출력되어야 합니다.

**Comment by jaeho0103** [comment]
이부분 known issue 로 수정해서 업데이트 대기중입니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.1
Android.v200181-180.0.1
iOS.v180.0.1(71)


![Image](https://github.com/planetarium/NineChronicles/assets/167295117/49a00768-3d0b-4127-8a80-c82ee9a0a91a)
