### ISSUE TITLE
[정찰 보상] 캐릭터 레벨과 상관 없이 350이상의 보상이 출력되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#4979]
### APV version info

v200181

### Client version info

v181.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
캐릭터 레벨과 상관 없이 350이상의 보상이 출력되는 현상
-팝업되는 PATROL REWARD 창에 350레벨 이상이 받는 보상이 출력됩니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/d35cd70a-7f7a-47e6-8112-3ab1ba8e3995)

### How to reproduce the issue

[재현 스텝]
1. 50레벨 캐릭터로 접속
2. 메인 로비 - 정찰 보상
3. 보상 아이콘이 350레벨 이상이 받는 보상인 것을 확인

[Should be]
레벨에 따라 각기 다른 이벤트 정찰 보상을 받아야 합니다.

**Comment by U-lis** [comment]
internal 에 방치보상 관련 정책이 잘 업데이트되지 않고 350 보상만 있었습니다.
빠진 정책 모두 업데이트 완료했습니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.4
Android.v200181-181.0.4
iOS.v181.0.4(73)


![Image](https://github.com/planetarium/NineChronicles/assets/167295117/9ab97fd7-04ac-44df-944c-a6b61ce9b258)



![Image](https://github.com/planetarium/NineChronicles/assets/167295117/4d3d7ccc-006c-400f-aaf8-1db09e3dc6e8)



![Image](https://github.com/planetarium/NineChronicles/assets/167295117/0a0801e0-17bc-4d64-a3be-1df95bde4375)
