### ISSUE TITLE
[K버전] 루비 아우라 / 룬 소환이 불가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4982]
### APV version info

K버전_v200181

### Client version info

v181.0.0

### Device

Android

### detailed device info

Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
루비 아우라 / 룬 소환이 불가능한 현상
-K버전 Android 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/0daa0aaf-b962-4cd5-9144-fb3b88bc2982

### How to reproduce the issue

[재현 스텝]
1. K버전 Android로 접속
2. 메인 화면 - 워크샵 - 소환 클릭
3. 루비 아우라 / 룬 탭 선택
4. 소환이 불가능한 현상 확인

[Should be]
K버전 Android 환경에서 루비 아우라 / 룬 소환이 가능해야 합니다.

**Comment by eugene-doobu** [comment]
clo파일 문제로 판단되어 clo파일을 수정해두었습니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.1
Android.v200181-180.0.1
iOS.v180.0.1(71)



![Image](https://github.com/planetarium/NineChronicles/assets/167295117/7c833ad7-4b91-472c-9159-076ddc420d4f)
