### ISSUE TITLE
[워크샵] 소환 탭 스킬 설명 UI 내 이미르 아우라의 스킬 정보가 키 값으로 출력되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#4983]
### APV version info

v200181

### Client version info

v181.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
소환 탭 스킬 설명 UI 내 이미르 아우라의 스킬 정보가 키 값으로 출력되는 현상
-루비 아우라 / 골든 아우라 모두 발생하고 있습니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/c993583a-2407-416f-9e0c-646ee2fbbc4a)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 루비 아우라 소환 - 돋보기 버튼 클릭
3. 이미르 아우라의 스킬 정보가 키 값으로 출력되는 현상 확인

[Should be]
해당 스킬의 명칭이 표기되어야 합니다.

**Comment by jaeho0103** [comment]
수정해서 다음버전에서는 잘 보이고 있습니다. 181.0.1 버전에서 체크 부탁드리겠습니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.1
Android.v200181-180.0.1
iOS.v180.0.1(71)



![Image](https://github.com/planetarium/NineChronicles/assets/167295117/c217b0be-266b-4fb2-964a-10e1c4663f25)
