### ISSUE TITLE
[K버전] 이벤트 배너 내 NCG 표현 출력

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4985]
### APV version info

K버전_v200181

### Client version info

v181.0.0

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
이벤트 배너 내 NCG 표현 출력
-K버전 Android, iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/11040ec3-1bf8-4b9e-9af4-d6f8e4b8e7d9)
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/49f11d9c-3488-45ed-beb6-7f6456d4ced3)

### How to reproduce the issue

[재현 스텝]
1. K버전으로 접속
2. 메인 화면 - 햄버거 버튼 - 공지 버튼 클릭
3. 이벤트 탭 내 '친구를 초대하세요!' / 몬스터 콜렉션 배너 클릭
4. 배너에서 출력된 이벤트 배너 내 NCG 표현 출력 확인

**Comment by jaeho0103** [comment]
@boramqo83 
저위의 2 배너 NCG-> 골드 버전 리소스 제작 부탁드리겠습니다.

**Comment by jaeho0103** [comment]
[배너리소스.zip](https://github.com/user-attachments/files/15541398/default.zip)
이 파일로 교체하면 될 것 같습니다.

**Comment by eugene-doobu** [comment]
배너 이미지 변경했습니다
https://github.com/planetarium/NineChronicles.LiveAssets/commit/b7940d45da0bdb65f9d02ec68daddadecd8378c0

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200181-181.0.4
iOS.v181.0.4(73)


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/915c0e2f-4e0a-48b5-ba65-2d8eccef1e13)
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/3651e03f-db53-4d21-aa57-76a687c21808)
