### ISSUE TITLE
[정찰 보상] 정찰 보상 획득 불가 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#4987]
### APV version info

v200181

### Client version info

v181.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
정찰 보상 획득 불가 현상
-Windows / Android / iOS 환경에서 확인하였습니다.

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 정찰 보상 클릭
2. 보상 획득 버튼 클릭
3. 로딩만 계속되고 보상을 획득하지 못하는 것을 확인

[Should be]
보상 획득 버튼을 클릭하면 해당 보상을 획득해야 합니다.

**Comment by OHHyungGeun** [comment]
해당 현상 발생 확인했습니다.
이슈 되돌리겠습니다.

[테스트 환경]
Windows.v200181-181.0.4
Android.v200181-181.0.4
iOS.v181.0.4(73)

**Comment by U-lis** [comment]
internal service 리셋을 하면서 nonce 가 맞지 않아 발생한 것으로 확인했습니다. 
nonce 맞추고 이전 보상 수령 이력 삭제해두었습니다. 다시 한번 확인 부탁드립니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.4
Android.v200181-181.0.4
iOS.v181.0.4(73)

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 발생 확인했습니다.
이슈 되돌리겠습니다.

[테스트 환경]
Windows.v200210-210.0.2
Android.v200210-210.0.2
iOS.v210.0.2(97)

https://github.com/user-attachments/assets/aac37c17-40bd-422f-b653-098ddc79265c

해당 현상 발생 시 Log 파일 공유드립니다.
[Log.zip](https://github.com/user-attachments/files/16358619/Log.zip)

**Comment by U-lis** [comment]
internal service 리셋을 하면서 nonce 가 맞지 않아 발생한 것으로 확인했습니다.
nonce 맞추고 이전 보상 수령 시각을 1일 전으로 수정했습니다. 확인 부탁드립니다. 🙏

**Comment by QgamesGeonPyoNoh** [comment]
현재 헤임달 체인에서만 해당 현상이 발생 중에 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)



https://github.com/user-attachments/assets/41445f19-cbe9-476a-b047-9ce33e78670f

해당 이슈 발생 당시 Log 파일 공유 드립니다.

[Log.zip](https://github.com/user-attachments/files/16361282/Log.zip)

**Comment by U-lis** [comment]
heimdall 에 nonce 가 어긋나는 이슈가 있었습니다. 수정했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)

https://github.com/user-attachments/assets/9a8cbf18-03d0-4317-981e-2bf11620ce90
