### ISSUE TITLE
[K버전] 몬스터 컬렉션 안내 팝업 내 NCG 표현 출력

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4988]
### APV version info

K버전_v200181

### Client version info

v181.0.0

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
몬스터 컬렉션 안내 팝업 내 NCG 표현 출력
-K버전 Android, iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/8ce4c68c-2e07-40aa-817b-a8380b3a8440)

### How to reproduce the issue

[재현 스텝]
1. K버전으로 몬스터 컬렉션을 진행하지 않은 계정 접속
2. 메인 화면 - 몬스터 컬렉션 클릭
3. 몬스터 컬렉션 안내 팝업 내 NCG 표현 출력 확인

[Should be]
몬스터 컬렉션 안내 팝업 내 NCG 표현이 출력되지 않아야 합니다.

**Comment by jaeho0103** [comment]
얘는 known-issue 로 넘기고 추후에 한국어 전용 이미지를 제작 및 반영하도록 하겠습니다.
