### ISSUE TITLE
[시즌 패스] 시즌 패스가 시즌 6 패스로 출력되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#4989]
### APV version info

v200181

### Client version info

v181.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
시즌 패스가 시즌 6 패스로 출력되는 현상
-5월 시즌 패스가 적용되어 있는 상태입니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/b5df5555-cfb7-4ba5-8bd0-0cbe6697a296)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비
2. 화면 우측의 시즌패스 아이콘 확인
3. 시즌 패스 7로 바뀌지 않은 현상을 확인

[Should be]
6월달 시즌패스가 적용되어야 합니다.

**Comment by jaeho0103** [comment]
아 네 이부분은 현재 200180 RC와 9c-k 애플 버전 심사가 같이 진행되고 있어서 일부 패키지와 시즌패스의 이번버전 정보를 업데이트 하지 못하고 있는 부분입니다. 심사가 완료되는대로 정보 갱신하고 체크 요청드리겠습니다.

**Comment by U-lis** [comment]
오늘 오전에 시즌패스는 시즌7로 변경되었고, 구글 플레이에 상품 등록까지 되어 있습니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.4
Android.v200181-180.0.4
iOS.v180.0.4(73)



![Image](https://github.com/planetarium/NineChronicles/assets/167295117/a8027e41-f410-4d41-b4d4-686a98841d97)



![Image](https://github.com/planetarium/NineChronicles/assets/167295117/fb66e3a8-abd8-4b46-b68b-991dec706cc0)
