### ISSUE TITLE
[로그인] 파일 및 미디어 권한 미 허용 시 출력되는 안내 팝업에서 카메라 권한 요구 텍스트가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4992]
### APV version info

v200181

### Client version info

v181.0.0

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
파일 및 미디어 권한 미 허용 시 출력되는 안내 팝업에서 카메라 권한 요구 텍스트가 출력되는 현상
-카메라 권한이 아닌 미디어 권한으로 출력되어야 합니다.
-Android 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/85753d21-6028-45ec-85cc-e62d0de3819a

### How to reproduce the issue

[재현 스텝]
1. 게임 설치 후 게임에 첫 접속
2. 화면 우측 상단의 키 임포트 클릭
3. 현재 기기의 QR로 가져오기 클릭
4. (다시는 묻지 않기 체크) 거부 클릭
5. 카메라 권한 안내가 팝업되는 것을 확인

[Should be]
카메라 권한이 아닌 미디어 권한으로 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
@jaeho0103 혹시 해당 l10n 문구에서 '카메라 권한' -> '권한' 같이 공통적인 문구로 수정하는 것은 어떨까요?

![Image](https://github.com/planetarium/NineChronicles/assets/63496908/49fb1bbd-4712-4e56-b3e6-e95546a7ea77)

**Comment by jaeho0103** [comment]
네 키주시면 수정해서 올리겠습니다.

**Comment by tyrosine1153** [comment]
sentence.csv
STC_REQUIRED_CAMERA_PERMISSION_FOR_IMPORT_ACCOUNT_QR_CODE
입니다. 감사합니다.🙇

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200181-181.0.4

![sc](https://github.com/planetarium/NineChronicles/assets/150774808/acee0eb8-0c50-4908-8403-70f854c586a6)
