### ISSUE TITLE
[워크샵] 신규 룬의 스탯 감소 비율이 잘못 표기되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#4993]
### APV version info

v200181

### Client version info

v181.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
신규 룬의 스탯 감소 비율이 잘못 표기되는 현상
-소수점이 찍히지 않아 '-3009%'로 표기되고 있습니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/6be05eaa-0009-4606-a32b-63f1f4453c7e)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 루비/골든 룬 소환 - 돋보기 버튼 클릭
3. 신규 룬 정보를 확인하면 스킬 설명에 'by -3009%'로 표기된 것을 확인

[Should be]
퍼센트 값이 "-30.09%"로 표기되어야 합니다.

**Comment by NineSyu** [comment]
데이터 문제로 이상하게 보이는 것 체크하였습니다.
데이터 수정하여 정상적으로 출력되게 변경하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.5
Android.v200181-181.0.5
iOS.v181.0.5(74)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/23154369-d726-4285-896a-95e58dd8e320)
