### ISSUE TITLE
[인벤토리] 신규 룬이 거래 가능으로 표기되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#4994]
### APV version info

v200181

### Client version info

v181.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
신규 룬이 거래 가능으로 표기되는 현상
-신화 등급 오딘 룬의 상세 정보 확인 시 "거래 가능"으로 표기되어 있습니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/2fa58d4f-33c5-4a6a-84e5-a6fc497861d2)

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/d0eeeca1-3c10-4ee2-8bd6-a6de5c0f257a)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 화면 상단의 캐릭터 UI 클릭
2. 룬 조각 탭을 클릭
3. 신규 오딘 룬을 클릭하여 룬 상세 정보 팝업
4. 거래가능으로 표기되어있는 것을 확인

[Should be]
신화 등급 룬은 거래불가능으로 표기되어야 합니다.

**Comment by jaeho0103** [comment]
네 거래불가 추가 요청을 놓쳤네요. 추가 부탁드리겠습니다. @ipdae

**Comment by ipdae** [comment]
@jaeho0103 @NineSyu 적용해야하는 티커목록 알려주시면 반영해두겠습니다.

**Comment by NineSyu** [comment]
신규 룬 티커 2종 공유드립니다.
RUNESTONE_ODIN_WEAKNESS
RUNESTONE_ODIN_WISDOM

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.4
Android.v200181-181.0.4
iOS.v181.0.4(73)

![image](https://github.com/planetarium/NineChronicles/assets/150774808/e90fe14a-f838-4877-8734-b7128d09d23d)
