### ISSUE TITLE
[룬] 오딘 쇠약 룬 착용 후 전투 진입 시 클라이언트 종료 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#4997]
### APV version info

v200181

### Client version info

v181.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
오딘 쇠약 룬 착용 후 전투 진입 시 클라이언트 종료 현상
-어드벤쳐/아레나에서는 에러코드 99가 출력되며, 월드보스는 Start 버튼이 응답하지 않습니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/cecad8b5-cb92-4271-ba2c-c972f1701eda

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 임의의 스테이지 클릭
2. 오딘 쇠약 룬 착용
3. 스테이지 진입 시 클라이언트 종료 현상 확인

[Should be]
오딘 쇠약 룬 착용 후 전투 진입 시 전투 진행이 가능해야 합니다.

### Relevant log output

[2024-6-3 02:07:40] StatType NONE is missing in statMap.
Nekoyume.Game.<BackToMainAsync>d__155:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start(TStateMachine&)
Nekoyume.Game.Game:BackToMainAsync(Exception, Boolean)
Nekoyume.Blockchain.ActionRenderHandler:ExceptionHackAndSlash(ActionEvaluation`1)
UniRx.Subscribe`1:OnNext(T)
UniRx.Operators.ObserveOn_:OnNext_(T)
UniRx.QueuedAction`1:Invoke(Object)
UniRx.InternalUtil.ThreadSafeQueueWorker:ExecuteAll(Action`1)
UniRx.MainThreadDispatcher:Update()

**Comment by NineSyu** [comment]
룬 효과의 수치값이 비정상적으로 높아서 생긴 생긴 이슈로 보입니다.
다음 빌드 전달 시에 데이터 수정하여 정상 진입되게 처리하겠습니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.4
Android.v200181-180.0.4
iOS.v180.0.4(73)



https://github.com/planetarium/NineChronicles/assets/167295117/126ec881-a914-4783-8c83-96960415d40d
