### ISSUE TITLE
[룬] 오딘 쇠약 룬 제작 시 버튼에 "룬 레벨업"으로 표기되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#4998]
### APV version info

v200181

### Client version info

v181.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
오딘 쇠약 룬 제작 시 버튼에 "룬 레벨업"으로 표기되는 현상
-오딘 지혜 룬을 제작할 때는 "룬 제작"으로 표기되지만 쇠약 룬은 "레벨업"으로 표기됩니다.
-Windows / Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/48f69b68-0887-413b-8de0-ecc13e900dfa)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬
2. 오딘 쇠약 룬 제작
3. 제작 버튼에 "레벨업" 텍스트가 표기되는 것을 확인

[Should be]
오딘 지혜 룬과 마찬가지로 제작을 할 때에는 "룬 제작"이라는 텍스트가 표기되어야 합니다.

**Comment by eugene-doobu** [comment]
클라이언트 시작 후 첫 룬 제작시 발생하는 오류로 판단됩니다. 수정해두겠습니다

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.4
Android.v200181-181.0.4
iOS.v181.0.4(73)


https://github.com/planetarium/NineChronicles/assets/167295117/2912a248-1d37-4773-b886-91454f965fb0
