### ISSUE TITLE
[런쳐] 헤임달에서 오딘으로 NCG가 전송되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5005]
### APV version info

v200181

### Client version info

v181.0.3

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
헤임달에서 오딘으로 NCG가 전송되지 않는 현상
-헤임달 계정의 NCG는 차감되나 오딘 계정의 NCG는 증가하지 않았습니다.
-Windows 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/19d156d5-8ecb-4dc3-8aa0-c66a7e5f1ba8

### How to reproduce the issue

[재현 스텝]
1. 런쳐 - Send NCG 클릭
2. 오딘 계정에서 Target Planet을 헤임달로 선택
3. NCG 전송 진행
4. 헤임달 계정으로 접속 시 NCG가 전송되지 않는 현상 확인

[Should be]
헤임달에서 오딘으로 NCG가 전송되어야 합니다.

**Comment by U-lis** [comment]
internal node 를 세팅하는 과정에서 bridge 의 heimdall > odin 방향 초기화가 잘 되지 않은 것으로 보입니다.
브릿지 다시 초기화했고, heimdall > odin 잘 이동하는 것 확인했습니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.4


https://github.com/planetarium/NineChronicles/assets/167295117/9ad78055-7843-4122-8aa7-5ed149a00c64

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재 발생했습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200200-200.0.1

https://github.com/planetarium/NineChronicles/assets/150774808/ad648b9e-828d-4f5d-8537-34b527f47ba2

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재 발생했습니다.
확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/67856302-4b20-4a69-a0e3-b8bbce7652db


[테스트 환경]
Windows.v200200-200.0.1

**Comment by U-lis** [comment]
internal 브릿지 block index 가 정상 초기화되지 않아 해당 현상이 재발했습니다.
다시 block index 잡아서 초기화했고, 테스트 전송까지 확인했습니다 :pray:

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.2

https://github.com/planetarium/NineChronicles/assets/150774808/f1098335-67f1-4b77-888f-72884722b022

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재발생 확인했습니다.
확인 부탁드립니다.

Uploading Heimdall-Odin.mp4…

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.1

https://github.com/user-attachments/assets/9d92edad-89c2-476a-ba42-80df2b8321a9

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재발생 확인했습니다.
오딘 > 헤임달은 현재 NCG가 없어 획인하지 못했습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200240-240.0.1


https://github.com/user-attachments/assets/64a18713-7ffc-4a55-ae43-1b6628075460

**Comment by U-lis** [comment]
내부 dns 설정을 변경하는 과정에서 문제가 있었습니다. 현재 해결되었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 현재 발생 중 입니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200240-240.0.2

https://github.com/user-attachments/assets/9bd66728-f0e8-48bb-867d-d337d3b99a34

**Comment by ipdae** [comment]
브릿지 복구된 상황이라 다시 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 수정되지 않았습니다.
확인 부탁드립니다.

https://github.com/user-attachments/assets/b6e39d85-3c9f-4dc2-8e46-377dae82f8ff

[Log.zip](https://github.com/user-attachments/files/17501863/Log.zip)

**Comment by U-lis** [comment]
internal  bridge 설정이 왠지 모르게 달라져 있었습니다. 수정했고, 내부 테스트 통과했습니다. 확인 부탁드립니다 🙏

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.4

https://github.com/user-attachments/assets/9c307a0b-2ce8-447a-a515-0fe56b464f10
