### ISSUE TITLE
[K버전] K버전 iOS 설치 후 최초 접속 시 Planet가 오딘으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5011]
### APV version info

K버전_v200181

### Client version info

v181.0.4

### Device

iOS

### detailed device info

iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
K버전 iOS 설치 후 최초 접속 시 Planet가 오딘으로 출력되는 현상
-Android / M버전 iOS는 헤임달이 디폴트로 설정되어 있습니다.
-iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/31e3f156-7232-4ccc-8333-4c65aa0ffb34

### How to reproduce the issue

[재현 스텝]
1. 아이폰에서 K버전 설치 후 최초 접속
2. 최초 접속 시 Planet가 오딘으로 출력되는 현상 확인

[Should be]
K버전 iOS 설치 후 최초 접속 시 Planet가 헤임달로 출력되어야 합니다.

**Comment by ipdae** [comment]
iOS K버전의 의도된 스펙입니다.
