### ISSUE TITLE
[시즌 패스] 동일한 계정의 다른 캐릭터로 구매할 수 없는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5013]
### APV version info

v200181

### Client version info

v181.0.4

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
동일한 계정의 다른 캐릭터로 구매할 수 없는 현상
-A라는 캐릭터가 시즌 패스를 구매하였을 경우 같은 계정의 B라는 캐릭터는 시즌 패스를 구매하려고 할 때, 구매가 불가능 합니다.
-Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/ede9b7a9-2272-4a74-9653-60b8a71c2fbf

### How to reproduce the issue

[재현 스텝]
1. A캐릭터로 프리미엄 시즌 패스를 구매
2. A캐릭터로 프리미엄+ 시즌 패스를 구매
3. B캐릭터로 프리미엄 시즌패스 구매 버튼 클릭
4. "판매 기한이 지난 상품입니다."라는 메시지가 출력되는 것을 확인
5. 만일 A캐릭터로 바로 프리미엄+ 시즌 패스를 구매할 경우,
6. B캐릭터로 프리미엄+ 시즌 패스 구매 버튼을 클릭하면 동일한 문제 발생

[Should be]
같은 캐릭터가 아닐 경우 상품을 구매할 수 있어야 합니다.

**Comment by U-lis** [comment]
상점 기본 정책으로는 agent 단위로 구매를 체크하고 있어서 season pass 상품에 대한 구매 수량 제한이 잘 적용되지 않는 이슈가 있었습니다.
최대 3개 아바타에서 구매할 수 있도록 제한을 변경했습니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200181-181.0.5
Android.v200181-181.0.5
iOS.v181.0.5(74)

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재 발생했습니다.
확인 부탁드립니다.

[테스트 환경]
K.Android.v200220-220.0.1

https://github.com/user-attachments/assets/d7e1dfd7-a75c-45df-8f16-ab09c41ea258

**Comment by U-lis** [comment]
예전에 발생한 것과 동일한 이슈였습니다. DB 의 값 변경 조치했으며, 구매 기준 값을 3으로 변경해 앞으로 재발하지 않도록 했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
K.Android.v200220-220.0.3

https://github.com/user-attachments/assets/d70a7376-f20e-40ed-bf9f-4cea83a0e860
