### ISSUE TITLE
[이미르 아우라] 디버프에 걸린 적이 파란색으로 출력되지 않는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5016]
### APV version info

v200181

### Client version info

v181.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
디버프에 걸린 적이 파란색으로 출력되지 않는 현상
-아레나, 월드 보스 캐릭터가 기본 색상을 유지하고 있습니다.
-Windows / Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/df300482-989f-4f95-918e-1ee830a97e1a

### How to reproduce the issue

[재현 스텝]
1. 이미르 아우라 착용
2. 아레나/월드 보스 진입
3. 상대가 디버프에 걸려도 파란색으로 출력되지 않는 현상 확인

[Should be]
이미르 디버프 효과를 받은 아바타의 색상이 파란색으로 변경되야 합니다.

**Comment by eugene-doobu** [comment]
월드보스 / 아레나의 경우 추후 빌드에서 수정하는것으로 남겨두겠습니다. 타겟 버전 200으로 변경하였습니다.

**Comment by eugene-doobu** [comment]
어드벤처 타임라인 관련해서 material 색상이 강제적으로 지정되는 부분이 있어 기존 로직으로 색상 변경 적용이 어렵습니다.
노운 이슈로 done처리 해두겠습니다
