### ISSUE TITLE
[K버전] 아레나 시즌 천막에 NCG 문구가 표기되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5017]
### APV version info

K버전_v200181

### Client version info

v181.0.4

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
아레나 시즌 천막에 NCG 문구가 표기되는 현상
-메인 로비에 아레나 UI를 보면 시즌 진행 천막에 NCG 문구가 표기되어 있습니다.
-Android / iOS 환경에서 확인하였습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/6edd5180-fb4e-453c-83e1-8f56360d57e4)

### How to reproduce the issue

[재현 스텝]
1. 오딘 서버에 접속
2. 메인로비
3. 아레나 UI에 NCG 문구가 표기된 천막이 있는 것을 확인

[Should be]
K 버전에는 "NCG" 문구가 모두 "골드"로 바꾸어 표기됩니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200181-181.0.5
iOS.v181.0.5(74)


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/dc55a01b-40b7-4874-ac78-5eee4baaae6d)
