### ISSUE TITLE
[K버전] 상점 상품의 가격이 0.00 으로 표기되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5018]
### APV version info

K버전_v200181

### Client version info

v181.0.4

### Device

iOS

### detailed device info

iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
상점 상품의 가격이 0.0 으로 표기되는 현상
-상점의 상품과 시즌 패스 상품의 가격이 0.0으로 표기되고 있습니다
-"3+1","무료","AP 포션 15" 상품은 정상적으로 표기되고 있습니다.
-iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/1fe7c771-4740-41ec-8c89-994c6a6c086d

### How to reproduce the issue

[재현 스텝]
1. 아이폰으로 K버전 접속
2. 메인로비 - 마켓
3. 진열된 상품 확인

[Should be]
가격이 표기되고, 결제가 진행되어야 합니다.

**Comment by jaeho0103** [comment]
네 아이폰 K버전은 신규 상품 데이터가 아직 심사전입니다. 정상 스펙입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
iOS.v181.0.5(74)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/7ea9d9d1-3f35-4fdb-9ebb-f72c2cb943cf)
