### ISSUE TITLE
[K버전] 마켓에서 구매한 아이템이 즉시 지급되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5023]
### APV version info

K버전_v200181

### Client version info

v181.0.5

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
마켓에서 구매한 아이템이 즉시 지급되지 않는 현상
-재 접속 시 아이템 지급 확인되었습니다.
-K버전 Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/60c4ed5c-7ec9-4a94-bc7d-5812fa010efa

### How to reproduce the issue

[재현 스텝]
1. K버전 모바일 접속
2. 메인 로비 - 마켓 클릭
3. 임의의 상품 구매 진행
4. 구매한 아이템이 즉시 지급되지 않는 현상 확인

[Should be]
K버전 마켓에서 구매한 아이템이 즉시 지급되어야 합니다.

**Comment by U-lis** [comment]
IAP 구매 로그는 정상적으로 잘 진행되었습니다. @eugene-doobu client 쪽 렌더가 원인일까 싶은데 체크 부탁드립니다.
===
IAP log
- 10시 45분 08초 google play 구매
- 10시 45분 14초 IAP 구매 요청
- 10시 45분 28초 Odin Tx 성공
- 10시 45분 36초 internal bridge 이벤트 발생
- 10시 45분 49초 heimdall Tx 성공 (지급 완료)
