### ISSUE TITLE
k 버전 업데이트 바로 가기가 M버전으로 연결되는 부분 수정 이슈

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5032]
k 버전 업데이트 바로 가기가 M버전으로 연결되는 부분 수정 이슈

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1717827867074879)

**Comment by tyrosine1153** [comment]
LiveAsset에 올라간 clo에 마켓 링크 수정했습니다
https://github.com/planetarium/NineChronicles.LiveAssets/commit/398fe0e23137952e6cc5c208037d573b51610ee7

**Comment by tyrosine1153** [comment]
@jaeho0103  LiveAsset에서 clo를 삭제했던 다른 버전들은 수정한 url 적용을 안받겠네요;; 아마 코드에 적힌 기본 url을 사용할텐데, LiveAsset에 이전 버전 clo라도 살려서 마켓 링크를 K로 가리키도록 할까요?

**Comment by jaeho0103** [comment]
네 K 버전 어차피 1개만 나갔을거라 해당버전에만 대응 부탁드리겠습니다.

**Comment by tyrosine1153** [comment]
넵 171.0.0 aos kr, 171.0.1 ios kr 수정해서 올리겠습니다
