### ISSUE TITLE
[몬스터콜렉션] 런쳐와 인게임 내 몬스터콜렉션 개러지 코인 보상이 다른 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5035]
### APV version info

메인넷.v200181

### Client version info

v181.0.5

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
런쳐와 인게임 내 몬스터콜렉션 개러지 코인 보상이 다른 현상
-Android / iOS 인게임 내 보상과도 상이합니다.
-Windows 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/54fd58e5-da64-41c3-8257-921457a0973a

### How to reproduce the issue

[재현 스텝]
1. 런쳐 - 스테이킹 클릭
2. 메인 로비 - 몬스터콜렉션 클릭
3. 스테이킹 5단계 (50,000 NCG) - 8단계 (10,000,000 NCG 확인)
4. 런쳐와 인게임 내 개러지 코인 보상이 다른 현상 확인

[Should be]
런쳐와 인게임 내 몬스터콜렉션 개러지 코인 보상이 동일해야 합니다.

**Comment by jaeho0103** [comment]
네 확인했습니다. 인게임에서 사용하는 안내표가 잘못되어있네요. 수정해서 업데이트해두겠습니다.

**Comment by jaeho0103** [comment]
크리스탈 1000만 (마지막 레벨) 에서 x5000M -> x5B 로 수정

개러지(오른쪽 마지막아이콘) 5만, 50만 - 로 변경 100만, 500만, 1000만 100, 10K, 100 K 로 변경
