### ISSUE TITLE
그리모어 소환과 기타

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5038]
부모 브랜치 : feature/charm
사용 브랜치 : ui/charm-add

- 업그레이드 텝 추가 ---> 완료
- 필터 버튼 추가 ---> 완료
- 망치 신성등급 아이콘 추가 ---> 완료
- 그리모어 12종 아이콘 추가 ---> 완료
- 배경 추가 ---> 완료
- 우측 캐릭터 추가 ---> 완료
- 해더메뉴에 에메랄드 더스트 추가 ---> 가이드 전달 완료
- 부적 소환 텝 메뉴 추가 ---> 완료
- 중앙 그리모어 이미지 ---> 완료
- 인벤토리 슬롯에 그리모어 착용 가능 알림 리소스 추가 ---> 완료

추후 리소스 교체 예정입니다. 일단 작업하실 수 있게 임시 이미지 적용해 두었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/15254e44-c206-474f-a89b-7637af332e5b)

- 업그레이드화면에서 좌측 참(책이미지) 텝 버튼 추가해 주었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/4885b4f0-d852-4444-b9b1-76262ecf232a)

- Type : Charm 버튼 추가했습니다.
- Upgrade Level : +5more -> +5로 수정해주고, +6more 버튼을 추가해 주었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/dfd51eea-6dda-4adc-aa79-a1ed97c208c9)

- 부적 아이콘 리소스 등록해 두었습니다.

**Comment by boramqo83** [comment]
조니님이 작업중이신 feature/adventure-boss-merge-to-prepare 요 브랜치에 등록된 이미지를 해당 브랜치에서도 같은 리소스를 올리고 있어 추후 충돌 날 수 있음을 알려드립니다.
- 600203 (에메랄드 아이콘 리소스)
- 600301 ~ 600306 (신성을 제외한 망치 아이콘 리소스)
- UI_HeaderMenuStatic (해더메뉴에 에메랄드 더스트 추가)

**Comment by boramqo83** [comment]
조니님이 작업중이신 feature/adventure-boss-merge-to-prepare 요 브랜치에서 해더 메뉴 프리퓁(UI_HeaderMenuStatic)에서 수정한 것(AP포션 추가)이 있어 불러온 후에 작업하는 것이 좋을 것 같습니다.




![Image](https://github.com/planetarium/NineChronicles/assets/102953029/9a8388f2-bd37-4881-9033-5d227324d1f6)

- 불러온 이후 작업할 것 : 에메랄드 더스트 추가하기 (요건 정민님이 추후 추가해 주세요.) - 맨 왼쪽에 에메랄드 더스트 추가
- 기존에 만들었던 더스트들 이미지와 이름 매칭 부탁드려요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/3c294fd5-c7e4-42f0-8501-dadc68b626c6)

- 그리모어 텝에서의 캐릭터는 Character_Grimoire를 켜 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/2492f851-993d-4679-a79a-9e1f48fdb94b)

- 왼쪽 텝 버튼에 그리모어 텝 버튼 추가해 주었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/d14d8865-f925-46e1-9ce5-a838195ac2ce)

- 그리모어 텝버튼 선택하면 단상 부분의 이름을 Grimoire로 나오도록 해 줍니다.
- 버튼에 아이콘 에메랄드 이미지 나오도록 해 주세요. (리소스 이름 : UI_main_icon_Emeraldpowder)

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/6757eedc-be24-4dce-a2e0-4c68c9a1ce66)

- 노말 아우라 뽑기의 경우 노란색 버튼이 아닌 갈색 버튼을 적용해 줍니다. (ButtonGroup_Normal 요거 추가해 두었습니다.)

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/4e87a9ce-ef5c-4772-9841-c29d01952953)

- 결과화면에서도 노말 아우라 뽑기는 갈색 버튼으로 적용해 주세요.
- 결과화면에서 에메랄드 뽑기 버튼 추가해 두었습니다.

**Comment by boramqo83** [comment]
언어대응해야 할 곳은 그리모어 뿐이 없는 것 같군요.

**Comment by boramqo83** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/d73b0d1f-688b-4259-841c-460c1158640f)

- 인벤토리 팝업창에 그리모어 비활성 이미지 적용해 두었습니다.
- 이름도 참 대신 그리모어로 수정했습니다.

**Comment by boramqo83** [comment]
거의 작업 완료해 주신 것 같군요.
https://planetariumhq.slack.com/archives/C06UMQR34GZ/p1718165294342879?thread_ts=1718158755.035609&cid=C06UMQR34GZ
위와 같은 요청이 있었는데요..
혹시 그리모어일 때만 단상 컬러 변경 가능할까요?
가능하다면 Bottom 이미지의 컬러를 B9FFB8로 수정 부탁드립니다.(그리모어일 때만 컬러 변경)

![Image](https://github.com/planetarium/NineChronicles/assets/102953029/40460576-1430-4022-989e-6fa38fdfee99)

@tyrosine1153

**Comment by tyrosine1153** [comment]
> 거의 작업 완료해 주신 것 같군요.
> https://planetariumhq.slack.com/archives/C06UMQR34GZ/p1718165294342879?thread_ts=1718158755.035609&cid=C06UMQR34GZ
> 위와 같은 요청이 있었는데요..
> 혹시 그리모어일 때만 단상 컬러 변경 가능할까요?
> 가능하다면 Bottom 이미지의 컬러를 B9FFB8로 수정 부탁드립니다.(그리모어일 때만 컬러 변경)
> 
> ![Image](https://github.com/planetarium/NineChronicles/assets/102953029/40460576-1430-4022-989e-6fa38fdfee99)
> 
> @tyrosine1153 

아.. 이걸 지금 봤네요. 원래 없던 스펙이니 새로 구현하면 되겠네요. 혹시 그리모어 외에도 단상 컬러가 바뀌었으면 하는게 또 있는지 확인 부탁드립니다.

**Comment by boramqo83** [comment]
그리모어 외에 다른 곳 단상컬러 변경되는 곳은 없습니다.
다만 고민되는 부분이 요 부분을 유니티에서 제가 편하게 수정할 수 있는 방법을 못찾고 있었던 점입니다.
정민님이 코드로 컬러 적용해주시는게 편하긴 한데 이후 수정이 번거롭다는 단점이 있긴하네요.
@tyrosine1153

**Comment by tyrosine1153** [comment]
코드로 컬러 수정하면서 유니티에서 수정할 수 있도록 같이 작업하겠습니다.

**Comment by tyrosine1153** [comment]
- 결과 화면에 금색 버튼은 더스트끼리 구분할 필요 없이 하나만 쓰면 되도록 수정했습니다. 이후 작업하실 때 참고해주세요.
- 그리모어는 소환 시 재생되는 영상이 없나요?
