### ISSUE TITLE
아레나 인게임에서 상대 블러드 스킬 이펙트 좌우 반전되어 있음

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5083]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/049868b7-fd7e-4e36-ba1b-b0d3974f1ed0)

**Comment by boramqo83** [comment]
요 잇슈 유진님과 이야기가 됬던 것으로 유진님께 전달 드립니다. @eugene-doobu

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/5114
에서 수정하였습니다
