### ISSUE TITLE
[몬스터콜렉션] 런쳐에서 Get Rewards 버튼이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5087]
### APV version info

v200190

### Client version info

v190.0.0

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
런쳐에서 Get Rewards 버튼이 출력되는 현상
-스테이킹 바로가기 버튼은 런쳐 업데이트 후 삭제되었습니다.
-Get Rewards 버튼은 출력되고 있으며, 보상 수령 후에도 활성화 상태로 출력됩니다.
-재 수령 시도 시 실패하며 메시지 출력되고 있습니다.
-Windows 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/ba08ac9c-5851-4c5a-aa6c-78820de9cc14

### How to reproduce the issue

[재현 스텝]
1. 스테이킹 보상 수령이 가능한 계정 진입
2. 런쳐에서 Get Rewards 버튼이 출력되는 현상 확인
3. Get Rewards 버튼 클릭하여 보상 수령 진행
4. 보상 수령 후에도 Get Rewards 버튼 활성화되는 현상 확인

[Should be]
런쳐에서 Get Rewards 버튼이 출력되지 않아야 합니다.

**Comment by jaeho0103** [comment]
런처에서 삭제되는 몬스터 콜렉션 관련 기능은 신규 진입 및 금액 수정등이며, 
migrate , get rewards 기능은 스펙 유지를 목표로 하고 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200190-190.0.0

**Comment by Akamig** [comment]
저거 자체의 유지는 기획의도가 맞긴 한데, 
보상 수령 후에도 Get Rewards가 출력되는건 버그로 보이네요... 다시 열도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
런쳐에서 Get Rewards 버튼 및 스테이킹 영역이 모두 삭제되었습니다.
해당 부분 의도된 사항인지 확인 부탁드립니다.

[테스트 환경]
Windows.v200190-190.0.1

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/ff5ab0a2-d007-4acd-9429-7595a88204e1)

**Comment by jaeho0103** [comment]
협의된 스펙이었으나, 또 변경될 예정으로 다시 이슈 상태 변경해두겠습니다

**Comment by Akamig** [comment]
아, 요거 결국 제거되는 것으로 협의되었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
네, 확인 감사드립니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200190-190.0.3
