### ISSUE TITLE
[런쳐] Planet 선택 시 Idun(Internal)이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5088]
### APV version info

v200190

### Client version info

v190.0.0

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Planet 선택 시 Idun(Internal)이 출력되는 현상
-접속이 가능하며 Heimdall 캐릭터가 출력되고 있습니다.
-Windows 환경에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/d90163af-ca86-4bc8-93ea-fb63c1ceaef7)

### How to reproduce the issue

[재현 스텝]
1. 런쳐 실행
2. Platent 드롭박스 클릭
3. Idun(Internal)이 출력되는 현상 확인

[Should be]
Planet 선택 시 Idun(Internal)이 출력되지 않아야 합니다.

**Comment by jaeho0103** [comment]
다음 버전 200200 내부 체크를 위해 이둔을 셋팅해둔 부분으로 테스트를 위한 임시 설정으로 이해해주시면 감사하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200190-190.0.0
