### ISSUE TITLE
[런쳐] 오딘에서 헤임달으로 NCG가 전송되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5090]
### APV version info

v200190

### Client version info

v190.0.0

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
오딘에서 헤임달으로 NCG가 전송되지 않는 현상
-오딘 계정의 NCG는 차감되나 헤임달 계정의 NCG는 증가하지 않았습니다.
-Windows 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/a97a2ff0-2527-4eac-bfb7-fd5d9caafc8f

### How to reproduce the issue

[재현 스텝]
1. 런쳐 - Send NCG 클릭
2. 오딘 계정에서 Target Planet을 헤임달로 선택
3. NCG 전송 진행
4. 헤임달 계정으로 접속 시 NCG가 전송되지 않는 현상 확인

[Should be]
오딘에서 헤임달으로 NCG가 전송되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
오딘 > 헤임달 NCG 전송 확인 완료되었습니다.
수정된 항목이 맞다면 이슈 종료하도록 하겠습니다.

[테스트 환경]
Windows.v200190-190.0.1

https://github.com/planetarium/NineChronicles/assets/150774808/f05e156c-a438-43d6-9e16-7803612b42f0

**Comment by Akamig** [comment]
아 넵 수정된 항목이 맞고 이슈 종료하시면 되겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 재 발생했습니다.
확인 부탁드립니다.

재현 영상 확보 시 업로드 하도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
재현 영상 공유드립니다.

https://github.com/user-attachments/assets/33a18344-dbee-4472-a625-313ff7cefc7d

**Comment by U-lis** [comment]
어... 원인은 모르겠는데 어떤 이유에연지 internal bridge 서비스가 내려가 있었습니다.
현재 다시 켜서 event 만들어지는 것 확인했습니다. 테스트 부탁드립니다 :pray:

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.1

https://github.com/user-attachments/assets/952e993b-1c3f-40ff-82f9-5b807a601576

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재발생했습니다.
확인 부탁드립니다.

https://github.com/user-attachments/assets/ba33aaa7-1d0c-4247-8e85-1b063260c4b5

**Comment by U-lis** [comment]
0826에 발생한 이슈는 [이 이슈](https://github.com/planetarium/NineChronicles/issues/5005) 와 동일한 원인인 것으로 파악됩니다. (브릿지 서비스가 너무 오래전 블록을 따라가고 있음)
현재 브릿지 서비스 정상화되어 최신 블록 따라가고 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.1

https://github.com/user-attachments/assets/e5d921c5-fc17-4224-bde9-78e55fbe08d8
