### ISSUE TITLE
[마켓] 마켓에 음식 등록 시 수량 지정이 가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5091]
### APV version info

v200190

### Client version info

v190.0.0

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
마켓에 음식 등록 시 수량 지정이 가능한 현상
-음식 수량 지정 기능이 추가되었는데 기획의도인지 확인 부탁드립니다.
-추가로, 개당 수량이 소수점 수치가 될 경우 등록이 불가능한데 기획의도인지 확인 부탁드립니다.
-Windows 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/9731e2fa-a9ef-432c-bb6e-2c89553e2112

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 마켓 클릭
2. Sell - 음식 탭 클릭
3. 2개 이상 보유하고 있는 음식 선택
4. 마켓에 음식 등록 시 수량 지정이 가능한 현상 확인

[Should be]
마켓에 음식 등록 시 수량 지정이 불가능해야 합니다.

**Comment by jaeho0103** [comment]
네 음식 마켓 등록 및 음식 사용 UX가 개편되었습니다. 같은 음식은 인벤토리에서 같은 칸에 수량으로 표시하는게 기본 방향성입니다. 마켓에서는 여러개 판매시 1개씩 상품이 여러건 등록되는 형태이며, 개별 정수의 판매가격만 지원하는게 스펙이 맞습니다.

**Comment by QgamesGeonPyoNoh** [comment]
코멘트 확인 시 기획 의도인 것이 확인되었습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200190-190.0.0
