### ISSUE TITLE
[마켓] 모바일 마켓 상품이 구매 시 지급되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5099]
### APV version info

v200190

### Client version info

v190.0.0

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모바일 마켓 상품이 구매 시 지급되지 않는 현상
-M버전 iOS , K버전에서 확인했습니다.
-M버전 Android는 APK 파일로 설치하여 진행하였으며, 구매 상품을 찾을 수 없다는 메세지가 출력됩니다.

https://github.com/planetarium/NineChronicles/assets/150774808/a99fa61b-3acb-45c1-942e-418fd76d695f

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/db0d52c5-ae0f-4d64-a9fa-d5fa392ac261)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 마켓 클릭
2. 임의의 아이템 구매 진행
3. 모바일 마켓 상품이 구매 시 지급되지 않는 현상 확인

[Should be]
모바일 마켓 상품이 구매 시 지급되어야 합니다.

**Comment by jaeho0103** [comment]
@QgamesGeonPyoNoh 
첨부해주신 영상을 보아하니 헤임달에서 구매테스트하신것 같은데 재현 환경에서 테스트하신 체인 정보도 같이 주시면 감사하겠습니다.
M버전의 경우 구글 한국 계정으로는 구매체크가 되지 않는 상황입니다.

**Comment by QgamesGeonPyoNoh** [comment]
네, 확인 감사드립니다.
오딘에서는 모바일 마켓 상품 지급 확인했습니다.
헤임달에서는 현재 지급되지 않고 있습니다.

**Comment by U-lis** [comment]
안녕하세요 @QgamesGeonPyoNoh 확인 결과 internal odin > heimdall bridge 서비스에서 Tx 를 잘 넘겨주지 못하는 것으로 확인했습니다.
현재 bridge service 를 리셋했고, 내부 테스트 확인했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200190-190.0.0
iOS.v190.0.0(75)

https://github.com/planetarium/NineChronicles/assets/150774808/90f5144c-47cb-4c97-beaf-979ff9ad7952

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재 발생 확인했습니다.
구매 후 아이템이 지급되지 않았으며, 재접속 시에도 지급되지 않았습니다.

[테스트 환경]
K.Android.v200210-210.0.5
K.iOS.v210.0.5(43)

https://github.com/user-attachments/assets/1f2991d6-4b29-4a0f-8076-2dcd97f4c3f6

**Comment by U-lis** [comment]
안녕하세요 해당 이슈는 internal 에서 상품 지급 action 을 변경하는 테스트의 영향으로 상품 지급이 정상처리되지 않은 것으로 확인되었습니다.
상품 지급 액션 변경은 이번에 들어갈 이슈가 아니어서 이전 버전으로 원복 후 구매 테스트 진행했습니다.
확인 부탁드립니다. :pray:

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
iOS.v210.0.5(100)
K.Android.v200210-210.0.5
K.iOS.v210.0.5(43)

https://github.com/user-attachments/assets/771d1325-7e0f-4aa4-90c9-bcd78a1b05c2

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재 발생 확인했습니다.
구매 후 아이템이 지급되지 않았으며, 재접속 시에도 지급되지 않았습니다.

[테스트 환경]
K.Android.v200220-220.0.1
iOS.v220.0.1(102)

https://github.com/user-attachments/assets/3ef644c5-8480-4131-93c3-d3c7582caeb6

**Comment by U-lis** [comment]
지난 금요일 node reset 문제로 IAP 계정에 설정되어 있던 재고도 같이 리셋되어 상품 전달이 되지 않고 있었습니다.
internal 에 재화 세팅 완료했습니다. 패키지 몇개 랜덤으로 구매했을 때 잘 전송되는 것 확인했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
K.Android.v200220-220.0.1
iOS.v220.0.1(102)

https://github.com/user-attachments/assets/d2f26dc6-3459-4c0b-9584-24d3ad05078f
