### ISSUE TITLE
[월드보스] 헤임달에서 월드보스 점수 기록이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5100]
### APV version info

v200190

### Client version info

v190.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
헤임달에서 월드보스 점수 기록이 출력되지 않는 현상
-오딘에서는 정상적으로 출력됩니다.
-Windows / Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/66f815cb-4f44-45d5-8c1a-f0588e936500

### How to reproduce the issue

[재현 스텝]
1. 헤임달으로 접속
2. 메인 로비 - 월드보스 클릭
3. 월드보스 공격 진행
4. 월드보스 점수 기록이 출력되지 않는 현상 확인

[Should be]
헤임달에서 월드보스 점수 기록이 출력되어야 합니다.

**Comment by ipdae** [comment]
data-provider 노드의 동기화 문제가 있었고, 아직 동기화처리중입니다. 동기화가 완료되면 공유드리겠습니다.

**Comment by ipdae** [comment]
공유가 늦어 죄송합니다. 노드 정상화됐으니 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
Heimdall(internal) 환경에서 월드보스가 종료되어,
해당 부분은 메인넷에서 수정 확인하도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 확인 완료했습니다.

[테스트 환경]
메인넷.Windows.v200200-v200.1.2

![Image](https://github.com/user-attachments/assets/d66d2190-b377-4340-ac66-28e61ca0f913)
