### ISSUE TITLE
[인벤토리] 오딘에서 제작 및 강화한 아이템이 인벤토리에 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5124]
### APV version info

v200190

### Client version info

v190.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
오딘에서 제작 및 강화한 아이템이 인벤토리에 출력되지 않는 현상
-헤임달에서는 제작 및 강화 시 즉시 획득 합니다.
-다른 행동을 취한 이후 인벤토리에 출력됩니다.
-Windows / Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/724ff9f7-24d8-491f-8108-91291394fe4c

### How to reproduce the issue

[재현 스텝]
1. 오딘으로 접속
2. 메인 로비 - 워크샵 - 제작 or 강화 클릭
3. 임의의 아이템 제작 or 강화 진행
4. 제작 및 강화한 아이템이 인벤토리에 출력되지 않는 현상 확인

[Should be]
오딘에서 제작 및 강화한 아이템이 인벤토리에 즉시 출력되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
장비 제작 및 강화 시 모래시계를 사용할 경우 해당 현상 발생 확인했습니다.
추가로, 해당 현상 발생 시 인벤토리 내 모래시계의 개수도 차감되지 않았습니다.
확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/ccaa7b35-444b-4cd3-83e9-c07ef4c7721a

**Comment by ipdae** [comment]
#5133 과 마찬가지로 메일을 읽었을때 해당 현상이 발생하는것같습니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200190-190.0.4

https://github.com/planetarium/NineChronicles/assets/167295117/f03947b8-2dfb-4064-a6fb-4500d9e1a5fa
