### ISSUE TITLE
[인벤토리] 오딘에서 수령한 시즌패스 보상이 인벤토리에 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5129]
### APV version info

v200190

### Client version info

v190.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
오딘에서 수령한 시즌패스 보상이 인벤토리에 출력되지 않는 현상
-헤임달에서는 구매 후 즉시 출력됩니다.
-Windows / Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/a6a83e2c-eb1e-4973-8c4e-d2f45c3e3068

https://github.com/planetarium/NineChronicles/assets/150774808/5a762ff6-66fc-4a88-8b4a-739cfc6d1b13

### How to reproduce the issue

[재현 스텝]
1. 오딘으로 접속
2. 메인 로비 - 시즌패스 클릭
3. 프리미엄+ 구매 시  시즌패스 보상이 인벤토리에 출력되지 않는 현상 확인
4. Receive all 클릭 시 시즌패스 보상이 인벤토리에 출력되지 않는 현상 확인

[Should be]
오딘에서 수령한 시즌패스 보상이 인벤토리에 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
해당 내용 pr 올려두었고, 적혀있듯이
- 클라이언트 연결이 일시적으로 끊긴 경우 해당 이슈 아직 발생할 수 있음
- 메일 레드닷 및 메일을 통해 어떤 아이템을 받았는지 확인 불가
현상이 남아있습니다
https://github.com/planetarium/NineChronicles/pull/5138

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200190-190.0.2
Android.v200190-190.0.2
iOS.v190.0.2(77)

https://github.com/planetarium/NineChronicles/assets/150774808/12a97906-70e0-4ac6-b622-02d171075631
