### ISSUE TITLE
[인벤토리] 아이템 획득 후 메일에서 수령 시 인벤토리 내 해당 아이템이 사라지는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5133]
### APV version info

v200190

### Client version info

v190.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
아이템 획득 후 메일에서 수령 시 인벤토리 내 해당 아이템이 사라지는 현상
-PC 마켓에서 장비, 음식 구매 / 모바일 마켓 구매 / 정찰보상 획득 시 발생 확인했습니다.
-아이템 획득 > 메일 수령이 빠른 시간 내에 진행한 경우 발생했습니다.
-Windows / Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/f8d2d3ee-a82e-495b-94ae-a407c36eb7ad

https://github.com/planetarium/NineChronicles/assets/150774808/872e670f-3760-46a4-b363-db6419f44e4d

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 정찰 보상 클릭
2. 정찰 보상 획득 진행
3. 인벤토리에서 정찰 보상 획득 확인 - 즉시 메일에서 수령 클릭
4. 획득한 정찰 보상이 인벤토리에서 사라지는 현상 확인

[Should be]
아이템 획득 후 메일에서 수령 시 인벤토리 내 해당 아이템이 유지되어야 합니다.

**Comment by eugene-doobu** [comment]
다른 서비스에서 관련 이슈를 처리하면서 같이 수정된것으로 보여 별도 pr없이 qa로 상태 이전되었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
PC 마켓에서 장비 구매 시 해당 현상 발생했습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200190-190.0.3

**Comment by ipdae** [comment]
mail.read호출시 타이밍따라 재현이 불규칙하게 일어나는듯한데..(블록높이가 변경된 상태면 발생하지않음) 코드 확인해보겠습니다.

**Comment by ipdae** [comment]
블록높이따라 재현이되고 안되는건 읽음처리할때 상태초기화가 남아있어서 그런것같습니다. 영상을 봤을땐 메일을 읽기전엔 이미 아이템이 들어온것처럼 반영되있어서(이것도 버근가 싶지만) mail.read에서 호출되고 있는 resetState를 전부 비활성화시키려합니다.

**Comment by ipdae** [comment]
노운이슈로 두고 다음 마일스톤에서 진행합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200190-190.0.6
Android.v200190-190.0.6
iOS.v190.0.6(80)

https://github.com/planetarium/NineChronicles/assets/150774808/84f491ff-364e-4b19-b2d3-81e513729df7
