### ISSUE TITLE
[인벤토리] 모바일 마켓 아이템 구매 후 메일에서 수령 시 인벤토리 내 해당 아이템이 사라지는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5135]
### APV version info

v200190

### Client version info

v190.0.1

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모바일 마켓 아이템 구매 후 메일에서 수령 시 인벤토리 내 해당 아이템이 사라지는 현상
-아이템 획득 > 메일 수령이 빠른 시간 내에 진행한 경우 발생했습니다.
-Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/5b0f3c14-3b30-4e81-836a-93b6e1ce8df2

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 마켓 클릭
2. 모바일 마켓 내 임의의 아이템 구매 진행
3. 인벤토리에서 구매한 아이템 획득 확인 - 즉시 메일에서 수령 클릭
4. 구매한 아이템이 인벤토리에서 사라지는 현상 확인

[Should be]
모바일 마켓 아이템 구매 후 메일에서 수령 시 인벤토리 내 해당 아이템이 유지되어야 합니다.

**Comment by eugene-doobu** [comment]
해당 내용 pr 올려두었고, 적혀있듯이
- 클라이언트 연결이 일시적으로 끊긴 경우 해당 이슈 아직 발생할 수 있음
- 메일 레드닷 및 메일을 통해 어떤 아이템을 받았는지 확인 불가
현상이 남아있습니다
https://github.com/planetarium/NineChronicles/pull/5138

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200190-190.0.2
iOS.v190.0.2(77)

https://github.com/planetarium/NineChronicles/assets/150774808/0f8c7f24-963b-4d48-9812-aae0a468f301
