### ISSUE TITLE
[튜토리얼] 신규 캐릭터 생성 후 워크샵 클릭 이후 진행이 불가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5142]
### APV version info

v200190

### Client version info

v190.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신규 캐릭터 생성 후 워크샵 클릭 이후 진행이 불가능한 현상
-Windows / Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/d57409c6-3de0-404e-b166-420d4e8c0bb2

### How to reproduce the issue

[재현 스텝]
1. 신규 캐릭터 생성 진행
2. 튜토리얼 중 워크샵 클릭
3. 워크샵 클릭 이후 진행이 불가능한 현상 확인

[Should be]
워크샵 클릭 이후 튜토리얼 진행이 가능해야 합니다.

**Comment by ipdae** [comment]
이거 혹시 항상 재연이 되시나요? 확인해봤을때 재연이 안되고 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
PC / Android / iOS에서 캐릭터 생성 후 최초 진입 시에 발생했습니다.
이 후 재접속 시에는 발생하지 않았습니다.

**Comment by eugene-doobu** [comment]
헤임달의 이미 캐릭터가 1개 있는 계정에서 190.0.2 ios에서 캐릭터 생성, 190.0.3에서 윈도우에서 시도해봤는데 재현되지 않았습니다

**Comment by QgamesGeonPyoNoh** [comment]
PC - Odin 체인에서 신규 계정 생성 후 캐릭터 생성 시 해당 현상 재현되었습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200190-190.0.3

https://github.com/planetarium/NineChronicles/assets/150774808/a83eb494-0377-47c1-9166-32285aa532ee

**Comment by eugene-doobu** [comment]
pc 테스트시 관련 로그 공유 가능할까요?

**Comment by QgamesGeonPyoNoh** [comment]
Android / iOS v200190-190.0.4에서 수정된 것 확인하였습니다. 감사합니다.
