### ISSUE TITLE
error CS0234: The type or namespace name 

### ISSUE THREAD

**Issue by huuanh1987** [planetarium/NineChronicles#516]
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/6972998/126031936-5bec5ee7-5a85-4de9-b777-393f12da8bcc.png">

Assets/_Scripts/BlockChain/ActionHandler.cs(5,16): error CS0234: The type or namespace name 'Action' does not exist in the namespace 'Nekoyume' (are you missing an assembly reference?)

Can you help me? I pull code, and run scene Game, is show error, Can you help me?

**Comment by Namyujeong** [comment]
Did you access it from the latest version of the branch? Both NineChronicles.development and submodules must be up to date.

If you give me more detailed information, I can reply. Hope the problem has already been resolved!
