### ISSUE TITLE
아레나 전투 후 인벤토리 상태 갱신

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#5164]
아레나 전투 후 인벤토리가 정상 상태로 갱신되도록 변경합니다

**Comment by sonohoshi** [comment]
테스트 좀 해보니까 eval.OutputState 안쓰고 쌩으로 GetState해서 그런거같고, OutputState 같은 Hash를 가져다가 갱신하거나 뭐 그러면 될 것 같습니다. 정상적으로 갱신이 될 때도 있고 아니기도 하고 그러네요.
