### ISSUE TITLE
Tools/Libplanet --> Delete All(Editor) - Make Genesis Block for Dev to Streaming Assets Folder.

### ISSUE THREAD

**Issue by huuanh1987** [planetarium/NineChronicles#517]
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/6972998/126054089-16fcc2cf-8357-4c01-a9d8-307aa05d8ae1.png">

Hi.
I do not see Tools/Libplanet --> Delete All(Editor) - Make Genesis Block for Dev to Streaming Assets Folder.

Can you help me ?

**Comment by area363** [comment]
Hi, there might be other issues looking at your error count but one thing I'm noticing is that you need to use the `2020.3.4f1` editor for Nine Chronicles. cc @boscohyun.

**Comment by huuanh1987** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6972998/126259920-c7c15793-9f3e-460e-aac4-abcfb7cc4b6e.png">


Hi I have change version 2020.3.4.f1.
But not see Tools/Libplanet --> Delete All(Editor) - Make Genesis Block for Dev to Streaming Assets Folder.

**Comment by boscohyun** [comment]
@huuanh1987 Sorry. I checked this now. The Unity Editor menu worked when there is no compile errors. Please check the console logs and solve all of compile errors then you can see all menus.
