### ISSUE TITLE
[월드보스] 연습모드 진입 시 간헐적으로 버튼 UI Material에 마젠타 현상이 발생합니다.

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5175]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0xD9fCe9E571ed4bdB34D3CF46A918Eb6938571a5B

### What happened?

[내용]
월드보스 연습모드 진입 시 간헐적으로 버튼 UI Material에 마젠타 현상이 발생합니다.
- Windows / Android / iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/02e4730a-2e95-490e-a5fb-e621fe5c65fd

### How to reproduce the issue

[재현 스탭]
1. 월드보스 진입
2. Practice UI 버튼 클릭
3. start 버튼 클릭
4. 보스 연출 중 skip 버튼 클릭
5. 빠른 타이밍으로 다시 Practice UI 버튼 클릭
6. start 버튼 클릭
7. 보스 연출 중 skip 버튼 클릭
8. 2 ~ 7 스탭 빠른 반복 중 영상 내 버튼 마젠타 현상 확인

[Should be]
마젠타 UI Material 수정이 필요합니다.

**Comment by eugene-doobu** [comment]
UIadd_Eff_Combination 와 같은 메터리얼의 셰이더가 고장나있는것으로 보입니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.2
Android.v200200-200.0.2
iOS.v200.0.2(83)

https://github.com/planetarium/NineChronicles/assets/150774808/584b8cd9-be0c-4602-a208-e4974d60eb1d
