### ISSUE TITLE
인벤토리와 아레나 전투준비화면의 CP표시 상이

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5176]
https://planetariumhq.slack.com/archives/CCFU9571C/p1718331603796449?thread_ts=1718329655.768649&cid=CCFU9571C

인벤토리의 아레나 섹션 CP 표시와
아레나 전투 준비화면에서 보이는 CP가 상이하다고 합니다.

**Comment by tyrosine1153** [comment]
룬 레벨 보너스 적용이 원인인 것으로 추정

https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1719305692620849
