### ISSUE TITLE
[우편함] Receive All 버튼을 통해 수령 시 이전에 받았던 아이템들까지 재 활성화 되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5179]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0xD9fCe9E571ed4bdB34D3CF46A918Eb6938571a5B

### What happened?

[내용]
우편함 Receive All 버튼을 통해 수령 시 이전에 받았던 아이템들까지 재 활성화 되는 현상

- Windows 환경에서 확인하였습니다.
- 로그 같이 첨부드립니다.

https://github.com/planetarium/NineChronicles/assets/167295117/19641783-f13d-4d55-ae19-c99ae7e232d7

### How to reproduce the issue

[재현 스탭]
1. 아이템 제작, 강화로 슬롯 1,2,3,4 채우기
2. 모래시계를 통해 슬롯 1,2,3,4 즉시 제작
3. 우편함 수령 시 Receive All 버튼으로 수령
4. 다시 아이템 제작, 강화로 슬롯 1,2,3,4 채우기
5. 모래시계를 통해 슬롯 1,2,3,4 즉시 제작
6. 우편함 확인 시 기존 Receive All로 받았던 아이템들 Receive 버튼 재 활성화 확인

[Should be]
Receive All로 이미 수령한 아이템들은 비활성화 처리가 유지되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈는 5180과 동일한 내용으로, 중복 사유로 처리토록 하겠습니다. 혼선 드려 죄송합니다.
