### ISSUE TITLE
[퀘스트] Receive All 버튼을 통해 수령 시 비활성 처리가 되지 않음

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5180]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0xD9fCe9E571ed4bdB34D3CF46A918Eb6938571a5B

### What happened?

우편함 Receive All 버튼을 통해 수령 시 이전에 받았던 아이템들까지 재 활성화 되는 현상

- Windows 환경에서 확인하였습니다.
- 로그 같이 첨부드립니다.

https://github.com/planetarium/NineChronicles/assets/167295117/4bd3de6d-7d22-4b57-92f1-b42ff4a79a93

### How to reproduce the issue

[재현 스탭]
1. 아이템 제작, 강화로 슬롯 1,2,3,4 채우기
2. 모래시계를 통해 슬롯 1,2,3,4 즉시 제작
3. 우편함 수령 시 Receive All 버튼으로 수령
4. 다시 아이템 제작, 강화로 슬롯 1,2,3,4 채우기
5. 모래시계를 통해 슬롯 1,2,3,4 즉시 제작
6. 우편함 확인 시 기존 Receive All로 받았던 아이템들 Receive 버튼 재 활성화 확인

[Should be]
Receive All로 이미 수령한 아이템들은 비활성화 처리가 유지되어야 합니다.

**Comment by OHHyungGeun** [comment]
[log.zip](https://github.com/user-attachments/files/15968883/log.zip)

**Comment by QgamesGeonPyoNoh** [comment]
퀘스트 보상의 경우는 Receive All 버튼을 탭해도 보상이 비활성화처리되고 있지 않습니다. 하기 영상 참고 부탁드리겠습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/df846de1-11cb-41ab-8554-05242a11857c

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/issues/5179 와 동일 이슈 아닐까요?

**Comment by ipdae** [comment]
네 제보내용은 중복이슈로 보입니다. 이 이슈는 @QgamesGeonPyoNoh 님이 코멘트로 남기신 메일수령관련내용으로 변경하면 될것같습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200190-190.0.6
Android.v200190-190.0.6
iOS.v190.0.6(80)
