### ISSUE TITLE
[마켓] 음식 여러개 판매 등록 시 가격의 단가가 소수점 포함 제한에 걸려 판매할 수 없는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5182]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Windows

### detailed device info

Windows 10

### account address info

0xD9fCe9E571ed4bdB34D3CF46A918Eb6938571a5B

### What happened?

음식 여러개 판매 등록 시 가격의 단가가 소수점 포함 제한에 걸려 판매할 수 없는 현상이 발생합니다.

첨부된 스크린샷 확인 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/5f204380-1d2a-40c8-bfaa-9c6d0b4bdcb8)

### How to reproduce the issue

[재현 스탭]
1. 3개 이상의 음식 준비
2. quantity 3 설정
3. 개당 가격이 소숫점으로 계산되게끔 가격 설정
4. 등록 불가 확인

[Should be]
모래시계나 ap포션처럼 소수점을 포함하여 등록할수 있게 수정 되어야 합니다.

**Comment by jaeho0103** [comment]
AP포션과 모래시계등의 Material 은 소수점 가격으로도 1개의 거래가 되지만, 얘는 여러개를 등록할경우 1개씩 여러개의 매물로 등록되는 형태로 당분간은 소수점 지원 계획이 없는 상태입니다.

**Comment by OHHyungGeun** [comment]
기획 내용 확인되었으므로 이슈 닫도록 하겠습니다.
