### ISSUE TITLE
[마켓] buy sell 탭 이동 시 캐릭터 선택 씬이 순간 출력되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5183]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Windows

### detailed device info

Windows 10

### account address info

0xD9fCe9E571ed4bdB34D3CF46A918Eb6938571a5B

### What happened?

[내용]
buy sell 탭 이동 시 캐릭터 선택 씬이 순간 출력되는 현상이 발생합니다.
첨부된 영상 확인 부탁드립니다.

https://github.com/planetarium/NineChronicles/assets/167295117/1cc02284-2676-41a0-ae4f-2ccead78282f

### How to reproduce the issue

[재현 스탭]
1. 마켓 진입
2. 우측 상단 햄버거 메뉴에서 캐릭터 선택씬 이동 클릭
3. 로비로 이동됨 확인
4. 마켓 진입
5. buy -> sell 탭 이동
6. 순간 캐릭터 선택씬 출력 확인

[Should be]
플레이에 지장은 없지만, 씬이 꼬여 익셉션이 발생할 가능성이 높아 기획의도에 맞는 보수가 필요합니다.

**Comment by eugene-doobu** [comment]
캐릭터 선택씬 이동 클릭을 했는데 로비로만 가는게 이상동작이 아닐까 하는 생각에 코멘트 남겨둡니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.
하기 이슈도 함께 종료하도록 하겠습니다.

[상점] 상점에서 캐릭터 선택 버튼 클릭 시 메인 로비로 이동하는 현상
https://github.com/planetarium/NineChronicles/issues/4682

[테스트 환경]
Windows.v200200-200.0.2

https://github.com/planetarium/NineChronicles/assets/150774808/b0a44536-e3fe-498e-9207-04546f2481ca
