### ISSUE TITLE
[시즌패스] 시즌패스 8 구매 불가 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5185]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Android, iOS

### account address info

0xf25ee3792Dba22aED619602cafc6C1fC5F645f47

### What happened?

[내용]
시즌패스 8 구매버튼 동작하지 않아 구매불가 현상
- Android / iOS M, K 전부 발생

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/ec002497-3760-4356-add3-0dbf9afad58e)

### How to reproduce the issue

[재현 스탭]
1. 로비
2. 우측 시즌패스 아이콘 탭
3. 좌측 프리미엄 '헤제하기'
4. 프리미엄, 프리미엄+ 둘 다 버튼 상호작용 없고 구매 불가한 것 확인

[Should Be]
프리미엄 구매가 가능해야 합니다.

**Comment by jaeho0103** [comment]
안드로이드 스토어에 상품등록하고 구매 가능한거 체크했습니다. 확인 부탁드리겠습니다.
애플은 추가했지만 심사 통과후 구매 가능하셔서 목요일 이후에 체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
답변 감사드립니다.
목요일 이후에 다시 체크해보도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/ef379a78-dc81-43b6-9c6f-52203abd5f41)
![Image](https://github.com/planetarium/NineChronicles/assets/150774808/a24852c9-0310-4938-9ace-d5303ab11b42)

버전코드 올려 주시어 추가 체크 진행하였으며, K 190.0.5에서도 동일현상 유지되고 있어 이미지 첨부 드립니다. 참고 부탁드립니다. 감사합니다.

**Comment by jaeho0103** [comment]
죄송합니다. 변경한것과 다른 부분에 추가 이슈 있는거 체크해서 190.0.5에서 구매가능 다시 확인했습니다.
한번더 안드로이드 에서 체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
V190.0.6 구글 게시된 버전으로 정상 구매 / 수령 가능한 점 확인하였습니다. 대응 감사드립니다.
