### ISSUE TITLE
[마켓] 일부 상품 내 '보유' 텍스트로 인해 정보 전달이 혼란스러운 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5187]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Android, iOS

### detailed device info

iOS 17.4 Android OS 8.1

### account address info

0xf25ee3792Dba22aED619602cafc6C1fC5F645f47

### What happened?

[내용]
크리스탈, 황금 잎사귀 룬 등 상점에 '보유'라고 디스플레이되어있는 텍스트와 표기된 수치가 다른 현상입니다.
현재상황 / 보유 : (지급 갯수)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/4c9e8c08-0fe6-4ce3-9006-a54d1d56579c)

### How to reproduce the issue

[재현 스탭]
1. 로비
2. 마켓
3. 핫 썸머 패키지 정보 열람
4. 상품 구매 시 크리스탈 지급 갯수 10M 확인
5. 현재 테스트 계정 크리스탈 보유량 449.03K 확인
6. 전시된 상품 중 크리스탈 아이콘 탭
7. 보유 : 10M 으로 노출되는 것 확인

[Should be]
두 정보는 일치해야 합니다.
ex case 1 - 보유 :  449.03K
ex case 2 - 지급 : 10M

**Comment by jaeho0103** [comment]
네 이부분은 known issue 로 두고 다음 버전에서 대응하도록 하겠습니다.
