### ISSUE TITLE
[마켓] IAP 구매 시점에 동기화가 이루어지지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5188]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Android, iOS

### detailed device info

iOS 17.4 Android OS 8.1

### account address info

0xf25ee3792Dba22aED619602cafc6C1fC5F645f47

### What happened?

[내용]
마켓에서 IAP 구매 후 아무리 기다려도 구매 정보를 동기화하는 과정이 발생하지 않아 재화량이 그대로이며, 별도의 피드도 없는 현상입니다.

재접속 시 재화가 동기화 됩니다.

동일 계정으로 디바이스 2에 접속 / IAP 구매 후 30여분을 방치 / 하기는 그대로 방치 / 상기는 재접속한 상황입니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/99736da4-e509-4e16-a89c-7f8ffd503485)

### How to reproduce the issue

[재현스탭[
1. 로비
2. 마켓
3. IAP 구매
4. 30분까지 대기
5. 보유 재화 변동없음 확인

[Should be]
상품 구매 후 재접속하지 않아도 재화량 증가 등의 주도적인 피드백이 있어야 합니다.

**Comment by jaeho0103** [comment]
제가 190.0.5 기준 2회 테스트해봤을때는 IAP 구매 안내 메일이 읽은 상태로 오구, 재화가 증가되어있는 상태였습니다.

**Comment by QgamesGeonPyoNoh** [comment]
Android / iOS 190.0.6 버전에서 발생하지 않는 부분 확인하였습니다. 대응 감사드립니다.
