### ISSUE TITLE
[마켓] IAP 레벨달성 패키지 100LV 지급 품목 중 황금 잎사귀 룬이 지급되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5189]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Android, iOS

### detailed device info

iOS 17.4 Android OS 8.1

### account address info

0xf25ee3792Dba22aED619602cafc6C1fC5F645f47

### What happened?

[내용]
레벨달성 패키지 100LV 지급 품목 중 황금 잎사귀 룬이 지급되지 않는 현상입니다.
구매 전 45개였으며, 구매 후 8개를 지급받지 못하였습니다.

테스트는 상기 계정으로 6월 25일 오후 11:54 진행되었습니다.

<1회성 구매상품으로 재구매 테스트가 쉽지 않아 이슈 먼저 등록합니다, 영상 추가확보되는대로 업로드토록 하겠습니다>

### How to reproduce the issue

[재현 스탭]
1. 로비
2. 마켓
3. 레벨 100레벨 이상 달성
4. 레벨달성 패키지 100LV 지급 목록에 황금 잎사귀 룬 8개 포함 확인
5. 레벨달성 패키지 100LV 구매
6. 지급 품목 수령 확인 - 황금 잎사귀 룬 8개 누락

**Comment by ipdae** [comment]
#5190 과 중복이슈로 보여 닫습니다.
