### ISSUE TITLE
[마켓] IAP 레벨 달성 패키지 100lv 지급 품목 중 황금 잎사귀 룬 8개가 누락된 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5190]
### APV version info

v200190

### Client version info

v190.0.4

### Device

Android, iOS

### detailed device info

iOS 17.4 Android OS 8.1

### account address info

0xf25ee3792Dba22aED619602cafc6C1fC5F645f47

### What happened?

[내용]
IAP 레벨 달성 패키지 100lv 지급 품목 중 황금 잎사귀 룬 8개가 누락된 현상입니다.
해당 상품이 1회성 구매 품목으로, 영상 확보는 추가테스트 후 업로드토록 하겠습니다.

해당 테스트는 6월 25일 오후 11:54경 진행되었습니다.

### How to reproduce the issue

[재현 스탭]
1. 로비
2. 마켓
3. 레벨 달성 패키지 100lv 지급 목록에 암흑 잎사귀 룬 8개 확인
4. 레벨 달성 패키지 100lv 구매 후 수령 확인
5. 암흑 잎사귀 룬 8개 누락된 것 확인

[Should be]
IAP 구매 시 디스플레이된 상품정보와 동일하게 수령되어야 합니다.
레벨 달성 패키지 100lv 구매 시 암흑 잎사귀 룬 8개를 받거나, 해당 상품이 지급 대상에 디스플레이 되지 않도록 조치해야 합니다.

**Comment by jaeho0103** [comment]
제 계정으로 2회 테스트했을때는 정상적으로 지급 되는게 확인되었습니다.
다시 체크해주시면 감사하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
iOS / Android OS 
190.0.4 ~190.0.5 버전 전부 재구매 시 위 현상 발생하지 않음을 확인하였습니다.

해당 이슈 처리 및 모니터링 / 추후 재발생 시 재보고드릴 수 있도록 하겠습니다.

감사합니다.




https://github.com/planetarium/NineChronicles/assets/150774808/4f3ce22b-8e2c-4244-b457-1568ad2d56ee
