### ISSUE TITLE
[랭킹] 오딘 World, Crafting, Equipment 리스트가 출력되지 않는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5201]
### APV version info

v200190

### Client version info

v190.0.6

### Device

Windows, Android, iOS

### account address info

0xD9fCe9E571ed4bdB34D3CF46A918Eb6938571a5B

### What happened?

오딘서버 내 랭킹 World, Crafting, Equipment 리스트가 출력되지 않는 현상이 발생합니다.

헤임달 서버에선 정상 출력 됩니다.

스크린샷 참고 부탁드립니다.

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/de6b693d-7cd2-49b0-99d6-95e6df25c309)

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/4d4c60da-407b-4f03-992f-282d37da1d09)

![Image](https://github.com/planetarium/NineChronicles/assets/167295117/916459c2-6ce7-4873-bacc-0314dd771d96)

### How to reproduce the issue

[재현 스탭]
1. 오딘 환경 접속
2. 우측 상단 메뉴 중 랭킹 진입
3. World, Crafting, Equipment 탭 로드되지 않는 현상 확인

[Should be]
오딘 서버 내 World, Crafting, Equipment 리스트가 정상 출력 되어야 합니다.

**Comment by ipdae** [comment]
인터널 db의 마이그레이션이 필요해서 작업중입니다. 다른 이슈 먼저 확인해주시고 나중에 다시 확인 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200190-190.0.6
Android.v200190-190.0.6
iOS.v190.0.6(80)


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/450ab390-2dc1-4b99-ae33-859a85863f21)
