### ISSUE TITLE
인벤토리에서 그리모어 정렬이 안됨

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#5205]
- 그리모어 보유한 상태일 때, 전투 준비화면에서 왼쪽 리스트의 그리모어 아이콘 우상단에 초록색 화살표 떠야하는데 안뜨고 있습니다. 제일 좋은 그리모어 맨 위로 올려주는 작업도 해야함.
- 그리모어는 추천장비 1종이 인벤토리 맨 위로 소팅되지 않습니다.

**Comment by tyrosine1153** [comment]
lib9c의 `GetAvailableEquipmentSlots` 메서드 (UnlockHelper.cs)에 Grimoire가 추가되어있지 않음.

**Comment by tyrosine1153** [comment]
GetAvailableEquipmentSlots 라는 lib9c의 메서드에 Grimoire가 추가가 안되었던 건데, 
해당 메서드는 GameConfig의 Obsolete되어있는 값을 보고 있었고, 해당 메서드를 참조하고 있는 메서드 모두 클라이언트에서만 쓰길래 lib9c에서 지우고 모두 클라이언트로 옮겨왔습니다.
