### ISSUE TITLE
AirBridge 버전 확인 

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#5224]
## 현재 프로젝트에 적용된 버전

Dependencies.xml
```
<iosPod name="AirBridge" version="1.33.4"/>
```

iOS SDK 1.35.1미만에는 알려진 이슈가 있습니다. 원활한 SDK 사용을 위해 1.35.1이상을 사용해주세요.

참고
https://help.airbridge.io/ko/developers/ios-sdk

**Comment by jonny-jeahyunchoi** [comment]
이거 airbridge 버전업데이트해야하는 이슈로 이어 진행하는것인지 체크필요합니다
