### ISSUE TITLE
인벤토리 정렬 기준 조사 및 개선

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#5226]
https://www.notion.so/planetarium/eadfdb1d3d6e4830b8a6899422f4c073

- 기본 인벤토리 리스트
    - 재료 탭에서 최상위 리스트 추가
        - 현행 - AP포션, 모래시계, 더스트
        - 변경 - AP포션, 모래시계, 더스트, 해머
- 강화시 재료 리스트
    - 현행 - 서브타입 안에서 무슨순선지 모르겠음;;
    - 변경 - 서브타입 안에서 희귀도순 1차 내림정렬후에, 같은 1차 정렬안에서 CP순 2차 내림정렬
- 샵 판매 대상 리스트
    - 현행 - 판매 가능 상태와 상관없이 리스트 하위차순
    - 변경 - 판매가능과 불가능을 먼저 그룹핑하여 판매 불가는 하단으로 다 미룸

**Comment by tyrosine1153** [comment]
이 이슈와 중복되는 것 같은데 일단 선민님께 넘기는게 좋을까용?
- https://github.com/planetarium/NineChronicles/issues/4655

**Comment by sonohoshi** [comment]
> 이 이슈와 중복되는 것 같은데 일단 선민님께 넘기는게 좋을까용?
> 
> * [업그레이드 장비 리스트에서 2차 정렬 CP 내림차순으로 조정 #4655](https://github.com/planetarium/NineChronicles/issues/4655)

outdated 같은데 그냥 코멘트 남겨놓고 close하면 될 것 같습니다. 제가 할게요

**Comment by sonohoshi** [comment]
상점 빼고 다 작업은 됐는데... 상점에서 쓰는 아이템 리스트가 기존 인벤토리와 완전히 같은 코드+모듈을 쓰고 있어서 정렬 기준을 바꾸려면 용도별로 바꿀 수 있게 분리하는게 필요한 상태입니다. 지금 우선순위와 일정으론 어려울 것 같다는 생각이 들고...
