### ISSUE TITLE
[UI] 시스템 점검 중 팝업의 키 백업 버튼이 동작하지 않는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5232]
### APV version info

메인넷_K_v200190

### Client version info

v190.0.6

### Device

Android

### detailed device info

Android12

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
시스템 점검 중 팝업의 키 백업 버튼이 동작하지 않는 현상
-K버전 Andorid 환경에서 확인햇습니다.
-M버전은 현재 메인넷 클라이언트 설치가 어려워 확인하지 못했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/71df1435-8247-4758-bfe8-3077d41c3fdf

### How to reproduce the issue

[재현스텝]
1. 점검 진행 중 앱 실행
2. 시스템 점검 중 팝업 출력
3. 키 백업 버튼 클릭 시 동작하지 않는 현상 확인

Should be
키 백업 버튼이 정상적으로 동작해야 합니다.

**Comment by sonohoshi** [comment]
처음 시작할때 로그인된 계정 정보로 찾게해놨는데, 저 팝업이 뜨는 시점에 로그인이 안돼있어서 생기는 문제였고 해결해서 PR 올리겠습니다...
