### ISSUE TITLE
튜토리얼전투시 어드벤처보스 분기처리 정상적이지않는문제

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#5233]
![Image](https://github.com/planetarium/NineChronicles/assets/138189475/863c74af-4492-44f6-8a4b-c50266d71858)

https://planetariumhq.slack.com/archives/C011716SDTM/p1719894672168449

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)

https://github.com/planetarium/NineChronicles/assets/150774808/afab93f0-2b15-4dc9-819f-f1a033100ff9
