### ISSUE TITLE
PayCost제거

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#5235]
사용하지 않는 PayCost 메서드를 제거합니다.

-> Action의 확장메서드로 구현

과거 블록 랜더 개선 프로젝트로 시동 걸면서 구멍만 내두었던 것들

**Comment by jonny-jeahyunchoi** [comment]
@boscohyun @eugene-doobu 해당이슈 진행여부 확인 부탁드립니다~

**Comment by boscohyun** [comment]
아직 진행하지 못했습니다.😅

**Comment by moreal** [comment]
@boscohyun @eugene-doobu GitHub 코드 검색 기능으로 `PayCost`로 살펴보았을때 모두 액션의 확장 메서드로 구현하고 있는 것으로 보이는데 해결된 부분일까요? 혹은

**Comment by eugene-doobu** [comment]
@moreal 제가 이해한건 payCost메서드가 구현하려다 폐기된 것으로 알고있어서 해당 메서드 자체를 지우는 것으로 알고 있습니다

**Comment by moreal** [comment]
> @moreal 제가 이해한건 payCost메서드가 구현하려다 폐기된 것으로 알고있어서 해당 메서드 자체를 지우는 것으로 알고 있습니다

@eugene-doobu 확인 감사합니다 🙇🏻‍♂️ 그러면 @boscohyun 님께 확인 받고 스프릔트 때 들고 가겠습니다 🏃🏻

**Comment by boscohyun** [comment]
@moreal 네 단순히 관련한 부분 삭제하는 것만으로도 충분할 거예요. 확인 감사합니다.
