### ISSUE TITLE
[시즌패스] 시즌패스 클릭 시 Failed to Connect 메세지가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5236]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌패스 클릭 시 Failed to Connect 메세지가 출력되는 현상
-Windows 환경에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/908d3a3f-1b66-4458-ba0b-ad2a94813d4a)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 시즌패스 아이콘 클릭
2. 시즌패스 클릭 시 Failed to Connect 메세지가 출력되는 현상 확인

[Should be]
시즌패스 클릭 시 시즌패스 화면이 출력되어야 합니다.

**Comment by U-lis** [comment]
남은 날짜가 표기되는 것으로 보아 현재 season pass 의 상태는 받아오는 것 같은데, 저 주소로 기록 한번 찾아보고 제쪽에서도 재현해보겠습니다.

**Comment by U-lis** [comment]
음.... 제쪽에서는 서비스 콜도 정상이고, 이리저리 해봐도 재현이 안 되는데요...
혹시 다시 한번 테스트 해봐주시고, 같은 현상이 재발하면 windows 기준 `Player.log` 파일을 같이 첨부해주실 수 있나요? 
`%appdata%\..\LocalLow\Planetariumlabs\NineChronicles\Player.log` 에 있을겁니다.
mobile 이라면 해당 시점의 debug console 에 빨간색 에러 메세지 같이 첨부해주시면 감사드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 해당 이슈 발생 중에 있어 로그 파일 첨부드립니다.
모바일에서는 발생하지 않고 있습니다.
[Player.log](https://github.com/user-attachments/files/16065225/Player.log)

**Comment by jonny-jeahyunchoi** [comment]
런처에서 실행인자로 플레닛레지스트리를 전달주지않아서 PC에서만 발생하는것으로 확인되었고 런처 수정되어 재배포될예정입니다. https://github.com/planetarium/9c-launcher/actions/runs/9758092340

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.1
![image](https://github.com/planetarium/NineChronicles/assets/150774808/c254f0d6-0089-4d77-90c1-5a896f4dc4ac)
