### ISSUE TITLE
[정찰보상] 정찰 보상 클릭 시 팝업이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5237]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
정찰 보상 클릭 시 팝업이 출력되지 않는 현상
-Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/3c7c32bc-fc79-4030-8eb0-543bf1638b7b

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 -  정찰보상 아이콘 클릭
2. 정찰 보상 클릭 시 팝업이 출력되지 않는 현상 확인

[Should be]
정찰보상 아이콘 클릭 시 정찰보상 팝업이 출력되어야 합니다.

**Comment by ipdae** [comment]
첨부된 영상을 봐선 서비스에 접속이 안된것같습니다. 인터널 서비스 상황 확인해보겠습니다.

**Comment by ipdae** [comment]
@QgamesGeonPyoNoh 서비스 설정에 문제가 있어 정상화 시켜놨습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.1
Android.v200200-200.0.1
iOS.v200.0.1(82)

https://github.com/planetarium/NineChronicles/assets/150774808/2d17fd49-41c6-44ee-a60d-fa09846ed4be

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재발생 확인했습니다.
발생 당시 Log 파일 공유드립니다.
[Log.zip](https://github.com/user-attachments/files/16508617/Log.zip)


[테스트 환경]
Windows.v200210-210.0.5
Android.v200210-210.0.5
K.Android.v200210-210.0.5
K.iOS.v210.0.5(43)

Uploading 이슈.mp4…

**Comment by ipdae** [comment]
네트워크 설정 과정에 문제가 있었던것같고 수정해뒀습니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 해당 현상 동일하게 발생하는 것을 확인했습니다.
다음 빌드에서 수정되는 부분인지 문의드립니다.
해당 이슈 발생 시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16517233/Log.zip)

[테스트 환경]
Windows.v200210-210.0.5
Android.v200210-210.0.5
iOS.v210.0.5(100)
K.Android.v200210-210.0.5
K.iOS.v210.0.5(43)

https://github.com/user-attachments/assets/f7c868fa-a474-4713-a217-de6500e43aca

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.0
Android.v200220-220.0.0
iOS.v220.0.0(101)
![image](https://github.com/user-attachments/assets/de0307ee-8c3d-4627-9cf0-8b058b715c25)

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 헤임달 메인넷에서 발생 확인되었습니다.
확인 부탁드립니다.

[테스트 환경]
메인넷.Windows.v200230-230.0.8
메인넷.Android.v200230-230.0.8
메인넷.iOS.v230.0.8(115)


https://github.com/user-attachments/assets/2a825cc4-3644-4697-82e2-9f5835913986

**Comment by ipdae** [comment]
헤임달 노드 문제가 원인으로 보입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.1.1
Android.v200230-230.1.1
iOS.v230.1.1(117)

![Image](https://github.com/user-attachments/assets/37eb4328-6f76-4610-bca3-03ee098ebe55)
