### ISSUE TITLE
[어드벤쳐 보스] 헤임달에서 어드벤쳐 보스의 남은 시간이 최초 확인 시 마이너스 블록으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5238]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
헤임달에서 어드벤쳐 보스의 남은 시간이 최초 확인 시 마이너스 블록으로 출력되는 현상
-Windows, Android, iOS 기기에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/3260e9b1-0881-48f6-86cc-49085397aa8e

### How to reproduce the issue

[재현 스텝]
1. 헤임달 체인 접속
2. 메인 로비 - 어드벤쳐 클릭
3. 어드벤쳐 보스의 남은 시간이 최초 확인 시 마이너스 블록으로 출력되는 현상 확인

[Should be]
어드벤쳐 보스의 남은시간 최초 확인 시 현재 남은 시간이 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
200.0.2 수정 되었습니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.2
Android.v200200-200.0.2
iOS.v200.0.2(84)

https://github.com/planetarium/NineChronicles/assets/150774808/0d33c92e-5ee3-46da-8a27-07174b7decbc
