### ISSUE TITLE
[어드벤쳐 보스] 현상금 추가 팝업 내 추가 횟수 텍스트가 두 줄로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5244]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
현상금 추가 팝업 내 추가 횟수 텍스트가 두 줄로 출력되는 현상
-Android, iOS 기기에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/20766440-e70b-442b-be87-340915e7371e)

### How to reproduce the issue

[재현 스텝]
1. 모바일 기기 접속
2. 메인 로비 - 어드벤쳐 클릭
3. 어드벤쳐 보스 - 현상금 추가 팝업 확인
4. 현상금 추가 팝업 내 추가 횟수 텍스트가 두 줄로 출력되는 현상 확인

[Should be]
현상금 추가 팝업 내 추가 횟수 텍스트가 한 줄로 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
기기 해상도 공유 부탁드립니다~!

**Comment by QgamesGeonPyoNoh** [comment]
Galaxy Note 20 Ultra - 1440 x 3088 pixels, 19.3:9 ratio
iPhone 12 - 1170 x 2532 pixels, 19.5:9 ratio
해당 현상 발생한 기기 해상도 공유드립니다.

**Comment by jonny-jeahyunchoi** [comment]
에디터 시뮬레이션에서는 현상 재현되지 않지만, 별개로 해당 텍스트 가로 길이가 너무 작게 세팅되어있는것같아서 추가여유분을 두는식으로 조정하겠습니다~! cc @boramqo83

**Comment by jonny-jeahyunchoi** [comment]
200.0.2 수정되었습니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.2
Android.v200200-200.0.2
iOS.v200.0.2(83)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/fe94a51c-2efc-453c-b632-948ff30e1ee0)
