### ISSUE TITLE
[룬] 어드벤쳐 보스 룬 조각 팝업 출력 시 아이템 이름이 키값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5245]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 룬 조각 팝업 출력 시 아이템 이름이 키값으로 출력되는 현상
-Windows, Android, iOS 기기에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/8034890b-2b51-41b2-9a56-e6055db4f6e5)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬 클릭
2. 어드벤쳐 보스 룬 클릭
3. 재료 항목 내 어드벤쳐 보스 룬 조각 클릭
4. 어드벤쳐 보스 룬 조각 팝업 출력 시 아이템 이름이 키값으로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 룬 조각 팝업 출력 시 아이템 이름이 텍스트로 출력되어야 합니다.

**Comment by NineSyu** [comment]
나오지 않던 L10n 추가했습니다.
재접속 후 테스트하시면 정상적으로 출력될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.2
Android.v200200-200.0.2
iOS.v200.0.2(83)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/f24a7d87-fa3c-46f3-acdc-f64678c4694e)
