### ISSUE TITLE
[룬] 어드벤쳐 보스 룬 조각이 거래 가능으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5246]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 룬 조각이 거래 가능으로 출력되는 현상
-Windows, Android, iOS 기기에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/a1df0ef8-6a81-4c16-8573-2a16e18ef426)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 - 룬 조각 탭 클릭
2. 어드벤쳐 보스 룬 조각 클릭
3. 어드벤쳐 보스 룬 조각이 거래 가능으로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 룬 조각이 거래 불가로 출력되어야 합니다.

**Comment by jaeho0103** [comment]
어드벤쳐 보스 룬조각은 거래가능 재화로 기획되어있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
기획 의도로 확인되어 이슈 종료하도록 하겠습니다.

[테스트 환경]
Windows.v200200-200.0.1
Android.v200200-200.0.1
iOS.v200.0.1(82)
