### ISSUE TITLE
[정찰보상] 정찰 보상 단축 이벤트가 적용되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5250]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
정찰 보상 단축 이벤트가 적용되지 않는 현상
-Windows, Android, iOS 기기에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/dda2f7df-1574-43a7-a771-0b91b4415677)

### How to reproduce the issue

[재현 스텝]
1. 메인로비 - 정찰 보상 클릭
2. 정찰 보상 단축 이벤트가 적용되지 않는 현상 확인

[Should be]
정찰 보상 시간이 6시간으로 단축되어야 합니다.

**Comment by ipdae** [comment]
인터널 정책 테이블 업데이트가 안되있던 문제로 반영해뒀습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.2
Android.v200200-200.0.2
iOS.v200.0.2(83)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/c0342cc5-bf6d-44bb-aa81-834c6cdaa4de)
