### ISSUE TITLE
[정찰보상] 정찰 보상에서 골든 더스트가 획득되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5254]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
정찰 보상에서 골든 더스트가 획득되는 현상
-Windows, Android, iOS 기기에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/05a71527-39c8-423b-8b24-91a9e52e2d2e)

### How to reproduce the issue

[재현 스텝]
1. 메인로비 - 정찰 보상 클릭
2. 정찰 보상에서 골든 더스트가 획득되는 현상

[Should be]
정찰 보상에서 골든 더스트가 획득되지 않아야 합니다.

**Comment by ipdae** [comment]
인터널 정책 테이블 업데이트가 안되있던 문제로 반영해뒀습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.2
Android.v200200-200.0.2
iOS.v200.0.2(83)


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/19e00cc9-b2df-42e6-adf7-0d3dff2934f7)
