### ISSUE TITLE
[워크샵] 소환 화면에서 돋보기 버튼의 아이콘이 i버튼으로 노출되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5257]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
소환 화면에서 돋보기 버튼의 아이콘이 i버튼으로 노출되는 현상이 발생합니다.
- 그리모어, 루비 아우라, 루비 룬, 골든 아우라, 골든 룬, 노멀 아우라 소환에서 모두 i버튼으로 노출되는 것을 확인했습니다.
- Windows, Android, IOS 기기에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/2e13ea19-5330-4f8c-b7e8-660e9547d37f

### How to reproduce the issue

[재현스텝]
1. 메인로비 - 워크샵 - 소환 버튼 터치
2. 소환 화면에서 돋보기 버튼의 아이콘이 i 버튼으로 노출되는 현상 확인

[Should be]
소환 화면에서 돋보기 버튼의 아이콘이 돋보기 이미지로 노출되어야 합니다.

**Comment by boramqo83** [comment]
아. 예리하시군요.
아이버튼으로 이번에 수정한 것 맞습니다.
해당 잇슈는 완료로 처리해 주세요.

**Comment by OHHyungGeun** [comment]
소환 화면에서 돋보기 버튼의 아이콘이 아이버튼으로 변경된 부분 확인하였습니다.
- 그리모어, 루비아우라, 루비룬, 골든아우라, 골든룬

[테스트 환경]
Windows.v200071-200.0.2
Android.v200071-200.0.2
iOS.v200.0.2(83)
