### ISSUE TITLE
[런쳐] Revoke 화면에서 3번째 이후 키 선택이 불가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5259]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Revoke 화면에서 3번째 이후 키 선택이 불가능한 현상
-Windows 기기에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/bef5e4f4-fcd2-45ed-836a-8b057987764e

### How to reproduce the issue

[재현 스텝]
1. 런쳐 실행
2. Forgot Passward? - Got no key? 선택
3. Revoke 화면에서 키 선택상자 클릭
4. 3번째 이후 키 선택이 불가능한 현상 확인

[Should be]
Revoke 화면에서 3번째 이후 키 선택이 가능해야 합니다.

**Comment by Akamig** [comment]
음..... 일단 저희쪽에서 다시 재현해보던 과정에서 재현에 실패하고, 정상적으로 키 선택이 되는걸 확인했는데 한번 다시 테스트해보시겠어요? 최근데 특별히 수정된 사항도 없습니다.

**Comment by QgamesGeonPyoNoh** [comment]
Revoke 화면에서 세번째 키 중간 부분 아래 부분부터는 클릭이 되지 않고 있습니다.
그리고 이전에 발생한 이력이 있는 이슈로 확인됩니다. (Asana 폐쇄로 인해 확인 불가)

[테스트 환경]
Windows.v200200-200.0.2

https://github.com/planetarium/NineChronicles/assets/150774808/181d6f8c-c676-43f8-b97a-de27f44213b6

**Comment by Akamig** [comment]
아, 이전에 발생했었던 이슈라면 원인을 찾은것 같습니다. 감사합니다.

**Comment by jaeho0103** [comment]
고치던 중이라고 하셨어서 In Progress 에 넣어둡니다.
