### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 푸시 알림 텍스트가 키 값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5261]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Android

### detailed device info

Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 푸시 알림 텍스트가 키 값으로 출력되는 현상
-Android 기기에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/ea6e12de-d9ae-4f51-8771-fccb44e89d2a)

### How to reproduce the issue

[재현 스텝]
1. 어드벤쳐 보스 푸시 출력
2. 푸시 알림 확인 시 텍스트가 키 값으로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 푸시 알림 확인 시 텍스트로 출력되어야 합니다.

**Comment by NineSyu** [comment]
나오지 않던 L10n 추가했습니다.
재접속 후 테스트하시면 정상적으로 출력될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200200-200.0.2

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/3fef1373-adaf-43f8-837e-ebcdd0e66ecb)
