### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 진입 시 로딩이 지속되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5262]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 진입 시 로딩이 지속되는 현상
-어드벤쳐 보스 오픈 상태 출력에도 시간이 오래 걸리고 있습니다.
-발생 당시 로그 파일 첨부 드립니다.
-Windows, Android, iOS 에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/bf73dfc7-c822-4620-96f3-708b557c03f1

[v200.0.1.zip](https://github.com/user-attachments/files/16068794/v200.0.1.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 어드벤쳐 보스 오픈 상태 클릭
3. 어드벤쳐 보스 진입 시 로딩이 지속되는 현상 확인

[Should be]
어드벤쳐 보스 진입 시 로딩이 완료 되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
200.0.2 수정되었습니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.2
Android.v200200-200.0.2
iOS.v200.0.2(83)

https://github.com/planetarium/NineChronicles/assets/150774808/b7988001-de2e-4c2e-a6c5-0944cdab461c
