### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 상태 출력 지연 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5263]
### APV version info

v200200

### Client version info

v200.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 상태 출력 지연 현상
-Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/1060aebc-fb62-4c68-914f-2b8759a40ee8

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 어드벤쳐 보스 상태 확인
3. 어드벤쳐 보스가 오픈되어 있으나 상태 출력 지연 현상 확인

[Should be]
어드벤쳐 보스의 상태가 즉시 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
200.0.2 수정되었습니다~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.2
Android.v200200-200.0.2
iOS.v200.0.2(83)

https://github.com/planetarium/NineChronicles/assets/150774808/b30352a9-8d20-4e46-8545-36c59d8c9bbe
