### ISSUE TITLE
운영보상 2번째 참가자 기대 보상 아이템 표시 안되는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5280]
최초 운영참가자 말고 2번째 이후의 참가자가 자신의 첫 운영보상을 제출할때 기대 보상 아이템부분이 비어있는 현상

기대동작 : 금액을 입력하면 해당 금액에 따른 현재기준으로 받게될거라 예상되는 아이템들이 표시되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
첫운영보상진행시 참여정보가 없어서 기대보상계산이 스킵되는 문제로 보임.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)

https://github.com/planetarium/NineChronicles/assets/150774808/bc7745c9-52ea-4e43-9e29-1d1ae29cdb1e
