### ISSUE TITLE
크리티컬 룬에 스탯의 소수점 부분이 표시되지 않는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5281]
이번에 추가된 10035 critical 룬이 기본스탯과 강화화면 등에서 소수점 스탯이 보이지 않는 현상

**Comment by tyrosine1153** [comment]
관련 스레드 : 
https://planetariumhq.slack.com/archives/C011716SDTM/p1719987342323779

CharacterStats의 _statMap에서 CRI의 자료형이 decimal임에도 반올림된 정수화된 값으로 stat value를 갖고있음.
그래서 AvatarInfoPopup 과 LoginDetail의 아바타 스탯 ui에서는 CRI를 정수로 표시할 것 같습니다.
이외의 룬 툴팁, 룬 강화화면은 정상으로 수정 했습니다.

**Comment by jaeho0103** [comment]
@NineSyu 님 체크하고 이슈 done 처리 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 CRI 룬 스탯이 소수점 형태가 출력되지 않는 형상 발생하고 있습니다.
확인 부탁드립니다.

-제작 전 스탯 출력


![Image](https://github.com/planetarium/NineChronicles/assets/150774808/fa853aa6-f555-43fd-983a-b80dadeef10d)

-인벤토리 내 스탯 출력

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/ce229aa0-50b9-474e-88a9-b17d4bc65dd5)

-제작 / 강화 결과 화면 내 스탯 출력
해당 부분은 스크린 샷 확보 시 전달 드리겠습니다.

**Comment by NineSyu** [comment]
머지 후 인터널에서 정상적으로 표시되는 것 확인했습니다.
재접속 후 정상적으로 표시되는 것 체크하실 수 있습니다!

**Comment by QgamesGeonPyoNoh** [comment]
강화 결과 창에서 출력되는 스탯에서 소수점 부분이 출력되지 않고 있습니다.
제작 결과 창도 동일할 것으로 예상됩니다. 확인 부탁드립니다.

[테스트 환경]
Windows.v200200-200.0.4

https://github.com/planetarium/NineChronicles/assets/150774808/938c8962-9528-4699-9435-54ca0a1b5fbb

**Comment by tyrosine1153** [comment]
수정해서 올립니다.

![image](https://github.com/planetarium/NineChronicles/assets/63496908/a51982e2-552b-4839-adc7-bee1f07d018e)
![image](https://github.com/planetarium/NineChronicles/assets/63496908/5e3c5cf2-9afb-4271-b91e-b7eafbb04d5b)

**Comment by QgamesGeonPyoNoh** [comment]
CRI 룬 제작 전 룬 UI에서 스탯이 1.06%가 아닌 1%로 출력되고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200200-200.0.5

https://github.com/planetarium/NineChronicles/assets/150774808/71ac413e-0185-4b71-9ae4-f509d2a503bc

**Comment by QgamesGeonPyoNoh** [comment]
이슈 수정 확인 완료했습니다.

[테스트 환경]
메인넷.Windows.v200200-v200.1.2

![Image](https://github.com/user-attachments/assets/ba8347f2-8238-4c0d-a4b6-f4903f6b74be)
