### ISSUE TITLE
인게임 어드벤처보스 타격이팩트 크기 수정

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5284]
보람님 별도로 제공해주신 가이드와 현재 타격이펙트 처리가 상이한 부분 수정 부탁드리겠습니다.

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103  @boramqo83 이슈가 너무 퍼져있어서 제공해주셨던 문서를 찾기가 어려운데 정리 부탁드려도될까요?
일단 크기키우고 고정위치에나오면되는것으로 알고있습니다

**Comment by boramqo83** [comment]
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=67600271
가이드는 요기에 있습니다.
@jonny-jeahyunchoi

**Comment by jonny-jeahyunchoi** [comment]
감사합니다 크기 2배였군요~!
