### ISSUE TITLE
현상금 걸기 화면에서 입력하는 부분을 터치하면 깜박거리는 선이 나오도록 수정

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5285]
운영 현상금 걸때 금액 입력부분을 클릭했을때
입력을 할수 있는 상태를 표시해주면 좋을 것 같습니다.

**Comment by jonny-jeahyunchoi** [comment]
현상금쪽 인풋필드가 일반적으로 사용하는 형태를 벗어난 디자인이어서 구조변경이 필요.
Caret을 직접 커스텀하게 컨트롤할수있도록 변경해야함.
사용자 인풋값에 inputCountObj를 켜고끄는구조도 맞춰서 변경해야함. 
인풋텍스트하이라키와 동일한곳에 케럿이 생기기때문.
