### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 결과 창이 월드 맵 진입 시마다 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5286]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 결과 창이 월드 맵 진입 시마다 출력되는 현상
-운영 / 토벌 둘 다 진행하지 않은 상태의 캐릭터 입니다.
-해당 현상 발생 시 출력되는 에러 코드 공유드립니다.
-간헐적으로 받기 버튼이 동작하지 않는 현상도 발생하고 있습니다.
-Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/eed57766-04ba-49b0-a746-99fa724ccdfd

https://github.com/planetarium/NineChronicles/assets/150774808/75117a7d-06b0-4692-aeda-a012694f38cf

### How to reproduce the issue

[재현 스텝]
1. 메인 로비  - 어드벤쳐 클릭
2. 월드 맵 출력 후 1 블럭 지난 뒤 어드벤쳐 보스 결과 창 출력
3. 받기 버튼 클릭 후 메인 로비 - 어드벤쳐 다시 진행
4. 월드 맵 진입 시마다 어드벤쳐 보스 결과 창 출력 확인

[기대 결과]
어드벤쳐 보스 보상 팝업은 월드 맵 진입 후 1회만 출력되어야 합니다.

### Relevant log output

SerializationException: The constructor to deserialize an object of type 'Nekoyume.Action.Exceptions.EmptyRewardException' was not found.
System.Runtime.Serialization.ObjectManager.GetConstructor (System.RuntimeType t) (at <00000000000000000000000000000000>:0)
System.Runtime.Serialization.ObjectManager.CompleteISerializableObject (System.Object obj, System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) (at <00000000000000000000000000000000>:0)
System.Runtime.Serialization.ObjectManager.FixupSpecialObject (System.Runtime.Serialization.ObjectHolder holder) (at <00000000000000000000000000000000>:0)
System.Runtime.Serialization.ObjectManager.DoFixups () (at <00000000000000000000000000000000>:0)
System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser serParser, System.Boolean fCheck) (at <00000000000000000000000000000000>:0)
Lib9c.Formatters.ExceptionFormatter`1[T].Deserialize (MessagePack.MessagePackReader& reader, MessagePack.MessagePackSerializerOptions options) (at <00000000000000000000000000000000>:0)
MessagePack.Formatters.Nekoyume.Action.NCActionEvaluationFormatter.Deserialize (MessagePack.MessagePackReader& reader, MessagePack.MessagePackSerializerOptions options) (at <00000000000000000000000000000000>:0)
MessagePack.MessagePackSerializer.Deserialize[T] (MessagePack.MessagePackReader& reader, MessagePack.MessagePackSerializerOptions options) (at <00000000000000000000000000000000>:0)
MessagePack.MessagePackSerializer.Deserialize[T] (System.ReadOnlyMemory`1[T] buffer, MessagePack.MessagePackSerializerOptions options, System.Threading.CancellationToken cancellationToken) (at <00000000000000000000000000000000>:0)
Nekoyume.Blockchain.RPCAgent.OnRender (System.Byte[] evaluation) (at <00000000000000000000000000000000>:0)
Nekoyume.Shared.Hubs.ActionEvaluationHubClient.OnBroadcastEvent (System.Int32 methodId, System.ArraySegment`1[T] data) (at <00000000000000000000000000000000>:0)
MagicOnion.Client.StreamingHubClientBase`2[TStreamingHub,TReceiver].<ConsumeData>b__27_0 (System.Object state) (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <00000000000000000000000000000000>:0)
Rethrow as SerializationException: The constructor to deserialize an object of type 'Nekoyume.Action.Exceptions.EmptyRewardException' was not found.
System.Runtime.Serialization.ObjectManager.CompleteISerializableObject (System.Object obj, System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) (at <00000000000000000000000000000000>:0)
System.Runtime.Serialization.ObjectManager.FixupSpecialObject (System.Runtime.Serialization.ObjectHolder holder) (at <00000000000000000000000000000000>:0)
System.Runtime.Serialization.ObjectManager.DoFixups () (at <00000000000000000000000000000000>:0)
System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser serParser, System.Boolean fCheck) (at <00000000000000000000000000000000>:0)
Lib9c.Formatters.ExceptionFormatter`1[T].Deserialize (MessagePack.MessagePackReader& reader, MessagePack.MessagePackSerializerOptions options) (at <00000000000000000000000000000000>:0)
MessagePack.Formatters.Nekoyume.Action.NCActionEvaluationFormatter.Deserialize (MessagePack.MessagePackReader& reader, MessagePack.MessagePackSerializerOptions options) (at <00000000000000000000000000000000>:0)
MessagePack.MessagePackSerializer.Deserialize[T] (MessagePack.MessagePackReader& reader, MessagePack.MessagePackSerializerOptions options) (at <00000000000000000000000000000000>:0)
MessagePack.MessagePackSerializer.Deserialize[T] (System.ReadOnlyMemory`1[T] buffer, MessagePack.MessagePackSerializerOptions options, System.Threading.CancellationToken cancellationToken) (at <00000000000000000000000000000000>:0)
Nekoyume.Blockchain.RPCAgent.OnRender (System.Byte[] evaluation) (at <00000000000000000000000000000000>:0)
Nekoyume.Shared.Hubs.ActionEvaluationHubClient.OnBroadcastEvent (System.Int32 methodId, System.ArraySegment`1[T] data) (at <00000000000000000000000000000000>:0)
MagicOnion.Client.StreamingHubClientBase`2[TStreamingHub,TReceiver].<ConsumeData>b__27_0 (System.Object state) (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <00000000000000000000000000000000>:0)
Rethrow as MessagePackSerializationException: Failed to deserialize Nekoyume.Action.NCActionEvaluation value.
MessagePack.MessagePackSerializer.Deserialize[T] (MessagePack.MessagePackReader& reader, MessagePack.MessagePackSerializerOptions options) (at <00000000000000000000000000000000>:0)
MessagePack.MessagePackSerializer.Deserialize[T] (System.ReadOnlyMemory`1[T] buffer, MessagePack.MessagePackSerializerOptions options, System.Threading.CancellationToken cancellationToken) (at <00000000000000000000000000000000>:0)
Nekoyume.Blockchain.RPCAgent.OnRender (System.Byte[] evaluation) (at <00000000000000000000000000000000>:0)
Nekoyume.Shared.Hubs.ActionEvaluationHubClient.OnBroadcastEvent (System.Int32 methodId, System.ArraySegment`1[T] data) (at <00000000000000000000000000000000>:0)
MagicOnion.Client.StreamingHubClientBase`2[TStreamingHub,TReceiver].<ConsumeData>b__27_0 (System.Object state) (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <00000000000000000000000000000000>:0)

**Comment by jonny-jeahyunchoi** [comment]
시즌종료시점에 접속중인 상황이었나요?

**Comment by jonny-jeahyunchoi** [comment]
재접속시 발생하나요?

**Comment by QgamesGeonPyoNoh** [comment]
재 접속 후에도 계속 발생하고 있습니다.
시즌 종료 시점에 접속 중은 아니었습니다.

**Comment by jonny-jeahyunchoi** [comment]
헤임달인가요?

**Comment by QgamesGeonPyoNoh** [comment]
네, 헤임달에서 확인 진행했습니다.
오딘에서는 해당 현상 확인되지 않았습니다.

**Comment by jonny-jeahyunchoi** [comment]
넵 답변감사합니다~!

**Comment by jonny-jeahyunchoi** [comment]
200.0.3 에 해당부분 예외처리한 내용이 추가되었습니다. 간헐적이슈로보여서 재현되는지 확인필요합니다~!

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 추가로 발생 확인되지 않았습니다.
해당 이슈 종료 하겠습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)
