### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 정보를 불러오는데 1 블록이 소요되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5287]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 정보를 불러오는데 1 블록이 소요되는 현상
-Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/d04aacdd-7e8b-4647-87d1-9d5a455b4b4f

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 어드벤쳐 보스 정보 확인
3. 어드벤쳐 보스 정보를 불러오는데 1 블록이 소요되는 현상

[Should be]
어드벤쳐 보스 정보가 확인 즉시 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
200.0.3에 수정될예정입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)

https://github.com/planetarium/NineChronicles/assets/150774808/e4b6c749-dafb-4222-a71b-33258214a9f3
