### ISSUE TITLE
어드벤쳐 보스 랜덤보상에서 룬 조각 수량이 표시되지 않는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5289]

**Comment by jaeho0103** [comment]
https://planetariumhq.slack.com/archives/C011716SDTM/p1719994503385509?thread_ts=1719994474.403709&cid=C011716SDTM
제보 링크입니다.

**Comment by jonny-jeahyunchoi** [comment]
200.0.3에서 수정예정입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/3df6f6f4-042e-4ecd-864c-4561f3a5019f)
