### ISSUE TITLE
어드벤쳐보스 층잠김 언락이 바로 갱신되지 않는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5290]
어드벤쳐보스에서 5층단위 도전후 신규층 언락을 재화를 소비해서 진행완료했는데, 완료 연출후에도 오픈상태로 갱신되지 않는 현상.
월드맵을 나갔다 들어오면 오픈되어있음

**Comment by jaeho0103** [comment]
https://planetariumhq.slack.com/archives/C011716SDTM/p1719994630543939?thread_ts=1719994474.403709&cid=C011716SDTM
제보 링크입니다.

**Comment by jonny-jeahyunchoi** [comment]
슬로스갱신 반영이 안되어있는부분으로 확인되었고, 200.0.3에 수정될예정입니다~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3

https://github.com/planetarium/NineChronicles/assets/150774808/237a2583-6d02-433f-99a7-5f05eda19d7f
