### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 현상금 추가 시 보유 NCG를 초과하는 금액 입력이 가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5291]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 현상금 추가 시 보유 NCG를 초과하는 금액 입력이 가능한 현상
-입력한 액수만 1회 메세지로 출력되며, 현상금 추가 버튼이 계속 진행 중 상태로 출력됩니다.
-Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/7cc042dd-db45-4758-852c-8d580e5d6702

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 -어드벤쳐 보스 클릭
2. 현상금 추가 팝업 출력
3. 보유 NCG 이상 입력 시도
4.  보유 NCG를 초과하는 금액 입력이 가능한 현상 확인

[Should be]
어드벤쳐 보스 현상금 추가 시 보유 NCG를 초과하는 금액 입력이 불가능해야 합니다.

**Comment by jaeho0103** [comment]
보유 NCG보다 많이 보내면 액션이 당연히 실패할거라 생각합니다 그렇겠죠? @U-lis 
그렇다해도 실패 TX를 굳이 허용해줄 이유는 없으니 여유되실떄 고쳐주시면 감사하겠습니다 @jonny-jeahyunchoi 
우선순위는 일단 p2로 조정해둡니다.

**Comment by jonny-jeahyunchoi** [comment]
넵 초과ncg 보내는경우 실패처리됩니다 초과입력못하도록 막는기능은 추후 작업진행하겠습니다~!

**Comment by U-lis** [comment]
네 액션 안에서는 transfer asset 을 수행하기 때문에 가진 돈보다 많이 입력하면 이 단계에서 액션이 실패합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)

https://github.com/planetarium/NineChronicles/assets/150774808/aa34288b-87bb-450d-a209-c1daeaecf9b3
