### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 오픈 후 최초 현상금 추가 시 예상 보상이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5293]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 오픈 후 최초 현상금 추가 시 예상 보상이 출력되지 않는 현상
-Windows, Android, iOS에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/2ad75e55-360c-47b9-b82c-20f00e1c2a91)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 클릭
2. 어드벤쳐 보스 오픈 후 현상금 추가 버튼 클릭
3. 최초 현상금 추가 시 예상 보상이 출력되지 않는 현상 확인

[Should be]
어드벤쳐 보스 오픈 후 최초 현상금 추가 시 예상 보상이 출력되어야 합니다.

**Comment by jaeho0103** [comment]
https://github.com/orgs/planetarium/projects/97/views/9?pane=issue&itemId=69619281
이 이슈와 동일 이슈로 예상됩니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)

https://github.com/planetarium/NineChronicles/assets/150774808/bfc51e81-3d96-4cdb-9823-7c61ecf6875f
