### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 현상금 추가 시 이전 시즌의 보상 정보가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5301]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 현상금 추가 시 이전 시즌의 보상 정보가 출력되는 현상
-이전 시즌 보스와 보상 아이템은 동일하나 수량은 다르게 출력됩니다.
-Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/232525d4-668f-4e2a-aa39-f259e29f6e2d

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 클릭
2. 어드벤쳐 보스 진행 후 다시 오픈
3. 현상금 추가 팝업 출력 시 이전 시즌의 보상 정보가 출력되는 현상 확인

[Should be]
현상금 추가 시 이전 시즌의 보상 정보가 출력되지 않아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
기존이슈 수정과 동일한 부분으로 판단되었습니다 [fix adventureboss bounty popup issue #5299](https://github.com/planetarium/NineChronicles/pull/5299)에서 수정되었으며 200.0.3에 적용될예정입니다~!

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 추가로 발생 확인되지 않았습니다.
해당 이슈 종료 하겠습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)
