### ISSUE TITLE
크리스탈로 레시피 오픈후에 자물쇠와 오픈 버튼이 안사라지는 이슈

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5305]

**Comment by jaeho0103** [comment]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1720069580459969

**Comment by ipdae** [comment]
https://github.com/planetarium/NineChronicles/assets/3193043/20ccdf0a-34ca-4666-849e-7436b59f470f

현재 인터널에서 테스트중인 버전에서 수정된 #5272 에서 같이 정상화된것으로 보입니다.
