### ISSUE TITLE
[인벤토리] 아우라 강화 후 우편 수령 시 인벤토리에서 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5306]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
아우라 강화 후 우편 수령 시 인벤토리에서 출력되지 않는 현상
-Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/81dce9a3-ddcd-40ed-b28c-4da47f363421

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 강화 클릭
2. 아우라 강화 진행
3. 우편에서 강화된 아우라 수령
4. 인벤토리 확인 시 아우라가 출력되지 않는 현상 확인

[Should be]
아우라 강화 후 인벤토리 확인 시 즉시 출력되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 메인넷에서 발생 확인했습니다.
확인 부탁드립니다.

-아우라의 경우, 재접속 시까지 인벤토리에 출력되지 않았습니다.
-무기의 경우, 인벤토리에는 출력되나 강화 페이지에서 출력되지 않았습니다. 강화 페이지 재 진입 시 출력되었습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/9376de9d-6808-4c3d-8969-377d891daab9

-해당 현상 발생 로그 파일 공유드립니다.
[Log.zip](https://github.com/user-attachments/files/16157457/Log.zip)

[테스트 환경]
메인넷.Windows.v200200-200.0.5

**Comment by eugene-doobu** [comment]
@ipdae 해당 이슈 상태 Done으로 갱신해두었습니다
