### ISSUE TITLE
[마켓] 장바구니에 아이템이 담긴 상태에서 뒤로가기 버튼 터치 시 검은 화면이 노출되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5312]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
장바구니에 아이템이 담긴 상태에서 좌측상단의 뒤로가기 버튼 터치 시 검은 화면이 노출되는 현상
- 검은 화면이 노출된 상태에서 워크샵 빈 슬롯 터치를 통해 워크샵 화면으로 진입 가능합니다.
- Windows 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/5dd83535-04a2-4a78-adce-401c2e542d12

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 마켓 클릭
2. 마켓 화면에서 장바구니 클릭 후 아이템 클릭
3. 장바구니에 아이템이 담겨있는 상태에서 좌측상단의 뒤로가기 버튼 클릭
4. 경고 팝업 출력 시 YES 버튼 클릭
5. 검은 화면이 노출되는 것을 확인

[Should be]
장바구니에 아이템이 담긴 상태에서 좌측상단의 뒤로가기 버튼 터치 시 메인 로비 화면이 노출되어야 합니다.

**Comment by ipdae** [comment]
https://github.com/planetarium/NineChronicles/pull/5578 참고

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.3

https://github.com/user-attachments/assets/b3ec21b9-a912-4727-943f-4505df5eb64b
