### ISSUE TITLE
어드벤쳐 보스 배틀 결과화면 중 AP포션 사용 부분 변수 연결 반대로 되어있는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5313]
[0]과 [1]을 반대로 사용해서 l10n 갱신 부탁드립니다.

**Comment by jaeho0103** [comment]
https://planetariumhq.slack.com/archives/C011716SDTM/p1720076285968149

**Comment by NineSyu** [comment]
수정해서 L10n 다시 업데이트 했습니다.
{0} 과 {1} 순서를 서로 바꾸었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
영문 기준으로도 변경 되었는데 해당 부분 맞는지 확인 요청 드립니다.



![Image](https://github.com/planetarium/NineChronicles/assets/150774808/2c116332-73f3-4839-a088-39249fd4389e)

**Comment by U-lis** [comment]
![Screenshot from 2024-07-05 20-38-18](https://github.com/planetarium/NineChronicles/assets/3654082/a0668fc3-7aae-4611-9b51-d1da636cbbe8)
잘 변경된 것 확인했습니다

**Comment by jaeho0103** [comment]
@NineSyu 영문은 반대로 되어있네요. 수정해서 올려주세요.
@U-lis 이슈상태 변경하실때는 쓰레드 한번 체크해주시면 감사하겠습니다.

**Comment by NineSyu** [comment]
영문 및 다국어 번역 반대로 표시되던 이슈 수정했습니다.
재접속하시면 정상적으로 표시되는 것 확인할 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.5
Android.v200200-200.0.5
iOS.v200.0.5(88)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/fd0fa85c-f833-461c-af7a-ea4bc32f5ce7)



![Image](https://github.com/planetarium/NineChronicles/assets/150774808/277ddc5d-6e2f-4585-aa8f-18462ff6ae34)
