### ISSUE TITLE
[어드벤쳐 보스] K 버전에서 어드벤쳐 보스 입장 불가 메세지가 깨져서 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5314]
### APV version info

K_v200200

### Client version info

v200.0.2

### Device

Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
K 버전에서 어드벤쳐 보스 입장 불가 메세지가 깨져서 출력되는 현상
-Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/35c52c5c-36fc-44c7-913d-ff99cdf42731)

### How to reproduce the issue

[재현 스텝]
1. K버전 클라이언트 실행
2. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 클릭
3. 입장 불가 메세지가 깨져서 출력되는 현상 확인

[Should be]
K 버전에서 어드벤쳐 보스 입장 불가 메세지가 정상적으로 출력되어야 합니다.

**Comment by jaeho0103** [comment]
l10n 수정해놓겠습니다 "이 빌드에서는 " -> "이 버전에서는"

**Comment by NineSyu** [comment]
L10n 수정하여 "빌드" 명칭을 "버전"으로 수정하여 업데이트 했습니다.
재접속 후 다시 테스트하시면 정상적으로 표시되는 것 확인하실 수 있습니다!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
K_Android.v200200-200.0.3
K_iOS.v200.0.3(29)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/e066bc53-9c9d-41f1-b0c0-9ce197d825b6)
