### ISSUE TITLE
[그리모어] 그리모어 분해 시 획득 가능한 크리스탈이 1개로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5320]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
그리모어 분해 시 획득 가능한 크리스탈이 1개로 출력되는 현상
-Windows, Android, iOS에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/c453ffa9-dfa1-4253-9b84-9bca3afc5f41)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 분해 클릭
2. 그리모어 등록 진행
3. 획득 가능한 크리스탈이 1개로 출력되는 현상

[Should be]
그리모어 분해 시 획득 가능한 크리스탈이 정상적으로 출력되어야 합니다.

**Comment by jaeho0103** [comment]
데이터 수정해서 다시 올려두겠습니다 @NineSyu

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/b97bdf5d-0ff2-4015-b5d1-7e184c7d33e4)
