### ISSUE TITLE
[마켓] 판매 중인 아이템 회수 시 인벤토리에 출력되지 않는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5322]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
판매 중인 아이템 회수 시 인벤토리에 출력되지 않는 현상
- 아이템 회수 진행 후 우편 수령 시 수령 화면에 아이템 아이콘이 출력되지 않습니다.
- 재접속 시 인벤토리에 아이템이 정상적으로 출력되는 부분 확인했습니다.
- Windows 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/be42b6ce-b5b9-4122-9036-e5df09045188

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 마켓 클릭
2. 마켓 화면에서 셀 탭 진입 후 판매 중인 아이템 클릭
3. 아이템 정보 팝업에서 회수 버튼 클릭
4. 회수 진행 후 우편 수령 시 수령 화면에 아이템 아이콘이 출력되지 않는 것을 확인
5. 인벤토리에 회수한 아이템이 출력되지 않는 것을 확인

[Should be]
판매 중인 아이템 회수 시 해당 아이템이 인벤토리에 정상적으로 출력되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3

https://github.com/planetarium/NineChronicles/assets/150774808/323994db-3368-4077-87eb-6efa96b16049
