### ISSUE TITLE
[그리모어] 주옵션과 보조옵션이 동일한 그리모어의 정보 팝업에서 별의 개수가 2개로 노출되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5328]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
주옵션과 보조옵션이 동일한 그리모어의 정보 팝업에서 별의 개수가 2개로 노출되는 현상
- 주옵션과 보조옵션이 상이한 그리모어의 정보 팝업에서는 주옵션에 별 2개, 보조옵션에 별 1개가 노출되는 것을 확인했습니다.
- 공격의 그리모어(A), 방어의 그리모어(D)에서 해당 현상이 발생하는 것을 확인하였습니다.
- Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/5c72d56a-c94f-4e2c-b06e-82fc9ed1bbe9

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 인벤토리 클릭
2. 인벤토리에서 공격의 그리모어(A) 클릭
3. 공격의 그리모어(A) 상세 정보 팝업에서 공격력 옵션의 별 개수가 2개인 것을 확인

[Should be]
주옵션과 보조옵션이 동일한 그리모어의 정보 팝업에서 별의 개수가 3개로 노출되어야 합니다.

**Comment by tyrosine1153** [comment]
관련 스레드 :
https://planetariumhq.slack.com/archives/C011716SDTM/p1720084846757429

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.4
Android.v200200-200.0.4
iOS.v200.0.4(87)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/cc71ccf9-b41b-4800-9a98-7c7eac069ef6)
