### ISSUE TITLE
[그리모어] 그리모어 스킬 사용 시 스킬의 효과가 적에게 적용되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5332]
### APV version info

v200200

### Client version info

v200.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
그리모어의 스킬 사용 시 스킬의 효과가 적에게 적용되는 현상
- 공격의 그리모어, 방어의 그리모어, 기능의 그리모어 모두 해당 현상이 발생합니다.
- Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/30472c86-2735-48f7-b65a-136f266ac43d

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 어드벤처 - 스테이지 클릭
2. 스테이지 화면에서 방어의 그리모어 장착
3. 전투 시작 후 그리모어 스킬 사용 시 적에게 효과 연출이 출력되는 것을 확인
4. 그리모어 스킬 사용 시 적의 받는 피해가 감소한 것을 확인

[Should be]
그리모어의 스킬 사용 시 스킬의 효과가 아군에게 적용되어야 합니다.

**Comment by NineSyu** [comment]
데이터에 문제가 있는 것을 확인하였습니다. 데이터를 수정하여 이슈 해결하겠습니다.
재접속 후 테스트 하시면 정상동작하는 것을 확인하실 수 있을 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)

https://github.com/planetarium/NineChronicles/assets/150774808/b962687e-0719-4234-9448-a97c8761c6a8
