### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 현상금 추가 팝업 내 텍스트가 영문으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5334]
### APV version info

v200200

### Client version info

v200.0.3

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 현상금 추가 팝업 내 텍스트가 영문으로 출력되는 현상
-현상금 최소 금액 안내 / 현상금 최소 금액 미달 메세지가 영문으로 출력되고 있습니다.
-Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/83653d35-9730-4c69-b2ba-5d4b1564511e)

### How to reproduce the issue

[재현 스텝]
1. 모바일 클라이언트 실행
2. 메인 로비 - 어드벤쳐 - 이드벤쳐 보스 (오픈 가능 상태) 클릭
3. 현상금 추가 팝업 출력
4. 팝업 확인 시 텍스트가 영문으로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 현상금 추가 팝업 내 텍스트가 한글로 출력되어야 합니다.

**Comment by NineSyu** [comment]
@jonny-jeahyunchoi L10n 준비하여 적용완료되었습니다. 머지된후에 QA단계로 넘겨주시면 감사드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
현상금 입력 박스 내 최소 금액 안내가 영문으로 출력되고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200200-200.0.4
iOS.v200.0.4(87)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/7f120b55-4d47-4c34-bee5-593b6c97a22b)

**Comment by QgamesGeonPyoNoh** [comment]
현상금 입력 박스 내 최소 금액 안내가 키 값으로 출력되고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200200-200.1.3
![이슈](https://github.com/user-attachments/assets/87bf45da-4c9f-45d0-9ad7-ef925cead051)

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 체크 부탁드립니다~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
iOS.v200.1.2(94)
![IMG_0749](https://github.com/user-attachments/assets/64b92b7c-916f-4d92-ab05-97c882e64601)
