### ISSUE TITLE
ConcurrentDictionary로 변경된 타입들 처리결과 로그로 남기기

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#5339]
리턴값으로 로그 찍어주는게 좋지 않나 생각이 드네요

_Originally posted by @eugene-doobu in https://github.com/planetarium/NineChronicles/pull/5336#discussion_r1666169258_

**Comment by U-lis** [comment]
https://github.com/planetarium/NineChronicles/issues/5430 랑 관련...?
