### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 현상금 3회 추가 후 더하기 버튼 클릭 시 메세지가 키값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5341]
### APV version info

v200200

### Client version info

v200.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
 어드벤쳐 보스 현상금 3회 추가 후 더하기 버튼 클릭 시 메세지가 키값으로 출력되는 현상
-Windows, Android, iOS에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/07c3758a-871a-4ea3-9c79-41caf740868b)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 (오픈 상태) 클릭
2. 어드벤쳐 보스 - 현상금 추가 3회 진행
3. 3회 추가 후 현상금 추가 버튼 클릭 시 메세지가 키값으로 출력되는 현상 확인

[Should be]
현상금 3회 추가 후 출력되는 메세지가 텍스트로 출력되어야 합니다.

**Comment by NineSyu** [comment]
L10n이 누락되어 적용되지 않은 것을 확인했습니다.
재접속 후 확인하면 정상출력되는 것 체크 가능합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.3
Android.v200200-200.0.3
iOS.v200.0.3(86)

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/8577d86e-7e3d-47ed-a587-cbb0761fd401)
