### ISSUE TITLE
[어드벤쳐 보스] 5% 1인 당첨 시 별도의 팝업이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5343]
### APV version info

v200200

### Client version info

v200.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
5% 1인 당첨 시 별도의 팝업이 출력되지 않는 현상
-공헌도 보상으로 23.06 NCG가 결과 창에 출력되었으나 실제로는 38.06 NCG가 지급되었습니다.
-총 현상금 300의 5%인 15NCG가 지급된 것으로 추정되나 5% 1인 당첨 등의 별도 팝업은 출력되지 않았습니다.
-Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/222ee08c-2dce-4eff-b5a3-1d4b9a8c1a15

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 (오픈 상태) 클릭
2. 어드벤쳐 보스 - 도전 진행
3. 어드벤쳐 보스 시즌 종료 - 결과 창 출력
4. 결과 보상 수령 시 총 현상금의 5%를 획득하였으나 별도 팝업이 출력되지 않는 현상 확인

[Should be]
현상금 5% 당첨 시 별도의 팝업이 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
현상금의 5%를 받는 팝업안내는 시즌이 종료되고나서 누군가 최초 수령을 받는 순간 접속중인 모든플레이어에게 나오도록 되어있습니다.
이미 누군가 최초 보상을 받은뒤에 접속후 시즌보상을 받는다면 나오지않는것이 구현스팩이나, QA주신경우처럼 혼란의 여지가 있어보여 보완책이 필요해보입니다. @jaeho0103

**Comment by jaeho0103** [comment]
아 당첨자본인에게는 메일을 날려준다든지 하는 추가 스펙이 필요하겠네요. @jonny-jeahyunchoi

**Comment by jonny-jeahyunchoi** [comment]
메일보상 날리려면 lib9c 수정이 필요할듯 보입니다 @U-lis

**Comment by U-lis** [comment]
그럼 당첨자가 결정되는 순간 받았건 안받았건 당첨자한테 메일을 보내도록 해야 하는 걸까요?

**Comment by jaeho0103** [comment]
네 보내서 받게 하시죠.
Adventure boss random winner is you!
라는 형태로 보내면 되지 않을까 싶습니다.

**Comment by jonny-jeahyunchoi** [comment]
이거 위 이슈랑 별개로 슬로스 영향으로 기존스팩대로도 팝업이안뜨는 상황으로 체크되어 수정진행할예정입니다~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.4

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/b9208fe3-dbbf-4430-ba9b-f28c6a90aa8a)
