### ISSUE TITLE
[어드벤쳐 보스] 특정 적의 체력 바가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5345]
### APV version info

v200200

### Client version info

v200.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
특정 적의 체력 바가 출력되지 않는 현상
-헬라 타워 1F / 8F에서 확인했습니다.
-Windows, Android, iOS에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/406d58c3-9631-440d-aece-2a0343506fc3)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 (오픈 상태) 클릭
2. 헬라 타워 도전 진행
3. 특정 적의 체력 바가 출력되지 않는 현상 확인

[Should be]
어드벤쳐 보스 적의 체력 바가 출력되어야 합니다.

**Comment by boramqo83** [comment]
@eugene-doobu 유진님이 어드밴처 인게임 플레이할 때 상단 해더 UI가 몬스터 체력봐와 겹치지 않도록 무조건 일정 범위 안에 뿌려지도록 처리해 준 적이 있는데요. 어드밴처 보스 인게임의 층 게이지 표기되는 곳과 겹치지 않도록 영역 수정해 주실 수 있을까요? cc @jonny-jeahyunchoi

**Comment by eugene-doobu** [comment]
@boramqo83 모든 몬스터의 체력바를 아래로 내려야하는걸까요?

**Comment by boramqo83** [comment]
![image](https://github.com/planetarium/NineChronicles/assets/102953029/91913b03-7f1a-44e2-b53e-d46ee2e8c7c7)
@eugene-doobu 네. 모든 몬스터의 체력바가 해당 영역을 벗어나면 영역 안에 뿌려지도록 처리해 주세요.
