### ISSUE TITLE
[컬렉션] 모래시계를 사용하지 않고 제작한 음식이 컬렉션 수량에 반영되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5350]
### APV version info

v200200

### Client version info

v200.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모래시계를 사용하지 않고 제작한 음식이 컬렉션 수량에 반영되지 않는 현상
-Windows, Android, iOS에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/4900aefe-b12d-4184-ad2c-8563e53bf5c4

-발생 당시 로그 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16105508/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 제작 - 음식 클릭
2. 임의의 음식 제작 진행 - 모래시계 사용하지 않고 완료
3. 메인 로비 - 컬렉션 - 음식 탭 클릭
4. 제작한 음식의 수량이 증가하지 않는 현상 확인

[Should be]
모래시계를 사용하지 않고 제작한 음식 수량이 컬렉션에 반영되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
장비의 경우에도 발생하는 것으로 확인했습니다.
재현 영상 공유드립니다.

https://github.com/planetarium/NineChronicles/assets/150774808/94b5b360-6b58-4ff4-9f61-7bfa781a7fa9

**Comment by eugene-doobu** [comment]
부분적으로 상태를 해결했습니다. 아이템이 생성된 이후, 상단이나 좌측의 탭을 누르는 등의 행동으로 인해 아이템 뷰가 초기화되었을때 새로 생성된 아이템 수량이 적용되도록 수정했습니다.

**Comment by eugene-doobu** [comment]
아이템 생성 완료시 자동적으로 아이템 수량을 갱신하거나 하는 작업은 성능의 문제로 지금 작업하지 않는 것으로 이야기 되었습니다.
