### ISSUE TITLE
[튜토리얼] 5 스테이지 클리어 후 튜토리얼이 진행되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5354]
### APV version info

v200200

### Client version info

v200.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
5 스테이지 클리어 후 튜토리얼이 진행되지 않는 현상
-기존에는 아우라, 장비 착용 튜토리얼이 진행되었습니다.
-Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/c617dbb4-73ce-43e5-aac2-f08554448819

### How to reproduce the issue

[재현 스텝]
1. 신규 캐릭터 생성
2. 5스테이지까지 튜토리얼 따라 진행
3. 5스테이지 클리어 후 Main 버튼 클릭 (다음 스테이지 버튼 없음)
4. 5스테이지 클리어 후 튜토리얼이 진행되지 않는 현상 확인

[Should be]
5스테이지 클리어 후 튜토리얼이 진행되어야 합니다.

**Comment by sonohoshi** [comment]
원래 5스테이지 튜토리얼이 뭐였는지 확인 좀 해보겠습니다

**Comment by sonohoshi** [comment]
Summon tutorial인데...

**Comment by ipdae** [comment]
@QgamesGeonPyoNoh 이거 로그 좀 올려주실수있나요? 추가로, 앞으로 PC에서 테스트하시다 발생하는 이슈들은 가능하면 로그첨부 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
[Log.zip](https://github.com/user-attachments/files/16107794/Log.zip)
해당 이슈 발생 당시 Log 파일 첨부드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
튜토리얼 진행 시 동일하게 5스테이지 이후 진행되지 않았습니다.
재 접속 시 튜토리얼이 다시 진행되는 부분 확인했습니다.

[테스트 환경]
Windows.v200210-210.0.2

https://github.com/user-attachments/assets/53c05999-5146-4bad-b650-f98e294e75ea

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.4

https://github.com/user-attachments/assets/242bbe6b-0e87-4db0-a7c9-50cd8de70168
