### ISSUE TITLE
[어드벤쳐 보스] 간헐적으로 My info에 NCG 보상이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5356]
### APV version info

v200200

### Client version info

v200.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
간헐적으로 My info에 NCG 보상이 출력되지 않는 현상
-Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/150774808/173b3813-af1b-4506-8f07-aec70747ef0d

-해당 현상 발생 당시 Log 파일 공유드립니다.

[log.zip](https://github.com/user-attachments/files/16107672/log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 (오픈) 클릭
2. 도전 진행
3. 어드벤쳐 보스 로비 확인 시 My info에 NCG 보상이 출력되지 않는 현상 확인

[Should be]
어드벤쳐 보스 My info에 NCG 보상이 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
어드벤쳐 보스 로비 재접속시 정상갱신되나요?

**Comment by QgamesGeonPyoNoh** [comment]
현재 해당 현상이 발생한 어드벤쳐 보스가 종료되어 확인이 어렵습니다.
재 발생 시 확인 후 공유 드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 추가 발생 확인되지 않아 종료하겠습니다.

[테스트 환경]
Windows.v200210-210.0.3
![image](https://github.com/user-attachments/assets/406dc993-c3bc-467b-b3e5-917eee879b3a)
