### ISSUE TITLE
[워크샵] 장비 분해 후 분해 화면에서 장비 선택 시 몬스터 컬렉션 UI가 출력되지 않는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5363]
### APV version info

v200200

### Client version info

v200.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
장비 분해 후 분해 화면에서 장비 선택 시 몬스터 컬렉션 UI가 출력되지 않는 현상
- 워크샵 분해 화면, 인벤토리 분해 팝업에서 해당 현상이 발생합니다.
- 해당 현상 발생 시 분해 시 획득 가능한 크리스탈도 출력되지 않는 것을 확인했습니다.
- Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/planetarium/NineChronicles/assets/167295117/495dcb7a-0664-4553-82b9-3b41b41bf9ff

### How to reproduce the issue

[재현스텝]
1. 메인 로비 - 인벤토리 버튼 클릭
2. 분해 버튼을 클릭하여 분해 모드로 전환
3. 분해 진행
4. 분해 완료 후 장비 선택 시 몬스터 컬렉션 관련 UI가 출력되지 않는 것을 확인

[Should be]
장비 분해 후 분해 화면에서 장비 선택 시 몬스터 컬렉션 UI가 정상적으로 출력되어야 합니다.

**Comment by jaeho0103** [comment]
얘는 현재 메인넷에서도 이슈 있는 부분이긴 합니다.

**Comment by tyrosine1153** [comment]
이미지는 Grind에서 사용하는 Animator의 상태 머신이다.
![Image](https://github.com/user-attachments/assets/0a40d464-c3ba-41ee-8ebb-31011f8bb9f8)


Animator의 parameter 중 Trigger들은 아래의 상태일 때 Set 된다.
- FirstRegister: material이 추가되었을 때, count가 1이라면
- StartGrind: Grind 액션 호출
- EmptySlot: material의 수가 변경되었을 때, count가 0이라면

### 문제 원인
AnySlotState_Loop -> NormalState_Loop 의 경로에는 일반적으로 EmptySlot 트리거를 조건으로 설정한다.
하지만 StartGrind -> NormalState_Loop의 경로에는 아무 조건이 없다.
트리거가 Set되었는데도 해당 조건에 따라 이동할 상태가 없으면 트리거는 보류되었다가 전환할 상태가 되었을 때 사용됨

### 문제 재현 과정
1. 재료를 담아서 NormalState_Loop-> AnySlotState_Loop
2. Grind액션 호출로 인한 StartGrind 트리거가 Set됨 AnySlotState_Loop -> StartGrind
3. 아무 조건이 없기 때문에 대기하지 않고 상태 이동 StartGrind -> NormalState_Loop
4. 액션 호출로 인해 material이 비워지면서, EmptySlot 트리거도 Set됨
    - StartGrind 트리거로 인해 이미 NormalState_Loop로 와있는 상태라 EmptySlot 트리거가 보류
5. 이후 재료를 담아서 FirstRegister로 인해 NormalState_Loop-> AnySlotState_Loop 이동할 때 작동한다.
6. EmptySlot은 늘 보류되어 밀리고 있음

### 해결 방법
StartGrind -> NormalState_Loop의 경로에 EmptySlot 트리거를 조건으로 설정
