### ISSUE TITLE
[그리모어] 그리모어의 스탯 옵션 개수가 1개로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5366]
### APV version info

v200200

### Client version info

v200.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
그리모어의 스탯 옵션 개수가 1개로 출력되는 현상
-기존에 소환한 그리모어에서는 해당 현상 발생하지 않았으나, 금번 빌드에서 신규로 뽑은 그리모어에서 발생 확인했습니다.
-Windows, Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/7358fd57-26ed-4601-87a0-461e47b425a1)

해당 현상 발생 당시 로그 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16122346/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 그리모어 소환 진행
3. 획득한 그리모어 확인
4. 스탯 옵션 개수가 1개로 출력되는 현상 확인

[Should be]
그리모어의 스탯 옵션 개수가 3개로 출력되어야 합니다.

**Comment by sonohoshi** [comment]
테이블 데이터 이슈로 확인됐고 @NineSyu 님께서 패치테이블로 해결해주실 예정입니다.

**Comment by NineSyu** [comment]
데이터 수정하여 정상적으로 표시되게 수정하였습니다.
재접속 후 새로 뽑은 그리모어 장비는 정상적으로 표시될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200200-200.0.4

![Image](https://github.com/planetarium/NineChronicles/assets/150774808/f3b16ca0-286c-400d-b119-d8ad4ebd896b)
