### ISSUE TITLE
[워크샵] 이미르 아우라 소환 시 스탯이 2개만 부여되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5413]
### APV version info

v200200

### Client version info

v200.1.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
이미르 아우라 소환 시 스탯이 2개만 부여되는 현상
-Windows, Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/c9e5458b-1b00-4e78-b9b4-bcec6e274e02)

해당 현상 시 발생 로그 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16186467/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 화면 - 워크샵 - 소환 클릭
2. 임의의 아우라 소환 진행
3. 이미르 아우라 획득 시 확인
4. 이미르 아우라 스탯이 2개만 부여되는 현상 확인

[Should be]
이미르 아우라 획득 시 스탯이 3개 부여되어야 합니다.

**Comment by NineSyu** [comment]
이미르 아우라 데이터 수정하여 문제 해결하였습니다.

**Comment by jaeho0103** [comment]
별도 확인이 어려우신 이슈라 종료 처리하겠습니다.
