### ISSUE TITLE
[월드보스] 월드보스 보스 킬 보너스 팝업이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5420]
### APV version info

메인넷.v200200

### Client version info

v200.1.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
월드보스 보스 킬 보너스 팝업이 출력되지 않는 현상
-보스 킬 보너스 크리스탈 / 룬 조각 지급은 확인했습니다.
-Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/5d2599d1-4582-4ae6-8d1a-e4d1477a6ae4

해당 이슈 발생 시 로그 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16229406/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 월드보스 클릭
2. 월드보스 티켓 1회 사용 진행
3. 티켓 사용 후 현재 레벨 보스 처치 시 까지 대기
4. 현재 레벨 보스 처치 시 월드보스 티켓 1회 사용 진행
5. 결과 창에서 보스 킬 보너스 팝업이 출력되지 않는 현상 확인

[Should be]
월드보스 보스 킬 보너스 팝업이 출력되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
설치되어 있던 아테나 모드 삭제 후 해당 현상 발생 로그 및 재현 영상 첨부드립니다.

추가로, 안드로이드 버전에서도 발생 확인하였으나
iOS 버전에서 월드보스 스킵을 진행하지 않았을 시 해당 현상이 발생하지 않았습니다.
월드보스 연출 스킵이 해당 현상 발생에 영향을 주는지 확인 후 공유드리겠습니다.
[Log.zip](https://github.com/user-attachments/files/16245613/Log.zip)

https://github.com/user-attachments/assets/b8287095-22c0-474d-a4a0-cdb53a5b438b

**Comment by ipdae** [comment]
sloth 업데이트로 인해 렌더러에서 잘못된 데이터를 가져와서 문제가 되는걸로 추정되고, #5447 의 변경으로 정상화 됐을것으로 보입니다. 인터널에서 테스트해보면 될것같습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
iOS.v200.1.2(94)
