### ISSUE TITLE
개발없음//강화 화면에 CP 변화 부분에 MAX 텍스트 추가

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5423]
강화 할때 안내해주는 CP와 실제 강화 완료됐을 때 CP에 이격이 너무 큽니다.

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1721010289676259?thread_ts=1721010289.676259&cid=C062ZS68A21)

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/upgrade_cp_max-add
사용 프리퓁 : UI_Enhancement



![Image](https://github.com/user-attachments/assets/fb163bcb-3f7a-401b-8def-3bcffec70ad7)

- 변경될 수치 앞에 MAX 표기해 주었습니다.
