### ISSUE TITLE
어드밴처보스 폴리싱_요거 머지해 주세요.

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5425]
폴리싱 기획서
https://www.notion.so/planetarium/200210-bb15de8661f94b0f858c1fa3475f8d33
/
하위 테스크
어드밴처보스 폴리싱_어드밴처보스 메인화면
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=70906099
어드밴처보스 폴리싱_월드맵
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=70906016
어드밴처보스 폴리싱_이전시즌 리포트 팝업 추가
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=71020793

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/previous_season_report_popup-add
사용 프리퓁 : 
UI_AdventureBoss
AdventureBossWorldButton
UI_PreviousSeasonReportPopup

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/391656f8-1e76-4eda-a54e-4c71cf41d74f)

PrevButton 요 버튼 누르면 지난 시즌 리포트 팝업이 뜨도록 해 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/13bec4ec-a6bc-401e-bd55-d61e9d224d69)

시즌 종료 후 00시간 안에 보상을 받을 수 있다는 문구의 L10n 연결 부탁드립니다.

**Comment by jonny-jeahyunchoi** [comment]
fix/adventureboss-polishing 브랜치에서 이어서 작업진행중입니다~!
