### ISSUE TITLE
[ENHANCEMENT] 어드벤쳐 보스 내정보 섹션에 정보 추가 표시

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5431]
### Purpose

enhance UX

### Document

https://www.notion.so/planetarium/200210-bb15de8661f94b0f858c1fa3475f8d33

### issue description

어드벤쳐 보스 마이 인포 부분에
1. 내 점수 부분에 (공헌도 %) 정보 추가
2. 내 포션 사용량 정보 추가

**Comment by boramqo83** [comment]
![image](https://github.com/user-attachments/assets/2cebfd9f-b42e-4b12-b64e-5e9dfdbf0fb5)

- 참가자 보너스 대신 "시즌 참여 정보"로 텍스트 변경
- AP potion usage 텍스트 뒤에 (My usage) 넣어주기
- 전체 AP 사용량 숫자 뒤에 (내 AP 사용량 숫자) 넣어주기

따로 프리퓁 작업 할 것 없어 보입니다.
위 내용으로 진행해 주세요. @jonny-jeahyunchoi

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 관련내용 참조하셔야될것같습니다~!
