### ISSUE TITLE
원격 오류 제보를 위한 로깅 방법 R&D

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#5432]
원격 오류 제보(센트리, 믹스패널 등 로깅) 방법 리서치 및 가능하면 적용
https://www.notion.so/planetarium/iOS-d63356563e144c32919d146e3f804d26?pvs=4#24be14373d63447d9741dabfef99f7a8

**Comment by ipdae** [comment]
다음주 이슈 재분배 예정

**Comment by ipdae** [comment]
믹스패널에 LogException 을 핸들링해서 사용해보는게 어떨지 확인

**Comment by jonny-jeahyunchoi** [comment]
https://docs.unity3d.com/ScriptReference/Application-logMessageReceivedThreaded.html

유니티에서 발생하는 모든 로그에 걸리는 콜백을 활용하여 작업할수있을듯함. 
이방식을 사용하면 명시적으로 코드에서 찍는 로그 말고도 저장 가능할듯

**Comment by jonny-jeahyunchoi** [comment]
믹스패널에서 요청보내는것을 모아서보내야하는 이슈가 있는지 체크 필요.

**Comment by jonny-jeahyunchoi** [comment]
콜백관련 퍼포먼스 체크도 필요함

**Comment by jonny-jeahyunchoi** [comment]
https://docs.mixpanel.com/docs/tracking-methods/sdks/unity 일단 믹스패널에서 로그요청은 60초마다 한번씩 모아서 보내는식으로 sdk가 구성되어있어서 관련한 퍼포먼스의 문제는 크게 없을것으로 판단됨

**Comment by ipdae** [comment]
- [ ] 믹스패널 이벤트 종류 제어 필요
- [ ] 게임 정상 작동시에도 오류들이 발생중인데 로그 레벨 변경 또는 메시지 정리 필요

**Comment by jonny-jeahyunchoi** [comment]
이벤트 종류 제어의 경우 해당이슈에서 진행하면될것같고
게임정상 작동시 발생하는 오류관련하여 수정기준이나 로그레벨변경은 따로 이슈생성하여 정리하도록하겠습니다~!
