### ISSUE TITLE
아레나에서 동점일때 자기 자신이 동일 순위가 아니라 제일 상위 순위로 표시됨

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#5469]
아레나에서 이번 시즌부터 동점일때 자신은 동점 제외한 순위로 나오던데 이러면 보상시 오해의 소지가 있을 것 같은데 괜찮은가요

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1721385908893009?thread_ts=1721385908.893009&cid=C062ZS68A21)

**Comment by tyrosine1153** [comment]
@sonohoshi 혹시 아까 말씀하셨던 이 이슈의 원인이나 알고계신 부분에 대해서 설명해주실 수 있으신가요?

**Comment by sonohoshi** [comment]
@tyrosine1153 https://github.com/planetarium/NineChronicles/blob/main/nekoyume/Assets/_Scripts/State/RxProps.Arena.cs#L350 여기 보시면 됩니다. 헤드리스가 정렬해서 주는 상태가 액션 렌더 직후에는 갱신되어있지 않을 수 있어서 클라에서 갱신을 한번 더 한건데, 이 경우 생기는 문제입니다.

**Comment by tyrosine1153** [comment]
참고하겠습니다 감사합니다
