### ISSUE TITLE
상대 캐릭터 상세 보기 팝업에서 그리모어 슬롯 비어있을 때 아이콘이 무기 아이콘으로 들어가져 있음

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5474]
![Image](https://github.com/user-attachments/assets/ef15949c-3f25-42b5-8046-de74c9bc04b7)

**Comment by sonohoshi** [comment]
https://github.com/planetarium/NineChronicles/issues/5390
중복+이미 진행된 건이라서 close합니다.

**Comment by boramqo83** [comment]
오호. 그렇군요.
감사합니다. @sonohoshi
