### ISSUE TITLE
추가한 캐릭터 스파인을 확인하는 방법 간편화하기

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#5484]
기존의 정리되었던 확인 방법 : https://www.notion.so/planetarium/Spine-852172cf205f43da8e7c3e33755bcd51?pvs=4#0e1e6df70e734adcb1fcb182fd1f961d

개발자가 아닌 스파인을 추가하는 작업자가 직접 쉽게 스파인을 확인할 수 있도록 확인 방법을 간편화 시켜야 함

**Comment by ipdae** [comment]
[ ] 아래의 데이터 시트에 코스튬 정보가 추가되는 명령어 생성
    - [ ] CostumeItemSheet
    - [ ] CostumeStatSheet
    - [ ]ItemRequirementSheet
