### ISSUE TITLE
커스텀 장비_스킬 정보 팝업 //가이드 작업 완료

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5491]
사용 프리퓁 : 
UI_SummonSkillsPopup 
UI_SkillInfolPopup
SummonSkillsCell

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/6fb142cf-c3a1-46bb-a669-64a86fe7dc7b)

- 리스트 안의 내용이 늘어자면 각 리스트의 틀 크기가 변경되도록 처리해 주었습니다.

**Comment by boramqo83** [comment]
소환의 i 버튼 눌렀을 때 뜨는 팝업의 경우 SummonDetailCell, Space를 켜주어 아이템 이름까지 나오도록 해 주세요.
/

![Image](https://github.com/user-attachments/assets/0d3135e0-f575-42a1-878b-c1939cc860ab)
- UI_SkillInfolPopup 요 프리퓁을 이용해서 소환의 i 버튼 눌렀을 때 팝업을 대체해 주거나
/

![Image](https://github.com/user-attachments/assets/ade7507d-ae0f-49e3-ab22-d3eabf57daad)
- UI_SummonSkillsPopup 기존에 사용되던 소환의 i 버튼눌렀을 때 뜨는 팝업을 수정하거나 해 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/26bb27d7-8d84-4ae3-9d55-fec087d6dfec)

- UI_SummonSkillsPopup 기존에 사용되던 프리퓁의 경우, 리스트 내용량에 따라 크기가 변경되도록 하는데에 문제가 있습니다.
- 새로 올려드린 UI_SkillInfolPopup 요 프리퓁을 사용하거나
- 기존에 사용하던 UI_SummonSkillsPopup 요 프리퓁을 사용하여 수정하거나 해 주세요.

**Comment by sonohoshi** [comment]
중복
