### ISSUE TITLE
워크샵 팝업_프리퓁 작업 //가이드 작업 완료

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5494]

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/workshop_popup_slot-add
사용 프리퓁 :

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/7454f38c-b19d-47c0-afb1-aa3318926569)

- 슬롯 4종이 추가되었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/99c98356-7691-4870-a103-29d979f9a52b)

- 추가된 4개의 슬롯은 각각 오픈에 필요한 재화가 따로 있습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/c6cec396-2928-4e4c-b94b-5d69704e8b1f)

- 잠겨있는 슬롯을 터치하면 UI_PaymentPopup 팝업을 켜주세요.
- 안에 들어가지는 내용은 변경되야 합니다. "새로운 워크샵 슬롯을 열기 원합니까?" 정도의 느낌
- 잠긴 슬롯이 열렸을 때 모습도 참고해 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/d657dde2-cafa-4e52-ad2f-c007b2e969ca)

- 슬롯을 오픈하려는데 재화가 부족할 경우 위와 같이 팝업을 띄워주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/75a21105-8b7e-4f5d-92db-5b6697ae69bf)

요 부분 어떻게 처리할지 고민

**Comment by boramqo83** [comment]
올 오픈 팝업 만들어야 함

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/0ffd5601-bfe4-471f-bd3a-0a38c175ab9e)

- 상단 이미지는 맨 앞의 장비가 어떤 작업(장비 제작, 음식 제작, 업그레이드, 커스텀 장비 제작) 진행 중인가에 따라 띄워주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/00e8e076-4deb-4aa0-8e28-e9918cd715e9)

프리퓁 이름 : UI_CombinationSlotPopup
- 상단 이미지는 변경되지 않고 망치 이미지 하나로 고정시켜 줍니다. (지금은 어떤 작업 진행 중인지에 따라 상단 아이콘 이미지가 변경되고 있습니다.)

**Comment by eugene-doobu** [comment]
작업 전달받았고, 아래 pr에서 같이 작업해두겠습니다. 해당 이슈는 close 해두겠습니다.
https://github.com/planetarium/NineChronicles/pull/5597

**Comment by boramqo83** [comment]
적용 브랜치 : feature/extend-craft-slot

![Image](https://github.com/user-attachments/assets/f953eb20-2d8e-4773-b6c1-ed48a18eefb6)

- 재화를 사용해서 슬롯을 활성할 때 로딩 상태 표시
- LockPrice : 눈을 꺼주세요.
- IndicatorAnimation : 눈을 켜주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/dcf1f1bc-6753-4155-abd8-9e26fd463ff9)

- Button : 작업이 끝나면 요거 삭제해 주세요.
- ConditionalButton_Type5 : 요 버튼을 사용해 주세요.
