### ISSUE TITLE
[워크샵] 강화 화면에서 노멀 등급 장비 선택 시 강화 경험치 상승 연출이 끊기는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5501]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
강화 화면에서 노멀 등급 장비 선택 시 강화 경험치 상승 연출이 끊기는 현상
- 노멀 등급 이외의 장비 선택 시 강화 경험치 연출이 정상적으로 출력되었습니다.
- Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/85056c11-47ed-41a9-984f-9b07f88963e5

해당 이슈 발생 시 로그 파일 공유드립니다.

[log.zip](https://github.com/user-attachments/files/16356190/log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 강화 진입
2. 노멀 등급의 장비 선택
3. 장비 선택 시 강화 경험치 상승 연출이 끊기면서 출력되는 것을 확인

[Should be]
강화 화면에서 노멀 등급 장비 선택 시 강화 경험치 상승 연출이 정상적으로 출력되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)

https://github.com/user-attachments/assets/bd9b52dd-bde3-4086-92f4-93912e186c88
