### ISSUE TITLE
[이벤트 던전] 희귀도가 더 낮은 이벤트 음식의 스탯이 더 높게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5504]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
희귀도가 더 낮은 이벤트 음식의 스탯이 더 높게 출력되는 현상
-오렌지 젤리가 현재 제일 높은 스탯을 보유하고 있습니다.
-Windows, Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/d246ad08-9853-49a7-8643-4bac934e2168)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 제작 클릭
2. 이벤트 아이템 탭 클릭
3. 이벤트 음식 스탯 확인 시 희귀도가 더 낮은 음식의 스탯이 더 높은 현상 확인

[Should be]
희귀도가 더 높은 이벤트 음식의 스탯이 높게 출력되어야 합니다.

**Comment by NineSyu** [comment]
스텟 데이터를 잘 못 넣어 생긴 이슈입니다. 데이터 수정하여 정상적으로 표시되게 수정하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)


![Image](https://github.com/user-attachments/assets/03cd6771-c79c-4af3-8b6d-198d17f79a82)
