### ISSUE TITLE
[이벤트 던전] 오렌지 메달이 획득 가능 아이템 목록에 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5508]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
오렌지 메달이 획득 가능 아이템 목록에 출력되지 않는 현상
-Windows, Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/140051cb-8285-4f5a-b926-a3f4119bc990)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 이벤트 던전 클릭
3. 이벤트 던전 지급 아이템 아이콘 확인
4. 오렌지 메달이 출력되지 않는 현상 확인

[Should be]
이벤트 던전 획득 아이템 목록에 오렌지 메달이 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 요것도 시트이슈로 보이는데 확인부탁드려요~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)

![Image](https://github.com/user-attachments/assets/034bf065-b38a-4a7f-a616-9fde2b585ce1)
