### ISSUE TITLE
[워크샵] 소환 확률 팝업에 키 값이 출력되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5510]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
루비 아우라, 루비 룬 소환 확률 팝업에서 키 값이 출력되는 현상
- 그리모어, 골든 아우라, 골든 룬, 노멀 아우라 소환 확률 팝업에서는 키 값이 출력되지 않습니다.
-Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/7de7934e-de46-4c10-95ee-76a3a17afc77

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 소환 화면에서 루비 아우라 탭 클릭
3. 소환 확률 버튼 클릭
4. 소환 확률 팝업에 소환명이 키 값으로 출력되는 것을 확인

[Should be]
루비 아우라, 루비 룬 소환 확률 팝업에서 키 값이 출력되지 않아야 합니다.

**Comment by tyrosine1153** [comment]
@NineSyu L10n 값으로 아래 키 값 추가 부탁드립니다, (+ summon_name.csv 기준으로는 레드 아우라, 레드 룬의 키가 잘못 맞춰져있는 것 같습니다.)
```
SUMMON_NAME_30001
SUMMON_NAME_30002
```

**Comment by NineSyu** [comment]
빠진 문구 추가하여 해결했습니다. 재접속 후 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)

![Image](https://github.com/user-attachments/assets/4be529d8-012e-4a6c-92b8-f89946eacc68)
