### ISSUE TITLE
[이벤트 던전] 이벤트 음식 제작 재료 수량이 기획서와 상이한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5511]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
이벤트 음식 제작 재료 수량이 기획서와 상이한 현상
-기획서 상에서는 5개로 작성되어 있으나 , 현재 1개로 출력되고 있습니다.
-Windows, Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/ce689a16-18ec-4a83-853a-431bf7c90aca)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 제작 클릭
2. 이벤트 아이템 탭 클릭
3. 이벤트 음식 제작 시 소모되는 수량 확인
4. 실제 소모되는 수량과 기획서 상 수량이 상이한 현상 확인

[Should be]
이벤트 음식 제작 시 소모되는 수량이 기획서와 일치해야 합니다.

**Comment by NineSyu** [comment]
제작에 필요한 수량을 잘못 적용한 이슈입니다. 수치 변경하여 정상적으로 표시되게 적용하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)

![Image](https://github.com/user-attachments/assets/ed12c48d-284d-432e-b2bd-cae8b8f1bd5f)
