### ISSUE TITLE
[워크샵] 비스트 아우라 미리보기가 실제 착용시와 다르게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5512]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
비스트 아우라 미리보기가 실제 착용시와 다르게 출력되는 현상
-실제 착용 시보다 더 큰 아우라로 출력되고 있습니다.
-Windows, Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/c5f40ff3-dd6e-44bd-ad25-483afb3781a8)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 아우리 탭 선택 - 확률 정보 버튼 클릭
3. 비스트 아우라 선택 시 출력되는 미리보기 확인
4. 미리보기와 실제 착용 시 이미지가 상이한 현상 확인

[Should be]
비스트 아우라 미리보기와 실제 착용 시 이펙트가 동일해야 합니다.

**Comment by tyrosine1153** [comment]
아우라는 장비 레벨에 따라 이펙트의 모양이 다르고, 팝업에서는 레벨이 최고값인 경우의 아우라 이펙트를 미리 보여줍니다.
위의 스크린샷에 보이는 아우라는 최고값인 경우의 아우라 이펙트와 같은 모습이고, 비스트 아우라는 아우라 레벨 별로 크기 차이가 나는 것을 확인했습니다.

즉, 정상 스펙으로 보입니다.

![Image](https://github.com/user-attachments/assets/f3355656-4ad2-43ff-aa21-19c3527cbd73)

**Comment by tyrosine1153** [comment]
확인 스레드 : https://planetariumhq.slack.com/archives/CR9EFE4H4/p1721807902280989

**Comment by QgamesGeonPyoNoh** [comment]
기획의도인 것을 확인하여 이슈 종료하겠습니다.

[테스트 환경]
Windows.v200210-210.0.2
Android.v200210-210.0.2
iOS.v210.0.2(97)
