### ISSUE TITLE
[워크샵] 소환 확률 팝업에서 아이템명과 확률 텍스트가 겹쳐서 출력되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5513]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
루비 아우라, 골든 아우라, 노멀 아우라 소환 확률 팝업에서 아이템명과 확률 텍스트가 겹쳐서 출력되는 현상
- Windows, Androids, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/7ba811ac-3126-4912-ade6-a18019bedda8

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 소환 화면에서 루비 아우라 탭 클릭
3. 소환 확률 버튼 클릭
4. 소환 확률 버튼 팝업에서 아이템명과 소환 확률 텍스트가 겹쳐서 출력되는 것을 확인

[Should be]
루비 아우라, 골든 아우라, 노멀 아우라 소환 확률 팝업에서 아이템명과 확률 텍스트가 겹쳐서 출력되지 않아야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)

https://github.com/user-attachments/assets/2fc0103e-0dbf-4a82-914d-4e2b22e171e0
