### ISSUE TITLE
[워크샵] 분해 화면에서 희귀도가 더 낮은 장비가 상단에 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5518]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
분해 화면에서 희귀도가 더 낮은 장비가 상단에 출력되는 현상
- 현재는 희귀도 상관없이 CP 순으로 출력되는 것으로 추정됩니다.
- Windows, Androids, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/d330b9a7-284f-4548-a87e-4f4e9658d3c6)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 분해 클릭
2. 인벤토리 내 정렬 상태 확인
3. 희귀도가 더 낮은 장비가 상단에 출력되는 현상 확인

[Should be]
분해화면에서 희귀도가 더 낮은 장비는 하단에 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
이거 정렬기준 관련 기획체크가 필요해보입니다~! @jaeho0103 @NineSyu

**Comment by jaeho0103** [comment]
분해시에는 희귀도가 낮은 장비가 더 위에 보이는게 의도된 스펙이 맞습니다.

**Comment by QgamesGeonPyoNoh** [comment]
정렬 개선은 강화 화면에만 적용되는 것으로 확인했습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200210-210.0.2
Android.v200210-210.0.2
iOS.v210.0.2(97)
