### ISSUE TITLE
[마켓] 헤임달에서 패키지 구매 시 상품이 지급되지 않는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5525]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
헤임달에서 패키지 구매 시 상품이 지급되지 않는 현상
- 오딘에서 패키지 구매 시 상품이 정상적으로 지급되는 것을 확인하였습니다.
- Androids, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/681b9cb8-2308-42ae-a391-a736cb57ef6a

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 마켓 클릭
2. 마켓에서 패키지 구매
3. 패키지 구매 후 상품이 지급 되지 않는 현상 확인

[Should be]
헤임달에서 패키지 구매 시 상품이 정상적으로 지급되어야 합니다.

**Comment by NineSyu** [comment]
@U-lis 현님! 이슈 체크 부탁드립니다!

**Comment by U-lis** [comment]
@ipdae @moreal  bridge 이슈인 것 같은데, 오후에 snapshot reset 한 것에 연관되어 nonce 이슈가 생기거나 한 게 있는지 확인 부탁드립니다 🙏

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200210-210.0.3
iOS.v210.0.3(98)

https://github.com/user-attachments/assets/87f14e60-b651-4f05-9b57-2584d0e933c0
