### ISSUE TITLE
에디터 테스트용 clo 데이터 갱신

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#5527]
현재 팀에 공유되어있는 에디터 테스트용을 위한 clo 데이터를 갱신합니다

**Comment by jonny-jeahyunchoi** [comment]
레포에 있는 clo데이터말씀하시는거면 보안상 서비스 url들 공개가 안되는것이 좋을것같다는 기존히스토리가있었던것으로 기억합니다.
저도 개발환경측면에서는 레포에 아에 올라가있는게 좋을것같다고 생각합니다~!

**Comment by tyrosine1153** [comment]
네트워크, 상황 별 clo의 정확한 값을 가져올 수 있도록 정리
1. 노션 문서로 정리
2. PlanetRegistry를 참조해 인자를 받아오는 슬랙봇을 만들기

**Comment by tyrosine1153** [comment]
https://www.notion.so/planetarium/clo-json-Command-Line-Options-preset-94b54ea8f9cf46be8b808338f1aa07d4

**Comment by tyrosine1153** [comment]
키워드로 노션 문서 링크를 공유하는 슬랙봇을 만들었고, 9c 팀 채널에 공유했습니다.
https://planetariumhq.slack.com/archives/CBU2JFAF3/p1722580595917059
