### ISSUE TITLE
[어드벤쳐 보스] 보상 수령 기한 안내가 2줄로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5529]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
보상 수령 기한 안내가 2줄로 출력되는 현상
- Windows 환경에서 확인 했습니다.

![Image](https://github.com/user-attachments/assets/7008344f-97b7-407f-a23b-b7dcc08241f3)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 어드벤쳐 보스 (오픈 상태) 클릭
3. 어드벤쳐 보스 보상 수령 기한 안내 텍스트가 2줄로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 보상 수령 기한 안내 텍스트가 1줄로 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 이거 기본문구길이가 블록표기 텍스트길이를 고려하지않은문장이라 문구 수정이 필요해보입니다~!

**Comment by NineSyu** [comment]
문구 수정하여 한줄로 보이게 하였습니다. 재접속 후 확인하시면 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by NineSyu** [comment]
수정해서 다시 올렸습니다! 일괄 적용하는 과정에서 누락된 것 같습니다.
재시작 후 체크하시면 정상적으로 출력되는 것을 확인할 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.3

![Image](https://github.com/user-attachments/assets/e21be1ca-038f-4861-a183-07160b76d738)
