### ISSUE TITLE
[어드벤쳐 보스] 이전 시즌 정보 팝업이 키 값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5532]
### APV version info

v200210

### Client version info

v210.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
이전 시즌 정보 팝업이 키 값으로 출력되는 현상
- Android, iOS 환경에서 확인 했습니다.

![Image](https://github.com/user-attachments/assets/2b50e622-8d6e-4db5-95c1-71ed294b3a0a)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 어드벤쳐 보스 이전 시즌 정보 버튼 클릭
3. 어드벤쳐 보스 이전 시즌 정보 팝업이 키 값으로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 이전 시즌 정보 팝업이 키 값으로 출력되지 않아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
이거 디폴트로 영어만 세팅되어있어서 한국어 문구 추가 작업 진행해주시면 될것같습니다~! @NineSyu

**Comment by NineSyu** [comment]
문구 추가했습니다. 재접속 후 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 최상단 팝업 제목 / 공헌도 영역 내 my reward가 키 값으로 출력되고 있습니다.
추가로, 출력되는 텍스트도 영문으로 출력되고 있습니다.
해당 부분 확인 부탁드립니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)

![Image](https://github.com/user-attachments/assets/510e7b23-78cb-4749-bf7d-ea7fb068eef3)

**Comment by NineSyu** [comment]
문구 오적용 및 누락하여 생긴 이슈입니다. 문구 다시 적용하였습니다. 재접속 후 다시 확인하시면 정상적으로 출력되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200210-210.0.3
iOS.v210.0.3(98)

![Image](https://github.com/user-attachments/assets/17069f63-d1f0-4078-82c9-71d282238873)
