### ISSUE TITLE
[워크샵] 강화 재료 자동 등록 버튼이 영문으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5533]
### APV version info

v200210

### Client version info

v210.0.2

### Device

iOS, Android

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
강화 재료 자동 등록 버튼이 영문으로 출력되는 현상
- Android, iOS 환경에서 확인 했습니다.

![Image](https://github.com/user-attachments/assets/9abda3b4-3e4e-4bbc-986b-6743e69e987c)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 강화 클릭
2. 강화 재료 자동 등록 버튼이 영문으로 출력되는 현상 확인

[Should be]
강화 재료 자동 등록 버튼이 한글로 출력되어야 합니다.

**Comment by NineSyu** [comment]
번역 문구가 적용되지 않아 생긴 이슈입니다. 수정하여 재적용했습니다. 재접속 후 정상적으로 출력될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200210-210.0.3
iOS.v210.0.3(98)

![Image](https://github.com/user-attachments/assets/e5fe65fc-b7d4-4d87-b5c2-57b7a4bcd4d7)
