### ISSUE TITLE
[어드벤쳐 보스] 결과 창에서 획득한 아이템이 3개까지만 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5542]
### APV version info

v200210

### Client version info

v210.0.3

### Device

Windows, iOS, Android

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
결과 창에서 획득한 아이템이 3개까지만 출력되는 현상
- Windows, Androids, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/791d4361-ac47-4b94-a9a2-394ca82b0136)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 어드벤쳐 보스 (오픈 상태) 클릭
3. 어드벤쳐 보스 진행
4. 결과 창에서 획득한 아이템이 3개까지만 출력되는 현상 확인

[Should be]
어드벤쳐 보스 결과 창에서 획득한 아이템이 모두 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu @U-lis 결과창은 최대 4개까지 아이템이 나올수있도록 되어있는데요 혹시 아직등록되지않은 룬이나 메터리얼, 룬, 크리스탈 요 3가지 타입이아닌경우는 안나오게될수있습니다 확인부탁드려요

**Comment by NineSyu** [comment]
데이터 문제로 보상이 정상적으로 적용되지 않았던 것을 확인했습니다!
데이터 패치를 진행하였습니다. 재접속 후 어드벤쳐 보스 진입 시 보상이 4종 표시되는 것을 확인할 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.3
Android.v200210-210.0.3
iOS.v210.0.3(98)

![Image](https://github.com/user-attachments/assets/97e929ee-aaf7-4348-8619-fc639fc68349)
