### ISSUE TITLE
[로그인] 계정 로그인 후 QR 코드 인식 단계에서 Back 버튼 클릭 시 로그인 UI가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5552]
### APV version info

v200210

### Client version info

v210.0.3

### Device

Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
계정 로그인 후 QR 코드 인식 단계에서 Back 버튼 클릭 시 로그인 UI가 출력되지 않는 현상
-인식 단계에서 에러 발생 시에도 동일 현상 발생합니다.
-Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/a9e41247-43ec-42c3-83fa-2b05c553b679

### How to reproduce the issue

[재현 스텝]
1. 모바일 기기 내 앱 설치
2. 연동된 구글 / 애플 계정 로그인 진행
3. 다른 기기의 QR로 가져오기 선택
4. 카메라 출력 후 Back 버튼 클릭
5. 로그인 UI가 출력되지 않는 현상 확인

[Should be]
QR 코드 인식 단계에서 Back 버튼 클릭 시 로그인 UI가 출력되어야 합니다.

**Comment by ipdae** [comment]
![Image](https://github.com/user-attachments/assets/669ac002-b558-461b-a04f-3d4d262cb3f1)

이상태로 돌아가야함

**Comment by jonny-jeahyunchoi** [comment]
@sonohoshi 요거 수정 진행하신것으로아는데 확인부탁드려요~!
아직수정안되어있다면 제가진행해보겠습니다~!
