### ISSUE TITLE
[워크샵] 장비 전체 경험치 수치와 추가되는 경험치의 차이가 클 경우 수치 애니메이션이 어색하게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5553]
### APV version info

v200210

### Client version info

v210.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
장비 전체 경험치 수치와 추가되는 경험치의 차이가 클 경우 수치 애니메이션이 어색하게 출력되는 현상
-해머 팝업에서도 동일하게 발생합니다.
-Windows, Androids, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/0a5b1914-2b8b-47c4-aa15-df7cfcf600d4

### How to reproduce the issue

[재현 스텝]
1. 메인 화면 - 워크샵 - 강화 클릭
2. 장비 경험치가 높은 장비 선택
3. 노말 등급 장비 재료로 등록
4. 장비 경험치 수치 애니메이션이 어색하게 출력됨

[Should be]
장비 경험치 수치 애니메이션이 어색함 없이 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
@QgamesGeonPyoNoh 영상에서 애니메이션이 어색하게 출력된다는게 처음에 나오는 모습을 말씀하시는 건가요, 아니면 그 이후에 나오는 모습을 말씀하시는 건가요?

**Comment by QgamesGeonPyoNoh** [comment]
재현 영상이 다른 영상으로 업로드 되어있어 수정했습니다.
혼란을 드려 죄송합니다.

해머의 경우 현재 경험치가 증가하여 해당 현상이 발생하고 있지 않습니다.

**Comment by jaeho0103** [comment]
경험치 바의 최소단위에 의해 애니메이션이 어색하게 보여지는건 바형태를 사용할때 상정한스펙안의 현상으로 취급하고 있습니다. 이슈는 종료 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
기획 의도임을 확인하여 이슈 종료하겠습니다.
