### ISSUE TITLE
[해머] 특정 등급 해머 등록 후 다른 등급 해머 클릭 시 처음에 등록한 해머 배너가 다른 해머로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5554]
### APV version info

v200210

### Client version info

v210.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
특정 등급 해머 등록 후 다른 등급 해머 클릭 시 처음에 등록한 해머 배너가 다른 해머로 출력되는 현상
-Windows, Androids, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/58b3e4b8-52e9-4793-bee6-dcb892534d2b

해당 현상 발생 시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16378009/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 강화 클릭
2. 임의의 장비 등록
3. A 등급 해머 클릭 후 등록 진행
4. B 등급 해머 클릭 후 팝업을 닫음
5. A 등급 해머 다시 클릭 시 B 등급 해머 팝업이 출력

[Should be]
특정 등급 해머 클릭 시 해당 등급의 해머 팝업이 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
수정하였습니다~ 다음 버전에서 확인 부탁드리겠습니다
https://github.com/planetarium/NineChronicles/pull/5557
