### ISSUE TITLE
해머 팝업 메터리얼 로그 정리

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#5555]
![image](https://github.com/user-attachments/assets/94afa044-e2f0-48f9-8be3-ca6941fca7fb)

**Comment by jonny-jeahyunchoi** [comment]
![image](https://github.com/user-attachments/assets/b0b86709-dd5f-4f59-95ad-803979b2e330)
![image](https://github.com/user-attachments/assets/bb6bf2ea-473c-4074-8af0-c5815f9e36eb)
![image](https://github.com/user-attachments/assets/b7d5a62e-8fa9-4bbc-959c-8a7a99208c03)
![image](https://github.com/user-attachments/assets/4f6768cc-ed91-4f9d-a25f-7aeb8e37f39f)

UI Particle에서 스텐실이 없는 다른 메터리얼을 사용해서 발생한 문제로 확인되었습니다.
