### ISSUE TITLE
[워크샵] PC 루비 아우라 소환 확률 팝업 상단에 Aure로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5558]
### APV version info

v200210

### Client version info

v210.0.4

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
PC 루비 아우라 소환 확률 팝업 상단에 Aure로 출력되는 현상
- Windows 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/f3b8f947-739c-4045-852f-c644453225f3)

### How to reproduce the issue

[재현 스텝]
1. PC 클라이언트 접속
2. 메인 로비 - 워크샵 - 소환 클릭
3. 루비 아우라 탭  - 소환 확률 클릭
4. 소환 확률 팝업 상단에 Aure로 출력되는 현상 확인

[Should be]
루비 아우라 소환 확률 팝업 상단에 Aure가 아닌 Aura로 출력되어야 합니다.

**Comment by NineSyu** [comment]
문구에 오타를 수정하여 다시 적용했습니다. 재접속 후 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200210-210.0.4

![Image](https://github.com/user-attachments/assets/0dd2a95e-c974-4173-8f14-49c47a5f265c)
