### ISSUE TITLE
[워크샵] 모바일 루비 아우라 / 루비 룬 소환 확률 팝업에 레드 아우라 / 레드 룬으로 출력되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5559]
### APV version info

v200210

### Client version info

v210.0.4

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
모바일 루비 아우라 / 루비 룬 소환 확률 클릭 시 노출되는 팝업에서 팝업 상단에 레드 아우라 / 레드 룬 텍스트가 출력되는 현상
- Androids, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/a2a315dd-896b-42e6-b3f0-4094c10c0dd3

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 루비 아우라 탭 클릭
3. 소환 확률 버튼 클릭
4. 출력된 팝업 상단에 '레드 아우라' 텍스트가 노출된 것을 확인

[Should be] 
모바일 루비 아우라 / 루비 룬 소환 확률 팝업에 루비 아우라 / 루비 룬 텍스트가 출력되어야 합니다.

**Comment by NineSyu** [comment]
문구를 레드에서 루비로 변경하여 다시 적용했습니다. 재접속 후 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200210-210.0.4
iOS.v210.0.4(99)

https://github.com/user-attachments/assets/3eae110e-f660-4f8b-bcc2-ac88fedf88ec
