### ISSUE TITLE
[어드벤쳐] Sweep 연출을 스킵할 수 있는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5560]
### APV version info

v200210

### Client version info

v210.0.4

### Device

Windows, Android

### detailed device info

Windows 10, Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Sweep 연출을 스킵할 수 있는 현상
-Windows에서는 ESC키 입력 시 연출이 스킵됩니다.
-Android 기기에서는 Back 버튼 클릭 시 연출이 스킵됩니다.
-Windows / Android 환경에서 확인했습니다.

https://github.com/user-attachments/assets/0e118cff-0f8c-4f41-8c3b-374a6ff0027f

해당 현상 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16385986/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 임의의 스테이지 클릭
2. Sweep 클릭 후 진행
3. Sweep 애니메이션 출력 시 Esc / Back 버튼 입력
4. Sweep 애니메이션이 스킵되는 현상 확인

[Should be]
Sweep 애니메이션이 스킵되지 않아야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 발생 확인했습니다.
확인 부탁드립니다.

이슈 발생 당시 Log 파일 공유드립니다.
[Log.zip](https://github.com/user-attachments/files/16744317/Log.zip)

[테스트 환경]
Windows.v200220-220.0.1
Android.v200220-220.0.1

https://github.com/user-attachments/assets/832e07ba-84b0-450c-9f60-470bb94a4f83

**Comment by eugene-doobu** [comment]
240에서 다시 확인 부탁드립니다~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1


https://github.com/user-attachments/assets/7a202ccb-1bbb-4896-b4fe-911bfd41c439
