### ISSUE TITLE
상점 price per unit 정렬에서 맞지 않는 값이 끼어있는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5563]
Price per Unit 오름차순으로 정렬했을때 안 맞는 경우가 생기는 것 같습니다.

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1722049746936819?thread_ts=1722049746.936819&cid=C062ZS68A21)

**Comment by ipdae** [comment]
https://github.com/planetarium/market-service/blob/main/MarketService/Controllers/MarketController.cs#L88-L89 필터에서 정렬을 unit price로만 정렬을 해서 그런것같습니다. 추가 조건으로 price도 추가해두면 될듯합니다.
