### ISSUE TITLE
PC shop 거래가능 아이템 대응(custom equipment)

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#5572]
Shop에 custom equipment관련 판매/구매를 할 수 있는 UI 추가

**Comment by eugene-doobu** [comment]
BuyView._toggleSubTypes

subType값을 기반으로 MarketServiceClient.GetBuyProducts로 아이템 조회

**Comment by eugene-doobu** [comment]
RegisterProduct

**Comment by eugene-doobu** [comment]
두 인터페이스간의 차이

**Comment by tyrosine1153** [comment]
- [ ] 샵 뷰 소팅 순서 변경
- [ ] 소팅 당 기본 오름/내림차순 설정
