### ISSUE TITLE
Update Grinding: add materials

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#5574]
lib9c issue : https://github.com/planetarium/lib9c/issues/2688
기획서(노션) : https://www.notion.so/planetarium/9c70cecb25814c9ab6a7d1612d0d507d

**Comment by tyrosine1153** [comment]
UI prefab issue : https://github.com/planetarium/NineChronicles/issues/5493

**Comment by tyrosine1153** [comment]
- UI 프리펩 대응
  - [x] AvatarInfoPopup와 Grind에서 공통적으로 override하고 있는 부분은 Apply해둔다.
  - [ ] 이후 GrindModule 안의 RectTransform 정리
  - [ ] Grind Animator를 Grind Module 안으로 이동

**Comment by jonny-jeahyunchoi** [comment]
@tyrosine1153 9c 이슈가 남아있는것으로 보이는데 필요한경우 신규이슈로 진행하면될것같습니다~!

**Comment by tyrosine1153** [comment]
넵! 감사합니다
