### ISSUE TITLE
[마켓] 헤임달 체인에서 결제한 상품이 지급되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5579]
### APV version info

v200210

### Client version info

v210.0.5

### Device

Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
헤임달 체인에서 결제한 상품이 지급되지 않는 현상
- Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/adde6b96-b5da-42e7-ac3d-7efe804fcd56

### How to reproduce the issue

[재현 스텝]
1. 헤임달 체인 / Mobile 환경 접속
2. 메인 로비 - 마켓 클릭
3. 임의의 상품 구매 진행
4. 결제한 상품이 지급되지 않는 현상 확인

[Should be]
헤임달 체인에서 구매한 상품이 지급되어야 합니다.

**Comment by U-lis** [comment]
internal bridge 가 정상적으로 처리되지 않는 것으로 보입니다. 확인해서 조치해두겠습니다.

**Comment by U-lis** [comment]
상품 잘 지급되는 것 확인했습니다. 체크 부탁드립니다.

**Comment by OHHyungGeun** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200210-210.0.5
iOS.v210.0.5(43)

https://github.com/user-attachments/assets/a976364b-5d85-4523-a9d1-cacf40175c63
