### ISSUE TITLE
[시즌 패스] 시즌 패스 칭호 설명 텍스트 깨짐 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5580]
### APV version info

v200210

### Client version info

v210.0.5

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌 패스 칭호 설명 텍스트 깨짐 현상
-Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/7ad9e758-895d-4540-8a0a-9ceca1d635eb)

### How to reproduce the issue

[재현 스텝]
1. Mobile 환경 접속
2. 메인 로비 - 시즌 패스 아이콘 클릭
3. 프리미엄 해제 버튼 클릭 - 팝업 출력
4. 팝업 내 칭호 아이콘 클릭 시 텍스트 깨짐 현상 확인

[Should be]
시즌 패스 칭호 설명 텍스트가 깨지지 않고 출력되어야 합니다.

**Comment by NineSyu** [comment]
칭호 문구의 범죄자를 대상으로 명칭을 변경하여 다시 적용했습니다.
재접속 후 정상적으로 표시되는 것을 확인할 수 있습니다.
