### ISSUE TITLE
푸시알림 오차 범위시간 로직 삭제

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#5583]
블록 시간이 많이 안정화돼서 오차 범위를 이제 안넣어도 될 것 같음.

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 이거 푸시알림 실행시간 관련해서 딱히 오차 범위관련 보정하는 로직이 없는것으로 파악됩니다. 각 타겟시간에 맞춰서 블록당초수를 https://github.com/planetarium/NineChronicles.LiveAssets/blob/main/Assets/Json/GameConfig.json 에 세팅된 값으로 가져와서계산하고있고 이외 다른 보정은 없는것으로 확인되는데 체크부탁드립니다~!

**Comment by jaeho0103** [comment]
그렇군요. 그럼 구현이 요청과는 다른 형태로 되어있었나보네요. 그럼 푸쉬의 오차가 왜 발생하는지 체크해봐야 할 것 같습니다.

**Comment by jonny-jeahyunchoi** [comment]
15프로 추가하는게 있다고함.

**Comment by jonny-jeahyunchoi** [comment]
- PUSH_ARENA_TICKET_CONTENT(아레나 입장권이 곧 모두 채워집니다) 아레나 티켓관련 PUSH에서 인위적으로 300블록만큼 시간을 당긴것이 있으나 의도로 보임 https://github.com/planetarium/NineChronicles/blob/6fb20f7085fe360e3c735ca4bbc0d2ebab7d6906/nekoyume/Assets/_Scripts/Game/Game.cs#L1195
- PUSH_WORLDBOSS_TICKET_CONTENT 월드보스 티켓관련도 인위적으로 300블록만큼 당김
이외에는 15프로정도 타겟블록을 보정하는등의 로직은 없는것으로 확인됩니다.
@jaeho0103

**Comment by jonny-jeahyunchoi** [comment]
딱히 수정해야되는 부분이 보이지않아 이슈 닫도록 하겠습니다
