### ISSUE TITLE
최초 통신 에러 메세지 수정 체크

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5584]
통신상태 에러일때 Commandline등으로 유저가 이해하기 어려운 상태의 에러메세지를 변경해서 표시해줍니다.

5분째 세번 껐켰해도 이렇게 나오는데 저만 이러는걸까요

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1722408504294849?thread_ts=1722408504.294849&cid=C062ZS68A21)

**Comment by ipdae** [comment]
- 저장소에 오류예외처리관련 번역어 포함해야함
- 네트워크 장애인것들 인식할 수 있게 핸들링 필요
