### ISSUE TITLE
강화재료 올린 후 스크롤 시 아이템이 지나치게 뻔떡거려서 버그처럼 보임

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#5593]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1722480177491359

**Comment by tyrosine1153** [comment]
기존에 존재하던 현상입니다.
강화 재료 슬롯이 꺼져있다가 보일 때 '등록' 애니메이션이 재생되는데, 애니메이터에서 재생 조건인 재료 등록과 스크롤을 넘겨서 화면에 보이는 상황을 구분하지 못하는게 원인이었던 것으로 기억합니다.
그라인드에서 사용하는 재료 슬롯 또한 같은 애니메이터를 사용하기 때문에 해당 현상이 재현됩니다.

**Comment by jaeho0103** [comment]
그럼 어떻게 해결해야 할까요?;;

**Comment by tyrosine1153** [comment]
애니메이터가 화면에 보일 때마다 초기화 되기 때문에 이전에 봤을 때는 쉽게 수정하는건 어려워 보여서 넘겼습니다.
좀 전에 머리 잡고 다시 봤을 때는... 애니메이터의 상태 머신을 대략 아래와 같이 수정하면 될 것 같습니다.
실제로 테스트는 해보지 않아서 그라인드 ui 작업 끝나고 마저 수정해서 적용하겠습니다.

as is
![image](https://github.com/user-attachments/assets/1d8b6479-7456-4a2e-b52c-47643ecbb2ca)
to be
![image](https://github.com/user-attachments/assets/d451717f-a537-4dcf-897c-90102340a124)

**Comment by tyrosine1153** [comment]
이방법으로 해결이 안될 것 같습니다. 애초에 스크롤 시 cell 이 보이는 것과 등록 후 새 아이템이 반짝여야하는 상황이 같은 코드로 호출됩니다.
