### ISSUE TITLE
어드벤처보스 리포트 클릭 포인트가 좀 작음. 약간 늘리기//개발없음

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#5594]

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/230.0.x
적용 브랜치 : ui/worldmap_touch_area-edit
사용 프리퓁  : UI_WorldMap

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/8fd7f90a-67ec-4d5b-8855-8c43c06401a5)
- 지난 시즌 리포트 버튼의 사이즈를 위 가이드 만큼 넓혀 주었습니다.
