### ISSUE TITLE
어드벤쳐 보스 승/패가 클라이언트와 실제결과가 다르다는 제보

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5598]
<!subteam^S01DCKBUM9D|@9c-dev>
<https://heimdall.9cscan.com/tx/d663c57807883d777e28d4b5f135452b2d14e9b6d36a94be6cf79ee480416f48>
어드벤쳐 보스에서 클라에서는 패배, 결과는 승리로 나온다는 제보인데
리플레이 한번 돌려봐주시면 감사하겠습니다. 비슷한 제보가 전에 dogfooding 채널에서도 있었습니다.

[Slack Message](https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1722564599300109)

**Comment by jonny-jeahyunchoi** [comment]
https://github.com/planetarium/NineChronicles/pull/5463 기존에 슬로스 영향으로 어드벤쳐 결과가 달라졌던부분과 동일한문제가 다른 시뮬레이터활용하는 부분에 적용이 아직안되어있는것이 원인으로 보임.
