### ISSUE TITLE
[로그인] 일부 백업한 QR코드가 '현재 기기의 QR로 가져오기'에서 인식되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5617]
### APV version info

v200210

### Client version info

v210.0.5

### Device

iOS

### detailed device info

iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
일부 백업한 QR코드가 '현재 기기의 QR로 가져오기'에서 인식되지 않는 현상
- '다른 기기의 QR로 가져오기'로 카메라 촬영 시에는 인식됩니다.
- iOS 환경에서 백업한 QR 코드입니다.
- Android, iOS 환경에서 모두 인식되지 않았습니다.

https://github.com/user-attachments/assets/751e4128-e331-41c9-bb6e-ba13717befbc

'현재 기기의 QR로 가져오기'에서 인식되지 않는 QR 코드 공유드립니다.

![Image](https://github.com/user-attachments/assets/319ef829-059e-4579-92b7-42a2c8a76ee5)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 설정 - 프라이빗 키 백업 진행
2. 재설치 후 키 임포트 클릭
3. 현재 기기의 QR로 가져오기 클릭
4. 백업한 QR 코드 선택 시 인식되지 않는 현상 확인

[Should be]
백업한 QR코드가 '현재 기기의 QR로 가져오기'에서 인식되어야 합니다.

**Comment by sonohoshi** [comment]
흠... 실제로는 정상적인 데이터가 있고 그 데이터를 읽어오는것도 문제가 없는데, 엉뚱한 데이터로 인식하는 것 같네요 왜인진 모르겠고

**Comment by sonohoshi** [comment]
확장자 문제는 아니고

**Comment by sonohoshi** [comment]
와 이거 어떻게하지

**Comment by sonohoshi** [comment]
jfif가 문젠가?

**Comment by sonohoshi** [comment]
사이즈 문제인 것 같고

**Comment by sonohoshi** [comment]
@QgamesGeonPyoNoh 이거 다음 버전(v200220)부터 새로 생성한 QR코드는 이런 문제 없을 것으로 예상되는데, 다음 QA때 체크해주시면 되겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 추가 발생하지 않아 이슈 종료하겠습니다.

[테스트 환경]
Android.v200220-220.0.0
iOS.v220.0.0(101)
