### ISSUE TITLE
도면과 제도 도구에 재료 획득처 추가

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#5632]
https://www.notion.so/planetarium/UI-3ffd3227c37d4d26b82d62a4fd84736f?pvs=4#f41bd52f3ff7478baab0acc8a6acde18

#5492

**Comment by tyrosine1153** [comment]
- [x] 어드벤처 보스 바로가기 구현 https://github.com/planetarium/NineChronicles/pull/5758
  - [x] 스크롤, 서클에 바로가기 적용
- [ ] 월드 보스 바로가기 구현
  - [ ] 스크롤, 서클에 바로가기 적용

**Comment by tyrosine1153** [comment]
- [ ] 그라인드 바로가기 구현
  - [ ] 스크롤 서클에 적용
