### ISSUE TITLE
어드벤쳐 보스 도전시 획득가능 보상 및 획득 보상 리스트 최대 8종까지 지원

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#5647]
### APV version info

v200220

### Client version info

v220.0.0

### Device

Windows

### account address info

all account

### What happened?

어드벤쳐 보스의 챌린지와 돌파에서 획득가능 재료 및 획득한 재료가 최대 8개까지 나올수 있도록 대응 부탁드립니다.

### How to reproduce the issue

1. Click Button
2. Crash

**Comment by jonny-jeahyunchoi** [comment]
UI 레이아웃 나와야하는 이슈로 @boramqo83 님도 같이 걸어둡니다~!

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/adventureboss_reward8-edit
사용 프리퓁 : 
UI_AdventureBossBattlePopup
UI_AdventureBossResultPopup
/
![image](https://github.com/user-attachments/assets/00d37b0d-1601-47a1-abfc-71fcf275cf28)
![image](https://github.com/user-attachments/assets/80049cd0-7a53-4210-8df4-f3346ab77d9f)
- 보상이 8개가 나올 수 있도록 프리퓁 수정해 주었습니다.
- 작업해서 올려두었으니 머지 후 작업 부탁드립니다.
