### ISSUE TITLE
GetStateByBlockHash 대신 GetStateByStateRootHash 를 사용하도록 변경

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#5653]
- [ ] 클라이언트에서 호출되는 GetState 내부동작을 GetStateByBlockHash대신 GetStateByStateRootHash 사용
- [ ] GetStateByBlockHash 사용하는곳 삭제 및 변경

**Comment by jonny-jeahyunchoi** [comment]
RPCAgent에서 OnRenderBlock 주기마다 StateRootHash 캐싱 및 기존 GetState동작에서 캐싱된 RootHash사용하도록 변경하는방향으로 진행

**Comment by eugene-doobu** [comment]
첫 OnRenderBlock 실행 전에 GetStateByBlockHash 가 호출될 수 있을까요? 아바타 초기화 과정에서 상태 마이그레이션때 GetStateByBlockHash 을 써야할 것 같아 질문드립니다

**Comment by jonny-jeahyunchoi** [comment]
내부적으로 캐싱된 StateRootHash 가 없을경우 기존 GetStateByBlockHash 를 호출하는식으로 진행할예정이에요

**Comment by jonny-jeahyunchoi** [comment]
이거 보니 이미 캐싱하고있는 roothash가 있어서 그것활용하는방식으로 수정하였습니다.
