### ISSUE TITLE
[월드보스] 월드보스 전투가 간헐적으로 진행되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5686]
### APV version info

v200220

### Client version info

v220.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
월드보스 전투가 간헐적으로 진행되지 않는 현상
- 펜리르 / 제림니르 모두 발생 확인했습니다.
- Windows / Android / iOS에서 발생 확인했습니다.

https://github.com/user-attachments/assets/38f1b96f-b58b-4904-9b79-6ca6a96f30db

해당 이슈 발생 시 Log 파일 공유 드립니다.

[Log.zip](https://github.com/user-attachments/files/16701103/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 월드보스 클릭
2. 월드보스 입장
3. 간헐적으로 월드보스 전투가 진행되지 않는 현상 확인

[Should be]
월드보스 전투 진행 시 정지되지 않아야 합니다.

### Relevant log output

iOS / Odin 체인 / 월드보스 펜리르에서 확인된 로그 공유드립니다.
Andorid / Heimdall 체인 / 월드보스 제림니르에서도 유사한 로그 출력되었습니다.

NullReferenceException: Set `doubleattack_m_normal` first in ObjectPool.
Nekoyume.Game.Util.ObjectPool+Impl.Create (System.String objName, UnityEngine.Vector3 position) (at <00000000000000000000000000000000>:0)
Nekoyume.Game.Util.ObjectPool+Impl.Get (System.String objName, System.Boolean create, UnityEngine.Vector3 position) (at <00000000000000000000000000000000>:0)
Nekoyume.Game.VFX.Skill.SkillController.Get[T] (Nekoyume.Game.Character.Character target, Nekoyume.Model.BattleStatus.Skill+SkillInfo skillInfo) (at <00000000000000000000000000000000>:0)
Nekoyume.Game.Character.RaidCharacter+<CoDoubleAttack>d__50.MoveNext () (at <00000000000000000000000000000000>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)

**Comment by eugene-doobu** [comment]
아래 pr에서 에셋 로드방식을 수정하였습니다. 220.0.1 빌드에서 확인 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/5692

**Comment by QgamesGeonPyoNoh** [comment]
월드보스 전투 진행 시 해당 이슈 추가 발생하지 않았습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200220-220.0.1
Android.v200220-220.0.1
iOS.v220.0.1(102)
