### ISSUE TITLE
[인트로] 인트로 씬 종료 후 검은 화면에 캐릭터가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5687]
### APV version info

v200220

### Client version info

v220.0.0

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
인트로 씬 종료 후 검은 화면에 캐릭터가 떠있는 이미지가 출력되는 현상
- Windows 환경에서는 확인 후 공유 드리겠습니다.
- Android / iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/e2d9d351-5630-4411-82c5-ab833a1390fd

### How to reproduce the issue

[재현 스텝]
1. 앱 설치 후 최초 로그인
2. 인트로 씬 출력 확인
3. 인트로 씬 종료 후 검은 화면에 캐릭터가 출력되는 현상 확인

[Should be]
인트로 씬 종료 후 캐릭터 선택 화면이 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
시놉시스 또는 게임 로딩 후 캐릭터 선택 또는 게임 진입까지 갈 때 씬 이동하는 데에 보여주는 UI가 아무것도 없어서 발생함.
await가 걸리는 부분에 LoadingScreen을 추가했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.3
Android.v200220-220.0.3
iOS.v220.0.3(104)

https://github.com/user-attachments/assets/74984dba-f26d-432d-83f0-450799068994
