### ISSUE TITLE
[이벤트] 350 스테이지에서 크리스탈 장비 재료가 6개만 지급되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5688]
### APV version info

v200220

### Client version info

v220.0.0

### Device

Windows, iOS, Android

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
350 스테이지에서 크리스탈 장비 재료가 6개만 지급되는 현상
- 기획서 상에는 8개로 기재되어 있습니다.
- Windows / Android / iOS에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/8942863d-3d32-4f84-828e-302d4b533f4f)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 7월드 클릭
2. 350 스테이지 진입
3. 350 스테이지 클리어 후 결과 팝업 확인
4. 크리스탈 장비 재료가 6개만 지급되는 현상 확인

[Shoulde be]
350 스테이지 클리어 시 크리스탈 장비 재료가 8개 지급되어야 합니다.

**Comment by jaeho0103** [comment]
획득재료수량이 아닌 등장 확률로 밸런스 조정한 부분으로 스펙 변경된 부분입니다. 기획문서 업데이트 해두겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
기획 의도인 부분으로 확인되어 이슈 종료하겠습니다.

[테스트 환경]
Windows.v200220-220.0.0
Android.v200220-220.0.0
iOS.v220.0.0(101)
