### ISSUE TITLE
[어드벤쳐] 어드벤쳐에서 특정 스킬 사용 시점에 전투가 정지되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5689]
### APV version info

v200220

### Client version info

v220.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
특정 스킬 사용 시점에 전투가 정지되는 현상
- 캐릭터나 몬스터의 특정 모션 출력 시점에 정지 후 수 초 후 다시 재개되었습니다.
- Windows / Android / iOS 환경에서 발생 확인했습니다.
- 해당 이슈 발생 시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16703580/Log.zip)

https://github.com/user-attachments/assets/0ed4836e-535b-4204-8c5b-ba05378e891c

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 임의의 스테이지 진입
3. 특정 스킬 사용 시점에 전투가 정지되는 현상 확인

[Should be]
어드벤쳐 진행 시 특정 스킬 사용 시점에 전투가 정지되지 않아야 합니다.

**Comment by eugene-doobu** [comment]
아래 pr에서 에셋 로드방식을 수정하였습니다. 220.0.1 빌드에서 확인 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/5692

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.1
Android.v200220-220.0.1
iOS.v220.0.1(102)

https://github.com/user-attachments/assets/20391655-927a-43fa-84d6-879f2332b5d0
