### ISSUE TITLE
[시즌패스] 시즌패스 경험치가 지급되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5690]
### APV version info

v200220

### Client version info

v220.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌패스 경험치가 지급되지 않는 현상
- 어드벤쳐 / 아레나 / 월드보스 모두 지급되지 않고 있습니다.
- Windows / Android / iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/2a2eb191-a9da-4219-a71e-dff62a40f58b

해당 현상 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16703636/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 시즌패스 클릭
2. 시즌패스 1레벨 경험치 0 확인
3. 임의의 컨텐츠 진행
4. 시즌패스 경험치가 지급되지 않는 현상 확인

[Should be]
컨텐츠 진행 시 시즌패스 경험치가 지급되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
시즌패스경험치는 서비스에서 부여하는것으로 알고있어서 갱신 시간이 좀걸리는것으로 알고있습니다. @U-lis 확인부탁드려요~!

**Comment by U-lis** [comment]
확인 결과 heidmall 에서만 발생하고 있었을 것 같습니다. season pass heimdall internal DB 의 block index 값이 현재 설정된 internal network 보다 앞서나가 있었습니다. 조치 완료해 현재 경험치 잘 수집되고 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.0
Android.v200220-220.0.0
iOS.v220.0.0(101)

https://github.com/user-attachments/assets/47c0fefa-275a-40db-929f-1739c832eb91
