### ISSUE TITLE
[어드벤쳐 보스] 도전/돌파 선택 팝업 내 '랜덤 보상' 텍스트가 두 줄로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5694]
### APV version info

v200220

### Client version info

v220.0.0

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
도전/돌파 선택 팝업 내 '랜덤 보상' 텍스트가 두 줄로 출력되는 현상
- Windows 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/936b3be0-d792-4f5b-874f-01b04eafbef9)

![Image](https://github.com/user-attachments/assets/24340b9f-d7d1-4a25-a2e7-4b8bbfe6a004)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 (오픈) 클릭
2. 입장 버튼 클릭 - 도전/돌파 선택 팝업 출력
3. '랜덤 보상' 텍스트가 두 줄로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 도전/돌파 팝업 내 '랜덤 보상' 텍스트가 한 줄로 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
@boramqo83 지금 해당 이슈 대응이 어려우시면 제가 대신 할까요?

**Comment by boramqo83** [comment]
아. 네. 부탁드립니다. @tyrosine1153

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.3

![Image](https://github.com/user-attachments/assets/22b88ed1-2588-4395-9029-f757a46e9050)
