### ISSUE TITLE
[아레나] 헤임달에서 아레나 공격 대상이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5696]
### APV version info

v200220

### Client version info

v220.0.0

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
헤임달에서 아레나 공격 대상이 출력되지 않는 현상
- Windows / Android / iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/ee6077a4-7486-4f71-9e1a-c459ad3051fa)

해당 이슈 발생 시 Log 파일 공유드립니다.

[Log_Heimdall.zip](https://github.com/user-attachments/files/16706999/Log_Heimdall.zip)

### How to reproduce the issue

[재현 스텝]
1. 헤임달 체인 접속
2. 메인 로비 - 아레나 클릭
3. 아레나 입장 시 공격 대상이 출력되지 않는 현상 확인

[Should be]
헤임달 체인에서 아레나 입장 시 공격 대상이 출력되어야 합니다.

**Comment by jaeho0103** [comment]
저도 최근에 가끔 겪는 현상입니다.
몇분 지나서 재시도하면 정상적으로 되긴 했습니다.

**Comment by ipdae** [comment]
@QgamesGeonPyoNoh 서비스 동기화에 문제가 있는듯하고 재실행해서 현재는 목록이 표시되는걸로 확인됩니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.0
Android.v200220-220.0.0
iOS.v220.0.0(101)

![Image](https://github.com/user-attachments/assets/3094540a-78cd-4ae0-a063-919042b3b0cb)

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 오딘 / 헤임달 모두 발생 확인되었습니다.
확인 부탁드립니다.

해당 현상 발생 당시 Log 파일 공유드립니다.
[Log.zip](https://github.com/user-attachments/files/16743079/Log.zip)

[테스트 환경]
Windows.v200220-220.0.1
Android.v200220-220.0.1
iOS.v220.0.1(102)
![image](https://github.com/user-attachments/assets/3350c7b4-ea4f-4e63-9d58-d6b47d09c31e)

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 현재 발생하지 않아 종료하겠습니다.

[테스트 환경]
Windows.v200220-220.0.1
Android.v200220-220.0.1
iOS.v220.0.1(102)
