### ISSUE TITLE
커스텀 제작 폴리싱_슬롯에 레드닷 적용

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5705]

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/b17f1714-47a1-4ced-84dd-77d1037d1c36)

- 만들 수 있는 새로운 장비가 열렸을 때 레드닷을 켜 주세요.
- 얼마동안 켜져 있을지는 재호님께 문의해 주세요.

**Comment by sonohoshi** [comment]
이거 일단 프리팹은 머지된 상태라서 merge로 옮길게요
