### ISSUE TITLE
[워크샵] 소환 결과 화면에서 아이콘 클릭 시 정보 팝업이 출력되지 않는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5717]
### APV version info

v200220

### Client version info

v220.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
소환 결과 화면에서 아이콘 클릭 시 정보 팝업이 출력되지 않는 현상
- 노멀 아우라, 골든 아우라, 골든 룬 소환에서 발생하는 것을 확인하였습니다.
- Windows / Android / iOS에서 발생 확인했습니다.

https://github.com/user-attachments/assets/bc9b18aa-5c34-40a4-b771-4466e6c48fa0

해당 이슈 발생 당시 Log 파일 공유드립니다.

[log.zip](https://github.com/user-attachments/files/16743050/log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 클릭
2. 워크샵 화면에서 소환 버튼 클릭
3. 소환 화면에서 노멀 아우라 탭 클릭 후 소환 진행
4. 소환 결과 화면에서 아이콘 클릭 시 정보 팝업이 출력되지 않는 것을 확인

[Should be]
소환 결과 화면에서 아이콘 클릭 시 정보 팝업이 정상적으로 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
Payment Popup이 SummonResultPopup보다 낮은 위치에 있어서 가려지는것이 원인

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.3
Android.v200220-220.0.3
iOS.v220.0.3(104)

![Image](https://github.com/user-attachments/assets/c97f29bb-679f-4a9f-8ef7-508f52b14fad)
