### ISSUE TITLE
[시즌패스] 시즌패스 10 칭호 이름이 위대한 모험가 10으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5724]
### APV version info

v200220

### Client version info

v220.0.1

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌패스 10 칭호 이름이 위대한 모험가 10으로 출력되는 현상
- 기획서 상에는 Odin’s warrior로 작성되어 있습니다. 기획의도 확인 부탁드립니다.
- Android / iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/6dffff23-4b16-4582-a3fb-63e9edfa8b5a)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 시즌패스 클릭
2. 해제하기 버튼 클릭
3. 프리미엄 해제 팝업 내 칭호 아이콘 클릭
4. 칭호 이름이 위대한 모험가 10으로 출력되는 현상 확인

[Should be]
시즌 패스 칭호 이름이 Odin’s warrior로 출력되어야 합니다.

**Comment by NineSyu** [comment]
odin's warrior 로 표시되게끔 수정하여 갱신하였습니다.
재접속 후 확인하시면 변경된 이름을 확인하실 수 있습니다!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200220-220.0.1
iOS.v220.0.1(102)

![Image](https://github.com/user-attachments/assets/e883543e-6d95-457a-a94f-a102874c1f47)
