### ISSUE TITLE
[워크샵] 소환 결과 화면에서 확인 버튼 클릭 시 재화 부족 팝업이 출력되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5725]
### APV version info

v200220

### Client version info

v220.0.1

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
소환 재화가 부족한 상태에서 소환 결과 화면의 확인 버튼 클릭 시 재화 부족 팝업이 출력되는 현상
- 소환 재화가 부족한 상태에서 소환 결과 화면의 소환 버튼 클릭 시 팝업이 출력되지 않는 것을 확인하였습니다.
- Android / iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/f0f3240c-c0b3-4755-b2cf-c062fb46c119

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 클릭
2. 워크샵 화면에서 소환 버튼 클릭
3. 소환 화면에서 실버 더스트를 10개 보유한 상태로 소환 1회 진행
4. 소환 결과 화면에서 소환 버튼 터치 시 재화 부족 팝업이 출력되지 않는 것을 확인
5. 소환 결과 화면에서 확인 버튼 터치 시 재화 부족 팝업이 출력되는 것을 확인

[Should be]
소환 재화가 부족한 상태에서 소환 결과 화면의 확인 버튼 클릭 시 재화 부족 팝업이 출력되지 않아야 합니다.

**Comment by tyrosine1153** [comment]
SummonResultScreen이 툴팁보다 위에 있어서 가려지는 것이 원인

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 추가로 발생하지 않아 이슈 종료 하겠습니다.

[테스트 환경]
Android.v200220-220.0.3
iOS.v220.0.3(104)
