### ISSUE TITLE
[아레나] 레이팅 점수가 -100점 이하로 차이나는 유저의 프로필이 리스트에 노출되는 현상

### ISSUE THREAD

**Issue by OHHyungGeun** [planetarium/NineChronicles#5734]
### APV version info

v200220

### Client version info

v220.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
레이팅 점수가 -100점 이하로 차이나는 유저의 프로필이 리스트에 노출되는 현상
- 레이팅 점수가 1160점일 때 1194~1000점의 유저가 리스트에 노출되는 것을 확인하였습니다.
- Windows / Android / iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/aac666a2-3ec7-48ef-a08d-6b9d4dbdf3cf

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 아레나 클릭
2. 아레나 입장
3. 레이팅 보드에 점수가 -100점 이하로 차이나는 유저의 프로필이 노출되는 것을 확인

[Should be]
아레나 레이팅 보드에 레이팅 점수가 200점 이상 -100점 이하로 차이 나는 상대가 출력되지 않아야 합니다.

**Comment by ipdae** [comment]
@OHHyungGeun 네트워크가 오딘일까요 헤임달일까요?

**Comment by OHHyungGeun** [comment]
@ipdae 오딘에서 발생했습니다.

**Comment by OHHyungGeun** [comment]
> [@OHHyungGeun](https://github.com/OHHyungGeun) 네트워크가 오딘일까요 헤임달일까요?

오딘에서 발생했습니다.

**Comment by ipdae** [comment]
@OHHyungGeun 점수 저장 기록 방식에 문제가 있어서 유저 점수를 제대로 못가져오는 문제가 있었고 수정해서 서비스를 배포해뒀습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200220-220.0.3
Android.v200220-220.0.3
iOS.v220.0.3(104)

![Image](https://github.com/user-attachments/assets/7a0282c6-48d7-45d3-beba-5be64c369622)
