### ISSUE TITLE
커스텀 제작_폴리싱_스파인에 칭호 안보이게

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5737]

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/da247eda-2207-43f5-b015-7d98a0e2ecb8)

- 캐릭터 스파인 머리 위에 칭호 빼주세요.
- 캐릭터가 밟고 서 있는 바닥 판은 빼 주었습니다.

**Comment by sonohoshi** [comment]
이거 이미 안나오는 상태라서 close하겠습니당
