### ISSUE TITLE
커스텀 제작_폴리싱_구간언락 버튼 안에 적용

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5738]

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/de1fb1a1-fadf-4c48-88a3-9f5ba289645a)

- 구간 언락에 대한 추가 비용을 버튼 안에 넣어주었습니다.
- NCG, 루비더스트, 골든더스트 중 소비 재화를 켜 주세요.

**Comment by sonohoshi** [comment]
메모: 일단 골든더스트를 요구하니까 골든더스트를 만들어놨는데, 레드 더스트는 코드 작업을 해야하는 상태임
