### ISSUE TITLE
커스텀 제작_폴리싱_리스트 가로로 7개 배치되도록 처리

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5741]

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/600b946f-ad38-4b7e-9b0a-4002daf0fdd0)

- 프리퓁에서 수정이 안되는 군요.
- 요거 가로로 7개가 들어가지도록 처리해 주세요.

**Comment by sonohoshi** [comment]
![image](https://github.com/user-attachments/assets/a286ce50-265d-4a36-9a0c-3685591d908a)
요래 수정됐습니다.
