### ISSUE TITLE
커스텀 제작 가능한 외형에 레드닷 붙이기

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#5753]
제작할 수 있는 외형들 중 요구 친밀도가 현재 친밀도 - 10 이내인 외형들에 레드닷을 붙이면 된다

**Comment by tyrosine1153** [comment]
https://github.com/planetarium/NineChronicles/issues/5802 <- 이 이슈와 겹치는 것 같습니다.
