### ISSUE TITLE
커스텀 제작 감정 결과 팝업 연출

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5760]
리소스 위치
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=76516761

**Comment by boramqo83** [comment]
- 사용 프리퓁 : UI_CustomCraftEvaluationCompletedPopup

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/7f902126-0bed-4a80-bdb1-6b8790ab399a)

- 감정이 완료 되면 위 팝업을 띄워줍니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/d36a7b96-861a-45dc-a057-44fb5a060ebe)

- 애니메이션은 3개로 이루어져 있습니다.
- UI_CustomCraftEvaluationCompleted@Loop : 등장 연출이 끝나면 루프로 연결시켜 줍니다.
- UI_CustomCraftEvaluationCompleted@Show : 랜덤이 아닌 장비 제작을 눌렀을 때 시작되는 연출입니다.
- UI_CustomCraftEvaluationCompletedRandom@Show : 랜덤 제작을 눌렀을 때 시작되는 연출입니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/f7926944-61ad-4d7d-aa39-2ca35b0a7994)



![Image](https://github.com/user-attachments/assets/5769e628-836f-4b94-bfaf-efb2f92171f6)


https://github.com/user-attachments/assets/0d4163c7-3286-4751-8dda-4630530f4569


- UI_CustomCraftEvaluationCompleted@Show , UI_CustomCraftEvaluationCompleted@Show 등장 연출의 해당 프레임에 이펙트가 나오도록 처리해 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/5df92036-e552-42bc-a86b-49837d5be203)



https://github.com/user-attachments/assets/de0ecc74-4813-4ec7-a035-dd7edd288320

- UI_CustomCraftEvaluationCompleted@Loop 루프 연출에서 90, 105, 120, 135 프레임에 스텟 등장 연출 나오도록 해 주세요.
- 이해를 돕기위해 영상 올려드립니다.

**Comment by sonohoshi** [comment]
이거 세세한 연출을 지금 당장 작업하기엔 밀린 이슈가 많아서, 연출 관련 정리는 추가 이슈로 만들어서 다음주 중으로 작업하도록 하겠습니다.
