### ISSUE TITLE
[UI] 패치노트 내 텍스트가 꺠져서 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5765]
### APV version info

메인넷.v200220

### Client version info

v220.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
패치노트 내 텍스트가 꺠져서 출력되는 현상
- Windows의 경우 시즌패스 내용의 쉼표 뒤로 공백이 출력되고 있습니다.
- 모바일 환경의 경우 일부 텍스트가 사각형 형태로 출력되고 있습니다.

![Image](https://github.com/user-attachments/assets/29fb4940-7efd-4064-8d86-ebbb3b12cf1d)

![Image](https://github.com/user-attachments/assets/dda744d0-3725-461a-a520-1e593b107c10)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 햄버거 버튼 - 공지사항 클릭
2. 패치 노트 탭 클릭
3. v200220 패치노트 확인 시 텍스트가 깨져서 출력되는 현상 확인

[Should be]
v200220 패치노트 내 텍스트가 깨지지 않고 출력되어야 합니다.

**Comment by jaeho0103** [comment]
수정 완료했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200220-220.0.3
iOS.v220.0.3(104)

![Image](https://github.com/user-attachments/assets/d6facc0d-5360-47a1-904b-4f726ff5ba1d)
