### ISSUE TITLE
커스텀 제작 메일의 텍스트를 기존 제작 메일과 구분해야함

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#5800]

**Comment by sonohoshi** [comment]
지금 MailExtensions에서 ToInfo를 돌릴때 CustomCraftMail과 CombinationEquipmentMail의 번역 내용이 같은 l10n key를 사용중입니다. 이게 지금 코드에서 분기는 쳐져있는데 내용을 복붙하기만 한거라 그걸 수정해주시면 될거같습니다

**Comment by tyrosine1153** [comment]
@sonohoshi 텍스트만 수정하면 되나요? 버튼이나 NPC 아이콘은 따로 더 볼 필요 없을까요?

**Comment by sonohoshi** [comment]
@tyrosine1153 네 메일 아이콘은 구분되고 있고 버튼은 제가 따로 작업하면 되는 일입니다. ToInfo만 고쳐주시면돼요
