### ISSUE TITLE
커스텀 크래프트 메뉴에 빨콩 조건을 관리해줘야함

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#5802]

**Comment by tyrosine1153** [comment]
@sonohoshi reddot 조건이 포함된 문서가 혹시 있을까요?

**Comment by tyrosine1153** [comment]
@jaeho0103 커스텀 제작의 Red Dot 조건에 대한 설명이 기획서에 있나요?

**Comment by sonohoshi** [comment]
아 확인이 늦었습니다 죄송합니다 @tyrosine1153 
이거 구두로만 이야기했던 내용이라 저도 기억이 안나서 재호님이 답변해주셔야할거같아요

**Comment by jaeho0103** [comment]
아뇨 지금 추가해두겠습니다.
내용은 다음과 같습니다.

- 커스텀 메뉴 레드닷
제작이 1개이상 가능한 재료가 있으면 레드닷 표시
- 커스텀 메뉴 개별 스킨 레드닷
두번째 이후의 친밀도 구간이 열리고 5번의 제작이 진행될때까지 신규 구간 외혀엥 전부 레드 닷 표시
(제작해도 사라지지 않고, 친밀도가 올라야 사라짐)
