### ISSUE TITLE
커스텀 제작_폴리싱_NPC스파인 수정

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5814]
리소스 위치
https://github.com/orgs/planetarium/projects/97/views/8?pane=issue&itemId=76516761

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/144049fa-fda1-4054-b7ec-ac9ec88b7623)


- 등장과 사라지는 애니메이션이 추가되었습니다.

**Comment by sonohoshi** [comment]
했습니다
