### ISSUE TITLE
커스텀 크래프트_폴리싱_#4_리스트 가로 간격 넓히기

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5854]

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/e4666c96-6b08-42bf-803a-d83e2259d163)

- 왼쪽 리스트 바닥의 가로 범위를 느려주었습니다.
- 기존 간격이 너무 붙어있는 것 같으니 지금보다 5픽셀 더 간격을 적용해 주세요. (프리퓁에서 적용 불가)

**Comment by sonohoshi** [comment]
이거 간격을 프리팹에서 적용 못하면 코드에서도 불가능할거같은데 😂 확인해보겠습니다

**Comment by sonohoshi** [comment]
![Image](https://github.com/user-attachments/assets/9ab082d1-7fda-4bfb-af92-e1e7e5048a7d)
진짜 억지로 조금 더 늘렸습니다.
