### ISSUE TITLE
커스텀 크래프트_폴리싱_#4_스텟표기 변경

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5858]

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/fa14f349-e33d-4d1c-8953-dcc766aa4091)

- 서브 스텟 CP 하단에 ATK, DEF, HP, SPD, HIT의 맥스 값을 %가 아닌 최대 획득 가능한 수치를 표기하는 것으로 수정합니다.

**Comment by sonohoshi** [comment]
메인 스탯 말고 서브스탯도 전부 다 최대 스탯 표시해주려면 UI 코드 작업이 더 필요한데 음... 일단 메인스탯만 먼저 적용해놓고 서브스탯은 잠깐 고민 좀 해보겠습니다.

**Comment by sonohoshi** [comment]
![Image](https://github.com/user-attachments/assets/0d3aeb33-d58c-48cc-be05-6aaf9de2fd18)
