### ISSUE TITLE
커스텀 제작_추가 무기 리소스 등록/추가개발 없음

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#5890]

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/230.0.x
적용 브랜치 : ui/20161023-26_resource_add

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/711291ab-43f6-4a02-ad8f-b7b0cb36abbd)
![Image](https://github.com/user-attachments/assets/b8bc8715-e522-4951-8628-bff5a98591e7)
- 아이콘 리소스 등록해 두었습니다.
- 스파인 이미지 등록해 두었고, 스파인 손에 들리도록 설정까지 해 두었습니다.

**Comment by eugene-doobu** [comment]
전투 준비 화면 피드백
-> 스파인 보다 ui가 항상 위에 배치되야 합니다.
