### ISSUE TITLE
메인넷, 인터널, 프리뷰넷 별로 클라이언트 아이콘을 구별하도록 수정

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#5910]
관련 스레드: https://planetariumhq.slack.com/archives/C0358KRU0CB/p1725627115819999

**Comment by tyrosine1153** [comment]
작업 스레드

https://planetariumhq.slack.com/archives/C0358KRU0CB/p1726217761778139

**Comment by ipdae** [comment]
CI에서 이미지를 갈아껴줘야함

**Comment by ipdae** [comment]
- 아이콘 리소스도 1주년 기념 이미지로 변경 필요
- PC에만 적용

**Comment by ipdae** [comment]
- 모바일은 현재 빌드 프로세스의 경우 네트워크 구분을 할 수 없음(해당 빌드가 바로 배포가 됨)
- pc의 경우 이미 런쳐가 네트워크마다 아이콘 구분을 하고 있음. 런쳐를 통해서만 실행되고 있는 현재 환경에서 아이콘 구분을 하려면 아트팀, 개발팀의 추가 리소스를 투입해야함

위 2가지 사유로 이 이슈는 진행하지않으려합니다. 의견부탁드립니다. @jaeho0103 @Namyujeong
