### ISSUE TITLE
커스텀 장비의 이름은 "Custom {장비 이름}" 형식으로 나와야함

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#5911]
- 이전 작업: https://github.com/planetarium/NineChronicles/issues/5754
- 일반 장비와 커스텀 장비에서 id와 iconId를 분리하지 않고 있기 때문에 아래와 같이 수정함
  - 커스텀 장비 이름의 L10n 키 값을 `ITEM_NAME_CUSTOM_{id}` 로 설정함 (이때 `id` 는 iconId 값)
  - L10n 내용은 "Custom {장비 이름}" 형식임

**Comment by moreal** [comment]
안녕하세요 @tyrosine1153 님, 요 이슈 #5931 에서 해결된 건데 닫히진 않은 걸까요? 혹은 아직 더 작업해야 할 내용이 남았을까요?

**Comment by tyrosine1153** [comment]
> 안녕하세요 @tyrosine1153 님, 요 이슈 #5931 에서 해결된 건데 닫히진 않은 걸까요? 혹은 아직 더 작업해야 할 내용이 남았을까요?

연결된 pr이 머지될 당시 타겟브랜치가 development 여서 close 되지 않은 것으로 보입니다. 실제로는 해걸이 된 이슈이니 닫는게 맞아보여요!
이 이슈 외에도 pr 내용이 반영되었어도 닫히지 않은게 많을텐데 이슈 정리중이라면 저한테 할당된 것들 제가 정리를 하는게 편하실까요?

**Comment by moreal** [comment]
> 연결된 pr이 머지될 당시 타겟브랜치가 development 여서 close 되지 않은 것으로 보입니다. 실제로는 해걸이 된 이슈이니 닫는게 맞아보여요!
이 이슈 외에도 pr 내용이 반영되었어도 닫히지 않은게 많을텐데 이슈 정리중이라면 저한테 할당된 것들 제가 정리를 하는게 편하실까요?

@tyrosine1153 답변 감사합니다 🙇🏻‍♂️ 제가 차주에 진행할 행사에서 기여자에게 제안할 이슈들을 찾던 중 질문드렸던거라서 시간이 크게 들지 않는다면 정리해주시면 좋을 것 같아요! 일정 상 바쁘시다면 천천히 해주셔도 될 것 같아요 🙏🏻
