### ISSUE TITLE
[상점] PC 상점 내 아이템 가격이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5947]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
PC 상점 내 아이템 가격이 출력되지 않는 현상
- Windows 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/39ed47c7-b00b-4cd5-9954-ef3a37295ce0)

### How to reproduce the issue

[재현 스텝]
1. PC 환경 접속
2. 메인 로비 - 상점 클릭
3. 상점 내 아이템 가격이 출력되지 않는 현상 확인

[Should be]
PC 상점 내 아이템 가격이 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
아래 pr에서 수정하여 적용하였습니다. 다음 rc에서 체크 부탁드립니다 
https://github.com/planetarium/NineChronicles/pull/5957

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.2

![Image](https://github.com/user-attachments/assets/a6de411c-6307-4af4-8cdf-91cff06e8157)
