### ISSUE TITLE
[상점] PC 상점 내 장비 아이템의 초기 정렬이 CP 오름차순으로 정렬되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5948]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
PC 상점 내 장비 아이템의 초기 정렬이 CP 오름차순으로 정렬되는 현상
- 최초 진입 시에는 무기 탭 CP 내림차순으로 출력되나 다른 장비 탭 클릭 시 CP 오름차순으로 정렬됩니다.
- 음식 아이템에서도 동일 현상 발생했습니다.
- Windows 환경에서 발생 확인했습니다.
 
https://github.com/user-attachments/assets/bb59ce6e-d6a5-43a3-a71b-2440edf30a50

### How to reproduce the issue

[재현 스텝]
1. PC 환경 접속
2. 메인 로비 - 상점 클릭
3. 무기 CP 내림차순으로 출력
4. 다른 장비 탭 클릭
5. CP 오름차순으로 정렬되는 현상 확인

[Should be]
PC 상점 내 장비 / 음식 탭의 초기 정렬이 CP 오름차순으로 정렬되어야 합니다.

**Comment by jaeho0103** [comment]
@tyrosine1153 
요거 기획 체크를 못했는데 제가 오름차순으로 요청했으면
잘못 요청드린겁니다. 내림차순으로 부탁드리겠습니다.

**Comment by tyrosine1153** [comment]
https://www.notion.so/planetarium/24-q3-4dbed4b7f88e4f329093c00e5ab6ff81?pvs=4#50466f520be7491287fefe76759496a1
이부분 전체 적용이 안되어있던 것으로 확인했습니다. 수정해서 올리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.2
![Image](https://github.com/user-attachments/assets/0a8ccd80-067c-4f12-94b7-0306dc8b9347)
