### ISSUE TITLE
[커스텀 제작] B등급 이하 Heal 스킬의 수치가 0으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5950]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
B등급 이하 Heal 스킬의 수치가 0으로 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/13793d95-ab13-4454-885b-a6deed28a146

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 커스텀 제작 클릭
2. 임의의 장비 외형 선택
3. 예상 CP 범위 우측 돋보기 버튼 클릭
4. 스킬 정보 탭 클릭 - B등급 이하 Heal 스킬의 돋보기 버튼 클릭
5. B등급 이하의 Heal 스킬 수치가 0으로 출력되는 현상 확인

[Should be]
B등급 이하의 Heal 스킬 수치가 0으로 출력되지 않아야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
스피드 감소 디버프 (HIT 옵션 / DEF 옵션)에서도 동일 현상 발생 확인했습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200230-230.0.2
Android.v200230-230.0.2
iOS.v230.0.2(109)

https://github.com/user-attachments/assets/512a971a-725e-46a9-ac85-aa23a2baa621

**Comment by NineSyu** [comment]
감사합니다. 데이터 체크 과정에서 문제있는 부분은 체크하여 수정했습니다.
데이터 패치하여 해당 상황 해결하였습니다.

재접속 이후 정상적으로 동작하는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 PC 버전에서만 Heal(BH) / Heal(CH)에 해당되는 스킬이 Heal(BA) / Heal(CD)로 출력되고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200230-230.0.3

![Image](https://github.com/user-attachments/assets/17422ccf-78cb-4729-b200-4c70feaf670a)

**Comment by NineSyu** [comment]
감사합니다. 스킬 이름이 잘못 적용되었던 것을 확인했습니다.
수정해서 재적용했습니다. 재접속 후 확인하시면 정상적으로 표시되는 것을 확인할 수 있습니다.

수정 내역 (2종)
- Heal (BA) -> Heal(BH)
- Heal (CD) -> Heal(CH)

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3

![Image](https://github.com/user-attachments/assets/f18ef6ec-2674-4d9d-a059-f674d83ef698)
