### ISSUE TITLE
[커스텀 제작] 일부 스킬의 정보가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5952]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
일부 스킬의 정보가 출력되지 않는 현상
- 목걸이 디스펠 / 반지 모든 공격 명중 스킬의 정보가 출력되지 않는 것을 확인했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/02d5c511-5410-4f2e-b5f9-2c0c34dacf65

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 커스텀 제작 클릭
2. 임의의 목걸이 / 반지 외형 클릭
3. 예상 CP 범위 우측 돋보기 버튼 클릭
4. 스킬 정보 탭 클릭 - 목걸이 디스펠 / 반지 모든 공격 명중 스킬의 돋보기 버튼 클릭
5. 일부 스킬의 정보가 출력되지 않는 현상 확인

[Should be]
목걸이 디스펠 / 반지 모든 공격 명중 스킬 정보가 출력되어야 합니다.

**Comment by sonohoshi** [comment]
번역어 누락 문제로 확인되어 @NineSyu 님께 담당 돌립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.2
Android.v200230-230.0.2
iOS.v230.0.2(109)

https://github.com/user-attachments/assets/21f1d3d2-d75c-4dea-b39e-15286904d801
