### ISSUE TITLE
[UI] 뒤로가기 버튼 범위가 넓게 설정되어 있는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5953]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
뒤로가기 버튼 범위가 넓게 설정되어 있는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/72637cb7-b257-4ae3-9a23-eff62370c53e

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 클릭
2. 모래시계 아이콘 좌측 영역 클릭
3. 뒤로가기 버튼 영역으로 설정되어 있는 현상 확인

[Should be]
뒤로가기 버튼 영역은 뒤로가기 버튼 영역에만 설정되어야 합니다.

**Comment by boramqo83** [comment]
![Uploading image.png…]()
- 닫기 버튼이 요 아이콘으로 되어있었던거 같은데 , 현재는 BackButton에 버튼이 들어가져 있네요. 요렇게 수정된 히스토리가 따로 있는것 일까요? @sonohoshi
