### ISSUE TITLE
[몬스터컬렉션] 몬스터컬렉션 보상 목록 내에 스크롤 아이템이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5954]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
몬스터컬렉션 보상 목록 내에 스크롤 아이템이 출력되지 않는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/8125cf0b-83e4-407b-b277-5b8c413b62f0)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 몬스터컬렉션 클릭
2. 보상 목록 탭 확인
3. 보상 목록 내 스크롤 아이템이 출력되지 않는 현상 확인

[Should be]
몬스터컬렉션 보상 목록 내 스크롤 아이템이 출력되어야 합니다.

**Comment by jaeho0103** [comment]
보상 목록은 인터널과 메인넷이 같은걸 사용하고 있어서 업데이트 대기중입니다.
메인넷 릴리즈 후에 다시 체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
네, 확인 감사합니다.
메인넷 릴리즈 후 체크 진행하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.1.1
Android.v200230-230.1.1
iOS.v230.1.1(117)

![Image](https://github.com/user-attachments/assets/f29e481b-f5d7-4b0a-896f-391fc28cd20e)
