### ISSUE TITLE
[커스텀 제작] 일부 스킬의 옵션 연결이 잘못되어 있는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5956]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
일부 스킬의 옵션 연결이 잘못되어 있는 현상
- 옵션명은 BA / CA이나 ATK이 아닌 DEF / SPD 옵션에 연결된 것으로 출력되고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/ad7168b8-9a4d-47a6-97e5-a461f0129068

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 커스텀 제작 클릭
2. 임의의 무기 외형 클릭
3. 예상 CP 범위 우측 돋보기 버튼 클릭
4. 스킬 정보 탭 클릭 - 더블 어택(BA) 스킬의 돋보기 버튼 클릭
5. ATK가 아닌 DEF 옵션에 연결된 것을 출력되는 현상 확인

[Should be]
스킬의 이름과 정보 내 옵션이 동일하게 연결되어야 합니다.

**Comment by NineSyu** [comment]
감사합니다. 체크해보니 스킬과 효과 연결을 잘못하여 생긴 이슈였습니다.

데이터를 패치하여 정상동작하게 변경하였습니다.

재접속후 정상 동작하는 것을 확인할 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상이 목걸이  - 받는 데미지 감소 스킬에서도 확인되었습니다.
확인 부탁드립니다.

![Image](https://github.com/user-attachments/assets/c3dc3b62-e350-43f1-89b2-db14d111b447)

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

**Comment by NineSyu** [comment]
확인했습니다. 스킬에 버프가 잘못 연결되어 있었습니다.
데이터 수정하여 문제를 해결하겠습니다.

재접속 후 다시 테스트하시면 정상 동작하는 것을 확인할 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

![Image](https://github.com/user-attachments/assets/b87702bd-a154-45c9-92ee-49ef9986d68c)
