### ISSUE TITLE
[어드벤쳐] 스테이지 클리어 보상으로 스크롤 아이템이 지급되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5958]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
스테이지 클리어 보상으로 스크롤 아이템이 지급되는 현상
- 기획 의도인 부분인지 확인 부탁드립니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/3ab9d886-52b9-4436-8671-fbefc7aa0175

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 350 / 400 중 임의의 스테이지 선택
3. 보상 미리보기에 스크롤 아이템 출력 확인
4. 해당 스테이지 진행
4. 스크롤 아이템이 보상으로 지급되는 현상 확인

[Should be]
스테이지에서 스크롤 아이템이 보상으로 지급되지 않아야 합니다.

**Comment by jaeho0103** [comment]
갱신되었습니다. 다시 체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.2
Android.v200230-230.0.2
iOS.v230.0.2(109)

![Image](https://github.com/user-attachments/assets/17d68eb4-ddbb-4a96-b9b5-2d6c6373739b)
