### ISSUE TITLE
[커스텀 장비] 서클 아이템 팝업 내 스테이지 바로가기가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5959]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
서클 아이템 팝업 내 스테이지 바로가기가 출력되지 않는 현상
- 200, 250, 300, 350, 400 스테이지에서 획득 가능하나 바로가기가 출력되지 않고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/3f8a350a-bfb1-4e7a-85c4-5b6cf2a246b5)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 버튼 클릭
2. 재료 탭 내 서클 아이템 클릭
3. 서클 아이템 팝업 내 스테이지 바로가기가 출력되지 않는 현상 확인

[Should be]
서클 아이템 팝업 내 스테이지 바로가기가 출력되어야 합니다.

**Comment by sonohoshi** [comment]
@QgamesGeonPyoNoh 이게 원래 스테이지에서 나오는게 아닌데, 테스트 편의를 위해서 스테이지에서 드랍되게 한거라 정상 스펙이 맞습니다. cc @jaeho0103

**Comment by sonohoshi** [comment]
@tyrosine1153 확인 부탁드립니당.

**Comment by QgamesGeonPyoNoh** [comment]
움직일 수 있는 스크롤을 추가되었으나 스테이지는 동일하게 출력되지 않고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200230-230.0.2
Android.v200230-230.0.2
iOS.v230.0.2(109)

https://github.com/user-attachments/assets/52ee0557-524b-4628-afca-1025cb96b199
