### ISSUE TITLE
[커스텀 장비] 서클 아이템 팝업 내 띄어쓰기 오류 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5960]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
서클 아이템 팝업 내 띄어쓰기 오류 현상
- With Odin`s ring 부분의 띄어쓰기가 길게 출력되고 있습니다.
- Windows 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/fb8d04a5-e443-423b-aeac-b17b3d97df69)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 버튼 클릭
2. 재료 탭 내 서클 아이템 클릭
3. 서클 아이템 팝업 내 띄어쓰기 오류 현상 발생 확인

[Should be]
서클 아이템 팝업 내 띄어쓰기 오류가 수정되어야 합니다.

**Comment by sonohoshi** [comment]
@NineSyu 확인 부탁드립니다

**Comment by NineSyu** [comment]
텍스트 수정 후 띄어쓰기 사라진 것 확인했습니다.
재접속 후 확인하시면 정상적으로 표시되는 것 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3

![Image](https://github.com/user-attachments/assets/c43b7f16-83d4-4078-8b96-2ae4d6741f60)
