### ISSUE TITLE
[커스텀 제작] 친밀도 팝업 내 설명이 작성되어 있지 않은 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5961]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
친밀도 팝업 내 설명이 작성되어 있지 않은 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/b6888f88-ad8e-47f4-a160-2d7a49ebce55)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 커스텀 제작 클릭
2. 친밀도 프로그레스 바 내 i 버튼 클릭
3. 친밀도 팝업 내 설명이 작성되어 있지 않은 현상 확인

[Should be]
친밀도 팝업 내 설명이 작성되어야 합니다.

**Comment by sonohoshi** [comment]
@NineSyu 이거 이따 제가 번역어 키 싹 모아서 공유드릴테니 한꺼번에 정리해주시면 될 것 같습니다.

**Comment by NineSyu** [comment]
번역어 텍스트 재적용하여 재접속 후 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.2
Android.v200230-230.0.2
iOS.v230.0.2(109)

https://github.com/user-attachments/assets/e9fe6e99-05fd-4d44-869d-c5a96c77acc3
