### ISSUE TITLE
[어드벤쳐보스] 어드벤쳐보스 클리어 화면에 서클 아이템이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5962]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐보스 클리어 화면에 서클 아이템이 출력되지 않는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/aa6c0720-e7bb-4896-abbf-2d584fe6daf7)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 (오픈) 클릭
2. 1 - 5 층 구간 최초 클리어 도전 진행
3. 클리어 화면에서 서클 아이템이 출력되지 않는 현상 확인

[Should be]
어드벤쳐 보스 1 - 5 층 구간 최초 클리어 시 클리어 화면에 서클 아이템이 출력 되어야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6023 에서 수정하였습니다 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

![Image](https://github.com/user-attachments/assets/55b67fb4-ed6e-4311-8a86-6ea249f160fb)
