### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 도전 팝업에서 최초 클리어 보상이 전부 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5968]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, iOS, Android

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 도전 팝업에서 최초 클리어 보상이 전부 출력되지 않는 현상
- 현재 1 - 5층 기준 스피드 룬 조각이 출력되지 않고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/51139136-7d8e-4c42-94cf-d20516469f75)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 (오픈) 클릭
2. 입장 버튼 클릭 - 도전 팝업 출력
3. 도전 팝업 확인 시 최초 클리어 보상이 전부 출력되지 않는 현상 확인

[Should be]
어드벤쳐 보스 도전 팝업 확인 시 최초 클리어 보상이 모두 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6023 에서 수정하였습니다 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

![Image](https://github.com/user-attachments/assets/ac76ac6d-f300-40fe-bc7e-8026b4070e34)
