### ISSUE TITLE
[커스텀 제작] 서클 아이템의 등급 색상이 노말 등급으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5971]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
서클 아이템의 등급 색상이 노말 등급으로 출력되는 현상
- 스테이지에서 지급되는 거래불가 서클은 신성 등급 색상으로 출력됩니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/7ef31f9e-7b0c-4e63-8c40-75f7ad9da13e)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 - 재료 탭 클릭
2. 서클 아이템 아이콘 확인
3. 노말 등급 색상으로 출력 확인
4. 서클 아이콘 클릭
5. 서클 아이템 팝업 확인 시 노말 등급 색상으로 출력 확인

[Should be]
서클 아이템의 등급 색상이 신성 등급에 해당되는 붉은색으로 출력되어야 합니다.

**Comment by sonohoshi** [comment]
@QgamesGeonPyoNoh 혹시 이 노멀등급 서클은 어떤 경로로 얻은건지 파악될까요? (e.g. 스테이지, 그라인딩 등)

**Comment by sonohoshi** [comment]
@tyrosine1153 이거 정민님이 체크 부탁드립니다. 월보에서 나온 서클이 혼자 등급이 다른거같습니다

**Comment by tyrosine1153** [comment]
@jaeho0103 기존에는 Material 아이템이 Tradable하면 기존 등급보다 한 단계 높인 색상으로 인벤토리에서 보여줍니다.
하지만 커스텀 장비의 경우 최대 등급인 신성 등급이기 때문에 색상값이 오버플로우되어 기본 색으로 표시된 것 같습니다.
이 경우의 처리에 대해 결정 부탁드립니다.
개인적인 판단으로는 현재 스테이지에서 나오는 아이템이 거래 불가능하긴 하지만 서클, 스크롤은 모두 거래 가능을 지향하는 것으로 아는데, AP포션/모래시계와 같이 색을 구분할 필요가 없지 않을까 싶습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 현재 동일하게 발생 중입니다.
확인 부탁드립니다.

스테이지에서 획득하는 서클만 신성등급 색상 거래불가로 획득되며,
월드보스, 어드벤쳐 보스, 그라인딩, 상점 구매 서클은 노말 색상 거래 가능으로 출력됩니다.

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.
- 서클이 나뉜 부분은 기존에 스테이지에서 획득한 거래불가 서클입니다.

[테스트 환경]
Windows.v200230-230.0.4
Android.v200230-230.0.4
iOS.v230.0.4(111)

![Image](https://github.com/user-attachments/assets/2d0a4768-516b-4994-9421-d93356b808d3)
