### ISSUE TITLE
[커스텀 제작] 커스텀 제작 튜토리얼이 1회 제작한 후에 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5973]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
커스텀 제작 튜토리얼이 1회 제작한 후에 출력되는 현상
- 이미 201 스테이지를 클리어한 계정에서 커스텀 제작 1회 진행 후 튜토리얼이 발생했습니다.
- Windows 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/06421541-df75-4940-80a5-a79af9cc0c1c

### How to reproduce the issue

[재현 스텝]
1. 201 스테이지 클리어 계정 접속
2. 메인 로비 - 워크샵 - 커스텀 제작 클릭
3. 커스텀 제작 최초 1회 진행
4. 커스텀 제작 튜토리얼이 1회 제작한 후에 출력되는 현상 확인

[Should be]
커스텀 제작 튜토리얼이 커스텀 제작 최초 접근 시에 출력되어야 합니다.

**Comment by jaeho0103** [comment]
우선순위 조정해서 할당 드렸습니다. 체크 부탁드립니다 @sonohoshi

**Comment by sonohoshi** [comment]
친밀도 조건 설정을 잘못했던거라, 커스텀 크래프트를 한적 없는 유저가 튜토리얼도 본적 없으면 나오게끔 고쳤습니다

**Comment by QgamesGeonPyoNoh** [comment]
튜토리얼이 현재 발생하고 있지 않아 확인이 어려운 상황입니다.
메인넷에서 확인 진행해도 될지 문의드립니다.

**Comment by sonohoshi** [comment]
넵 내부체크는 된 상태라서 괜찮을 것 같습니다. @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.1.1
Android.v200230-230.1.1
iOS.v230.1.1(117)

![Image](https://github.com/user-attachments/assets/fc3f6bdc-9da1-4695-b9ae-da7e37cb7d98)
