### ISSUE TITLE
[커스텀 제작] 커스텀 제작 완료 시 우편이 워크샵 탭에 포함되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5977]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
커스텀 제작 완료 시 우편이 워크샵 탭에 포함되지 않는 현상
- 특정 탭에 출력되지 않고 전체 탭에서만 확인 가능합니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/f069ca6c-e5a3-485f-8614-fda438605ed0

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 커스텀 제작 클릭
2. 임의의 커스텀 장비 제작 진행
3. 완료 후 우편함 확인 시 워크샵 탭에 포함되지 않는 현상 확인

[Should be]
커스텀 제작 완료 시 우편이 워크샵 탭에서 출력되어야 합니다.

**Comment by ipdae** [comment]
그라인딩메일처럼 클라이언트 메일팝업에서 커스텀 제작 메일도 워크샵으로 보내야함
