### ISSUE TITLE
[퀘스트] 메인 화면에서 퀘스트 UI 클릭 시 해당 퀘스트 위치로 이동하지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#5980]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
메인 화면에서 좌측의 퀘스트 UI 클릭 시 해당 퀘스트 위치로 이동하지 않는 현상
- 어드벤쳐 퀘스트, 제작 퀘스트 모두 이동이 되지 않는 것을 확인했습니다.
- 퀘스트 UI 내에 보상 아이콘 클릭 시 아이템 정보 팝업이 정상적으로 출력되는 것을 확인하였습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/90769527-b214-4d4e-9b24-5b73ce6ace3c

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 진입
2. 메인 로비 좌측의 퀘스트 UI 클릭
3. 해당 퀘스트 위치로 이동하지 않는 것을 확인

[Should be]
메인 화면에서 좌측의 퀘스트 UI 클릭 시 해당 퀘스트 위치로 이동해야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.1.1
Android.v200230-230.1.1
iOS.v230.1.1(117)

https://github.com/user-attachments/assets/91715540-e93c-497a-91ec-3e8a2db0e52a
