### ISSUE TITLE
[커스텀 제작] 커스텀 제작 진행 시 출력되는 화면에서 장비 아이콘이 아닌 상자 아이콘이 출력

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5982]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
커스텀 제작 진행 시 출력되는 화면에서 장비 아이콘이 아닌 상자 아이콘이 출력
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/eb8aabb6-66c0-4d76-9727-9d85e6899055)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경에서 접속
2. 메인 로비 - 워크샵 - 커스텀 제작 클릭
3. 임의의 커스텀 장비 제작 진행
4. 진행 시 출력되는 화면에서 장비 아이콘이 아닌 상자 아이콘이 출력되는 현상 확인

[Should be]
커스탐 장비 제작 진행 시 출력되는 화면에서 제작하는 장비의 아이콘이 출력돠어야 합니다.

**Comment by sonohoshi** [comment]
이거 #5919 에서 해결된 내용인데, 아직 배포가 안됐습니다. 다음 rc 배포때 다시 안내드릴테니 체크해주시면 될 것 같습니다! @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.2
Android.v200230-230.0.2
iOS.v230.0.2(109)

https://github.com/user-attachments/assets/5bf62406-2fe9-40cc-a991-697ca3d9f2a8
