### ISSUE TITLE
[커스텀 제작] 커스텀 제작 감정 전 워크샵 슬롯 확인 시 장비 이름이 키 값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5983]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
커스텀 제작 감정 전 워크샵 슬롯 확인 시 장비 이름이 키 값으로 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/ff08268c-0ca2-44bc-a5c7-da17868cf912)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경에서 접속
2. 메인 로비 - 워크샵 - 커스텀 제작 클릭
3. 임의의 커스텀 장비 제작 진행
4. 감정 전 워크샵 슬롯 확인 시 장비 이름이 키 값으로 출력되는 현상 확인

[Should be]
커스텀 제작 감정 전 워크샵 슬롯 확인 시 장비 이름이 제작한 장비의 이름으로 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6005 에서 번역키 추가되어 랜덤장비 제작시 전용 텍스트 나올 예정입니다. 다음 rc에서 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

https://github.com/user-attachments/assets/15afae42-1a59-4c90-8f0b-868f5862e74f
