### ISSUE TITLE
[커스텀 제작] Reduced Damage Received 스킬 사용 시 아이콘이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5990]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Reduced Damage Received 스킬 사용 시 아이콘이 출력되지 않는 현상
- 해당 스킬 사용 시 방패 이펙트는 출력되나 상단의 아이콘은 출력되지 않습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/cd9b4c31-a194-4977-8f68-1cedfebed944

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 클릭
2. 임의의 스테이지 선택
3. Reduced Damage Received 스킬을 보유한 장비 착용 후 진입
4. 해당 스킬 사용 시 아이콘이 출력되지 않는 현상 확인

[Should be]
Reduced Damage Received 스킬 사용 시 아이콘이 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
@QgamesGeonPyoNoh 안녕하세요 이 이슈 현재 버전(v230.0.5) 에서도 발생하는 건지 확인하고 싶어서 코멘트 남깁니다. 지금 버전에서도 재현 되는지 봐주실 수 있으실까요?

**Comment by QgamesGeonPyoNoh** [comment]
Reduced Damage Received 스킬 버프 아이콘이 출력되지 않는 현상 재현되었습니다.
이 외의 스킬에서는 아직 해당 현상 발생 확인되지 않았습니다.

https://github.com/user-attachments/assets/1040b1bc-4f57-405d-a500-8dbef3924286

**Comment by eugene-doobu** [comment]
데이터 변경으로 수정된 것으로 보입니다. 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.1.1
Android.v200230-230.1.1
iOS.v230.1.1(117)

https://github.com/user-attachments/assets/d9bf44a7-093c-4eee-96c1-ccac2181de2c
