### ISSUE TITLE
[튜토리얼] 제작 튜토리얼 진행 중 일반 장비 감정 팝업이 화면을 가리는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#5995]
### APV version info

v200230

### Client version info

v230.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
제작 튜토리얼 진행 중 롱소드 제작으로 출력되는 일반 장비 감정 팝업이 화면을 가리는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/ef05ddb2-7655-4366-bdba-4ce763870910

### How to reproduce the issue

[재현 스텝]
1. 신규 캐릭터 생성
2. 메인 로비로 진입 후 공방 제작 튜토리얼 진행
3. 제작한 롱소드의 감정 팝업이 튜토리얼 진행 중 출력되는 것을 확인
4. 해당 감정 팝업이 화면을 가리는 것을 확인

[Should be]
제작 튜토리얼 진행 중 롱소드 제작으로 출력되는 일반 장비 감정 팝업이 화면을 가리지 않아야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/5996 에서 튜토리얼 & 전투중에 일반 장비 감정 완료 팝업 안뜨도록 수정했습니다. 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

https://github.com/user-attachments/assets/bdc5f39e-5611-4eb4-8afb-8c05c0f5360f
