### ISSUE TITLE
[인벤토리] 인벤토리에서 분해 모드로 반복 진입 시 분해 버튼이 노출되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#5997]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
인벤토리에서 분해 모드로 반복 진입 시 분해 버튼이 노출되지 않는 현상
- 해당 현상이 발생한 상태에서 아이템 선택 후 분해 버튼이 있던 위치 클릭 시 분해가 진행되는 것을 확인했습니다.
- Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/0bce7f48-ac29-406a-8d40-5a4668523eb3

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 진입
2. 인벤토리에서 하단의 분해 버튼 연타
3. 분해 모드 진입 시 분해 버튼이 노출되지 않는 것을 확인

[Should be]
인벤토리에서 분해 모드로 반복 진입 시 분해 버튼이 노출되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 동일하게 발생하고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

https://github.com/user-attachments/assets/8e643bf9-1c6e-4dea-bb3a-6755fc61af5d
