### ISSUE TITLE
[몬스터컬렉션] 보유 NCG 이상 스테이킹 시도 시 출력되는 팝입이 몬스터 컬렉션 팝업을 닫은 후에 출력됨

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5998]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
보유 NCG 이상 스테이킹 시도 시 출력되는 팝입이 몬스터 컬렉션 팝업을 닫은 후에 출력됨
- Windows 환경에서 확인했습니다.

https://github.com/user-attachments/assets/f371c839-bfcb-4256-9270-e8d09858fa8a

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 몬스터 컬렉션 클릭
2. 현재 보유하고 있는 NCG 이상 입력 후 스테이킹 시도
3. NCG 부족 팝업이 출력되지 않음
4. 몬스터 컬렉션 팝업을 닫음
5. 이 후 NCG 부족 팝업이 출력되는 현상 확인

[Should be]
보유 NCG 이상 스테이킹 시도 시 즉시 NCG 부족 팝업이 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6010 에서 수정하였습니다. 다음 rc에서 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3

https://github.com/user-attachments/assets/e1172e4e-9ebc-4e03-9beb-5a8a3ab9c32a
