### ISSUE TITLE
[D:CC] 펫 소환 / 레벨업 재화 부족 시 출력되는 팝업이 소환 팝업을 닫은 후에 출력됨

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#5999]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
펫 소환 / 레벨업 재화 부족 시 출력되는 팝업이 소환 팝업을 닫은 후에 출력됨
- Windows 환경에서 확인했습니다.

https://github.com/user-attachments/assets/f86d79b3-289d-4779-ab76-7dfce9f55118

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - D:CC 클릭
2. 현재 소환 / 레벨업이 불가능한 펫 소환 / 레벨업 시도
3. 재료 부족 팝업이 출력되지 않음
4. 소환 / 레벨업 팝업을 닫음
5. 이 후 재료 부족 팝업이 출력되는 현상 확인

[Should be]
소환 / 레벨업이 불가능한 펫 소환 / 레벨업 시도 후 바로 재료 부족 팝업이 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6010 에서 팝업 대신 한줄 팝업 띄우는 것으로 수정하였습니다. 다음 rc에서 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3

https://github.com/user-attachments/assets/61639be9-f80c-41b2-9fc8-893c56510660
