### ISSUE TITLE
[UI] 모바일 NCG 부족 팝업 텍스트 확인 요청

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6000]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모바일 NCG 부족 팝업 텍스트 확인 요청
- 스테이킹 / D;CC 컨텐츠에서 재화 부족 시 해당 팝업이 출력되고 있습니다.
- 텍스트가 의도하신 내용이 맞는지 확인 부탁드립니다.

![Image](https://github.com/user-attachments/assets/53d9e760-9e87-49e2-98e9-cf29a8fc06cb)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 몬스터 컬렉션 클릭
2. 현재 보유하고 있는 NCG 이상 입력 후 스테이킹 시도
3. NCG 부족 팝업 내용 확인

**Comment by eugene-doobu** [comment]
기존 소울스톤 체크처리가 NCG부족 처리랑 공통된 코드로 한줄 토스트 메시지를 띄워주고 있었어서 같이 휘말린 것 같은데, 기존 한줄 토스트메시지로 롤백하면 될 것 같습니다. 그럼 아래 이슈도 같이 처리됩니다 @jaeho0103 
https://github.com/planetarium/NineChronicles/issues/5999

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6010 에서 팝업 대신 한줄 팝업 띄우는 것으로 수정하였습니다. 다음 rc에서 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200230-230.0.3
iOS.v230.0.3(110)

![Image](https://github.com/user-attachments/assets/f96dbf4c-a436-41c2-8a8b-20379bc16634)
