### ISSUE TITLE
[상점] PC 상점 메일 내 아이템 명이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6001]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
PC 상점 메일 내 아이템 명이 출력되지 않는 현상
-구매 / 취소 시에는 아이템 명이 출력되지 않고 판매 시에는 NCG 수량이 출력되지 않습니다.

![Image](https://github.com/user-attachments/assets/83a36340-f038-430f-93a4-0ba0e89b0fe1)

### How to reproduce the issue

[재현 스텝]
1. PC 환경 접속
2. 메인 로비 - 상점 클릭
3. 임의의 아이템 구매 진행
4. 메일 확인 시 아이템 명이 출력되지 않는 현상 확인

[Should be]
PC 상점에서 아이템 구매 / 취소 시 아이템 명이 메일에 출력되어야 합니다.
판매 시에는 획득한 NCG 수량이 출력되어야 합니다.

**Comment by ipdae** [comment]
https://github.com/planetarium/market-service/issues/123 의 변경사항으로 인해 마켓에서 정보를 못찾아오는 경우 발생하는 문제로 보입니다. BuyProduct에서 결과로 전송시켜주는 판매자, 구매자 메일에 필요한 정보를 추가해서 해결하려합니다.

**Comment by QgamesGeonPyoNoh** [comment]
구매 / 판매 시에는 아이템 명이 출력되었으나, 취소 시에는 출력되지 않고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200230-230.0.3

![Image](https://github.com/user-attachments/assets/cb0b81f7-6822-41c6-b214-743f2116d69c)

**Comment by sonohoshi** [comment]
@ipdae 이거 ProductCancelMail에도 Product 넣는거 적용해야할 것 같습니다 🥴
@jaeho0103 아니면 취소 메일 형태를 간략화해서 어떤 물품을 회수했는지 대신 아이템을 회수했다 정도로만 남기는건 어떨지 여쭤봅니다.

**Comment by sonohoshi** [comment]
취소 메일은 노운이슈로 두고 다음 버전에서 스펙 재설정하기로 내부 결정되었습니다. @QgamesGeonPyoNoh 
확인 감사드립니다

**Comment by ipdae** [comment]
https://github.com/planetarium/lib9c/pull/2859
