### ISSUE TITLE
[상점] PC 상점 음식 스탯 탭이 서로 변경되어 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6002]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
PC 상점 음식 스탯 탭이 서로 변경되어 출력되는 현상
- 크리티컬 / 디펜스 탭, 스피드 / 히트 탭이 서로 변경되어 있습니다.

https://github.com/user-attachments/assets/bc8e79b2-f1a2-4a03-bb9b-d86305a762e1

### How to reproduce the issue

[재현 스텝]
1. PC 환경 접속
2. 메인 로비 - 상점 클릭
3. 크리티컬 / 디펜스 / 스피드 / 히트 음식 탭 확인
4. 음식 스탯 탭이 서로 변경되어 출력되는 현상 확인

[Should be]
음식 스탯 탭에 해당되는 음식이 출력되어야 합니다.

**Comment by sonohoshi** [comment]
@tyrosine1153 이건 클라이슈일까요? 확인 한번 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3

https://github.com/user-attachments/assets/d0378239-6f42-4bda-a10b-8c47521ba5a3
