### ISSUE TITLE
[상점] PC 상점에서 구매한 아이템이 메일에서 수령되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6004]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
PC 상점에서 구매한 아이템이 메일에서 수령되지 않는 현상
- 아이템은 인벤토라에 지급됩니다.
- 받기 버튼은 동작하지 않고, 모두 받기 버튼 클릭 시 구매한 아이템 아이콘이 출력되지 않습니다.

https://github.com/user-attachments/assets/f579ff4b-b356-4e1b-9cb6-1dfb0aa05d54

### How to reproduce the issue

[재현 스텝]
1. PC 환경 접속
2. 메인 로비 - 상점 클릭
3. 임의의 아이템 구입
4. 메일에서 받기 버튼 클릭 시 반응 없음 현상 확인
5. 메일에서 모두 받기 버튼 클릭 시 구매한 아이템의 아이콘이 출력되지 않는 현상 확인

[Should be]
PC 상점에서 아이템 구매 후 메일에서 받기 / 모두 받기 시 해당 아이템이 출력되어야 합니다.

**Comment by sonohoshi** [comment]
PC 상점이 전체적으로 고장난 느낌인데

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3

https://github.com/user-attachments/assets/68c56d1a-b725-490b-a1ff-d551c60adb4c
