### ISSUE TITLE
[이벤트] 정찰 보상 이벤트가 적용되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6007]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
정찰 보상 이벤트가 적용되지 않는 현상
- 현재 9월 정찰 보상 이벤트 상태로 적용되어 있습니다.
- Windows, Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/4c5bf52a-581f-4871-808e-060879e2b44a)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 정찰 보상 클릭
2. 정찰 보상 아이템 확인
3. 정찰 보상 이벤트가 적용되지 않은 현상 확인

[Should be]
정찰 보상에 10월 이벤트가 반영되어야 합니다.

**Comment by ipdae** [comment]
지난 정책의 유효기간이 잘못설정되있는게 원인으로 보여서 수정해놨습니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 정찰 보상 팝업이 출력되지 않는 현상 발생하고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200230-230.0.2
Android.v200230-230.0.2
iOS.v230.0.2(109)

https://github.com/user-attachments/assets/a236bb5e-0dfa-4906-83b4-1759de98efe1

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 발생 당시 에러 로그 공유 드립니다.

ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Nekoyume.UI.PatrolRewardPopup.GetRewardType (Nekoyume.UI.Model.Patrol.PatrolRewardModel reward) (at <00000000000000000000000000000000>:0)
Nekoyume.UI.PatrolRewardPopup.SetRewards (System.Collections.Generic.List`1[T] rewardModels) (at <00000000000000000000000000000000>:0)
UniRx.Observer+Subscribe`1[T].OnNext (T value) (at <00000000000000000000000000000000>:0)
UniRx.ReactiveProperty`1[T].Subscribe (System.IObserver`1[T] observer) (at <00000000000000000000000000000000>:0)
UniRx.ObservableExtensions.Subscribe[T] (System.IObservable`1[T] source, System.Action`1[T] onNext) (at <00000000000000000000000000000000>:0)
Nekoyume.UI.PatrolRewardPopup.Init () (at <00000000000000000000000000000000>:0)
Nekoyume.UI.PatrolRewardPopup.ShowAsync (System.Boolean ignoreShowAnimation) (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) (at <00000000000000000000000000000000>:0)
Nekoyume.UI.PatrolRewardPopup.ShowAsync (System.Boolean ignoreShowAnimation) (at <00000000000000000000000000000000>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress (UnityEngine.EventSystems.PointerEventData pointerEvent, System.Boolean pressed, System.Boolean released) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchEvents () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.Process () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.EventSystem.Update () (at <00000000000000000000000000000000>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <00000000000000000000000000000000>:0)

**Comment by sonohoshi** [comment]
모래시계가 보상으로 추가되면서 발생한 이슈로 확인되어 수정중에 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.4
Android.v200230-230.0.4
iOS.v230.0.4(111)

https://github.com/user-attachments/assets/ca97cd00-77de-4800-882c-0cbcc92fd5dc
