### ISSUE TITLE
[아레나] 아레나 공격 대상이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6008]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
아레나 공격 대상이 출력되지 않는 현상
- 오딘, 헤임달 체인에서 동일하게 발생합니다.
- Windows, Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/7b092bfc-3f2a-4e42-917a-47129a0bca92)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 아레나 진입
2. 아레나 화면에서 입장 버튼 클릭
3. 아레나 공격 대상이 출력되지 않는 것을 확인

[Should be]
아레나 공격 대상이 정상적으로 출력되어야 합니다.

**Comment by jaeho0103** [comment]
서비스 갱신되어 정상동작 하는것 확인했다고 하십니다. 다시 체크 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.2
Android.v200230-230.0.2
iOS.v230.0.2(109)

![Image](https://github.com/user-attachments/assets/fb4d62fb-24cb-46f4-8a3f-9601e5f31db5)

**Comment by QgamesGeonPyoNoh** [comment]
오딘 체인에서 해당 현상 재 발생했습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200230-230.0.5
Android.v200230-230.0.5
iOS.v230.0.5(112)

![Image](https://github.com/user-attachments/assets/28475337-bc0e-498a-8b76-d238488f727f)

**Comment by ipdae** [comment]
테스트용 서비스에 문제가 있는듯 해서 재실행했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.5
Android.v200230-230.0.5
iOS.v230.0.5(112)

![Image](https://github.com/user-attachments/assets/1a78328a-83a6-4e50-920d-0319883f94e0)
