### ISSUE TITLE
[K버전] 재화 부족 팝업 내에 NCG 표현이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6011]
### APV version info

K버전_v200230

### Client version info

v230.0.2

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
인벤토리 룬 슬롯 해금 시 출력되는 재화 부족 팝업 내에 NCG 표현이 출력되는 현상
- 룬 강화 시 출력되는 재화 팝업에서도 동일한 현상이 발생했습니다.
- Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/26601ba9-c68b-4b3c-8a12-fdc81d73272e)

### How to reproduce the issue

[재현 스텝]
1. 메인 화면 - 인벤토리 진입
2. 룬 슬롯 해금에 필요한 NCG가 부족한 상태에서 잠겨있는 NCG 룬 슬롯 클릭
3. 재화 부족 팝업 출력 확인
4. 재화 부족 팝업 내에 NCG 표현이 출력되는 것을 확인

[Should be]
재화 부족 팝업 내에 NCG 표현이 출력되지 않아야 합니다.

**Comment by eugene-doobu** [comment]
@NineSyu 해당 키 수정해서 올려주실 수 있으실듯 하여 할당드렸습니다

**Comment by NineSyu** [comment]
감사합니다. NCG 문구를 골드로 변경하여 재적용 하였습니다.
재접속 후에는 골드라는 단어로 표시되는 것을 확인할 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
K.Android.v200230-230.0.3
K.iOS.v230.0.3(54)

![Image](https://github.com/user-attachments/assets/6b35073e-4b7d-476e-b405-1c337784637b)
