### ISSUE TITLE
[워크샵] 크리스탈 장비 제작 시 감정 팝업에서 오버플로우된 수치가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6013]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
크리스탈 장비 제작 시 감정 팝업에서 오버플로우된 수치가 출력되는 현상
- Android 환경에서는 0%로 출력되고 있습니다.
- Windows 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/0ae4c59d-65fa-4999-addb-7dffb2e1659a)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 제작 클릭
2. 크리스탈 장비 탭 클릭 후 제작 진행
3. 감정 팝업 출력 시 오버플로우된 수치가 출력되는 현상 확인

[Should be]
크리스탈 장비 제작 후 출력되는 감정 팝업에서 오버플로우된 수치가 출력되지 않아야 합니다.

**Comment by sonohoshi** [comment]
@eugene-doobu 할당드렸습니다.

**Comment by eugene-doobu** [comment]
'230.0.4' 적용 예정
https://github.com/planetarium/NineChronicles/pull/6029 에서 수정하였습니다. 230.0.4 이후 버전에서 체크 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.4
Android.v200230-230.0.4
iOS.v230.0.4(111)

![Image](https://github.com/user-attachments/assets/8ea334b4-5991-4045-ad5b-32c85bd1c8d4)
