### ISSUE TITLE
[커스텀 제작] 스킬 옵션의 등급은 다르나 효과가 동일하게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6016]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
스킬 옵션의 등급은 다르나 효과가 동일하게 출력되는 현상
- 커스텀 무기 장비의 크리티컬 데미지 증가 / 감소 스킬은 등급 별 수치 차이가 없습니다.
- Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/550400f4-29b2-4e63-86bb-cc5fbc70a49c

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 커스텀 제작 클릭
2. 임의의 무기 외형 선택 후 CP 우측 돋보기 버튼 클릭
3. 크리티컬 데미지 증가 / 감소 스킬 등급별 수치 확인
4. 크리티컬 데미지 증가 / 감소 스킬이 등급 별로 수치 차이가 없는 현상 확인

[Should be]
크리티컬 데미지 증가 / 감소 스킬이 등급 별로 상이한 수치로 출력되어야 합니다.

**Comment by NineSyu** [comment]
감사합니다. 크리티컬 데미지 증가 효과량이 전부 동일하게 적용되어있던 것을 확인했습니다.
데이터를 변경하여 정상적으로 표시되게 수정하겠습니다.

재접속 테스트하시면 정상적으로 표시될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

https://github.com/user-attachments/assets/6bc6e98c-12ca-446e-bfdf-185a1653f402
