### ISSUE TITLE
[커스텀 제작] 스킬 옵션의 수치는 다르나 이름이 동일하게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6017]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
스킬 옵션의 수치는 다르나 이름이 동일하게 출력되는 현상
- 커스텀 반지의 단일 / 연속 전체 공격 스킬은 수치는 다르나 모두 등급이 S 등급으로 출력되고 있습니다.
- Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/c290ac50-a6fb-4aa7-b2a9-7a3f62242cd0

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 커스텀 제작 클릭
2. 임의의 반지 외형 선택 후 CP 우측 돋보기 버튼 클릭
3. 단일 / 연속 전체 공격 스킬 확인
4. 단일 / 연속 전체 공격 스킬이 모두 S등급으로 출력되는 것을 확인

[Should be]
단일 / 연속 전체 공격 스킬이 수치 별로 등급이 다르게 출력되어야 합니다.

**Comment by NineSyu** [comment]
스킬 이름이 잘못 연결되어있던 것을 확인하였습니다.
데이터 및 L10n 수정하여 문제를 해결하겠습니다.

재접속 후 테스트하시면 정상동작하는 것을 확인할 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 해당 수치가 다른 스킬이 같은 확률로 출력되는 현상 발생하고 있습니다.
확인 부탁드립니다.

![Image](https://github.com/user-attachments/assets/adf23583-7ac6-4a02-87f4-cc24dd769593)

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

**Comment by sonohoshi** [comment]
@NineSyu 의도하신건지 확인 부탁드립니다

**Comment by NineSyu** [comment]
데이터랑 문구 변경 후 확률을 변경하지 않아 생긴 이슈입니다.
데이터 수정하여 정상 확률로 표시되게 수정하겠습니다.

꼼꼼이 봐주셔서 감사합니다.

재접속 후 정상 확률로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.3
Android.v200230-230.0.3
iOS.v230.0.3(110)

![Image](https://github.com/user-attachments/assets/4a659694-733f-439a-9b9c-5ce456422a42)
