### ISSUE TITLE
[UI] 모바일에서 마켓(PC) 획득처 버튼 클릭 시 아이템 정보 팝업이 닫히지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6025]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
모바일에서 아이템 팝업에 출력되는 마켓(PC) 획득처 버튼 클릭 시 팝업 바깥 부분을 클릭해도 팝업이 닫히지 않는 현상이 발생합니다.
- 스크롤, 서클 아이템 팝업에서 해당 현상이 발생하는 것을 확인했습니다.
- Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/442af96a-1179-437f-9753-ee582612fb89

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 진입
2. 인벤토리 팝업에서 재료 탭 클릭 후 스크롤 아이템 클릭
3. 출력된 스크롤 아이템 팝업에서 마켓(PC) 획득처 버튼 클릭
4. 팝업 바깥 부분을 클릭해도 팝업이 닫히지 않는 것을 확인

[Should be]
모바일에서 아이템 팝업에 출력되는 마켓(PC) 획득처 버튼 클릭 후 팝업 바깥 부분 클릭 시 팝업이 정상적으로 닫혀야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 현재 발생 중입니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200230-230.0.4
iOS.v230.0.4(111)

https://github.com/user-attachments/assets/596a76fe-3dc8-4d22-a171-f0b8a1fba25c

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 현재 발생 중 확인했습니다.
확인 부탁드립니다.

추가로, 어드벤쳐 보스가 닫힌 상태일 때 어드벤쳐 보스 바로가기 클릭 / 장비의 스킬 정보 팝업 출력 상태일 때 팝업 닫기 시도 시
해당 현상이 동일하게 발생했습니다. 확인 부탁드립니다.

[테스트 환경]
Android.v200230-230.1.1
iOS.v230.1.1(117)

https://github.com/user-attachments/assets/ebff1c0d-4acf-4db5-b20f-4dfbf1129f77

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 수정되지 않았습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200240-240.0.1
iOS.v240.0.1(120)


https://github.com/user-attachments/assets/a3251ce7-e016-4da2-b17e-1830df2897b4

**Comment by jonny-jeahyunchoi** [comment]
240.0.2에서 의심포인트 수정진행하였습니다 체크 부탁드립니다~! @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

https://github.com/user-attachments/assets/4d1d1fa7-aa4c-4134-bd1b-54595ea035b9
