### ISSUE TITLE
[월드보스] 모바일에서 월드보스 전투 등급 보상 탭 클릭 시 레드닷이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6027]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모바일에서 월드보스 전투 등급 보상 탭 클릭 시 레드닷이 출력되는 현상
- 수령 가능한 보상이 없으니 해당 탭 클릭 시 레드 닷이 출력됩니다.
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/1d2723af-047e-46ac-8a4c-3502e0d84e53)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 접속
2. 메인 로비 - 월드보스 클릭
3. 보상 버튼 - 전투 등급 보상 탭 클릭
4. 전투 등급 보상 탭 버튼 확인 시 레드닷이 출력되는 현상 확인

[Should be]
월드보스 전투 등급 보상 탭 클릭 시 수령가능한 보상이 없을 경우 레드닷이 출력되지 않아야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 수정되지 않았습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)

![Image](https://github.com/user-attachments/assets/b115f80f-fe30-4d34-803b-fa066e29de57)

**Comment by tyrosine1153** [comment]
@QgamesGeonPyoNoh 해당 이슈의 발생 상황에 대해 질문이 있습니다. (원인 확인을 위함입니다.)
1. pc 환경에서 나타난 적 있나요?
2. 최초 표시 같은 특정 상황이 아닌 계속 보이고 있나요?

**Comment by QgamesGeonPyoNoh** [comment]
1. PC 환경에서는 발생하지 않고 있습니다.
2. 모바일에서는 계속 발생 중 입니다.

**Comment by tyrosine1153** [comment]
답변 감사합니다!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.3
Android.v200240-240.0.3
iOS.v240.0.3(122)

![Image](https://github.com/user-attachments/assets/1087f6c5-be30-4b65-aa53-d6b7471e87da)
