### ISSUE TITLE
[UI] 재화 부족 팝업을 통해 해금되지 않은 컨텐츠로 이동할 수 있는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6031]
### APV version info

v200230

### Client version info

v230.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x33c449C3786DE46971a78727A11927967CbcD653

### What happened?

[내용]
상점, 분해 컨텐츠가 해금되지 않은 상태에서 재화 부족 팝업을 통해 해당 컨텐츠 화면으로 이동할 수 있는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/573b1afc-e027-4075-a40f-af6e89f5d3b9

### How to reproduce the issue

[재현 스텝]
1. 분해 컨텐츠가 해금되지 않은 상태에서 메인 로비 상단의 워크샵 슬롯 버튼 클릭
2. 워크샵 슬롯 팝업에서 크리스탈로 해금 가능한 슬롯 클릭
3. 해당 슬롯 구매 시도 시 재화 부족 팝업 출력 확인
4. 재화 부족 팝업 하단의 분해 버튼 클릭
5. 분해 화면으로 이동되는 것을 확인

[Should be]
재화 부족 팝업을 통해 해금되지 않은 컨텐츠로 이동할 수 없어야 합니다.

**Comment by eugene-doobu** [comment]
해금되지 않은 콘텐츠 이동하려고 시도시 한줄 팝업으로 해당 컨텐츠가 막혀있다고 알리고 이동하지 못하도록 수정하였습니다. 아래 pr에 스크린샷 첨부하였습니다. 240에서 확인 부탁드립니다!
https://github.com/planetarium/NineChronicles/pull/6079

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)


https://github.com/user-attachments/assets/5cd146c3-6d0e-4aee-a38c-9167d7fe8100
