### ISSUE TITLE
[어드벤쳐 보스] 어드벤쳐 보스 도전 진행 후 룬 조각 보상이 즉시 지급되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6033]
### APV version info

v200230

### Client version info

v230.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 도전 진행 후 룬 조각 보상이 즉시 지급되지 않는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/8d192ec4-4ffa-4c9c-b192-4f7d571cf39d

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스 (오픈) 클릭)
2. 어드벤쳐 보스 도전 진행
3. 보상으로 룬 조각을 획득
4. 인벤토리 확인 시 룬 조각이 즉시 지급되지 않는 현상 확인

[Should be]
어드벤쳐 보스 도전 진행 후 룬 조각 보상이 인벤토리에 바로 지급되어야 합니다.

**Comment by eugene-doobu** [comment]
어드벤처보스 탐색 직후 보상 수령할 수 있도록 클라이언트 코드 수정하였습니다. 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.5
Android.v200230-230.0.5
iOS.v230.0.5(112)

https://github.com/user-attachments/assets/e32222f2-3ae4-46d2-aa04-2f5e0cfd77db
