### ISSUE TITLE
커스텀 제작_폴리싱_#5_메뉴 잠겼을 때 크기와 위치 수정

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#6035]

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/2a55a854-4298-4d04-8409-a87311f9d448)
- 잠겨 있을 때 이미지 위치와 크기가 맞지 않아 수정합니다.

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/230.0.x
적용 브랜치 : ui/customcraft_menu-edit
사용 프리퓁 : UI_CombinationMain

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/0a6c9aa1-0a4f-4035-a910-165182f8038e)
- 잠겨있을 때는 LockObjects를 제외한 나머지 부분은 꺼 주세요.

**Comment by sonohoshi** [comment]
![Image](https://github.com/user-attachments/assets/10e5bd09-e636-4451-8279-6dc0ecf9e128)
![Image](https://github.com/user-attachments/assets/64bc77bf-c672-49b1-9611-9ae28ece79c1)

적용완료
