### ISSUE TITLE
[커스텀 제작] Heal 스킬 HP 옵션과 HIT 옵션의 이름이 같아 혼동 우려

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6039]
### APV version info

v200230

### Client version info

v230.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
Heal 스킬 HP 옵션과 HIT 옵션의 이름이 같아 혼동 우려
-Heal 스킬 S 옵션일 경우 HP  / HIT 옵션 모두 Heal(SH)로 이름이 동일합니다.
-Windows, Andorid, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/b97cf6fa-387e-40e2-b5b7-1f9d748284fc)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 커스텀 제작 클릭
2. 임의의 외형 선택 후 CP 우측 돋보기 버튼 클릭
3. 스킬 탭 - Heal 스킬 정보 확인
4. Heal 스킬 HP 옵션과 HIT 옵션이 이름이 동일한 것을 확인

**Comment by NineSyu** [comment]
관련하여 문구 어떻게 수정할지 고려중입니다.

**Comment by NineSyu** [comment]
스킬 이름 문구 수정하여 재적용하였습니다.
HP의 경우 HP, HIT의 경우 HIT로 표기하기로 했습니다.

재접속 후 확인하시면 변경된 문구 체크하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.4
Android.v200230-230.0.4
iOS.v230.0.4(111)

![Image](https://github.com/user-attachments/assets/4f6813e1-4f43-48cc-a693-dc4bccae6455)
