### ISSUE TITLE
[시즌패스] 시즌패스 11 칭호가 YGG Knights로 지급되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6043]
### APV version info

v200230

### Client version info

v230.0.3

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌패스 11 칭호가 YGG Knights로 지급되는 현상
- 기획서 상 시즌패스 11 칭호는 Hallow Winner / SPD 100,033 / HP 281,716 입니다.
- Andorid, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/f28f59d2-1910-4830-a0d1-81416ac6fb50)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 접속
2. 메인 로비 - 시즌패스 버튼 클릭
3. 프리미엄+ 구매 진행
4. 지급된 칭호가 YGG Knghits인 현상 확인

[Should be]
시즌패스 11 프리미엄+ 구매 시 Hallow Winner 칭호가 지급되어야 합니다.

**Comment by sonohoshi** [comment]
@NineSyu @jaeho0103 @U-lis 확인 부탁드립니다

**Comment by U-lis** [comment]
확인 결과 칭호 일련번호에 변경이 있었던 부분이 DB 에 제대로 반영되지 않은 것으로 확인했습니다.
DB 에서 변경 완료했고, 이제 정상적으로 보여야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
칭호는 변경되었으나 현재 칭호 아이콘이 상자 아이콘으로 출력되고 있습니다.
확인 부탁드립니다.

![Image](https://github.com/user-attachments/assets/53133e37-ebb9-4a84-873e-8fabfece176a)

[테스트 환경]
Android.v200230-230.0.4
iOS.v230.0.4(111)

**Comment by U-lis** [comment]
네 이 내용도 같이 확인되어서 수정했고, 새 버전 빌드 중입니다. 금방 새 버전으로 확인하실 수 있도록 말씀드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.5
Android.v200230-230.0.5
iOS.v230.0.5(112)

![Image](https://github.com/user-attachments/assets/c1c5031c-ee0a-4bc8-8d31-b02cae7b0600)
