### ISSUE TITLE
[워크샵] 워크샵 슬롯 Open Now 텍스트가 두 줄로 출력되는 현상//개발 없음

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6048]
### APV version info

v200230

### Client version info

v230.0.4

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
워크샵 슬롯 Open Now 텍스트가 두 줄로 출력되는 현상
-Windows 환경에서 발생 확인했습니다.
-모바일 환경은 빌드 배포 후 확인하겠습니다.

![Image](https://github.com/user-attachments/assets/91c774a9-24af-4446-a922-f9a7b6a62f8f)

### How to reproduce the issue

[재현 스텝]
1. PC 환경 접속
2. 메인 로비 - 워크샵 슬롯 버튼 클릭
3. Open Now 텍스트가 두 줄로 출력되는 현상 확인

[Should be]
워크샵 슬롯 내 Open Now 텍스트가 한 줄로 출력되어야 합니다.

**Comment by boramqo83** [comment]
부모 브랜치 : prepare/230.0.x
적용 브랜치 : ui/workshop_botton-edit240926
사용 프리퓁 : UI_CombinationSlotsPopup

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.5

![Image](https://github.com/user-attachments/assets/36eebe6a-7e5e-4b2b-a885-3671bb60b78f)
