### ISSUE TITLE
[아레나] 헤임달에서 챔피언십 메달 보상이 상자 아이콘으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6054]
### APV version info

v200230

### Client version info

v230.0.5

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
헤임달에서 챔피언십 메달 보상이 상자 아이콘으로 출력되는 현상
- 오딘에서는 메달 보상이 메달 아이콘으로 출력되는 것을 확인하였습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/8369d264-d82c-4131-8dc8-9a6972ebfe04)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 아레나 진입
2. 아레나 화면에서 좌측 스크롤을 통해 챔피언십 정보 확인
3. 챔피언십 보상 항목에 메달이 상자 아이콘으로 출력되는 것을 확인

[Should be]
헤임달에서 챔피언십 메달 보상이 메달 아이콘으로 출력되어야 합니다.

**Comment by NineSyu** [comment]
체크해보니 8시즌 메달이 챔피언쉽2 메달로 표기되고
챔피언쉽 2 메달이 미표시 되고 있는 것으로 보입니다.
체크한번 부탁드립니다.

**Comment by tyrosine1153** [comment]
관련 논의 슬랙 스레드 : https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1727406466872989

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6061 에서 수정하였습니다. 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200230-230.0.8
Android.v200230-230.0.8
iOS.v230.0.8(115)

![Image](https://github.com/user-attachments/assets/63154cc5-e350-4fe1-afd2-81ce2f5535bc)
