### ISSUE TITLE
[워크샵] 간헐적으로 일반 장비 감정 팝업 내 UI가 사라지는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6057]
### APV version info

v200230

### Client version info

v230.0.5

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
간헐적으로 일반 장비 감정 팝업 내 UI가 사라지는 현상
- Windows 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/3105aefc-2e1a-420d-b1f7-fab47aef9b57)

해당 현상 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17157930/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. PC 환경 접속
2. 메인 로비 - 워크샵 - 제작 클릭
3. 임의의 장비 제작 진행
4. 감정 팝업 출력 시 간헐적으로 UI가 사라지는 현상 발생 확인

[Should be]
일반 장비 감정 팝업 출력 시 UI가 사라지지 않아야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6059 에서 수정하였습니다. 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 추가로 발생하지 않아 이슈 종료하겠습니다.

[테스트 환경]
Windows.v200230-230.1.1
Android.v200230-230.1.1
iOS.v230.1.1(117)
