### ISSUE TITLE
[UI] 모바일에서 착용 불가능한 장비 장착 시도 시 아이템 정보 팝업이 닫히지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6058]
### APV version info

v200230

### Client version info

v230.0.5

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
모바일에서 착용 불가능한 장비 장착 시도 시 아이템 정보 팝업이 닫히지 않는 현상
- 요구 레벨이 부족하여 장착이 불가능한 장비에서 해당 현상이 발생하는 것을 확인했습니다.
- 특정 컨텐츠에서 착용이 불가능한 룬 장착 시도 시 동일한 현상이 발생하는 것을 확인했습니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/6c67bbcf-1bab-4a3c-b0f6-5182c077e1c3

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 진입
2. 장비 탭에서 요구 레벨이 부족하여 착용이 불가능한 장비 클릭
3. 출력된 아이템 정보 팝업에서 장착 버튼 클릭
4. 팝업 바깥 부분을 클릭해도 팝업이 닫히지 않는 것을 확인

[Should be]
모바일에서 착용 불가능한 장비 장착 시도 후 팝업 바깥 부분 클릭 시 팝업이 정상적으로 닫혀야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 현재 발생 중 확인했습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200230-230.1.1
Android.v200230-230.1.1
iOS.v230.1.1(117)

https://github.com/user-attachments/assets/2e5a45fd-2562-4c5d-911d-d65752fc5c77

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 수정되지 않았습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200240-240.0.1
iOS.v240.0.1(120)


https://github.com/user-attachments/assets/46967375-0224-46f2-80c5-79e406e29c97

**Comment by ipdae** [comment]
#6025 도 팝업문제인데, 모바일에서 이슈가 발생하는거봐선 원인이 같을것같습니다.

**Comment by jonny-jeahyunchoi** [comment]
240.0.2에서 의심포인트 수정진행하였습니다 체크 부탁드립니다~! @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200240-240.0.2
iOS.v240.0.2(121)

https://github.com/user-attachments/assets/9184a3b4-4eaa-4f53-9658-2615030688ae

**Comment by QgamesJeongWonChoe** [comment]
현재 착용 불가능한 룬 장착 시도 시 아이템 정보 팝업이 닫히지 않는 현상이 발생하고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

https://github.com/user-attachments/assets/272bc9a2-2881-47df-a233-77958df0628f

**Comment by jonny-jeahyunchoi** [comment]
240.0.3에 포함될예정입니다~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200240-240.0.3
iOS.v240.0.3(122)

https://github.com/user-attachments/assets/9802c4e8-9a62-46e8-8fb4-70b9ff08b2a0
