### ISSUE TITLE
[커스텀 제작] 친밀도 상한 재료가 제작 버튼 영역을 벗어나는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6070]
### APV version info

v200230

### Client version info

v230.0.8

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
친밀도 상한 재료가 제작 버튼 영역을 벗어나는 현상
- 친밀도 단계 상승 가능 상태에서 커스텀 제작 화면 최초 진입 시 발생했습니다.
- Windows 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/ac0ece3b-9797-41f4-9dfc-bb254332c25f)

### How to reproduce the issue

[재현 스텝]
1. 커스텀 제작 친밀도 상승 가능 상태 도달
2. 클라이언트 실행 후 최초로 메인 로비 - 워크샵 - 커스텀 제작 클릭
3. 친밀도 상한 재료가 제작 버튼 영역을 벗어나는 현상 확인

[Should be]
친밀도 상한 재료가 제작 버튼 영역을 벗어나지 않아야 합니다.

**Comment by sonohoshi** [comment]
이거 핫픽스로 고쳐놨습니다

**Comment by QgamesGeonPyoNoh** [comment]
커스텀 제작에서 친밀도 상승 가능 상태 도달하기 위한 재화가 부족하여
현재 수정 확인이 어렵습니다. 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.9
Android.v200250-250.0.9
iOS.v250.0.9(134)

![image](https://github.com/user-attachments/assets/73b49d03-cf0e-4b2d-a2b5-dcf0d9673c61)
