### ISSUE TITLE
커스텀 장비 랜덤 only 외형 선택시 버튼에 craft와 주사위 표시되는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#6075]
버튼있는 곳 정보가 두 가지 나오고 있습니다.

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1727694677076139?thread_ts=1727694677.076139&cid=C062ZS68A21)

**Comment by sonohoshi** [comment]
260.0.* 타겟으로 작업할 예정입니다
