### ISSUE TITLE
커스텀 제작에서 재료 툴팁에서 거래불간로 표시되는 현상

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#6077]
커스텀 제작에서 재료 툴팁에서 거래불간로 표시되는 현상

[Slack Message](https://planetariumhq.slack.com/archives/C062ZS68A21/p1727847078306969?thread_ts=1727847078.306969&cid=C062ZS68A21)

**Comment by sonohoshi** [comment]
260.0.* 타겟으로 작업합니다

**Comment by ipdae** [comment]
가상 모델을 TradableMaterial로 만들어야함
