### ISSUE TITLE
펫 관련 레이아웃 변경

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#6081]
제작창, DCC 대상으로 확장 진행

**Comment by jonny-jeahyunchoi** [comment]
클라 팻선택도 동적으로 체워지도록 작업되어있어서 데이터만넣으면 되는수준으로 확인중

**Comment by jonny-jeahyunchoi** [comment]
기획팀에 실데이터에가까운 더미데이터 요청후 클라에서 작업할부분 추가적으로 찾으면 좋을듯

**Comment by U-lis** [comment]
일단은 동적으로 되어 있어서 새 pet data 넣어서 보고 @jaeho0103 @boramqo83  님에게 공유

**Comment by eugene-doobu** [comment]
아래 이슈에서 이어서 진행하겠습니다
https://github.com/planetarium/NineChronicles/issues/6095
