### ISSUE TITLE
Synthesize

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#6086]
synthesize system

- https://github.com/planetarium/NineChronicles/issues/6501
- https://github.com/planetarium/NineChronicles/issues/6502
- https://github.com/planetarium/NineChronicles/issues/6503
- https://github.com/planetarium/NineChronicles/issues/6555

**Comment by ipdae** [comment]
- 조합, 소환처럼 레시피 를 사용하도록 처리
- 서브 레시피가 있는 레시피는 완전 랜덤 선택
- 합성으로 완성된 아이템은 바로 사용가능해야함(레시피의 requiredBlockIndex 값 무시)
