### ISSUE TITLE
펫 베리에이션 추가

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#6095]

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/pet-edd241010
사용 프리퓁 :

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/0680e72b-c7c9-418c-b7fa-e62302d41264)
- 펫 리스트 추가되야 합니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/0b6a8147-8cda-4220-9c37-4dca733369aa)
- 임시 아이콘 등록해 두었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/638b31f2-3e5b-4b05-b582-ab5c8b120314)
- 스파인의 경우 폴더만 만들어 두었습니다. 리소스 나오면 여기에 등록하도록 하겠습니다. (10/17에 리소스 나옴)

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/a163113b-e582-4119-b0ab-7c7642bb5225)
- 펫 카드 추가해 주었습니다.
- 스파인 연결해 줘야 합니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/55e9abb5-de41-43dc-b2ec-e5cbebdfe280)
- 카드의 높이가 기존 보다 20픽셀 늘어나서 카드 간 간격 조정 필요합니다.

**Comment by eugene-doobu** [comment]
PetRenderingData 데이터 수정
