### ISSUE TITLE
Render `Skip` button in a language different from the setting language when playing Saehrimnir

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles#6098]
## Context

When playing Saehrimnir, the `Skip` button appears in a language different from the setting language. Even if you choose Korean, it renders the `Skip` button in English.

## Reproduce

You can reproduce such bug by playing Saehrimnir worldboss.

![image](https://github.com/user-attachments/assets/efed03c3-2bc3-4706-8dea-d7deec5d96e7)

## Tips

To resolve this issue, you can see ...

## Links

 - https://github.com/planetarium/NineChronicles/issues/4272

**Comment by HohyunKim-kr** [comment]
#4272 해결 되었습니다.
