### ISSUE TITLE
[프리팹 및 UI] 소환 시스템

### ISSUE THREAD

**Issue by boramqo83** [planetarium/NineChronicles#6109]

**Comment by boramqo83** [comment]
부모 브랜치 : development
적용 브랜치 : ui/summon-edit241014
사용 프리퓁 : 
UI_Summon

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/41f420ff-e575-438d-9ed1-b198bc73ffd3)
- 배경 높이 간격은 690이고, 맨 위 부터 그리모어, 아우라, 룬 배경입니다. (그 밑에 두 개의 배경은 12월에 출시될 코스큠과 칭호 배경입니다.)

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/717a2dec-8ae7-4e38-aedc-2a5fd2729798)
- 그리모어, 아우라, 룬 3개의 버튼으로 이루어지도록 수정해 줍니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/08e79b30-7c7b-4216-b1ae-1b0b31388435)![Image](https://github.com/user-![Image](https://github.com/user-attachments/assets/f074509b-8f11-40fb-8aa3-5507ba5900b0)


- 라디오 버튼에 선택되어 있는 갯수만큼 "1회 소환', "11회 소환", "111회 소환" 등 버튼이름이 변경되도록 해 주세요.
- 라디오 버튼에 선택되어 있는 갯수만큼 필요 재화의 수량이 변경됩니다.
- 등급 텍스트에 등급 컬러를 적용해 줍니다. (언어 대응 필요합니다.)

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/8fdf425e-976f-4907-9f45-b04f7ecd2f38)
- 선택된 라디오 버튼의 경우 Select를 켜주세요.
- 기본으로 선택되는 라디오 버튼의 우선 순위는 재호님과 논의해 주세요. (예 : 등급이 높은 재화로 뽑을 수 있는 바로 소환 가능한 최대 갯수)

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/de755a56-7b77-4c71-9d70-ac3498211887)
- 각 텝 버튼 별 단상 위 오브젝트는 아래의 것을 켜 줍니다.
- 그리모어 : GrimoireObj
- 아우라 : RedAuraObj
- 룬 : RedRuneObj

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/b286fa12-2009-4aec-9aba-b9e27f63d364)
- 기존 우측에 나오던 캐릭터 이미지는 사용하지 않습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/09c42047-a2b6-4d23-b77b-420293efe5f9)
- 기존 우하단에 있던 내용이 말풍선 안으로 들어가졌습니다. (필요하다면 텍스트를 량을 줄이는 방향으로)

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/0adf8f4e-6981-4fc8-8d35-37f8831b36be)
- 버튼이 2개 이하일 때는 Character_All의 위치를 아래로 -120픽셀 만큼 내려가도록 해 주실 수 있으면 좋겠는데 가능할까요?

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/e2d06558-68fb-46ce-b618-63fdb9943ed1)
- 헤더메뉴에서 RankingButton ~ MailButton 요 아이콘은 소환화면에서 보이지 않도록 해 주세요.
- 소환에 필요한 재화 4종가 메뉴 아이콘만 헤더메뉴에 나오도록 해 줍니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/fd74be72-5a8c-40e4-907c-9af868b9c9d5)
- 기존 MaterialAsset 이라고 되어있던 것을 각 재화에 맞게 수정했습니다. (요 4개의 재화가 모두 보여야 함)

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/d80e9e4b-59b9-4760-a762-ca2877bba276)
- 최종 소환 화면은 위 스샷과 같이 나오면 됩니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/cba30ba1-80ee-4023-adcc-2ac3d3d24b19)
- 소환 화면의 확률 정보 버튼을 누르면 뜨는 팝업 창입니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/d19792b1-870d-462f-b39a-4b13a7f3e53c)

- 스크롤 안에 들어갈 리스트 입니다.
- 아이템 아이콘, 아이템 이름, 스텟, 스킬 이름, 확률 등 정보 연결시켜 주세요.
- 소환 확률이 표기 되지 않는 상황에서는 하이픈(-)처리해 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/f2592019-0397-49a1-a448-7e9b597fc549)

- 캐릭터 안에 스파인 들어가지도록 처리해 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/c3901b80-72ab-417c-8620-83bb60c8c87a)
- 우측 내용 연결시켜 주세요.

**Comment by boramqo83** [comment]
- 소환 화면 구성 바꾸고 나면 튜토리얼 어드러지는 부분 없는지도 확인 부탁드립니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/ff02666a-f9b9-43c7-a891-fb2f470a0b70)
- 1, 11, 111개(111개 갯수는 수정될 수 있음) 뽑았을 때 아이템 나열 방식에 따라 정리해 주었습니다.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/4146e394-6863-4881-9383-4a86f4018417)
- 결과화면의 버튼은 기존과 같이 다시 뽑기 버튼과 OK 버튼 두개가 나옵니다. (소환 화면에서 골든더스트로 11번 뽑았다면 이 버튼에도 골든더스트 11번 뽑기가 나옵니다.)
- 뽑을 재화가 부족하면 필요 재화 부분에 붉은색 텍스트가 나오는 것도 동일합니다.
- 버튼 상단에 "등급 Guaranteed!"의 등급 텍스트 부분에 등급 컬러 적용해 주세요.

**Comment by boramqo83** [comment]
![Image](https://github.com/user-attachments/assets/a04c894d-2203-4114-b2ef-2e1884d9ced9)

- 배경 높이 간격은 690이고, 맨 위 부터 그리모어, 아우라, 룬 배경입니다. 그에 맞게 연결시켜 주세요.
- 그 밑에 두 개의 배경은 12월에 출시될 코스튬과 칭호 배경입니다.

**Comment by boramqo83** [comment]
https://planetariumhq.slack.com/files/UH5UW1A3A/F07TTV15TJL/241023___________________________.zip
요기에서 소환 연출 확인하실 수 있습니다.

**Comment by sonohoshi** [comment]
![image](https://github.com/user-attachments/assets/971cae64-e2c8-4720-95d3-6ca0e4e770a7)
![image](https://github.com/user-attachments/assets/331382e3-a8fb-441e-b28f-14d4c9b60eb9)

**Comment by sonohoshi** [comment]
![Uploading image.png…]()

**Comment by sonohoshi** [comment]
> 헤더메뉴에서 RankingButton ~ MailButton 요 아이콘은 소환화면에서 보이지 않도록 해 주세요.
요거까진 어렵습니다 ㅜㅜ

**Comment by boramqo83** [comment]
선민님. 헤더메뉴에 재화와 메뉴 버튼들 모두 노출시켜주는 것으로 픽스합니다.
왼쪽에 배너가 들어가는 자리 때문에 메뉴를 노출시키지 말자고 했던 거였는데요, 배너를 노출시키지 않는 방향으로 진행하기로 했습니다. @sonohoshi 
![image](https://github.com/user-attachments/assets/50bdfe91-2b37-4926-ac98-b712f80ba2f8)
