### ISSUE TITLE
1주년 기념 이벤트 던전 대응

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#6146]
- [x] 이벤트 던전 리소스 대응 (0.5~1D)
  - 관련 이슈 : https://github.com/planetarium/NineChronicles/issues/6241
- [x] 이벤트 던전 재료로 아우라, 그리모어 제작 (2D) ([기획서](https://www.notion.so/planetarium/24Q411-1-120ed889905f80c0ab14d53d775dba0c?pvs=4#c4bfc29c83634d91a05bdacb2a6abd22))
  - [x] 임시 시트 추가해서 의도대로 동작하는지 확인 필요

**Comment by tyrosine1153** [comment]
임시 시트 추가하고 클라이언트에서 하드코딩했던 recipe id 추가했을 때 큰 문제 없이 잘 동작하는 것 확인했습니다. 이후 l10n 추가될 때 UI를 넘기지 않도록 주의해야 할 것 같습니다.

https://github.com/user-attachments/assets/252d43fc-5aae-426f-ad63-9bee336bb96b

### 추가한 시트 데이터

Lib9c/TableCSV/Crystal/CrystalHammerPointSheet.csv
```
253,9999999,999999999
254,9999999,999999999
255,9999999,999999999
256,9999999,999999999
```
Lib9c/TableCSV/Item/EquipmentItemRecipeSheet.csv
```
253,10640003,600101,100,0,0,8,999,106400031,,,0,Aura
254,10650005,600101,100,0,0,8,999,106500051,,,0,Aura
255,10760007,600101,100,0,0,8,999,107600071,,,0,Grimoire
256,10760008,600101,100,0,0,8,999,107600081,,,0,Grimoire
```

**Comment by ipdae** [comment]
오늘 내부 시연에 포함할 예정
