### ISSUE TITLE
[워크샵] 룬 탭 진입 시 검은 화면이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6149]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
룬 탭 진입 시 검은 화면이 출력되는 현상
- Windows, Android 환경에서 확인 진행했습니다.
- iOS는 현재 앱 실행 불가 현상 발생하여 확인 불가합니다.

https://github.com/user-attachments/assets/111462f8-297b-4266-ad55-831ecdc00f8a

- 해당 현상 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17472482/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬 탭 클릭
2. 검은 화면이 출력되는 현상 확인

[기대 결과]
룬 탭 진입 시 룬 화면이 출력되어야 합니다.

### Relevant log output

KeyNotFoundException: The given key '10004' was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <00000000000000000000000000000000>:0)
Nekoyume.TableData.Sheet`2[TKey,TValue].get_Item (TKey key) (at <00000000000000000000000000000000>:0)
Nekoyume.UI.Model.RuneItem..ctor (Nekoyume.TableData.Rune.RuneListSheet+Row row, System.Int32 level) (at <00000000000000000000000000000000>:0)
Nekoyume.UI.Rune.SetInventory () (at <00000000000000000000000000000000>:0)
Nekoyume.UI.Rune.Show (System.Boolean ignoreShowAnimation) (at <00000000000000000000000000000000>:0)
Nekoyume.UI.CombinationMain.<Awake>b__14_4 () (at <00000000000000000000000000000000>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress (UnityEngine.EventSystems.PointerEventData pointerEvent, System.Boolean pressed, System.Boolean released) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchEvents () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.Process () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.EventSystem.Update () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by NineSyu** [comment]
Data 및 소팅 우선순위 관리하는 클라 작업이 누락되어 생긴 이슈였습니다.

관련 작업 진행한 PR 링크 공유드립니다.
https://github.com/planetarium/NineChronicles/pull/6158

**Comment by NineSyu** [comment]
데이터 패치 후 정상 진입되는 것 확인했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)

![Image](https://github.com/user-attachments/assets/e9b6b4ce-f9c0-40f7-a4ae-b7dbdda11a83)
