### ISSUE TITLE
[런쳐] 런쳐 업데이트 및 설치 시 런쳐 백그라운드 설정이 해제되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6153]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
런쳐 업데이트 및 설치 시 런쳐 백그라운드 설정이 해제되는 현상
- 기존에 백그라운드 기능이 설정되어 있던 PC도 모두 해제되었습니다.
- Windows 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/3c2b5270-23d5-4a01-ac35-f71278b40512

### How to reproduce the issue

[재현 스텝]
1. Windows 환경
2. 런쳐 업데이트 / 설치 진행
3. 설정 버튼 클릭
4. 런쳐 백그라운드 설정이 해제되는 현상 확인

[Should be]
런쳐 업데이트 진행 시 백그라운드 설정이 유지되어야 합니다.
런쳐 설치 진행 시 백그라운드 설정이 켜진 상태여야 합니다.

**Comment by Akamig** [comment]
음.... 일단 요거는 의도된 기본동작 변경으로서 
인터널 런쳐에서는 테스트 용이성을 고려했을때 런쳐 종료상태를 혼동하지 않도록 트레이에 들어가지 않게 기본 값을 변경했습니다. 그래서 지금 런쳐를 재설치하신 경우에는 해당 기본값이 적용되어 정상입니다.

**Comment by QgamesGeonPyoNoh** [comment]
네, 기획 의도인 부분 확인했습니다.
업데이트 시 설정값이 변경되는 부분은 다음 업데이트 시에는 발생하지 않는 부분인지 문의드립니다.

**Comment by Akamig** [comment]
네, 설치가 아닌 플레이어 / 런쳐 업데이트 시에는 변경되지 않아야 정상입니다.

**Comment by QgamesGeonPyoNoh** [comment]
네, 확인 감사드립니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200240-240.0.0
