### ISSUE TITLE
[어드벤쳐] 헤임달에서 Sweep 결과 창이 출력되지 않고 로딩이 지속되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6155]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
헤임달에서 Sweep 결과 창이 출력되지 않고 로딩이 지속되는 현상
- Windows, Android 환경에서 발생 확인했습니다.
- iOS는 현재 앱 실행 불가 현상이 발생하여 확인이 불가합니다.

https://github.com/user-attachments/assets/79bae525-74c3-4161-8b68-e07af8ece026

- 해당 현상 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17473235/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 헤임달 환경
2. 메인 로비 - 어드벤쳐 - 클리어한 임의의 스테이지 선택
3. Sweep 설정 후 진행
4. Sweep 로딩화면에서 로딩이 지속되는 현상 발생

[Should be]
헤임달에서 Sweep 진행 시 결과 화면이 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
디버깅해봤는데 액션응답이 안오는 것 같습니다 @ipdae

**Comment by eugene-doobu** [comment]
이거 차라리 UI에서 타임아웃 추가로 걸어두고 너무 오래걸리면 메인로비로 보내버리는 처리 할까 하는데 괜찮을까요?
액션에서의 타임아웃 설정된 값은 6분이라 유저 입장에서 기달리긴 힘든 수치 같습니다

**Comment by eugene-doobu** [comment]
노드 상태 불안정해서 생긴 이슈 보이고, 이미지 교체 후 정상 동작하는 것 확인했습니다. 해당 버전에서 바로 확인 부탁드립니다 @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 추가로 재현되지 않아 이슈 종료하겠습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)
