### ISSUE TITLE
[아레나] 헤임달에서 아레나 입장 시 로딩이 지속되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6156]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
헤임달에서 아레나 입장 시 로딩이 지속되는 현상
- Windows, Android 환경에서 발생 확인했습니다.
- iOS는 현재 앱 실행 불가 현상이 발생하여 확인이 불가합니다.

https://github.com/user-attachments/assets/912e7607-15e2-448a-85c0-06a443261dd0

### How to reproduce the issue

[재현 스텝]
1. 헤임달 환경
2. 메인 로비 - 아레나 클릭
3. 임의의 대상 공격 진행
4. 아레나 로딩화면에서 로딩이 지속되는 현상 확인

[Should be]
헤임달에서 아레나 입장 시 전투 화면으로 진행되어야 합니다.

**Comment by ipdae** [comment]
@QgamesGeonPyoNoh 윈도우쪽 로그 파일 첨부 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17473491/Log.zip)

**Comment by ipdae** [comment]
@QgamesGeonPyoNoh 네트워크 불안정이 원인으로 보입니다. 다시 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)

https://github.com/user-attachments/assets/edf41c23-2b7b-4c3a-95a2-abd7365bee72
