### ISSUE TITLE
[아레나] 아레나 전투 시 데미지가 출력되지 않고 체력이 변경되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6157]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
아레나 전투 시 데미지가 출력되지 않고 체력이 변경되지 않는 현상
- Windows, Android 환경에서 발생 확인했습니다.
- iOS는 현재 앱 실행 불가 현상이 발생하여 확인이 불가합니다.
- 헤임달 체인은 현재 로딩이 지속되는 현상이 발생하여 확인이 불가합니다.

https://github.com/user-attachments/assets/f72c3df2-5b4a-4d39-8dd3-5b377798cb28

- 해당 이슈 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17473450/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 아레나 클릭
2. 임의의 대상 공격 진행
3. 아레나 전투 화면에서 데미지 미 출력 / 체력 미 변경 현상 확인

[Should be]
아레나 전투 화면에서 데미지 및 체력 변화가 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
내부 패키지 에러로 보이며 발생 상황이 명확하지 않습니다. 아래 pr로 변경사항을 적용하였는데 같은 상황 재발하는지 확인 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/6168

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 추가로 발생 확인되지 않아 이슈 종료하겠습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)
