### ISSUE TITLE
[어드벤쳐] 간헐적으로 전투 중 캐릭터와 몬스터 모두 일시정지하는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6159]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
간헐적으로 전투 중 캐릭터와 몬스터 모두 일시정지하는 현상
- Windows, Android 환경에서 발생 확인했습니다.
- iOS는 현재 앱 실행 불가 현상이 발생하여 확인이 불가합니다.

https://github.com/user-attachments/assets/b9380131-4482-471f-8925-b11b9c99972d

- 해당 이슈 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17474807/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 임의의 스테이지 선택
2. 스테이지 입장
3. 전투 중 캐릭터와 몬스터가 모두 일시정지하는 현상 발생

[Should be]
아드벤쳐 전투 진행 시 캐릭터와 몬스터가 일시정지하지 않아야 합니다.

**Comment by eugene-doobu** [comment]
내부 패키지 에러로 보이며 발생 상황이 명확하지 않습니다. 아래 pr로 변경사항을 적용하였는데 같은 상황 재발하는지 확인 부탁드립니다.
https://github.com/planetarium/NineChronicles/pull/6168

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 추가로 재현되지 않아 이슈 종료하겠습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)
