### ISSUE TITLE
[룬] 신규 룬 조각 아이템  이름 및 설명이 키값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6160]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신규 룬 조각 아이템 이름 및 설명이 키값으로 출력되는 현상
- Windows, Android 환경에서 발생 확인했습니다.
- iOS는 현재 앱 실행 불가 현상이 발생하여 확인이 불가합니다.

![Image](https://github.com/user-attachments/assets/122b13d2-3e54-44f8-854c-55c7337cc567)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 클릭
2. 신규 룬 조각 아이콘 클릭
3. 룬 조각 팝업 확인 시 이름 및 설명이 키값으로 출력되는 현상 확인

[Should be]
신규 룬 조각 팝업 확인 시 이름 및 설명이 텍스트로 출력되어야 합니다.

**Comment by NineSyu** [comment]
L10n 추가하여 정상적으로 표시되게 수정하였습니다.
재접속 후 체크하시면 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

![Image](https://github.com/user-attachments/assets/eaa67493-c82b-4bf0-a538-5db6eef03b16)
