### ISSUE TITLE
[몬스터콜렉션] 재화 부족 팝업을 통해 몬스터 콜렉션 팝업 진입 시 배경이 검은 화면으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6162]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 8

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
재화 부족 팝업을 통해 몬스터 콜렉션 팝업 진입 시 배경이 기존의 메인로비 화면이 아닌 검은 화면으로 출력되는 현상
- Windows, Android 환경에서 발생 확인했습니다.
- iOS는 현재 앱 실행 불가 현상이 발생하여 확인이 불가합니다.

https://github.com/user-attachments/assets/610435a8-09ea-4949-8230-e41eee74fb0a

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 상단의 워크샵 슬롯 버튼 클릭
2. 루비 더스트 부족 상태에서 3번째 슬롯 해금 시도
3. 루비 더스트 재화 부족 팝업 출력
4. 팝업 하단의 몬스터 콜렉션 버튼 클릭
5. 몬스터 콜렉션 팝업으로 이동 시 배경이 검은 화면으로 출력되는 것을 확인

[Should be]
재화 부족 팝업을 통해 몬스터 콜렉션 팝업 진입 시 배경이 메인로비 화면으로 출력되어야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6183 에서 수정하였습니다. 240.0.2 버전에서 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

https://github.com/user-attachments/assets/4c351a15-85b0-4e9c-83ea-bf25b2bec36e
