### ISSUE TITLE
[월드보스] 월드보스 메인 화면 내 룬 조각 아이콘 클릭 시 팝업 내에서 이전 월드보스 룬 이미지가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6163]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
월드보스 메인 화면 내 룬 조각 아이콘 클릭 시 팝업 내에서 이전 월드보스 룬 이미지가 출력되는 현상
- Windows, Android 환경에서 발생 확인했습니다.
- iOS는 현재 앱 실행 불가 현상이 발생하여 확인이 불가합니다.

![Image](https://github.com/user-attachments/assets/3c0d44fc-19be-4d67-bb8b-134d1bbbd8db)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 월드보스 클릭
2. 월드보스 화면 내 룬 조각 아이콘 클릭
3. 메세지 팝업 확인 시 이전 월드보스 룬 이미지 출력 확인

[Should be]
월드보스 메인 화면 내 룬 조각 메세지 팝업 확인 시 신규 룬 이미지가 출력되어야 합니다.

**Comment by tyrosine1153** [comment]
@boramqo83 cc @jaeho0103 이부분에 대한 처리는 정한게 없는 걸로 아는데 혹시 어떻게 처리하면 좋을까요?

**Comment by boramqo83** [comment]
개인적으로는 아이콘이 안나와도 되지 않을까 싶습니다.

**Comment by tyrosine1153** [comment]
테이블 패치 후 수정되었습니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)

![image](https://github.com/user-attachments/assets/cdd0abab-8a16-43f0-9e7c-798187b7b20a)
