### ISSUE TITLE
[D:CC] 펫 정렬 순서가 일정하지 않은 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6164]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 12

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
펫 정렬 순서가 일정하지 않은 현상
- 꼬마 펜리르 3종 / 빛의 발키리 3종과 동글이 3종 / 블랙캣 3종의 정렬 순서가 상이합니다.
- 의도하신 정렬 순서가 맞는지 확인 부탁드립니다.

https://github.com/user-attachments/assets/c5d802a4-b81b-4663-b785-4f4f026eb5ba

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 슬롯 클릭
2. 슬롯 내 펫 영역 클릭
3. 펫 팝업 출력
4. 펫 팝업 내 정렬 순서 확인 시 일정하지 않은 현상 확인

[Should be]
펫 팝업 내 펫들의 정렬 순서가 일정해야 합니다.

**Comment by eugene-doobu** [comment]
현재 정렬 기준(Grade 내림차순 -> Level 내림차순 -> ID 오름차순)기준으로는 저 상태가 맞습니다.
더 직관적인 정렬 기준 적용이 필요해보이시면 적용해두겠습니다 cc @jaeho0103

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6187 에서 '등급을 기준으로 내림차순 정렬'옵션을 제거합니다.
240.0.2 버전에서 정렬 순서 다시 확인 부탁드립니다 @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

![Image](https://github.com/user-attachments/assets/94d98dd6-247d-4792-a631-5431e8daf774)
