### ISSUE TITLE
[D:CC] 기획서와 펫 이름이 상이한 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6166]
### APV version info

v200240

### Client version info

v240.0.0

### Device

Windows, Android

### detailed device info

Windows 10, Android 8

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
기획서와 펫 이름이 상이한 현상
- Valkyrie of Green Light > Valkyrie of Blue Light 등 대부분 펫의 이름이 변경되었습니다.

![Image](https://github.com/user-attachments/assets/f3c497f4-a0f8-419b-8413-6811af9ed83b)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 슬롯 클릭
2. 슬롯 내 펫 영역 클릭
3. 펫 팝업 출력
4. 펫 팝업 내 펫 이름이 기획서와 상이한 현상

[Should be]
펫 이름이 기획서와 동일해야 합니다.

**Comment by NineSyu** [comment]
펫이름 기획서에 맞게 변경하여 재적용하였습니다.
재접속 후 확인하시면 정상 출력되는 것일 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)

![Image](https://github.com/user-attachments/assets/8450b4c4-a824-4d36-835e-0a75631f165b)
