### ISSUE TITLE
[메인 화면] 모바일 환경에서 메인 로비 진입 시 간헐적으로 퀘스트 / 캐릭터 UI 출력이 지연되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6172]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모바일 환경에서 메인 로비 진입 시 간헐적으로 퀘스트 / 캐릭터 UI 출력이 지연되는 현상
- 해당 현상 발생 시 동일한 에러가 반복적으로 출력되고 있습니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/69861b0c-7acd-414a-b7af-5c6011c0c46c

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경
2. 메인 로비 진입
3. 캐릭터 / 퀘스트 UI 출력이 지연되는 현상 확인

[Should be]
모바일 환경에서 메인 로비 진입 시 캐릭터 / 퀘스트 UI가 즉시 출력되어야 합니다.

### Relevant log output

NullReferenceException: Object reference not set to an instance of an object.
UnityEngine.Transform.set_position (UnityEngine.Vector3 value) (at <00000000000000000000000000000000>:0)
DG.Tweening.Plugins.Vector3Plugin.EvaluateAndApply (DG.Tweening.Plugins.Options.VectorOptions options, DG.Tweening.Tween t, System.Boolean isRelative, DG.Tweening.Core.DOGetter`1[T] getter, DG.Tweening.Core.DOSetter`1[T] setter, System.Single elapsed, UnityEngine.Vector3 startValue, UnityEngine.Vector3 changeValue, System.Single duration, System.Boolean usingInversePosition, DG.Tweening.Core.Enums.UpdateNotice updateNotice) (at <00000000000000000000000000000000>:0)
DG.Tweening.Core.TweenerCore`3[T1,T2,TPlugOptions].ApplyTween (System.Single prevPosition, System.Int32 prevCompletedLoops, System.Int32 newCompletedSteps, System.Boolean useInversePosition, DG.Tweening.Core.Enums.UpdateMode updateMode, DG.Tweening.Core.Enums.UpdateNotice updateNotice) (at <00000000000000000000000000000000>:0)
DG.Tweening.Tween.DoGoto (DG.Tweening.Tween t, System.Single toPosition, System.Int32 toCompletedLoops, DG.Tweening.Core.Enums.UpdateMode updateMode) (at <00000000000000000000000000000000>:0)
DG.Tweening.Core.TweenManager.Goto (DG.Tweening.Tween t, System.Single to, System.Boolean andPlay, DG.Tweening.Core.Enums.UpdateMode updateMode) (at <00000000000000000000000000000000>:0)
DG.Tweening.Sequence.ApplyInternalCycle (DG.Tweening.Sequence s, System.Single fromPos, System.Single toPos, DG.Tweening.Core.Enums.UpdateMode updateMode, System.Boolean useInverse, System.Boolean prevPosIsInverse, System.Boolean multiCycleStep) (at <00000000000000000000000000000000>:0)
DG.Tweening.Tween.DoGoto (DG.Tweening.Tween t, System.Single toPosition, System.Int32 toCompletedLoops, DG.Tweening.Core.Enums.UpdateMode updateMode) (at <00000000000000000000000000000000>:0)
DG.Tweening.Core.TweenManager.Update (DG.Tweening.UpdateType updateType, System.Single deltaTime, System.Single independentTime) (at <00000000000000000000000000000000>:0)
DG.Tweening.Core.DOTweenComponent.Update () (at <00000000000000000000000000000000>:0)

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6177 에서 수정하였습니다. 240.0.2에서 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 추가 재현되지 않아 이슈 종료하겠습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)
