### ISSUE TITLE
[워크샵] 크리스탈 부족 팝업에서 분해 화면으로 이동 시 워크샵 슬롯 팝업이 닫히지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6173]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Windows, iOS, Android

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
크리스탈 부족 팝업에서 분해 화면으로 이동 시 워크샵 슬롯 팝업이 닫히지 않는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/db1ae67c-c2bf-4ae4-8519-2c3d671f1ec5

### How to reproduce the issue

[재현 스텝]
1. 크리스탈 20,000,000개 이하 보유 상태
2. 메인 로비 - 워크샵 슬롯 버튼 클릭
3. 잠겨있는 5번째 워크샵 슬롯 클릭
4. 잠금 해제 시도 시 분해 화면 이동 팝업 출력
5. 분해 화면으로 이동 시 워크샵 슬롯 팝업이 계속 출력되는 현상 확인

[Should be]
분해 화면으로 이동 시 워크샵 슬롯 팝업은 닫혀야 합니다.

**Comment by ipdae** [comment]
@QgamesGeonPyoNoh 오류발생시의 PC버전 로그 첨부 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 발생 당시 Log 파일 첨부드립니다.

[Log.zip](https://github.com/user-attachments/files/17483770/Log.zip)

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6183 에서 수정하였습니다. 240.0.2 버전에서 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

https://github.com/user-attachments/assets/46153058-dfb8-444c-b8f0-7530de6e5c1a
