### ISSUE TITLE
[D:CC] 워크샵 슬롯에서 미보유 중인 펫 클릭 시 D:CC Collection 화면으로 이동되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6175]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
워크샵 슬롯에서 미보유 중인 펫 클릭 시 D:CC Collection 화면으로 이동되지 않는 현상
- 장착 중인 펫 클릭 시 동일한 현상이 발생합니다.
- 보유, 미장착 중인 펫 클릭 시 D:CC Collection 화면으로 이동되는 것을 확인했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/98ea5e5b-ff73-459a-89d9-36142f288278

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 슬롯 클릭
2. 슬롯 내 펫 영역 클릭
3. 펫 팝업 출력
4. 미보유 중인 펫 클릭
5. D:CC Collection 화면으로 이동되지 않는 것을 확인

[Should be]
워크샵 슬롯에서 미보유 중인 펫 클릭 시 D:CC Collection 화면으로 이동되어야 합니다.

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6184 에서 수정하였습니다. 240.0.2에서 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
현재 워크샵 슬롯 펫 팝업에서 출력되는 선택 버튼을 눌렀을 때만 D:CC Collection으로 이동하고 있습니다.
의도하신 사항인지 문의드립니다.

추가로, 해당 팝업 내에 선택 버튼은 어떤 용도로 출력되고 있는 것인지 확인 부탁드립니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

https://github.com/user-attachments/assets/fa559ed8-fe3c-44a7-ad45-fc36a2eaaca9

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6212 에서 펫 버튼 영역을 버튼이미지에서 펫 아이템 전체로 변경하였습니다. 다음 빌드에서 확인 부탁드립니다. (v240.0.3)

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.3
Android.v200240-240.0.3
iOS.v240.0.3(122)

https://github.com/user-attachments/assets/35b01767-5f8f-432d-a5ea-bb8710b62dd5
