### ISSUE TITLE
[월드보스] 월드보스 공격 보상이 기존 룬 조각으로 지급되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6178]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
월드보스 공격 보상이 기존 룬 조각으로 지급되는 현상
- 현재 오픈 상태인 제림니르에서 확인했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/7deefc5a-21bf-48d4-bb7b-cc84cd302eee)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 월드보스 클릭
2. 월드보스(오픈 상태) 공격 진행
3. 보상 획득 시 신규 룬 조각이 아닌 기존 룬 조각으로 지급되는 현상 확인

[Should be]
월드보스 공격 보상 획득 시 신규 룬 조각이 지급되어야 합니다.

**Comment by jaeho0103** [comment]
수정 및 체크 완료했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)

https://github.com/user-attachments/assets/e63d7133-f33f-4a15-bce5-17d762ff785e
