### ISSUE TITLE
[워크샵] 룬 강화 애니메이션 출력 단계에서 OK 버튼 클릭 시 애니메이션이 종료되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6179]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
룬 강화 시 애니메이션 출력 단계에서 OK 버튼 클릭 시 애니메이션이 종료되지 않고 강화 완료 후에도 화면을 가리는 현상
- 룬 제작 시에도 동일한 현상이 발생합니다.
- 애니메이션 출력 단계에서 OK 버튼을 클릭 하지 않을 시 애니메이션이 정상적으로 종료됩니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/1f32cc52-3afa-4e61-9ad2-e6731491e13a

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬 클릭
2. 룬 강화 진행
3. 애니메이션 출력 단계에서 OK 버튼 클릭
4. 룬 강화 완료 후에도 애니메이션이 종료되지 않고 화면을 가리는 현상 확인

[Should be]
룬 강화 시 애니메이션 출력 단계에서 OK 버튼 클릭 시 애니메이션이 종료되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@eugene-doobu 에디터 재현시 dotween문제로 보이는데 관련수정 리버트후 개선되었는지 체크필요해보입니다~! ![Image](https://github.com/user-attachments/assets/24e51945-7e70-48dc-b601-f5d327baa5ff)

**Comment by eugene-doobu** [comment]
@jonny-jeahyunchoi 이게 간헐적으로 발생한 이슈였는지는 모르겠는데 롤백한 커밋 기준으로 정상 동작 합니다~

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6177 에서 수정하였습니다. 240.0.2에서 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

https://github.com/user-attachments/assets/9abc0dcd-0e31-43d5-8aff-e9d2563904bf
