### ISSUE TITLE
[어드벤쳐 보스] 현상금 추가 팝업 내 요르문간드의 보상이 CRI 룬으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6180]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
현상금 추가 팝업 내 요르문간드의 보상이 CRI 룬으로 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/e3d771ae-67b6-410f-9ec3-c1bb54bd8ed0)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 - 어드벤쳐 보스(대기 상태) 클릭
2. 현상금 추가 팝업 출력
3. 현상금 추가 팝업 내 요르문간드의 보상이 CRI 룬으로 출력되는 현상

[Should be]
현상금 추가 팝업 내 요르문간드의 보상이 '어드벤쳐 보스 HP 룬 조각'으로 출력되어야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 체크 부탁드립니다~!

**Comment by jaeho0103** [comment]
수정 및 확인 완료했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.1
Android.v200240-240.0.1
iOS.v240.0.1(120)

![Image](https://github.com/user-attachments/assets/b71804c4-a0e0-4fa9-8b28-d01a9a8fc68b)
