### ISSUE TITLE
마일리지 지급상품 구매시 안내문구 번역키 추가

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#6186]
![Image](https://github.com/user-attachments/assets/bac09d09-fb30-4aa9-b94e-5bcfeead2fbc)
https://www.notion.so/planetarium/l10n-123ed889905f80ffbcdacdbbe31ed4ce
- UI_IAP_PURCHASE_WITH_MILEAGE_COMPLETE {마일리지값}
    - 마일리지가 있는 상품 구매시 완료팝업  contents
    - 아이콘 사용 예시 <Style=Mileage><size=20> **50** mileage earned

요거 확인 부탁드립니다~!

현재 인터널환경에서 무료상품 패키지 구매시 마일리지지급하며 해당문구뜨도록되어있습니다

**Comment by NineSyu** [comment]
문구 추가하였습니다!
다시 체크하시면 정상적으로 표시되는 것 확인 가능합니다.
