### ISSUE TITLE
[룬] 일부 룬 조각의 이름이 키 값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6188]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
일부 룬 조각의 이름이 키 값으로 출력되는 현상
- 어드벤쳐 보스 ATK / DEF 룬, 제림니르 AS 룬에서 확인했습니다.
- 등급도 노말 등급으로 출력되고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/56953785-4fce-4819-955d-4acdae5c0d63

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 - 룬 조각 탭 클릭
2. 해당 이슈가 발생한 룬 조각 아이콘 클릭
3. 해당 룬 조각 이름 및 설명이 키 값으로 출력되는 현상 확인

[Should be]
룬 조각 이름 및 설명이 텍스트로 출력되어야 합니다.

**Comment by NineSyu** [comment]
문구 추가하여 해당 문제 수정하였습니다.
재접속 후 확인하시면 정상 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

https://github.com/user-attachments/assets/46fec1a3-2e35-4f96-9860-c70e15388289
