### ISSUE TITLE
[룬] 룬 이름 내 오타 확인 요청

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6189]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
룬 이름 내 오타 확인 요청
- Saehrimmir  HPA RUne로 현재 출력되고 있습니다.
- 띄어쓰기 2칸 / U 대문자로 작성이 오타로 추정되어 확인 요청드립니다.
- Windows 환경에서 발생 확인했습니다.
![Image](https://github.com/user-attachments/assets/90760ef2-7d1a-424d-90bf-ec619d3561d3)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 - 룬 조각 탭 클릭
2. Saehrimmir  HPA RUne 확인
3. 이름 내 오타 확인

[Should be]
룬 이름이 'Saehrimmir HPA Rune' 으로 수정되어야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 룬 이름에서 동일한 현상 확인했습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200240-240.0.2


![Image](https://github.com/user-attachments/assets/d9c7be9e-141d-43d7-9490-999ab49bdaab)

**Comment by QgamesGeonPyoNoh** [comment]
해당 팝업에서도 동일 현상 확인되었습니다.
확인 부탁드립니다.

![Image](https://github.com/user-attachments/assets/7f4f2039-08bf-41ee-afd8-f9300c065fb7)

**Comment by NineSyu** [comment]
수정하는 과정에서 누락된 L10n 체크하였습니다.
수정하여 정상 표시되게 적용하였습니다.
재시작 후 체크하시면 정상 표시될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2

https://github.com/user-attachments/assets/9f238418-bf92-4bf2-973c-b6c5f1b9b19b
