### ISSUE TITLE
[월드보스] 제림니르 등급보상에서 레전더리 룬 조각이 많이 지급되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6193]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
제림니르 등급보상에서 레전더리 룬 조각이 다소 많이 지급되는 현상
- 제림니르 강타의 룬 조각이 AS 룬 조각보다 더 많이 지급되고 있습니다.
- Windows 환경에서 발생 확인했습니다.
- Android, iOS 환경에서 확인 필요합니다.

![Image](https://github.com/user-attachments/assets/0b000834-c01e-4248-bd24-aeb00f86feea)

- 해당 이슈 발생 당시 Log 파일 공유드립니다.

[log.zip](https://github.com/user-attachments/files/17486523/log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 월드보스(제림니르) 클릭
2. 제림니르 최초 진입 전투 진행
3. 제림니르 등급 보상 수령
4. 제림니르 강타의 룬 조각이 AS 룬 조각보다 더 많이 지급되는 현상 확인

[Should be]
제림니르 룬 3종 중 제림니르 강타의 룬 조각이 가장 적게 지급되어야 합니다.

**Comment by NineSyu** [comment]
아이콘 연결이 잘못되어 발생한 문제입니다.
다음 빌드에서 체크하시면 정상적으로 출력되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
아이콘 연결 수정 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

![Image](https://github.com/user-attachments/assets/b3cecfb2-750a-4499-8b67-7fe98c31e89c)
