### ISSUE TITLE
[룬] 신규 월드보스 스킬 룬의 스킬 설명이 키 값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6194]
### APV version info

v200240

### Client version info

v240.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신규 월드보스 스킬 룬의 스킬 설명이 키 값으로 출력되는 현상
- 제림니르 강타의 룬 2 / 펜리르 출혈의 룬 2 모두 발생하고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/f60e652e-2e2b-4f27-9ce5-dc8919a51a26)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬 클릭
2. 제림니르 강타의 룬 2 / 펜리르 출혈의 룬 2 클릭
3. 스킬 설명이 키 값으로 출력되는 현상 확인

[Should be]
신규 월드보스 스킬 룬의 스킬 설명이 출력되어야 합니다.

**Comment by NineSyu** [comment]
스킬 설명 추가하여 정상적으로 표시되게 수정하였습니다.
재접속 후 확인하시면 정상적으로 표시되는 것 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

https://github.com/user-attachments/assets/7c8de5d8-405a-4960-a86b-2a9cdb7d1b54
