### ISSUE TITLE
[룬] 어드벤쳐 보스 DEF 룬의 스탯이 SPD로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6196]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 DEF 룬의 스탯이 SPD로 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/6fb18b9b-42b2-41c8-a345-c4e26439e54c)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬 클릭
2. 어드벤쳐 보스 DEF 룬 클릭
3. 룬 스탯이 SPD로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 DEF 룬의 스탯이 DEF로 출력되어야 합니다.

**Comment by NineSyu** [comment]
데이터에 문제가 있는 것을 확인하였습니다.
데이터 수정하여 문제 해결하였습니다.
재접속 후 다시 확인하시면 정상적으로 표시될 것입니다.
