### ISSUE TITLE
[룬] 제림니르 강타의 룬 2 크리티컬 데미지 수치가 5250%로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6199]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
제림니르 강타의 룬 2 크리티컬 데미지 수치가 5250%로 출력되는 현상
- 과도하게 높은 수치로 출력되고 있어 확인 요청드립니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/b2684005-26c0-4395-b226-a411b714c053)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬 클릭
2. 제림니르 강타의 룬 2 클릭
3. 스킬 옵션 확인 시 1레벨 기준 크리티컬 데미지 5250% 증가 확인

[Should be]
제림니르 강타의 룬 2의 크리티컬 데미지 수치가 조정되어야 합니다.

**Comment by NineSyu** [comment]
데이터 수정하여 효과량 정상적으로 표시되게 수정하였습니다.
재접속 후 체크하시면 정상동작하는 것을 확인할 수 있습니다.
