### ISSUE TITLE
[룬] 제림니르 강타의 룬 2 스킬 설명 내에 적 DEF 감소로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6200]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
제림니르 강타의 룬 2 스킬 설명 내에 적 DEF 감소로 출력되는 현상
- 스킬 이름은 ATK 감소이나 설명 내에는 DEF 감소로 출력되고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/ca7f9d68-0e4e-41f8-8661-1c20dc4ba37e)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬 클릭
2. 제림니르 강타의 룬 2 클릭
3. 스킬 옵션 확인 시 적 DEF 감소 출력 확인

[Should be]
제림니르 강타의 룬 2 스킬 설명 확인 시 적 ATK 감소로 출력되어야 합니다.

**Comment by NineSyu** [comment]
스킬 설명에 문구가 잘못 적힌 부분을 수정하였습니다.
재접속 후 확인하시면 정상 표시될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

![Image](https://github.com/user-attachments/assets/adf3ac3a-5873-41c3-95c2-16098902db67)
