### ISSUE TITLE
[아레나] 아레나 메달 보상이 상자 아이콘으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6203]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
아레나 메달 보상이 상자 아이콘으로 출력되는 현상
- 오딘, 헤임달에서 동일하게 발생합니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/3dbfac4b-bc2c-4a18-898f-b11a9632e73c)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 아레나 진입
2. 아레나 화면에서 좌측 스크롤을 통해 시즌 정보 확인
3. 시즌 보상 항목에 메달이 상자 아이콘으로 출력되는 것을 확인

[Should be]
아레나 메달 보상이 메달 아이콘으로 출력되어야 합니다.

**Comment by sonohoshi** [comment]
@QgamesJeongWonChoe 안녕하세요, 현재 데이터 갱신으로 해결된 상태로 보입니다. 다시한번 확인 부탁드립니다.

**Comment by NineSyu** [comment]
데이터 수정 후 정상적으로 표시되게 수정되었습니다.
재접속 후 확인하시면 정상적으로 표시될 것입니다!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

![Image](https://github.com/user-attachments/assets/7dd0709f-aa21-434e-977f-49ea946ba8db)
