### ISSUE TITLE
[룬] 제림니르 강타의 룬 2 스킬 사용 시 적에게 공격력 증가 버프가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6204]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
제림니르 강타의 룬 2 스킬 사용 시 적에게 공격력 증가 버프가 출력되는 현상
- 어드벤쳐 / 아레나 / 월드보스에서 모두 발생했습니다.
- 공격력이 상당히 높게 증가하는 것이 데미지를 통해 확인됩니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/987f60f5-e6d2-47b6-93a9-257788e9194f

- 해당 이슈 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17499455/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 임의의 전투 컨텐츠 진입
2. 제림니르 강타의 룬 2 장착
3. 전투 진행 시 룬 스킬 사용
4. 적에게 공격력 증가 버프가 적용되는 현상 확인

[Should be]
제림니르 강타의 룬 2 스킬 사용 시 적에게 공격력 감소 디버프가 적용되어야 합니다.

**Comment by NineSyu** [comment]
월드보스 룬 스펙을 변경하여 재적용하였습니다.
재접속 후 확인하시면 변경된 스펙을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
제림니르 강타의 룬 2 스킬 사용 시 현재 캐릭터에서 쏜즈 버프 아이콘이 출력되고 있으며,
적에게는 디버프 아이콘이 출력되지 않고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200240-240.0.4

![Image](https://github.com/user-attachments/assets/ebff0a34-ac18-4bbf-9013-91a216015664)

**Comment by NineSyu** [comment]
가시는 자신에게 거는 버프이며 자신을 타격한 대상에게 피해를 주는 버프가 맞습니다!
정상 스펙으로 보여집니다! 체크해주셔서 감사드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
제림니르 강타의 룬 스펙 및 정보 변경 확인했습니다.
현재 스킬 설명 내 ATK가 AKT로 출력되고 있습니다. 확인 부탁드립니다.
![Image](https://github.com/user-attachments/assets/a31aac6e-a728-4fab-8bc7-9fbb5e4193e8)
[테스트 환경]
Windows.v200240-240.0.4
Android.v200240-240.0.4
iOS.v240.0.4(123)

**Comment by NineSyu** [comment]
감사합니다 문구 수정하여 재적용하였습니다!
재접속 후 체크하시면 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.4
Android.v200240-240.0.4
iOS.v240.0.4(123)

![Image](https://github.com/user-attachments/assets/c0fc72b9-27aa-4e31-b16e-af9c51490370)
