### ISSUE TITLE
[룬] 펜리르 출혈의 룬 2 스킬 사용 시 적에게 방어력 증가 버프가 적용되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6205]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows, iOS, Android

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
펜리르 출혈의 룬 2 스킬 사용 시 적에게 방어력 증가 버프가 적용되는 현상
- 어드벤쳐 / 아레나 / 월드보스에서 모두 발생했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/07d3b846-1b90-4bc5-94c1-c2bbfe3f8b54

- 해당 이슈 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17499596/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 임의의 전투 컨텐츠 진입
2. 펜리르 출혈의 룬 2 장착
3. 전투 진행 시 룬 스킬 사용
4. 적에게 방어력 증가 버프가 적용되는 현상 확인

[Should be]
펜리르 출혈의 룬 2 스킬 사용 시 적에게 방어력 감소 디버프가 적용되어야 합니다.

**Comment by NineSyu** [comment]
월드보스 룬 스펙을 변경하여 재적용하였습니다.
재접속 후 확인하시면 변경된 스펙을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
펜리르 출혈의 룬 2 스펙 및 정보 변경 확인 완료했습니다.

[테스트 환경]
Windows.v200240-240.0.4
Android.v200240-240.0.4
iOS.v240.0.4(123)

https://github.com/user-attachments/assets/97869284-1e9f-46d1-94f6-bf6b6d46c31f
