### ISSUE TITLE
[아레나] 오딘에서 아레나 공격 대상이 일부만 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6206]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
오딘에서 아레나 공격 대상이 일부만 출력되는 현상
- 현재 인터널 내에서 테스트 중인 계정만 출력되는 것으로 확인됩니다.
- 일부 계정에서는 아레나 진입 시 무한 로딩 발생하고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/647fb6cc-3783-4e28-b330-d4fc96112a79)

- 헤당 이슈 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17499693/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 오딘 환경
2. 메인 로비 - 아레나 클릭
3. 공격 대상 확인
4. 아레나 공격 대상이 일부만 출력되는 현상 확인

[Should be]
오딘에서 아레나 진입 시 공격 대상이 전체 출력되어야 합니다.

**Comment by ipdae** [comment]
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/c92a30bd-7e96-432a-9678-d484877fea53">
@QgamesGeonPyoNoh 실제 목록이 3명인것으로 보이는데, 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 상태에서 아레나 테스트 진행 시, 점수 차이로 인해  공격이 불가능한 상태가 됩니다.
확인 부탁드립니다.

**Comment by ipdae** [comment]
@QgamesGeonPyoNoh 테스트 해봤을때 아레나 목록엔 문제가 없는것처럼 보입니다. 계정상태 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
아레나에 인터널 테스트 진행 중인 캐릭터만 출력되고 있는 현 상황이 정상 상태라는 말씀이실지 문의드립니다.
현재 점수가 1100점을 초과할 경우 점수 차이로 인해 아레나 대상이 출력되지 않습니다.

![Image](https://github.com/user-attachments/assets/fb09fbeb-8cc6-4552-9ba7-cdae33c6e036)

[테스트 환경]
Windows.v200240-240.0.2
Android.v200240-240.0.2
iOS.v240.0.2(121)

**Comment by ipdae** [comment]
<img width="700" alt="image" src="https://github.com/user-attachments/assets/6c6ddef7-5f4c-4497-88c3-514ff0cc4696">

@QgamesGeonPyoNoh 점수를 기준으로 필터링 되는건 의도된 동작이고, 인터널 환경 특성상 참여자가 적은게 원인으로 보입니다. 점수가 낮은 플레이어 입장에선 정상적으로 목록이 표시되고 있어 문제사항이 아닌걸로 판단되어 이슈는 닫아두겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
네, 확인 감사합니다.
