### ISSUE TITLE
[시즌패스] iOS에서 시즌패스 프리미엄+ 구매가 불가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6207]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows, iOS

### detailed device info

iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
iOS에서 시즌패스 프리미엄+ 구매가 불가능한 현상
- 가격이 0.00으로 출력되며 클릭 시 구매가 진행되지 않습니다.
- iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/7a739c47-e05c-4955-a70a-e5afddd6324a)

### How to reproduce the issue

[재현 스텝]
1. iOS 환경
2. 메인 로비 - 시즌패스 클릭
3. 해제하기 클릭
4. 시즌패스 프리미엄+ 구매 버튼 클릭 시 구매 불가 현상 확인

[Should be]
iOS 환경에서 시즌패스 프리미엄+ 구매가 가능해야 합니다.

**Comment by jaeho0103** [comment]
ios 에서는 아직 상품 심사가 완료되지 않았습니다. 월요일정도에 재시도 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
iOS.v240.0.3(122)|

https://github.com/user-attachments/assets/ba5ceec0-cd75-4132-bab8-ae97e2f88ea5
