### ISSUE TITLE
[시즌패스] 시즌패스 12 칭호가 변경되지 않은 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6208]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌패스 12 칭호가 변경되지 않은 현상
- 시즌패스 11 칭호 '할로우 위너'가 계속 출력되고 있습니다.
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/59ecd5bc-8588-4ad3-b2a2-c87deaf657c0)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경
2. 메인 로비 - 시즌패스 클릭
3. 해제하기 클릭
4. 시즌패스 칭호가 '할로우 위너'로 출력되는 현상 확인

[Should be]
시즌패스 칭호가 변경되어야 합니다.

**Comment by NineSyu** [comment]
칭호의 이름과 내용 추가하여 갱신하였습니다. 재접속 후엔 정상적으로 표시될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.3
Android.v200240-240.0.3
iOS.v240.0.3(122)

![Image](https://github.com/user-attachments/assets/5be033a7-d30b-4739-9e72-8e793fca2651)
