### ISSUE TITLE
[컬렉션] 도감 재료 등록 시 아이템 정보 팝업이 사라지는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6209]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
도감 재료 등록 팝업이 출력된 상태에서 우측의 등록 팝업 클릭 시 좌측 아이템 정보 팝업이 사라지는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/ab1191f9-431e-4ff7-ad2c-09817aa64b08

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 컬렉션 진입
2. 등록 가능한 재료의 Activate 버튼 클릭
3. 출력된 도감 재료 등록 팝업에서 우측의 등록 팝업 클릭
4. 좌측 아이템 정보 팝업이 사라지는 것을 확인

[Should be]
도감 재료 등록 팝업이 출력된 상태에서 우측의 등록 팝업 클릭 시 좌측 아이템 정보 팝업이 사라지지 않아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
240.0.3 에서 수정될예정입니다~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.3
Android.v200240-240.0.3
iOS.v240.0.3(122)

https://github.com/user-attachments/assets/8dfcc561-0bd8-463e-bfb6-c6b76aa55664
