### ISSUE TITLE
[상점] 다중 구매 진행 시 NCG 부족 팝업에 출력되는 NCG 수량과 실제 가격이 상이한 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6213]
### APV version info

v200240

### Client version info

v240.0.2

### Device

Windows

### detailed device info

Windows 10

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
다중 구매 진행 시 NCG 부족 팝업에 출력되는 NCG 수량과 실제 가격이 상이한 현상
- 다중 구매가 아닌 일반 구매 시 NCG 부족 팝업에 출력되는 NCG 수량은 실제 가격과 동일하게 출력됩니다.
- Windows 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/dc2dab36-c997-4fe0-b4e3-3e49fca42fa8

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 상점 진입
2. 장바구니 버튼 클릭
3. 아이템 선택 후 NCG가 부족한 상태에서 구매 버튼 클릭
4. NCG 부족 팝업 출력
5. NCG 부족 팝업 상단에 출력된 NCG 수량과 실제 가격이 상이한 것을 확인

[Should be]
다중 구매 진행 시 NCG 부족 팝업에 출력되는 NCG 수량과 실제 가격이 동일해야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200240-240.0.3

https://github.com/user-attachments/assets/f5fe9051-6186-44f9-937b-7b57eaba1d2a
