### ISSUE TITLE
[상점] iOS에서 패키지 구매 시 간헐적으로 구입 정보 확인 불가 팝업이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6218]
### APV version info

v200240

### Client version info

v240.0.2

### Device

iOS

### detailed device info

iOS 17

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
iOS에서 패키지 구매 시 간헐적으로 구입 정보 확인 불가 팝업이 출력되는 현상
- 해당 팝업이 출력된 후 구매했던 패키지 상품이 정상적으로 수령되는 부분 확인했습니다.
- iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/0626e0bb-54c1-4179-88e8-644c2b5a2815)

### How to reproduce the issue

[재현 스텝]
1. iOS 환경에서 메인 로비 - 상점 진입
2. 패키지 상품 구매 진행
3. 구매 후 간헐적으로 구입 정보 확인 불가 팝업이 출력되는 것을 확인

[Should be]
iOS에서 패키지 구매 시 구입 정보 확인 불가 팝업이 출력되지 않아야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
문제 발생시 로그도 같이 첨부 부탁드립니다~!

**Comment by jonny-jeahyunchoi** [comment]
@QgamesJeongWonChoe 영상도 같이 첨부가능할까요?

**Comment by jonny-jeahyunchoi** [comment]
@QgamesJeongWonChoe 다운받으신 클라이언트가 k버전인지 글로벌버전인지 체크가능할까요?

**Comment by QgamesJeongWonChoe** [comment]
> @QgamesJeongWonChoe 다운받으신 클라이언트가 k버전인지 글로벌버전인지 체크가능할까요?

글로벌 버전입니다.

**Comment by QgamesJeongWonChoe** [comment]
> 문제 발생시 로그도 같이 첨부 부탁드립니다~!

해당 현상 발생 시에 출력된 에러 로그 공유 드립니다.
onPurchaseFailedEvent(productId:a_pkg_level200 message:APPLE_알 수 없는 오류가 발생했습니다. storeSpecificErrorCode: SKErrorUnknown) UnityEngine.Purchasing.Extension.UnityUtil:Update()

현재 해당 현상은 재현되지 않는 상태입니다.

**Comment by jonny-jeahyunchoi** [comment]
@QgamesJeongWonChoe 에러로그뿐만아니라 그 당시 로그를 쭉 보고싶은데요 스크린샷 공유가능하실까요?

**Comment by QgamesJeongWonChoe** [comment]
> @QgamesJeongWonChoe

스크린샷은 없습니다. 해당 이슈 재현 시 바로 공유드리겠습니다.

**Comment by jonny-jeahyunchoi** [comment]
넵 확인감사합니다~!

**Comment by jonny-jeahyunchoi** [comment]
이슈 재현되지않는것같고 당시 통신문제로 보여서 닫도록 하겠습니다~!
