### ISSUE TITLE
[워크샵] 신규 음식의 이름 및 설명이 키 값으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6223]
### APV version info

v200240

### Client version info

v240.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신규 음식의 이름 및 설명이 키 값으로 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/33b60f4a-5991-4375-a22f-35eb9559b5fd)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 제작 클릭
2. 음식 탭 - DEF 탭 클릭
3. 신규 음식 제작 진행
4. 신규 음식 확인 시 이름 및 설명이 키 값으로 출력되는 현상 확인

[Should be]
신규 음식의 이름 및 설명이 키 값으로 출력되지 않아야 합니다.

**Comment by NineSyu** [comment]
스테이크 이름과 내용을 추가하여 갱신하였습니다.
재접속 후 체크하시면 정상표시되는 것을 확인 하실 수 있습니다.
