### ISSUE TITLE
[콜렉션] 스킬 부여 장비로 스킬 미부여 컬렉션 등록 불가 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6224]
### APV version info

v200240

### Client version info

v240.0.3

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
스킬 부여 장비로 스킬 미부여 컬렉션 등록 불가 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/89cfd975-6908-4311-9d08-91acdf4a5dac

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 제작 클릭
2. 롱 소드 (바람) 제작 진행
3. 100% 확률로 스킬이 부여된 롱 소드 (바람) 획득
4. 해당 장비를 컬렉션 등록 시도 시 불가능한 현상 확인

[Should be]
스킬 부여된 장비로 스킬 미부여 콜렉션 등록이 가능해야 합니다.

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 이거 의도인지 체크 부탁드립니다~!

**Comment by jaeho0103** [comment]
스킬 부여 장비로 스킬 미부여 장비 콜렉션에 못넣는건 의도된 스펙입니다.
다만 표시가 스킬 미부여야 한다가 아니다보니 전달에 이슈 있어보이네요. 추후 스킬이 없어야 한다 표시되면 좋을 것 같습니다.
cc @boramqo83

**Comment by boramqo83** [comment]
![image](https://github.com/user-attachments/assets/8f965d09-aed1-4915-a900-6310388b571a)
- "스킬 없는 장비" 등 문구 다르게 적용

**Comment by ipdae** [comment]
마일스톤 옮겨두겠습니다.

**Comment by tyrosine1153** [comment]
@ipdae 이 수정사항 이번 버전에 들어가야 합니다

**Comment by ipdae** [comment]
다시 돌려놨습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
메인넷.Windows.v200240-240.0.4
메인넷.Android.v200240-240.0.4
메인넷.iOS.v240.0.4(123)

![image](https://github.com/user-attachments/assets/28bf941b-fde6-453f-9995-83305cab98ff)
