### ISSUE TITLE
[커스텀 제작] 랜덤 정보 팝업 내의 텍스트가 영문으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6227]
### APV version info

v200240

### Client version info

v240.0.3

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
랜덤 정보 팝업 내의 텍스트가 영문으로 출력되는 현상
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/0575c578-64e3-4705-9492-6a3b316077cd)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 커스텀 제작 진입
2. 랜덤 제작 선택 후 랜덤 정보 버튼 클릭
3. 랜덤 정보 팝업 하단에 영문이 출력되는 것을 확인

[Should be]
랜덤 정보 팝업 내의 텍스트가 영문으로 출력되지 않아야 합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.9
iOS.v250.0.9(134)

![Image](https://github.com/user-attachments/assets/1c1ae66a-6fbd-4a62-950f-226dde306204)
