### ISSUE TITLE
[상점] 추천 상품 탭에서 출력되는 마스터 펫 콜렉터 패키지의 상품 구성이 실제 상품 구성과 상이한 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6231]
### APV version info

v200240

### Client version info

v240.0.4

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
추천 상품 탭에서 출력되는 마스터 펫 콜렉터 패키지의 상품 구성이 실제 상품 구성과 상이한 현상
- 추천 상품 탭에서는 상품 구성이 D:CC 블랙캣 120개, 빛의 발키리 15000개, 빨간 동글이 20개, 꼬마 펜리르 150개, 크리스탈 10개로 노출됩니다.
- 패키지 클릭 시 출력되는 상품 팝업의 상품 구성은 실제 구매 시 지급되는 개수와 동일하게 노출됩니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/7c96a001-60ab-4cb5-8644-e4b486feebec

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경에서 메인 로비 - 상점 진입
2. 상점 화면에서 추천 상품 탭 클릭
3. 마스터 펫 콜렉터 패키지의 상품 구성이 D:CC 블랙캣 120개, 빛의 발키리 15000개, 빨간 동글이 20개, 꼬마 펜리르 150개, 크리스탈 10개로 노출되는 것을 확인
4. 상품 구매 시 D:CC 블랙캣 10개, 빛의 발키리 10개, 빨간 동글이 10개, 꼬마 펜리르 10개, 크리스탈 10M개가 지급되는 것을 확인

[Should be]
추천 상품 탭에서 출력되는 마스터 펫 콜렉터 패키지의 상품 구성이 실제 상품 구성과 동일해야 합니다.

**Comment by U-lis** [comment]
이미지 교체해두었습니다.
새 이미지를 확인하시려면 게임 재시작이 필요합니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200240-240.0.4
iOS.v240.0.4(123)

![Image](https://github.com/user-attachments/assets/abd6fc9a-9780-4d94-b9a5-1dab6374eb09)
