### ISSUE TITLE
SummonDetailPopup에 새 레이아웃 적용

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#6238]
~31일까지 기본 UI
11월 1일까지 미흡한 연출 개선 추가작업 진행

1105 수정
- 여태 110회 소환 연출 수정했음
- 아우라/그리모어/룬 상세 스펙 팝업 진행중~11월 6일까지
- 이후 시연 전까지 development에 PR 머지시키고 미흡한 부분 보완 예정

**Comment by sonohoshi** [comment]
![Image](https://github.com/user-attachments/assets/45e4b0fe-d82d-453c-94bf-e0de77e3aa67)
![Image](https://github.com/user-attachments/assets/5bd8dffc-1f0d-40b6-b185-c9229ad468a1)
![Image](https://github.com/user-attachments/assets/8266a7e6-e6db-4bfe-9a9e-d834dc2f8843)
![Image](https://github.com/user-attachments/assets/057d57e2-645c-46a2-a382-a64bb3b80f29)
![Image](https://github.com/user-attachments/assets/efb87b1d-0b0e-4d9b-83d9-55bef231bbbf)
![Image](https://github.com/user-attachments/assets/e3eedf21-da93-437a-ae39-d3df07ec908f)

**Comment by ipdae** [comment]
- 소환액션 연결까지 1차 PR
- 110회 연출 변경 2차 PR
- 상세팝업 및 나머지 3차 PR
