### ISSUE TITLE
시즌패스 다양화 Client

### ISSUE THREAD

**Issue by jonny-jeahyunchoi** [planetarium/NineChronicles#6243]
- [x] 셀개수 동적변화에 따른 UI대응
  - [x] 스크롤러 시작 위치 계산
  - [x] 라인 이미지 길이 계산
  - [x] 30개 이상의 셀이 필요한경우 동적생성
- [x] 이벤트 기반 시즌패스 UI갱신 구조 변경
- [x] 카테고리탭 및 UX플로우 정리
- [x] l10n 키 생성, 연결, 정리
  - [x] 프리미엄 상품 키 구조 변경해야함(시즌패스 타입이 추가되어야함)
  - [x] 프리미엄 상품 설명 l10n키구조도 변경해야함.
- [x] API 구조 변경 대응
- [x] UX 플로우에 api 요청 연결
- [x] 로비 버튼에 이름 변경 및아이콘 변경스팩 삭제
- [x] 2차 시연피드백 수정
  - [x] 래밸텍스트, 슬라이더 색상 변경되도록
  - [x] 배경및 아이콘 순서 바뀐 문제
- [x] 카테고리 red dot 추가 및 기능 추가
- [x] 시즌 비활성화 처리 (UI 및 예외처리)
- [ ] 시즌패스 상품 테스트

**Comment by ipdae** [comment]
번역어, red dot 같은 추가 수정이 있을수 있으나 7일 시연에서 핵심적인 부분(API 연동 등)은 확인가능

**Comment by ipdae** [comment]
경험치를 올렸을때 수령이 정상적으로 돌아가는지 보기

**Comment by ipdae** [comment]
- 전체적으로 요청에 대한 응답이 느림. 초기화 관련 fetch API를 추가하거나 서비스입장에서 low query가 생겼는지 확인 필요
