### ISSUE TITLE
컬렉션 재료 정보에서, 스킬없음 조건에 스킬 아이콘 지우기

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#6245]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1730248984285919

![Image](https://github.com/user-attachments/assets/8fceabfe-01e3-4b27-a559-77e8eb1c0976)

**Comment by moreal** [comment]
안녕하세요 @ipdae 님. 기여자분들이 9c 클라이언트에 기여가능한 이슈를 확인하던 중 이 이슈를 발견했는데요, 모바일에서 컬렉션 뷰 확인했을때는 해결된 것으로 보여서 확인 부탁드립니다 🙏🏻

**Comment by ipdae** [comment]
@moreal 네 최근 릴리즈에서 해결된것같습니다. 이 이슈는 닫겠습니다.
