### ISSUE TITLE
[콜렉션] 8월드 장비 콜렉션 스탯이 7월드 장비보다 낮게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6258]
### APV version info

메인넷.v200240

### Client version info

v240.0.4

### Device

Windows, iOS, Android

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
 8월드 장비 콜렉션 스탯이 7월드 장비보다 낮게 출력되는 현상
- 8월드 무기(ATK) / 갑옷(HP) 콜렉션 스탯 수치가 7월드 장비도다 낮게 출력됩니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/1bca8ecd-edbe-4500-9862-02b12621ffa3)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 콜렉션 클릭
2. 7월드 무기 / 갑옷 0강 콜렉션 (스킬 O / 스킬 X) 확인
3. 8월드 무기 / 갑옷 0강 콜렉션 (스킬 O / 스킬 X) 확인
4. 8월드 무기 / 갑옷의 스탯이 7월드 장비보다 낮게 출력되는 현상 확인

[Should be]
8월드 무기 / 갑옷의 콜렉션 스탯이 7월드 장비보다 높게 출력되어야 합니다.

**Comment by jaeho0103** [comment]
8월드까지 진행의 독려의미로 1~7월드 콜렉션에 추가 가중치를 두어 일어난 부분으로 현재로서는 의도된 부분입니다.

**Comment by QgamesGeonPyoNoh** [comment]
기획 의도인 부분 확인했습니다.
이슈 종료하겠습니다.
