### ISSUE TITLE
[콜렉션] 8월드 장비 콜렉션에서 기존 장비와 다른 스탯이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6259]
### APV version info

메인넷.v200240

### Client version info

v240.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
 8월드 장비 콜렉션에서 기존 장비와 다른 스탯이 출력되는 현상
- 벨트 HIT / 목걸이 SPD 옵션이었으나 8월드 장비는 반대로 설정되어 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/013a369c-2b2f-4620-b3da-0c53a8f51fdf)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 콜렉션 클릭
2. 7월드 이하 벨트 / 목걸이 스탯이 HIT / SPD 인 것을 확인
3. 8월드 벨트 / 목걸이 스탯이 SPD / HIT인 현상 확인

[Should be]
8월드 벨트 콜렉션 스탯은 HIT / 8월드 목걸이 콜렉션 스탯은 SPD로 변경되어야 합니다.

**Comment by jaeho0103** [comment]
앞 월드의 콜렉션이 잘못 들어간 부분이었으나, 이미 달성한 분들을 고려하여 그대로 둔 부분으로, 이후에는 원래 장비 스탯에 따라 콜렉션리워드 스탯이 분배될 예정입니다. 의도된 부분입니다.

**Comment by QgamesGeonPyoNoh** [comment]
기획 의도인 부분 확인했습니다.
이슈 종료하겠습니다.
