### ISSUE TITLE
[워크샵] 전사의 목걸이 슈퍼 크래프트 비용이 상위 장비보다 더 높게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6260]
### APV version info

v200240

### Client version info

v240.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
전사의 목걸이 슈퍼 크래프트 비용이 상위 장비보다 더 높게 출력되는 현상
- 전사의 목걸이 슈퍼 크래프트 비용이 크리스탈 8000000개로 출력되는 것을 확인했습니다.
- 상위 장비인 전설의 목걸이 슈퍼 크래프트 비용이 크리스탈 1000000개로 출력되는 것을 확인했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/c58c2914-2018-42fb-bfd2-f9ca01962149

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 제작 진입
2. 전사의 목걸이 레시피 클릭 후 슈퍼 크래프트 UI 클릭
3. 슈퍼 크래프트 비용이 크리스탈 8000000개로 출력되는 것을 확인
4. 전설의 목걸이 레시피 클릭 후 슈퍼 크래프트 UI 클릭
5. 슈퍼 크래프트 비용이 크리스탈 1000000개로 출력되는 것을 확인

[Should be]
전사의 목걸이 슈퍼 크래프트 비용이 상위 장비보다 낮게 출력되어야 합니다.

**Comment by jaeho0103** [comment]
50만으로 수정해서 올려두었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.4
Android.v200260-260.0.4
iOS.v260.0.4(139)

![Image](https://github.com/user-attachments/assets/8a64b901-315d-4e97-bed3-5707c0040480)
