### ISSUE TITLE
클라이언트에서 제네시스 분기 처리 추가하기

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#6265]
현재는 오딘이 아니면 헤임달로만 처리중인 부분을 토르까지 처리할 수 있어야합니다.

**Comment by eugene-doobu** [comment]
lib9c ThorGenesisHash 확인?
https://github.com/planetarium/lib9c/pull/2973/files

**Comment by eugene-doobu** [comment]
분기 처리 되는 것으로 보여 close 하겠습니다
