### ISSUE TITLE
코스튬 착용 후 전투에 즉시 반영되지 않는 것으로 보임

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/NineChronicles#6289]
에디터에서 돌릴때 튀어나온거라 실제로 동작 어떤지 확인부터 해봐야함, 확인 및 수정에 1일정도 투자해볼 수 있을듯

**Comment by jonny-jeahyunchoi** [comment]
https://github.com/planetarium/NineChronicles/issues/6352 해당이슈와 동일한 문제로 이슈닫도록하겠습니다
