### ISSUE TITLE
[로그인] 모바일에서 체인 선택 버튼이 로그인 영역에 가려지는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6340]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
모바일에서 체인 선택 버튼이 로그인 영역에 가려지는 현상
- Android, iOS 환경에서 발생 확인했습니다.
![Image](https://github.com/user-attachments/assets/304a20ca-e473-4036-a1a5-bc885dd31f6c)

### How to reproduce the issue

[재현 스텝]
1. 비로그인 상태로 모바일 환경에서 앱 접속
2. 로그인 버튼 출력 시 체인 선택 버튼이 로그인 영역에 가려지는 것을 확인

[Should be]
모바일에서 체인 선택 버튼이 로그인 영역에 가려지지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6353 에서 수정하였습니다. v250.0.2 버전에서 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 동일하게 발생하고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200250-250.0.3
iOS.v250.0.3(128)

![Image](https://github.com/user-attachments/assets/e28aae4c-dd67-46ae-9359-720f07885475)

**Comment by eugene-doobu** [comment]
250.0.4 버전에서 UI 겹침 문제 재현되는거 확인했습니다. 하지만 보내주신 스크린샷처럼 4개의 UI가 보이는 현상은 일어나지 않는데 혹시 250.0.4 이후 버전에서 같은 현상 발생하면 로그 공유 가능할까요?

250.0.4버전은 지금 qa에 전달되지 않은 것으로 알고있어서 아마 새로 qa이슈 대응이 포함된 250.0.5이후 빌드에서 확인 가능하실 것 같습니다.

**Comment by eugene-doobu** [comment]
위 내용과 별도로 UI 겹침 문제 자체는 수정해두도록 하겠습니다

**Comment by QgamesGeonPyoNoh** [comment]
말씀해주신 4개의 UI가 구글 / 애플 / 트위터 / 디스코드 버튼 말씀이신지 문의드립니다.

**Comment by eugene-doobu** [comment]
@QgamesGeonPyoNoh 넵 맞습니다!

**Comment by QgamesGeonPyoNoh** [comment]
K버전에서는 디스코드 / 트위터 버튼이 출력되지 않으나
M버전에서는 4개 버튼이 현재 출력되고 있습니다.

**Comment by eugene-doobu** [comment]
![image](https://github.com/user-attachments/assets/62fc1a8a-022f-4abb-bbc5-54e9a1f13b83)

관련해서 스펙 자체가 위 스크린샷처럼 바뀌어서 해당 이슈가 발생하지 않을 것 같습니다. 스펙 변경으로 이슈 close해도 괜찮을까요? 해당 변경 사항은 250.0.6 (아마 목요일 오후 중 빌드 후 전달 예상)에 진행될 예정입니다

https://github.com/planetarium/NineChronicles/issues/6430

**Comment by QgamesGeonPyoNoh** [comment]
네, UI 변경 예정이라면 이슈 종료 해주셔도 괜찮습니다.
