### ISSUE TITLE
[실행] PC 버전 클라이언트 실행 시 모바일 체인 선택 UI가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6343]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
PC 버전 클라이언트 실행 시 모바일 체인 선택 UI가 출력되는 현상
- 클릭 시 체인 선택 팝업이 출력되나 바로 PC 클라이언트로 실행됩니다.
- Windows 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/e4f7c73b-efbc-4a71-9a44-ebaba58e0828

### How to reproduce the issue

[재현 스텝]
1. PC 환경 세팅
2. 클라이언트 실행
3. 실행 시 모바일 체인 선택 UI 가 출력되는 현상 확인

[Should be]
PC 클라이언트 실행 시 모바일 체인 선택 UI가 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles/pull/6353 에서 수정하였습니다. v250.0.2 버전에서 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.3

https://github.com/user-attachments/assets/32137aed-ed7c-4fb2-989a-07f4f92c53a2
