### ISSUE TITLE
[UI] 크리스탈 팝업 내 보유량이 소수점 단위까지 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6344]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
크리스탈 팝업 내 보유량이 소수점 단위까지 출력되는 현상
- 크리스탈이 소수점 형태로 보유할 수 있는 것인지 확인 부탁드립니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/d785a0fc-d746-4bcd-90e0-a5e039a53e81)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 크리스탈 수치 영역 클릭
2. 크리스탈 팝업 확인 시 수량이 소수점으로 출력되는 현상 확인

[Should be]
크리스탈 팝업 내 보유량이 소수점 단위까지 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
스팩상 보유할수있으나 표기시 소수점을 표기하지않도록 수정하였습니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.3
Android.v200250-250.0.3
iOS.v250.0.3(128)

![Image](https://github.com/user-attachments/assets/4ccae75d-be28-4ae6-bc2d-19bbe0ebd507)
