### ISSUE TITLE
[아우라] 신성 비스트 아우라의 아이콘과 외형이 님블 아우라로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6345]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
신성 비스트 아우라의 아이콘과 외형이 님블 아우라로 출력되는 현상
- 아우라 확률 팝업에서 확인했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/795a0f8e-9ad8-4978-8c59-bd16c2335631)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 아우라 탭  - 소환 확률 버튼 클릭
3. 신성 비스트 아우라의 아이콘이 님블 아우라 아이콘으로 출력되는 현상 확인
4. 신성 비스트 아우라 돋보기 버튼 클릭
5. 신성 비스트 아우라의 외형이 님블 아우라 외형으로 출력되는 현상 확인

[Should be]
신성 비스트 아우라의 아이콘 / 외형이 비스트 아우라로 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
https://github.com/planetarium/NineChronicles/issues/6236#issuecomment-2440950949
![Image](https://github.com/user-attachments/assets/f63402db-7e22-4349-b7ce-ab878c6721ed)
아우라 아이콘 및 이팩트 아이템아이디랑 실제 테이블아이디가 달라진것같습니다
@NineSyu 체크 부탁드려요~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.3
Android.v200250-250.0.3
iOS.v250.0.3(128)

![Image](https://github.com/user-attachments/assets/225161c3-80c0-4c79-8b3a-7f16886f599c)
