### ISSUE TITLE
[정찰 보상] 오딘 체인에서 정찰 보상 수령이 불가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6351]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
오딘 체인에서 정찰 보상 수령이 불가능한 현상
- 정찰 보상 및 시간 UI가 모두 0으로 출력되고 있습니다.
- 보상 수령 시도 시 실패 메세지가 출력됩니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/c4600a1f-3b34-452c-a08b-0ea0377764e8

- 해당 현상 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17748705/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 오딘 체인 접속
2. 메인 로비 - 정찰 보상 클릭
3. 정찰 보상 및 시간 UI가 모두 0으로 출력되는 현상 확인
4. 정찰 보상 수령 시도 시 실패 메세지가 출력되는 현상 확인

[Should be]
오딘 체인에서 정찰 보상 수치 출력 및 보상 수령이 가능해야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
@QgamesGeonPyoNoh 테이블 데이터 세팅 문제였고 세팅 완료했습니다. 다시 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
현재 PC 버전에서 정찰 보상 UI가 출력되지 않는 현상 발생했습니다. (헤임달 / 오딘 / 토르)
추가로, 모바일 버전에서는 정찰 시간과 UI가 일치하지 않는 상태로 출력되고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200250-250.0.1
Android.v200250-250.0.1
iOS.v250.0.1(125)

![image](https://github.com/user-attachments/assets/00138dbb-ab9c-4d08-8669-bda6ebf4c689)

![l_151510722_858_33bffb4613c4071035a83197715257f2](https://github.com/user-attachments/assets/916cea03-2f2e-44be-ad3d-5848b10b9ab2)

- 해당 현상 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17759750/Log.zip)

**Comment by tyrosine1153** [comment]
@ipdae 혹시 이번 정찰보상에 모래시계, ap 포션, 골든더스트, 실버더스트 외의 종류의 아이템이 추가되었나요?

**Comment by QgamesGeonPyoNoh** [comment]
기획서 상 350레벨 이상 유저에게는 루비 더스트가 지급됩니다.
해당 레벨 이상 유저에서만 이슈 발생하는 것으로 추정됩니다.

**Comment by tyrosine1153** [comment]
보상 아이템 종류가 정적이라 기존 아이템이 아닌 경우 대응을 하지 못하고 있었습니다. 이부분 대응해서 올리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.3
Android.v200250-250.0.3
iOS.v250.0.3(128)

https://github.com/user-attachments/assets/1255827d-9e00-4cce-9e21-3b6689e31ba9
