### ISSUE TITLE
[토르 체인] 토르 체인 내 월드 랭킹 목록에 다른 체인 랭킹이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6356]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
토르 체인 내 월드 랭킹 목록에 다른 체인 랭킹이 출력되는 현상
- 현재 출력되는 랭킹은 헤임달 랭킹이 출력되고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/1ef5a648-7e99-47f3-9cab-236769e5071e)

### How to reproduce the issue

[재현 스텝]
1. 토르 체인 접속
2. 메인 로비 - 랭킹 버튼 클릭
3. 랭킹 팝업 - 월드 랭킹 탭 클릭
4. 토르 체인 랭킹이 아닌 다른 체인 랭킹이 출력되는 현상 확인

[Should be]
토르 체인 월드 랭킹 확인 시 토르 체인 유저 랭킹이 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by U-lis** [comment]
@tyrosine1153  랭킹 정보는 DP 에서 가져오는 것으로 알고 있는데, 혹시 이거 planets 나 clo 같은데서 URL 받아서 가져오고 있을까요?

**Comment by tyrosine1153** [comment]
> @tyrosine1153 랭킹 정보는 DP 에서 가져오는 것으로 알고 있는데, 혹시 이거 planets 나 clo 같은데서 URL 받아서 가져오고 있을까요? 일단 DP 테이블 내용은 확인해보겠습니다

@U-lis 네 clo에서 네트워크별 dp url을 받고 있습니다

**Comment by U-lis** [comment]
@QgamesGeonPyoNoh DB 설정이 잘못 되어 있어서 다른 planet 정보를 가져오고 있었습니다.
해당 문제 수정했고, 게임을 재시작하시면 thor 에서는 thor 의 랭킹이 정상적으로 보입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.4
Android.v200250-250.0.4
iOS.v250.0.4(129)

![Image](https://github.com/user-attachments/assets/7415eed4-24c0-422e-b777-b7b04769ce29)
