### ISSUE TITLE
[아우라] 로드 아우라의 스탯이 일반 레전더리 아우라와 동일하게 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6358]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
로드 아우라의 스탯이 일반 레전더리 아우라와 동일하게 출력되는 현상
- 소환 확률 팝업 내 정보를 통해 확인했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/978bec15-6bc0-4e38-a2da-a62951b67081)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 소환 클릭
2. 소환 화면 - 아우라 탭 - 소환 확률 버튼 클릭
3. 로드 아우라 3종 우측 돋보기 버튼 클릭
4. 로드 아우라 3종 스탯 확인 시 일반 레전더리 아우라와 동일하게 출력되는 현상 확인

[Should be]
로드 아우라의 스탯은 일반 레전더리 아우라 Max 수치 + @ 수준으로 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by NineSyu** [comment]
로드 아우라는 레전더리 아우라 Max 보다 100 이상인 수치로 고정되어 나오게 데이터 수정하였습니다.
재접속 후 체크하시면 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.1
Android.v200250-250.0.1
iOS.v250.0.1(125)

![Image](https://github.com/user-attachments/assets/9e748da7-915b-478f-9285-08cea747009d)
