### ISSUE TITLE
[상점] PC 상점에서 검색 진행 시 빈 리스트가 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6364]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
PC 상점의 요리, 재료, 코스튬 탭에서 검색 진행 시 빈 리스트가 출력되는 현상
- 장비, 스톤 탭에서는 검색 정상 진행 확인했습니다.
- Windows 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/67a450e2-4ddc-4421-8b46-f243971815b0

### How to reproduce the issue

[재현 스텝]
1. PC 환경에서 상점 진입
2. 상점 화면에서 Food - Attack 탭 진입
3. 해당 탭 리스트에 Scarlet wine 아이템이 출력되는 것을 확인
4. 검색 입력란에 wine 입력
5. 빈 리스트가 출력되는 것을 확인

[Should be]
PC 상점에서 검색 기능이 정상적으로 동작해야 합니다.

### Relevant log output

```shell

```

**Comment by tyrosine1153** [comment]
@U-lis 이 이슈 말인데요, 장비 외 코스튬, 재료, 음식 아이템들은 인자로 iconIds를 보내줬던거라 발생한 문제였습니다. 이 경우 빈 결과값을 보내줍니다.
그런데 itemIds 로 수정하니 필터링이 되지 않는 전체 값을 돌려주는데, iconId 관련 수정 전과 같은 쿼리로 맞춰서 보내도 마찬가지입니다. 이 경우 클라이언트에서 인자를 어떻게 보내주는 게 맞나요?

쿼리 예시 
```
{url}/Market/products/items/0?limit=360&offset=0&order=cp_desc&stat=ATK&itemIds=201035&itemIds=201036&itemIds=201037
```

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.6

https://github.com/user-attachments/assets/68020e81-27d9-4856-a977-1ae5bbff83b6
