### ISSUE TITLE
[런쳐] 헤임달 - 토르 체인 간 NCG 전송이 불가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6368]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
헤임달 - 토르 체인 간 NCG 전송이 불가능한 현상
- NCG 전송 체인 선택 시 출력되지 않습니다.
- Windows 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/e3e938c0-b1fb-435e-9906-1c0c124ff2c6)

### How to reproduce the issue

[재현 스텝]
1. 런쳐 실행 - 헤임달 체인으로 로그인
2. Send NCG 클릭
3. 대상 체인 목록 확인
4. 토르 체인이 출력되지 않는 현상 확인

[Should be]
헤임달 - 토르 간 NCG 전송이 가능해야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
@QgamesGeonPyoNoh 헤임달 <> 토르간의 직접적인 전송은 정책적으로 막혀있습니다. NCG를 이동시키고 싶은경우에는 오딘을 통해야합니다.
