### ISSUE TITLE
[토르 체인] 오딘에서 토르 체인으로 NCG 전송이 되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6369]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows

### detailed device info

Windows 10

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
오딘에서 토르 체인으로 NCG 전송이 되지 않는 현상
- Windows 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/cc3f0dcb-32df-446c-801c-34826a192e49

- 해당 이슈 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/17771043/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. 런쳐 실행 - 오딘 체인 로그인
2. Send NCG 클릭
3. 토르 체인으로 NCG 전송 진행
4. 토르 체인으로 NCG 전송이 되지 않는 현상 확인

[Should be]
오딘 체인에서 토르 체인으로 NCG 전송이 가능해야 합니다.

### Relevant log output

```shell

```

**Comment by U-lis** [comment]
Thor 체인 오픈을 위한 리셋 등의 이슈로 bridge 서비스가 내려가 있었습니다.
현재 새 genesis 로 thor 체인을 새로 올렸고, 이에 맞는 bridge service 가 작동하고 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.3

https://github.com/user-attachments/assets/c4853821-ef3c-440e-a4e6-0bbe30bca05e

**Comment by QgamesGeonPyoNoh** [comment]
해당 이슈 재 발생했습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200250-250.0.6


https://github.com/user-attachments/assets/a3671dcb-c168-4512-b217-f6b026637c3f

해당 현상 발생 당시 Log 파일 첨부드립니다.

[Log.zip](https://github.com/user-attachments/files/17856376/Log.zip)

**Comment by U-lis** [comment]
브릿지 수정 완료했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.7

https://github.com/user-attachments/assets/12fcc4d1-12b8-4a50-9351-30e919f5a4a9
