### ISSUE TITLE
[소환] 소환 재화가 없는 상태에서 워크샵 소환 버튼에 레드닷이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6370]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
소환 재화가 없는 상태에서 워크샵 소환 버튼에 레드닷이 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/49e4a7cd-d6b8-42b9-b06c-c75cf775d639

### How to reproduce the issue

[재현 스텝]
1. 소환 재화가 없는 상태로 메인 로비 - 워크샵 진입
2. 워크샵 화면에서 소환 버튼에 레드닷이 출력되는 것을 확인

[Should be]
소환 재화가 없는 상태에서 워크샵 소환 버튼에 레드닷이 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.8
Android.v200250-250.0.8
iOS.v250.0.8(133)

https://github.com/user-attachments/assets/0852225e-464c-4af4-9f86-5ece67994392
