### ISSUE TITLE
[상점] 상품 상세 팝업에 획득 마일리지 정보가 표기되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6373]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
모바일 상점에서 상품 상세 팝업에 구매 시 획득 가능한 마일리지 정보가 표기되지 않는 현상
- 상품 구매 시 마일리지 정상 지급 확인했습니다.
- Android, iOS 환경에서 발생 확인했습니다.
![Image](https://github.com/user-attachments/assets/d9e4cb27-e44a-4620-959c-3fe1360df54b)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경에서 메인 로비 - 상점 진입
2. 임의의 상품 클릭
3. 출력된 상품 상세 팝업에서 획득 마일리지 정보가 표기되지 않는 것을 확인

[Should be]
모바일 상점에서 상품 상세 팝업에 구매 시 획득 가능한 마일리지 정보가 표기되어야 합니다.

### Relevant log output

```shell

```

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.6
iOS.v250.0.6(131)

https://github.com/user-attachments/assets/60f3803f-6e79-4923-b223-6543d132cb6c
