### ISSUE TITLE
[1주년] 이벤트 던전 진행 시 검은 배경이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6375]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
이벤트 던전 진행 중 다음 스테이지로 이동 시 검은 배경이 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/0f6a4098-b1db-446c-a90c-8f2cd9d99851

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤처 진입
2. 월드맵 화면에서 이벤트 던전 진입 후 입장
3. 이벤트 던전 진행 중 다음 스테이지로 이동 시 검은 배경이 출력되는 것을 확인

[Should be]
이벤트 던전 진행 중 다음 스테이지로 이동 시 검은 배경이 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
@tyrosine1153 이슈 확인중이신것같은데 마침 QA이슈도나와서 어사인달아두었습니다~!

**Comment by tyrosine1153** [comment]
관련 스레드 https://planetariumhq.slack.com/archives/C011716SDTM/p1731650980435339

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.3
Android.v200250-250.0.3
iOS.v250.0.3(128)

https://github.com/user-attachments/assets/8fbb9943-c0af-4a00-bcd1-a3727c93e17a
