### ISSUE TITLE
[어드벤쳐] 전투 진행 중 재화 부족 팝업을 통해 다른 컨텐츠로 이동이 가능한 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6377]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
전투 진행 중 워크샵 슬롯 해금 재화 부족 팝업을 통해 다른 컨텐츠로 이동이 가능한 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/1d811842-8c60-4db5-8ccd-d109d62b0060

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 어드벤쳐 진입
2. 스테이지 선택 후 전투 진입
3. 전투 진행 중 워크샵 슬롯 버튼 클릭
4. 워크샵 슬롯 팝업에서 재화 부족 상태로 슬롯 해금 진행
5. 출력된 재화 부족 팝업에서 컨텐츠 이동 버튼 클릭
6. 해당 컨텐츠로 이동되는 것을 확인

[Should be]
전투 진행 중 워크샵 슬롯 해금 재화 부족 팝업을 통해 다른 컨텐츠로 이동할 수 없어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
작업 머지했고 다음 버전(250.0.2)에서 확인 부탁드립니다!
https://github.com/planetarium/NineChronicles/pull/6381

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.3
Android.v200250-250.0.3
iOS.v250.0.3(128)

https://github.com/user-attachments/assets/04df8aea-e00d-4831-a2f7-b685eca290f2
