### ISSUE TITLE
[1주년] 1주년 이벤트 그리모어의 옵션이 ATK 2개로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6378]
### APV version info

v200250

### Client version info

v250.0.1

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
1주년 이벤트 그리모어의 옵션이 ATK 2개로 출력되는 현상
- 제작 시에는 HIT 옵션이 2개인 것으로 출력됩니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/58cd82de-0f8a-46e3-979f-cd06a387ce1b)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 = 제작 클릭
2. 장비 - 이벤트 탭 클릭
3. 이벤트 탭 내 1주년 이벤트 그리모어 클릭
4. 제작 전 옵션 미리보기 확인 시 HIT 옵션이 2개인 것을 확인
5. 1주년 이벤트 그리모어 제작 진행
6. 1주년 이벤트 그리모어 확인 시 ATK 옵션이 2개로 출력되는 현상 확인

[Should be]
1주년 이벤트 그리모어 스탯 확인 시 HIT 옵션 2개 / ATK 옵션 1개 / 스킬로 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by NineSyu** [comment]
HIT 스텟이 2종으로 붙는 것이 정상스펙입니다.
@tyrosine1153 장비 결과물에 ATK 별 2개가 붙는 이슈가 있는 것 같습니다. 체크 부탁드립니다.

**Comment by NineSyu** [comment]
데이터를 수정으로 ATK, HIT  옵션 1개씩만 표시되게 수정했습니다.
재접속 확인하시면 정상적으로 표시될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.5
Android.v200250-250.0.5
iOS.v250.0.5(130)

![Image](https://github.com/user-attachments/assets/792c888a-2524-4e3c-a5d3-088d7278557c)
