### ISSUE TITLE
[정찰보상] 350 레벨 이상 캐릭터에서 350 레벨 미만 캐릭터로 변경 시 정찰 보상에 루비더스트 출력 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6400]
### APV version info

v200250

### Client version info

v250.0.3

### Device

Windows

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
350 레벨 이상 캐릭터에서 350 레벨 미만 캐릭터로 변경 시 정찰 보상에 루비더스트 출력 현상
- 정찰 보상 수령 시 루비 더스트가 지급되지는 않습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/8e4b5210-fc01-4b4c-b9ce-fd216b29f086

### How to reproduce the issue

[재현 스텝]
1. 350 레벨 이상 캐릭터 세팅
2. 메인 로비 - 정찰 보상 클릭
3. 설정 - 캐릭터 변경 - 350 레벨 미만 캐릭터로 변경
4. 메인 로비 - 정찰 보상 클릭
5. 정찰 보상 목록에 루비 더스트 출력 확인

[Should be]
350 레벨 미만 캐릭터로 변경 시 정찰 보상 목록에 루비 더스트가 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by U-lis** [comment]
정찰보상쪽 수정하면서 아바타 수정쪽이 빠진 것 같음.
