### ISSUE TITLE
[마일리지 샵] 어드벤쳐 황제 칭호가 8000 마일리지로 판매되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6405]
### APV version info

v200250

### Client version info

v250.0.3

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 황제 칭호가 8000 마일리지로 판매되는 현상
- 아레나 황제 칭호는 4000 마일리지로 판매되고 있습니다, 의도하신 부분인지 확인 부탁드립니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/448a9291-73f8-4988-8a27-d25e5c59fb3c

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 메인 로비 - 마켓 - 마일리지 탭 클릭
3. 마일리지 탭 내 어드벤쳐 황제 칭호 확인
4. 어드벤쳐 황제 칭호가 8000 마일리지로 판매되는 현상 확인

[Should be]
어드벤쳐 황제 칭호가 4000 마일리지로 판매되어야 합니다.

### Relevant log output

```shell

```

**Comment by jaeho0103** [comment]
1차 데이터 업데이트 이후 밸런스가 변경된 부분으로 수정후 다시 체크 요청드리겠습니다.

**Comment by jaeho0103** [comment]
밸런스 조정중 판매가 홀딩된 제품으로 이슈는 종료처리부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 상품 판매 홀딩된 것으로 확인하여
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200250-250.0.6
Android.v200250-250.0.6
iOS.v250.0.6(131)
