### ISSUE TITLE
[1주년] 1주년 350레벨 무료 패키지 정보 내에 골든 더스트가 두 번 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6406]
### APV version info

v200250

### Client version info

v250.0.3

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
1주년 350레벨 무료 패키지 정보 내에 골든 더스트가 두 번 출력되는 현상
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/b9787857-c186-497d-8fb7-cbcf487e1bb5)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 메인 로비 - 마켓 - 패키지 탭 클릭
3. 1주년 350 레벨 무료 패키지 클릭
4. 1주년 350 레벨 무료 패키지 내 골든 더스트가 두 번 출력되는 현상 확인 

[Should be]
1주년 350 레벨 무료 패키지 팝업에서 골든 더스트가 한 번만 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by jaeho0103** [comment]
데이터가 잘못들어가 있는거 확인했습니다. 수정하도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
팝업 내 골든 더스트는 수정되었으나
현재 미리보기 이미지에 다른 상품이 출력되고 있습니다.
해당 현상 확인 부탁드립니다.

[테스트 환경]
Android.v200250-250.0.6
iOS.v250.0.6(131)

![Image](https://github.com/user-attachments/assets/b0973ae6-aedb-47ac-b070-8ba24bd25abd)

**Comment by jaeho0103** [comment]
@U-lis 이미지 체크 부탁드립니다.

**Comment by U-lis** [comment]
이미지 정리 완료했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 수정되지 않았습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200250-250.0.8
iOS.v250.0.8(133)

![Image](https://github.com/user-attachments/assets/79bbad05-9d86-48a6-ab3c-6c2c4e969e51)

**Comment by U-lis** [comment]
![Image](https://github.com/user-attachments/assets/eef51d6e-9f9e-429e-a40d-0e2f8c3eaa18)
음... 이미지 잘 나오는 것 확인했는데...
혹시 앱을 지우고 새로 클린설치해도 동일한 현상이 발생하나요?

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.8
iOS.v250.0.8(133)

![Image](https://github.com/user-attachments/assets/513da2e1-bda6-47d6-83a5-37d1cd8090d5)
