### ISSUE TITLE
[1주년] 1주년 무료 패키지 3종이 마켓 페이지 내에서 두 칸을 차지하는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6407]
### APV version info

v200250

### Client version info

v250.0.3

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
1주년 무료 패키지 3종이 마켓 페이지 내에서 두 칸을 차지하는 현상
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/0e1b6582-9a34-4d79-8a53-a17e422ac53a)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 메인 로비 - 마켓 - 패키지 탭 클릭
3. 1주년 무료 패키지 3종 확인
4. 1주년 무료 패키지 3종이 두 칸을 차지하는 현상 확인

[Should be]
1주년 무료 패키지 3종이 마켓 페이지에서 1칸으로 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by jaeho0103** [comment]
데이터 수정해서 업데이트 하도록 하겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.6
iOS.v250.0.6(131)

![Image](https://github.com/user-attachments/assets/13f8b45d-b63d-4b72-9b54-89cb70dd0dfc)
