### ISSUE TITLE
[토르 체인] 스테이킹이 진행되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6421]
### APV version info

v200250

### Client version info

v250.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
50NCG 이상 보유한 상태에서 몬스터 콜렉션 팝업에 금액 입력 후 save 버튼 클릭 시 스테이킹이 진행되지 않는 현상
- 해당 현상 발생 후 앱 재접속 시에도 스테이킹이 진행되지 않은 것을 확인했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/43e7d483-cf76-4cf6-8121-79969d92a5d2

### How to reproduce the issue

[재현 스텝]
1. 50NCG 이상 보유한 상태에서 메인 로비 - 몬스터 콜렉션 클릭
2. 몬스터 콜렉션 팝업에서 상단의 start 버튼 클릭
3. 50 입력 후 save 버튼 클릭
4. 스테이킹이 진행되지 않는 것을 확인

[Should be]
토르 체인에서 스테이킹이 정상 진행되어야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
@QgamesJeongWonChoe Windows빌드의 로그 첨부 부탁드립니다.

**Comment by QgamesJeongWonChoe** [comment]
@ipdae 해당 현상 발생 시의 Log 파일 공유드립니다.
[log.zip](https://github.com/user-attachments/files/17823196/log.zip)

**Comment by ipdae** [comment]
@QgamesJeongWonChoe 답변이 늦어져 죄송합니다. 네트워크 초기화이후에도 해당 문제가 발생하고 계신지 확인부탁드립니다.
