### ISSUE TITLE
[토르 체인] 정찰 보상 성장 부스터가 적용되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6423]
### APV version info

v200250

### Client version info

v250.0.4

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
정찰 보상 성장 부스터가 적용되지 않는 현상
- 1~200레벨 구간에서 토르 체인과 다른 체인의 정찰 보상이 모두 골든 더스트 1개, AP 포션 1개로 동일하게 출력되는 상태입니다.
- Windows, Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/39e48b60-47df-4138-9c06-4e6279ee6d74)

### How to reproduce the issue

[재현 스텝]
1. 헤임달 체인에서 1~200레벨 사이의 캐릭터로 정찰 보상 확인
2. 정찰 보상이 골든 더스트 1개, AP 포션 1개인것을 확인
3. 토르 체인에서 1~200레벨 사이의 캐릭터로 정찰 보상 확인
4. 정찰 보상이 동일하게 골든 더스트 1개, AP 포션 1개인것을 확인

[Should be]
토르 체인에서 정찰 보상 성장 부스터가 적용되어야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
@QgamesJeongWonChoe 보상정책을 오딘, 토르와 동일하게 적용했던게 원인으로 보입니다. 현재는 정책을 업데이트한 상황인데 확인 부탁드립니다.

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.4
Android.v200250-250.0.4
iOS.v250.0.4(129)
![화면 캡처 2024-11-20 103321](https://github.com/user-attachments/assets/b2ae4edf-beda-4d73-8327-f8f8408e2fad)
