### ISSUE TITLE
[상점] 마일리지 부족 상태에서 마일리지 상품 구매 시도 시 에러 팝업이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6424]
### APV version info

v200250

### Client version info

v250.0.4

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
마일리지 부족 상태에서 마일리지 상품 구매 시도 시 에러 팝업이 출력되는 현상
- Android, iOS 환경에서 확인했습니다.

![Image](https://github.com/user-attachments/assets/53bb6054-a475-462d-8709-c1e377fb61a1)

### How to reproduce the issue

[재현 스텝]
1. 마일리지 부족 상태에서 메인 로비 - 상점 진입
2. 상점 화면에서 마일리지 탭 클릭
3. 상품 구매 시도 시 구매 실패 에러 팝업이 출력되는 것을 확인

[Should be]
마일리지 부족 상태에서 마일리지 상품 구매 시도 시 에러 팝업이 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
이거 플로우따로 논의된바가 없어서 정리를해야될것같습니다~!
지금처럼 구매 실패 안내를 해주는것이 좋을지.. 이전에 막는다면 상세팝업에서 막을지 그전 셀버튼에서 막을지 정리가 필요해보입니다. @jaeho0103

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.6
Android.v200250-250.0.6
iOS.v250.0.6(131)

![Image](https://github.com/user-attachments/assets/0c548201-ed68-46db-80c7-17fd64e13a8b)
