### ISSUE TITLE
[토르 체인] 모바일 상점에서 상품 구매 시 에러 팝업이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6425]
### APV version info

v200250

### Client version info

v250.0.4

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
모바일 상점에서 상품 구매 시 에러 팝업이 출력되는 현상
- 구매한 상품은 정상적으로 지급되는 것을 확인했습니다.
- Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/51fd6d3c-589e-4214-b232-fbace6e69c52

### How to reproduce the issue

[재현 스텝]
1. 토르 체인에서 메인 로비 - 상점 진입
2. 골든 더스트 20개 상품 구매 진행
3. 상품 구매 완료 시 에러 팝업이 출력되는 것을 확인

[Should be]
토르 체인 모바일 상점에서 상품 구매 시 에러 팝업이 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
api 최신화이슈로 다음빌드에서 수정될예정입니다~! 참고 부탁드립니다~!

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.6
iOS.v250.0.6(131)

https://github.com/user-attachments/assets/27164cc0-2a90-4c4a-a7d0-aa0938887586
