### ISSUE TITLE
[시즌 패스] 시즌 패스 프리미엄 상품 설명이 없는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6456]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌 패스 프리미엄 상품 설명이 없는 현상
- 프리미엄 해제 팝업 내 별도 설명 텍스트가 출력되지 않습니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/7143f838-c94e-4b3f-b856-d1edfa1d9941

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 메인 로비 - 시즌 패스 클릭
3. 각 패스 별 해제하기 버튼 클릭
4. 해제하기 팝업 내 상품 설명 텍스트가 출력되지 않는 현상 확인

[Should be]
시즌 패스 해제하기 팝업 내 상품 설명 텍스트가 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 @NineSyu https://www.notion.so/planetarium/l10n-130ed889905f80f99f8aca4b44d24e65?pvs=4#131ed889905f80f18040e15bc6ad5733 l10n 키추가 부탁드립니다~!

**Comment by NineSyu** [comment]
L10n 추가하여 정상적으로 표시되게 수정했습니다.
재접속 후 확인하시면 정상출력될것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 현재 발생 중에 있습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200250-250.0.6
iOS.v250.0.6(131)

https://github.com/user-attachments/assets/d83e7484-5aac-4266-a6fa-7cf2dd8f5324

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.6
iOS.v250.0.6(131)

https://github.com/user-attachments/assets/e9de967a-bd09-4f92-bd86-e2fe89611a4b
