### ISSUE TITLE
[토르 체인] 모바일 시작 화면 내 토르 체인 배너 버튼이 동작하지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6458]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모바일 시작 화면 내 토르 체인 배너 버튼이 동작하지 않는 현상
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/301021ec-ecd9-4882-a831-d0011cafc373

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 시작 화면 - 토르 체인 배너 확인
3. 토르 체인 배너 내 자세히 버튼 클릭 시 동작하지 않는 현상 확인

[Should be]
토르 체인 배너 내 자세히 버튼이 동작해야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
해당 내용 수정하였습니다. v250.0.7에서 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.7
Android.v200250-250.0.7
iOS.v250.0.7(132)

https://github.com/user-attachments/assets/1b87091e-fde1-48f5-bddd-f45cd912358f
