### ISSUE TITLE
[마일리지] 무료 패키지 상품 수령 시에도 마일리지가 지급되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6461]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
무료 패키지 상품 수령 시에도 마일리지가 지급되는 현상
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/836fec75-f8f9-464f-a779-be1d7870b639

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 메인 로비 - 마켓 - 패키지 탭 클릭
3. 무료 패키지 3종 구매 진행
4. 구매 시 마일리지가 지급되는 현상 확인

[Should be]
무료 패키지 구매 시 마일리지가 지급되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by U-lis** [comment]
아이고 이거 내부 테스트용으로 임시로 넣은 값을 지우지 않았었네요 죄송합니다
값 0으로 수정했습니다 :pray:

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.6
iOS.v250.0.6(131)

https://github.com/user-attachments/assets/bbdbe21e-6572-495e-921d-3c75ca2f7d4d
