### ISSUE TITLE
[마켓] 스페셜 스펙업 패키지의 이름 텍스트가 깨져서 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6463]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
스페셜 스펙업 패키지의 이름 텍스트가 깨져서 출력되는 현상
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/223b97a5-9e22-4455-93e6-612ae446f9b8)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 메인 로비 - 마켓 - 패키지 탭 클릭
3. 스페셜 스펙업 패키지 확인
4. 스페셜 스펙업 패키지의 이름 텍스트가 깨져서 출력되는 현상 확인

[Should be]
스페셜 스펙업 패키지의 이름 텍스트가 깨지지 않고 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 따로 원격 키에 해당문구 추가하여 폰트구울때 포함되도록 진행될예정입니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.7
iOS.v250.0.7(132)

![Image](https://github.com/user-attachments/assets/e1091134-2de1-4769-a7a6-b0b03610784b)
