### ISSUE TITLE
[랭킹] 제작 / 장비 랭킹 출력 이상 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6471]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
제작 / 장비 랭킹 출력 이상 현상
- 제작 및 장비 랭킹이 출력되지 않거나 극히 일부 데이터만 출력되고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/9c1c5826-3c03-419f-8844-5392753bb462

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 랭킹 버튼 클릭
2. 제작 / 장비 탭 클릭
3. 랭킹이 출력되지 않거나 극히 일부 데이터만 출력되는 현상 확인

[Should be]
제작 / 장비 랭킹이 정상적으로 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
@U-lis dataprovider 장애와 연관있는것 같습니다. 확인 부탁드립니다.

**Comment by U-lis** [comment]
요번에 QA를 위해 internal 서비스를 올릴 때 내용 체크를 용이하기 위해 새 DB 를 새로운 곳에서 가져오도록 새로 세팅했습니다.
이 DB 는 비어있는 채로 시작했기 때문에 QA internal 세팅이 완료된 뒤부터의 기록만을 가지고 있습니다.
현재 영상에서 확인되는 내용과 internal DB 를 비교해보니 실제로 DB 에 몇 개 되지 않는 값들이 있어서 랭킹 정보가 몇 개 보이지 않는 것을 확인했습니다.
이 부분은 서비스상 버그이거나 하지 않고 DB 를 새로 세팅해서 생긴 현상으로, 다른 문제는 없는 정상 노출로 파악했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상은 버그가 아닌 것으로 확인하여 이슈 종료 하겠습니다.

[테스트 환경]
Windows.v200250-250.0.6
Android.v200250-250.0.6
iOS.v250.0.6(131)
