### ISSUE TITLE
[마일리지] 마일리지 팝업 내에서 마일리지가 단축 단위로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6473]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
마일리지 팝업 내에서 마일리지가 단축 단위로 출력되는 현상
- 팝업 내에서도 K 단위로 출력되어 정확한 마일리지 수량 확인이 불가능합니다.
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/576c6c58-e1b0-4277-897a-a928a6583000)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입 / 1,000 마일리지 이상 보유 캐릭터
2. 메인 로비 - 마켓 클릭
3. 상단 마일리지 UI 영역 클릭 - 팝업 출력
4. 마일리지 팝업 내에서도 수량이 단축 단위로 출력되는 현상 확인

[Should be]
마일리지 팝업 내 수량이 단축되지 않고 전체가 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
@jaeho0103 이거 혹시 정해진 룰이 있는지 확인 부탁드립니다.

**Comment by jaeho0103** [comment]
@jonny-jeahyunchoi cc @boramqo83 
요거 단축 사용하면 안되겠네요. 전체 표시로 부탁드리겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.9
iOS.v250.0.9(134)

![Image](https://github.com/user-attachments/assets/28972e52-65b4-4ff7-aa69-9780613b2c38)
