### ISSUE TITLE
[마켓] 모바일 마켓 내 상품의 미리보기와 팝업 내용이 일치하지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6474]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
모바일 마켓 내 상품의 미리보기와 팝업 내용이 일치하지 않는 현상
- 스페셜 스펙업 패키지 / 마스터 콤비네이션 패키지에서 발생했습니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/aea21502-93b0-4702-9104-8b28925751ad

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 메인 로비 - 마켓 - 패키지 탭 클릭
3. 스페셜 스펙업 패키지 / 마스터 콤비네이션 패키지 클릭
4. 상품의 미리보기와 팝업 내용이 일치하지 않는 현상 확인

[Should be]
모바일 마켓 내 상품의 미리보기와 팝업 내용이 일치해야 합니다.

### Relevant log output

```shell

```

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 현재 동일하게 발생하고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200250-250.0.6
Android.v200250-250.0.6
iOS.v250.0.6(131)

https://github.com/user-attachments/assets/78d4ce76-743d-4d56-841f-7d70a6ae86c1

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 @boramqo83 확인부탁드립니다~!

**Comment by U-lis** [comment]
아 이거 이미지 잘못 올라갔나.. 확인해서 수정해두겠습니다

**Comment by U-lis** [comment]
이미지 정리 완료했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
해당 현상 동일하게 발생하고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Android.v200250-250.0.7
iOS.v250.0.7(132)

https://github.com/user-attachments/assets/bc665c29-80f5-4e31-bcd9-ef3d5e1e6fda

**Comment by U-lis** [comment]
M 에서 해당 현상 확인해 수정해두었습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.8
iOS.v250.0.8(133)

https://github.com/user-attachments/assets/9af8dc10-55b0-4562-a008-fda430dbe5de
