### ISSUE TITLE
[토르 체인] 워크샵에서 1주년 기념 그리모어 레시피가 선택되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6481]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
토르 체인의 워크샵에서 1주년 기념 그리모어 레시피가 선택되지 않는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/5c99b019-64a3-49a6-8618-afde61ac2a95

### How to reproduce the issue

[재현 스텝]
1. 토르 체인에서 메인 화면 - 워크샵 - 제작 진입
2. 워크샵 제작 화면에서 1주년 기념 그리모어 레시티 클릭
3. 해당 레시피가 선택되지 않는 것을 확인

[Should be]
토르 체인 워크샵에서 1주년 기념 그리모어 레시피가 선택되어야 합니다.

### Relevant log output

```shell

```

**Comment by tyrosine1153** [comment]
@NineSyu 토르 체인의 EquipmentItemSubRecipeSheetV2에서 '1076000914' 번 키 확인 부탁드립니다!

**Comment by NineSyu** [comment]
데이터 수정하여 정상적으로 제작되게 수정하였습니다.
재접속 후 테스트하시면 정상적으로 표시되는 것을 확인하실 수 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.8
Android.v200250-250.0.8
iOS.v250.0.8(133)

https://github.com/user-attachments/assets/b2c80487-4fae-4014-a552-07fc18a5a0f0
