### ISSUE TITLE
커스텀 장비 강화시 스킬이 비정상 동작한다는 제보

### ISSUE THREAD

**Issue by jaeho0103** [planetarium/NineChronicles#6482]
### APV version info

200240

### Client version info

240.1.0

### Device

Windows

### account address info

none

### What happened?

Custom equipment skills are broken when upgrading to a level greater than +8. I upgraded a ring to +7 and it worked fine. Then I upgraded it to +9 and the skill couldn't be used. I upgraded it to +10 and +11 to check if it was only a problem at +9, but I still have the same problem.
![image](https://github.com/user-attachments/assets/5e5e4d0f-cc87-4d6a-a17f-a3e3ac94a74b)

### How to reproduce the issue

1. Click Button
2. Crash

**Comment by ipdae** [comment]
@jaeho0103 혹시 문제 발생한 사용자 주소같은 정보는 없을까요?

**Comment by ipdae** [comment]
https://github.com/planetarium/lib9c/pull/3038 에서 수정됐습니다.
