### ISSUE TITLE
[시즌 패스] 시즌 패스 프리미엄 구매 시 즉시 해금되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6488]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Android, iOS

### detailed device info

Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌 패스 프리미엄 구매 시 즉시 해금되지 않는 현상
- 다른 화면으로 1회 이동 후 복귀 시 해금 상태로 출력됩니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/00c6a835-c6d1-4fc7-b4ab-e5d9a0f9ae28

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 메인 로비 - 시즌 패스 클릭
3. 임의의 시즌 패스 프리미엄 상품 구입
4. 프리미엄 상품이 즉시 해금되지 않는 현상 확인

[Should be]
시즌 패스 프리미엄 상품 구매 시 즉시 해금되어야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
https://github.com/planetarium/NineChronicles/pull/6464 여기서 수정되었습니다 다음버전에서 수정확인할수있습니다~!
