### ISSUE TITLE
[시즌 패스] 어드벤쳐 보스 패스 보상 수령 후에도 계속 활성화 상태로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6490]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 패스 보상 수령 후에도 계속 활성화 상태로 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/432649b8-e425-47a3-8b09-a617ce3dd822

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 시즌 패스 클릭
2. 어드벤쳐 보스 패스 탭 클릭
3. 활성화된 보상 수령
4. 보상 수령 후에도 계속 활성화 상태로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 패스의 수령한 보상은 체크 표시로 변경되며 추가 수령 시도가 불가능해야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
@U-lis 이거 이미 클라에서는 보상요청에 응답받고나서 /api/user/status/all 요거요청 다시한다음에 갱신하는게 들어가있는데요 혹시 유저정보가 갱신되는데 시간이좀 걸리나요?

**Comment by U-lis** [comment]
이거 테스트하신 시간이 언젠지 모르겠는데 저 주소로 해당 패스 claim 기록이 없습니다
왠지 internal 새거 배포 올라가는 시간에 겹쳐가지고 아예 동작을 똑바로 못한건가 싶기도 한데
일단 좀 보겠습니다. claim 은 상태 변경 다 하고 응답을 주기 때문에 응답을 받았다면 무조건 완료된거로 봐야합니다.

**Comment by jonny-jeahyunchoi** [comment]
응답요청받고나서 ui스크롤러부분이 갱신된것으로보아 응답받아서 갱신진행된것같은데 유저상태변경이 안된것같습니다

**Comment by jonny-jeahyunchoi** [comment]
월드페스같은경우는 지금 갱신잘되는것 확인했습니다~!

**Comment by U-lis** [comment]
영상에 보면 6레벨이라고 되어 있는데, 제보주신 주소로 찾아보면 이미 adventure boss pass 만렙이고, 정상 claim 한 기록이 있습니다.

**Comment by QgamesGeonPyoNoh** [comment]
네, 확인 감사드립니다.
다시 재현여부 확인하여 공유 드리겠습니다.
