### ISSUE TITLE
[시즌 패스] 어드벤쳐 보스 패스의 프리미엄 상품 구매 시 보상이 지급되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6491]
### APV version info

v200250

### Client version info

v250.0.6

### Device

Android, iOS

### detailed device info

Android 8, iOS 17

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
어드벤쳐 보스 패스의 프리미엄 상품 구매 시 보상이 지급되지 않는 현상
- Android, iOS 환경에서 발생 확인했습니다.
https://github.com/user-attachments/assets/f85c1921-3a74-4111-87b0-54b7404e9220

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 시즌 패스 클릭
2. 어드벤쳐 보스 패스 탭 클릭
3. 프리미엄 상품 구매 진행
4. 구매 완료 후 보상이 지급되지 않는 것을 확인

[Should be]
어드벤쳐 보스 패스의 프리미엄 상품 구매 시 보상이 지급되어야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
@U-lis 요거도 응답은 성공했는데 서비스에 갱신이 정상처리안된것같습니다~!

**Comment by U-lis** [comment]
보상 지급 계정 내 재화 부족으로 확인되었습니다.

**Comment by U-lis** [comment]
internal network 에서 부족한 재화 확보해 구매 테스트 완료했습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.8
iOS.v250.0.8(133)

![Image](https://github.com/user-attachments/assets/8427c824-40e2-49ef-8761-0f3020d5dec4)
