### ISSUE TITLE
[토르 체인] 토르 체인에서 1주년 아우라 / 그리모어 제작 시 3 블록이 소요되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6496]
### APV version info

v200250

### Client version info

v250.0.8

### Device

Windows, Android, iOS

### detailed device info

Windows 10, Android 12, iOS 17

### account address info

0x3A73d8bC927D66fB6a6dFd8adB414EB0f34F3c72

### What happened?

[내용]
토르 체인에서 1주년 아우라 / 그리모어 제작 시 3 블록이 소요되는 현상
- 헤임달 / 오딘 체인은 2블록으로 출력되고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/a20006be-0ee4-467c-ac8c-75190941b69b)

### How to reproduce the issue

[재현 스텝]
1. 토르 체인 진입
2. 메인 로비 - 워크샵 - 제작 클릭
3. 이벤트 탭 - 1주년 그리모어 / 아우라 선택
4. 제작 시 소요되는 블록이 3 블록으로 출력되는 현상 확인

[Should be]
토르 체인에서 1주년 이벤트 그리모어 / 아우라 제작 시 2 블록 소요되어야 합니다.

### Relevant log output

```shell

```

**Comment by NineSyu** [comment]
1주년 장비 제작블록이 2이상으로 적용되어있는 것을 체크하여 수정하였습니다.
재접속 후 체크하시면 1블록으로 변경된 것을 확인하실 수 있을 것입니다. 감사합니다.

**Comment by QgamesGeonPyoNoh** [comment]
헤임달 / 오딘 / 토르 체인 모두 1 블록으로 변경 확인했습니다.

[테스트 환경]
Windows.v200250-250.0.8
Android.v200250-250.0.8
iOS.v250.0.8(133)

![Image](https://github.com/user-attachments/assets/d07a14b7-c835-4a89-bcfa-59fb6349e1b4)
