### ISSUE TITLE
유니티 에디터 아레나 전투 시뮬레이션 툴 MVP

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#6497]
- https://github.com/planetarium/NineChronicles/discussions/6451 파생 이슈
- 게임의 실행없이 유니티 에디터 자체에서 필요한 값들을 입력받아 `ArenaSimulator.Simulate` 를 실행할 수 있어야합니다.

- [ ] 아군/적군캐릭터의 스탯을 원하는 값으로 설정할 수 있어야함.
- [ ] 전투결과(Simulator.Log) 내용을 문자열로 확인할 수 있어야함. https://github.com/planetarium/NineChronicles/commit/a3645893106bccf2d7a8a7fce5173efbfec8b5f7 참고

**Comment by sonohoshi** [comment]
![Image](https://github.com/user-attachments/assets/a3840b69-1136-44eb-8cc8-7ea9118826ec)

**Comment by ipdae** [comment]
- guid대신 캐릭터 이름뜨게 정리해서 4시전까지 @NineSyu 님께 공유

**Comment by sonohoshi** [comment]
https://planetariumhq.slack.com/archives/CC7BWJYTZ/p1733295895551879
