### ISSUE TITLE
[토르 체인] 시즌패스 프리미엄 상품 팝업에 표기된 마일리지가 실제 획득 수량과 상이한 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6508]
### APV version info

v200250

### Client version info

v250.0.8

### Device

Android (9c M), iOS (9c M)

### detailed device info

Android 8, iOS 17

### Planet

Thor

### account address info

0x8676a974A6796C606361C5E553717e54c05Ef00F

### What happened?

[내용]
토르 체인에서 시즌패스 프리미엄 상품 팝업에 표기된 마일리지가 실제 획득 수량과 상이한 현상
- 용기 패스, 월드 클리어 패스, 어드벤처 보스 패스 모두 실제 획득하는 마일리지 수량과 다르게 표기된 것을 확인했습니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/5ae3379e-34a1-42f3-b892-2ccdebb18140

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경에서 토르 체인 메인 로비 - 시즌 패스 진입
2. 시즌 패스 화면에서 용기 패스 탭 선택 후 해제하기 버튼 클릭
3. 프리미엄 상품 팝업에 '240 마일리지를 획득합니다'로 표기된 것을 확인
4. 프리미엄 상품 구매 시 1200 마일리지를 획득한 것을 확인

[Should be]
토르 체인에서 시즌패스 프리미엄 상품 팝업에 표기된 마일리지가 실제 획득 수량과 동일해야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 @NineSyu  음 이거 번역키가 플레닛별 구분하는상태는아니라서 난감하네요.. 
오딘 헤임달(240) 토르(1200) 마일리지를 획득합니다 이런식으로 문구자체에서 플레닛별안내를 하는것은 어떨까요? 토르유도겸

**Comment by jonny-jeahyunchoi** [comment]
번역어로 대응하는것으로 정리

**Comment by jaeho0103** [comment]
각 번역어에 (Thor x5)로 토르에서는 다섯배 준다는 부분을 추가해두었습니다.

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.9
Android.v200250-250.0.9
iOS.v250.0.9(134)

![Image](https://github.com/user-attachments/assets/8d75a648-46f1-46e1-8314-c921cfcde746)
