### ISSUE TITLE
[시즌 패스] 어드벤쳐 보스 패스 프리미엄 구입 시 마일리지 / 패스 경험치가 적게 지급되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6509]
### APV version info

v200250

### Client version info

v250.0.8

### Device

iOS (9c M), Android (9c K)

### detailed device info

Android 12, iOS 17

### Planet

Odin

### account address info

0x8BF9cC0e359308a3ABd03b85D25837788D8c5Bb4

### What happened?

[내용]
어드벤쳐 보스 패스 프리미엄 구입 시 마일리지 / 패스 경험치가 적게 지급되는 현상
- 팝업에는 마일리지 120 / 패스 경험치 250 지급이나, 실제 구매 시 마일리지 80 / 패스 경험치 200 지급되고 있습니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/f61715ec-722d-4fc7-beb4-1d944feae30f

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 진입
2. 메인 로비 - 시즌 패스 클릭
3. 시즌 패스 - 어드벤쳐 보스 패스 탭 클릭
4. 해제하기 버튼 클릭 후 구매 진행
5. 구매 시 마일리지 / 패스 경험치가 더 적게 지급되는 현상 확인

[Should be]
어드벤쳐 보스 패스 프리미엄 구매 시 팝업에 출력된 수치와 동일한 마일리지 / 패스 경험치가 지급되어야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
번역어로 대응

**Comment by jaeho0103** [comment]
얘는 그냥 수치 갱신이 잘못되어있던 부분으로 업데이트 완료 했습니다. 체크 부탁드리겠습니다.
