### ISSUE TITLE
[시즌 패스] 시즌 패스가 잠긴 상태에서 레드닷이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6511]
### APV version info

v200250

### Client version info

v250.0.8

### Device

Windows, Android (9c M), iOS (9c M), Android (9c K), iOS (9c K)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Thor

### account address info

0xdde23c49C0e36B5f8206Dbdac60675288484B37E

### What happened?

[내용]
시즌 패스가 잠긴 상태에서 레드닷이 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/7acd74dc-6b90-4b59-b460-91d673015847)

### How to reproduce the issue

[재현 스텝]
1. 신규 캐릭터 생성 - 10 스테이지 클리어 진행
2. 메인 로비 - 시즌 패스 영역 확인
3. 시즌 패스가 잠긴 상태에서 레드닷이 출력되는 현상 확인

[Should be]
시즌 패스가 잠긴 상태에서 레드닷이 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
잠겨있더라도 패스경험치는 받는상황이라 나오게되는것같네요 잠겨있을때는 레드닷안뜨도록 예외처리가 필요한데 우선순위가 높은것같지는 않아보여 다음배포에 포함하는방향으로 진행하는것이 좋을것같습니다 확인부탁드립니다~! @jaeho0103

**Comment by jaeho0103** [comment]
네 조니님이 제안주신대로 진행해도 이슈 없을 것 같습니다.
근데 잠겨있는데 패스경험치를 왜 받을까요?;;

**Comment by jonny-jeahyunchoi** [comment]
아마 월드패스경험치 받은것으로 예상됩니다
