### ISSUE TITLE
[UI] 로키 흡혈 룬 정보 팝업에서 아이템명과 수량이 겹쳐서 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6512]
### APV version info

v200250

### Client version info

v250.0.9

### Device

Windows

### detailed device info

Windows 10

### Planet

Odin

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
워크샵 룬 화면에서 로키 흡혈 룬 정보 팝업의 아이템명과 수량이 겹쳐서 출력되는 현상
- 로키 흡혈 룬(어드벤쳐), 로키 흡혈 룬(월드보스)에서 동일하게 발생합니다.
- Windows 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/0ccd9c16-06ff-43be-afb4-880bb7643187)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 룬 진입
2. 로키 흡혈 룬 아이콘 클릭 후 상단 룬스톤 수량 UI 클릭
3. 출력된 로키 흡혈룬 정보 팝업에 아이템명과 수량이 겹쳐서 출력되는 것을 확인

[Should be]
워크샵 룬 화면에서 로키 흡혈 룬 정보 팝업의 아이템명과 수량이 겹쳐서 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by NineSyu** [comment]
L10n 수정하여 한줄로 표시되게 변경했습니다.
재접속 후 정상적으로 표시되는 것을 확인하실수 있습니다.

컨텐츠 제한 표시방법.
어드벤쳐 : AD
월드보스 : WB
아레나 : AR

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200250-250.0.9
![1127172401277181](https://github.com/user-attachments/assets/e5dbbc27-0618-4d3f-a9e5-9bffd730d75f)
