### ISSUE TITLE
[마켓] 마일리지 상품 이미지가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6513]
### APV version info

v200250

### Client version info

v250.0.9

### Device

Android (9c M), iOS (9c M)

### detailed device info

Android 8, iOS 17

### Planet

Odin

### account address info

0xc017856bF05aafD452bd921e136115B89dC21631

### What happened?

[내용]
마켓 - 마일리지 탭에서 상품 이미지가 잘려서 출력되는 현상
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/4d88dd19-6f5b-43bb-974f-61eb99ebbbd1)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경에서 메인 로비 - 마켓 진입
2. 마켓 화면에서 마일리지 탭 클릭
3. 상품 이미지가 잘려서 출력되는 것을 확인

[Should be]
마일리지 상품 이미지가 정상 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by jaeho0103** [comment]
네 어제 변경을 먼저 진행한 부분으로 관련 리소스 추가제작중에 있습니다.
해당 이슈는 리소스 변경후 팀에서 체크하고 마무리하겠습니다.

**Comment by U-lis** [comment]
이미지 변경 및 정상 출력 확인했습니다. 이슈 종료하겠습니다,
![Screenshot from 2024-11-27 13-19-38](https://github.com/user-attachments/assets/53c02fa6-979d-4aaf-8df9-647239aecde7)
