### ISSUE TITLE
[마켓] 일부 상품 구매 시 마일리지를 획득하지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6514]
### APV version info

v200250

### Client version info

v250.0.9

### Device

iOS (9c M), Android (9c K)

### detailed device info

Android 8, iOS 17

### Planet

Odin

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
일부 상품 구매 시 마일리지를 획득하지 않는 현상
- 콜렉션 부스터 패키지, 11월 데일리 패키지, 마스터 펫 콜렉터 패키지, 스피드업 펫 콜렉터 패키지, 확률업 펫 콜렉터 패키지에서 해당 현상이 발생하였습니다.
- 상품 구매 완료 팝업에서도 마일리지 획득 안내 문구가 출력되지 않는 것을 확인했습니다.
- Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/f1d30735-ad88-4540-b3ff-5e3ca90a21c8

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경에서 메인 로비 - 마켓 진입
2. 마켓 화면에서 펫 패키지 탭 클릭
3. 확률업 펫 콜렉터 상품 클릭
4. 상품 상세 팝업에 획득 마일리지가 160으로 표기된 것을 확인
5. 상품 구매 시 마일리지를 획득하지 않은 것을 확인
6 구매 완료 팝업에서 마일리지 안내 문구가 표기되지 않은 것을 확인

[Should be]
일부 상품 구매 시 마일리지가 정상적으로 획득되어야 합니다.

### Relevant log output

```shell

```

**Comment by U-lis** [comment]
해당 상품들에 대해 시트에 있는 마일리지 값이 DB 에 제대로 갱신되어 있지 않은 것을 확인해 값 갱신했습니다.

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200250-250.0.9
iOS.v250.0.9(134)

https://github.com/user-attachments/assets/90011031-3067-45fd-b5f8-f0bb9f0999cf
