### ISSUE TITLE
5월드 배경 이어붙이기가 제대로 안된 부분들이 있어서 검은색 노출됨

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles#6530]
https://planetariumhq.slack.com/archives/C062ZS68A21/p1732850278812909

**Comment by jonny-jeahyunchoi** [comment]
![Image](https://github.com/user-attachments/assets/b30cc810-0768-4752-9f40-869a2ed49653)
동일 스테이지에서 해당현상 발생안함. 에디터로 여러해상도에서 확인해봤는데도 문제상황이 발생하지않음

**Comment by jonny-jeahyunchoi** [comment]
재현케이스가 나오지 않고 있어서 닫도록 하겠습니다.
