### ISSUE TITLE
버튼 연출 통일_이벤트 공지 팝업

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#6535]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/e1b847fe-93d0-4026-92db-bea2bc6c7e2c)

1. 버튼 연출 통일, 대문자로 변경
2. 버튼 연출 통일

**Comment by ipdae** [comment]
연출과 별개로 대문자로 변경만 우선 진행

**Comment by dlwlgns268** [comment]
해당 이슈 제게 assign 해 주실수 있나요?

**Comment by boscohyun** [comment]
@dlwlgns268 네, 감사합니다!😊

**Comment by eugene-doobu** [comment]
애니메이션 관련 확인 후 CLOSE 처리하겠습니다
