### ISSUE TITLE
버튼 연출 통일_랭킹 팝업

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles#6536]
![Image](https://github.com/planetarium/NineChronicles/assets/102953029/e967812d-487f-480c-857b-4919cd35dc18)

1. 대문자 처리, 선택된 목록 커지지 않게
2. 대문자 처리, 볼드 없음, 선택된 목록 커지지 않게
3. 버튼 연출 공통 (중앙에서 커졌다가 작아지게)

**Comment by AKU430** [comment]
해당 이슈 저한테 어사인 해주세요

**Comment by boscohyun** [comment]
@AKU430 네, 감사합니다!😊

**Comment by eugene-doobu** [comment]
애니메이션 관련 확인 후 CLOSE 처리하겠습니다
