### ISSUE TITLE
[워크샵] 합성 화면에서 도움말 버튼 클릭 시 분해 관련 도움말이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6565]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 8, iOS 17

### Planet

Heimdall

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
합성 화면에서 도움말 버튼 클릭 시 분해 관련 도움말이 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/6eca695e-e1d3-4b68-84af-3e28584c71a0

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 화면 상단의 도움말 버튼 클릭
3. 분해 관련 도움말 문구가 출력되는 것을 확인

[Should be]
합성 화면에서 도움말 버튼 클릭 시 합성 관련 도움말이 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 pr에서 수정하였습니다. 260.0.1 빌드에서 확인 부탁드립니다 @QgamesGeonPyoNoh 
https://github.com/planetarium/NineChronicles/pull/6583

**Comment by QgamesJeongWonChoe** [comment]
현재 합성 화면에서 도움말 버튼 클릭 시 테스트 문구가 출력되는 상태입니다. 확인 부탁드립니다.

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)

![Image](https://github.com/user-attachments/assets/1524179e-273c-4a99-80d4-8418f279f261)

**Comment by eugene-doobu** [comment]
텍스트 수정된것 260.0.3 버전에서 적용되어있습니다. 확인 부탁드립니다.

**Comment by QgamesGeonPyoNoh** [comment]
도움말 텍스트 출력되었으나 텍스트에 이상한 점이 있어 문의드립니다.
1. 모바일) 그리모어가 그림외어로 출력되고 있습니다.
2. 모바일) 로드 아우라가 전설의 군주 오라 장비로 출력되고 있습니다.
3. 공통) 장착 중인 장비가 재료 선택 불가로 출력되고 있습니다. 착용 장비가 등록 불가인 것이 맞는지 기획 의도 확인 부탁드립니다.

![Image](https://github.com/user-attachments/assets/7680daeb-ac0b-45e2-961a-68d1c36e6145)


확인 부탁드립니다.

[테스트 환경]
Windows.v200260-260.0.3
Android.v200260-260.0.3
iOS.v260.0.3(138)

**Comment by ipdae** [comment]
@NineSyu @jaeho0103 텍스트 변경 진행 부탁드립니다.

**Comment by NineSyu** [comment]
누락된 문구 추가하였습니다. 재접속 후 확인하시면 정상적으로 출력되는 것을 확인하실 수 있습니다!

**Comment by QgamesGeonPyoNoh** [comment]
1. 모바일) 로드 아우라가 전설의 군주 오라 장비로 출력되고 있습니다.
2. 공통) 장착 중인 장비가 재료 선택 불가로 출력되고 있습니다.
착용 장비가 등록 불가인 것이 맞는지 기획 의도 확인 부탁드립니다.

해당 부분 현재 동일하게 나타나고 있습니다.
확인 부탁드립니다.

[테스트 환경]
Windows.v200260-260.0.4
Android.v200260-260.0.4
iOS.v260.0.4(139)

**Comment by NineSyu** [comment]
문구 잘못 작성되어있던 부분 수정해서 다시 적용했습니다!
재접속 후 체크해주시면 정상적으로 출력되는 것을 확인하실 수 있습니다!

**Comment by QgamesGeonPyoNoh** [comment]
다음 기준을 만족하는 장비는 재료로 선택될 수 없습니다.
- 현재 장착 중인 장비

장착 중인 장비는 현재 합성 재료로 사용이 가능한 상태입니다.
기획의도 확인 부탁드립니다.

![Image](https://github.com/user-attachments/assets/271ea9b7-65e7-4143-b396-daf8ff85d119)

**Comment by jaeho0103** [comment]
네 스펙 확인했습니다. 도움말 갱신해두겠습니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.4
Android.v200260-260.0.4
iOS.v260.0.4(139)

![Image](https://github.com/user-attachments/assets/a73f90f1-6f4a-4b43-9359-4bd7d65c2614)
