### ISSUE TITLE
[워크샵] 합성 화면에서 AP 포션 UI 클릭 시 상세 정보 팝업이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6566]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 8, iOS 17

### Planet

Heimdall

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
합성 화면에서 상단의 AP 포션 UI 클릭 시 상세 정보 팝업이 출력되지 않는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/dffe23f0-4469-4729-b031-9d35f52bed6e

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 화면 상단의 AP 포션 UI 클릭
3. 상세 정보 팝업이 출력되지 않는 것을 확인

[Should be]
합성 화면에서 상단의 AP 포션 UI 클릭 시 상세 정보 팝업이 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 PR에서 수정하였습니다. 260.0.2에서 확인 부탁드립니다
https://github.com/planetarium/NineChronicles/pull/6597

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.2
Android.v200260-260.0.2
iOS.v260.0.2(137)

![Image](https://github.com/user-attachments/assets/8e38285b-578d-40bf-95cc-19c62283192d)
