### ISSUE TITLE
[워크샵] 합성 등록 팝업에서 일부 문구가 영문으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6567]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Android (9c M), iOS (9c M)

### detailed device info

Android 8, iOS 17

### Planet

Heimdall

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
합성 등록 팝업에서 일부 문구가 영문으로 출력되는 현상
- 합성 등록 팝업 상단의 등록 문구, 아이템 선택 문구가 영문으로 출력되는 상태입니다.
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/69f6f207-0bc7-4f46-8dfc-3adc34a44feb)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 화면에서 선택 버튼 클릭
3. 출력된 등록 팝업에서 일부 문구가 영어로 출력되는 것을 확인

[Should be]
합성 등록 팝업에 문구가 영문으로 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 pr에서 수정하였습니다. 260.0.1 빌드에서 확인 부탁드립니다 @QgamesGeonPyoNoh 
https://github.com/planetarium/NineChronicles/pull/6583

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200260-260.0.1
iOS.v260.0.1(136)

![Image](https://github.com/user-attachments/assets/1339a04d-4e51-4823-9467-77047122fff4)
