### ISSUE TITLE
[워크샵] 합성 등록 팝업에서 재료를 0개 선택 시 등록 버튼이 활성화되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6568]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성 등록 팝업에서 재료를 0개 선택 시 등록 버튼이 활성화되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/1284a9d0-60a5-4b1e-8a34-ddc7bb22d20f

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 가능한 등급의 선택 버튼 클릭
3. 재료를 선택하지 않는 상태로 세팅
4. 등록 버튼이 활성화되는 현상 확인

[Should be]
합성 등록 팝업에서 재료를 0개 선택 시 등록 버튼이 활성화되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)

https://github.com/user-attachments/assets/80deb523-32fb-4dc0-83ca-be9dbc749f68
