### ISSUE TITLE
[워크샵] 강화한 장비를 합성 재료로 등록 시 별도의 안내 메세지가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6569]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
강화한 장비를 합성 재료로 등록 시 별도의 안내 메세지가 출력되지 않는 현상
- 기획서 상에는 강화 / 착용 중인 장비를 합성 재료로 등록 시 별도의 메세지가 출력되는 것으로 작성되어 있습니다.
- 현재 착용 중인 장비를 재료로 사용했을 시에만 안내 메세지가 출력되고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/86fb9efc-f7fd-4455-942d-fe06390ba4e2

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 가능한 등급의 선택 버튼 클릭
3. 강화된 장비를 합성 재료로 선택
4. 등록 버튼 클릭
5. 강화된 장비를 합성 재료로 등록 시 별도의 안내 메세지가 출력되지 않는 현상 확인

[Should be]
강화한 장비를 합성 재료로 등록 시 안내 메세지가 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by QgamesGeonPyoNoh** [comment]
착용 장비 - 재료 등록 팝업에서 메세지 출력
강화 장비 - 재료 등록 후 합성 버튼 클릭 시 메세지 출력

각 상황 별로 메세지 출력 타이밍이 다른 것으로 확인했습니다.
의도하신 부분인지 문의드립니다.

**Comment by eugene-doobu** [comment]
@jaeho0103 해당 케이스 디테일하게 생각을 못했었는데 장비 등록 팝업에서 강화 장비 메시지도 함께 출력해도 괜찮을까요?

**Comment by jaeho0103** [comment]
@eugene-doobu 
착용장비랑 강화(4강이상) 은 아예 재료로 선택되지 않게 스펙변경 기획정리중입니다.
그외의 3강이하 장비는 장비등록 팝업에서 메세지 표시해주시면 감사하겠습니다.

**Comment by eugene-doobu** [comment]
아래 pr에서 수정하였습니다. 260.0.1 빌드에서 확인 부탁드립니다 @QgamesGeonPyoNoh 
https://github.com/planetarium/NineChronicles/pull/6583

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)

https://github.com/user-attachments/assets/a6bf8087-1391-4d3e-9494-840e36c0513d
