### ISSUE TITLE
[워크샵] 합성에 필요한 AP 부족 시 AP 포션 부족 팝업이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6570]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성에 필요한 AP 부족 시 AP 포션 부족 팝업이 출력되는 현상
- AP 포션은 보유하고 있으나 해당 팝업이 출력되었습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/e5279e1f-4c10-44ef-8d05-c789866c68cd

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 가능한 등급의 선택 버튼 클릭
3. 합성 재료 선택 후 등록 버튼 클릭
4. AP 부족 상태 세팅
5. 합성 버튼 클릭 시 AP 포션 부족 팝업이 출력되는 현상 확인

[Should be]
합성에 필요한 AP 부족 시 AP 부족 팝업이 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 pr에서 수정하였습니다. 260.0.1 빌드에서 확인 부탁드립니다 @QgamesGeonPyoNoh 
https://github.com/planetarium/NineChronicles/pull/6583

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)

https://github.com/user-attachments/assets/dd386d56-d397-484d-93d9-8451189b7c33
