### ISSUE TITLE
[워크샵] 합성 재료 등록 팝업에서 등록한 재료에 빼기 버튼이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6572]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성 재료 등록 팝업에서 등록한 재료에 빼기 버튼이 출력되지 않는 현상
- 아이콘 클릭 시 등록 해제는 동작하고 있습니다.
- 기획서 상에는 등록한 장비에 빼기 버튼이 출력되는 것으로 작성되어 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/e879d021-0b36-4fba-b668-72626bb48cf9)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 가능한 등급의 선택 버튼 클릭
3. 합성 재료 선택
4. 선택된 합성 재료에 빼기 버튼이 출력되지 않는 현상 확인

[Should be]
합성 재료 등록 팝업에서 등록한 재료에 빼기 버튼이 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 pr에서 수정하였습니다. 260.0.1 빌드에서 확인 부탁드립니다 @QgamesGeonPyoNoh 
https://github.com/planetarium/NineChronicles/pull/6583
