### ISSUE TITLE
[워크샵] 합성 재료 등록 팝업 오픈 시 재료가 1개만 자동 선택되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6573]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성 재료 등록 팝업 오픈 시 재료가 1개만 자동 선택되는 현상
- 기획서 상에는 '최소 1회가 진행될 수량이 CP낮은 순으로 자동 선택' 으로 작성되어 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/f006fe2c-03fe-4bb9-95be-352e238851ed

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 가능한 등급의 선택 버튼 클릭
3. 합성 재료 등록 팝업 출력
4. 재료가 1개만 자동 선택되는 현상 확인

[Should be]
합성 재료 등록 팝업 출력 시 최소 1회가 진행될 수량이 CP낮은 순으로 자동 선택되어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 pr에서 수정하였습니다. 260.0.1 빌드에서 확인 부탁드립니다 @QgamesGeonPyoNoh 
https://github.com/planetarium/NineChronicles/pull/6583

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)

![Image](https://github.com/user-attachments/assets/abecefc3-d3a7-452f-ac6a-95891cc3af5a)
