### ISSUE TITLE
[워크샵] 합성 화면에서 그리모어 탭 선택 후 화면 재진입 시 아우라 등급 목록이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6574]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 8, iOS 17

### Planet

Heimdall

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
합성 화면에서 그리모어 탭 선택 후 화면 재진입 시 탭은 그리모어로 설정되어 있지만 아우라 등급 목록이 출력되는 현상.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/c26c3dd6-2fec-4808-aa9a-d8c8f848510f

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 그리모어 탭 클릭 후 그리모어 등급 목록이 출력되는 것을 확인
3. 합성 화면 상단의 뒤로가기 버튼 클릭 후 합성 화면 재진입
4. 그리모어 탭으로 설정되너 있지만 아우라 등급 목록이 출력되는 것을 확인

[Should be]
합성 화면에서 그리모어 탭 선택 후 화면 재진입 시 그리모어 등급 목록이 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 이슈에서 수정하였습니다. 260.0.1 빌드에서 확인 부탁드립니다 @QgamesGeonPyoNoh 
https://github.com/planetarium/NineChronicles/pull/6583

**Comment by eugene-doobu** [comment]
아래 pr에서 수정하였습니다. 260.0.1 빌드에서 확인 부탁드립니다 @QgamesGeonPyoNoh 
https://github.com/planetarium/NineChronicles/pull/6583

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)

https://github.com/user-attachments/assets/38a7c00b-0f8d-4101-b897-47d21dc4f1fe
