### ISSUE TITLE
[워크샵] 최대 합성 횟수 10회를 초과하여 합성이 가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6576]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
최대 합성 횟수 10회를 초과하여 합성이 가능한 현상
- 기획서 상에는 최대 합성 횟수 10회로 작성되어 있습니다.
- 레어 아우라 기준 12회가 최대 횟수로 출력되고 있습니다. 기획 의도 확인 부탁드립니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/29d509dd-bb83-42b9-8b5f-4a27821099f5

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 가능한 등급의 선택 버튼 클릭
3. 합성 재료를 10회 이상 분량 선택
4. 최대 합성횟수 10회를 초과하여 합성이 가능한 현상 확인

[Should be]
최대 합성 횟수 10회를 초과한 합성 시도는 불가능해야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
초기 기획값은 10개로 기획되었으나 이후 12회로 변경하는거 이슈 없다고 이야기 한 상황이였습니다 cc @jaeho0103 
확인 후 close처리 하겠습니다

**Comment by jaeho0103** [comment]
네 기획서 갱신이 안되어있는 부분이네요 갱신해두겠습니다.

**Comment by eugene-doobu** [comment]
확인 감사합니다. 해당 내용 QA상태로 옮겨두겠습니다 확인 후 close 부탁드립니다 @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
기획 의도인 부분 확인했습니다.
이슈 종료하겠습니다.

[테스트 환경]
Windows.v200260-260.0.0
Android.v200260-260.0.0
iOS.v260.0.0(135)
