### ISSUE TITLE
[워크샵] 합성 결과 출력 시 성공 - 실패 순으로 정렬되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6578]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성 결과 출력 시 성공 - 실패 순으로 정렬되지 않는 현상
- 기획서 상 성공 - 실패 순으로 정렬되는 것으로 작성되어 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/d47d4b1c-1dee-49fe-a653-e1b579952d2e)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 가능한 등급의 선택 버튼 클릭
3. 합성 2회 분 이상 재료 선택 후 등록
4. 합성 진행 후 결과 화면 확인
5. 합성 결과 화면에서 성공 - 실패 순으로 정렬되지 않는 현상 확인

[Should be]
합성 결과 화면에서 성공 - 실패 순으로 정렬되어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 이슈에서 수정하였습니다. 260.0.1 빌드에서 확인 부탁드립니다 @QgamesGeonPyoNoh 
https://github.com/planetarium/NineChronicles/pull/6583

**Comment by QgamesGeonPyoNoh** [comment]
실패 - 성공 순으로 현재 정렬되고 있는데 의도하신 부분인지 문의드립니다.

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)

![Image](https://github.com/user-attachments/assets/2a9050b9-651b-45a6-9b55-f3790368cac5)

**Comment by eugene-doobu** [comment]
@QgamesGeonPyoNoh 기획서상 반대로 되는게 맞아서 수정해야할 듯 합니다

**Comment by eugene-doobu** [comment]
아래 PR에서 수정하였습니다. 260.0.2에서 확인 부탁드립니다
https://github.com/planetarium/NineChronicles/pull/6597

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.2
Android.v200260-260.0.2
iOS.v260.0.2(137)

https://github.com/user-attachments/assets/3e8f4e5a-b9e8-42e2-8639-513ff56c0770
