### ISSUE TITLE
[워크샵] 합성 진행 시 합성 버튼이 영문으로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6579]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Android (9c M), iOS (9c M)

### detailed device info

Android 8, iOS 17

### Planet

Heimdall

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
합성 진행 시 합성 버튼에 '합성 진행 중' 문구가 영문으로 출력되는 현상
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/45f766fe-977b-4786-b3af-164e9ffcb913)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 재료 선택 후 합성 진행
3. 합성 버튼에 합성 진행 중 문구가 영문으로 출력되는 것을 확인

[Should be]
합성 진행 시 합성 버튼에 '합성 진행 중' 문구가 영문으로 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 PR에서 수정하였습니다. 260.0.2에서 확인 부탁드립니다
https://github.com/planetarium/NineChronicles/pull/6597

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200260-260.0.2
iOS.v260.0.2(137)

![Image](https://github.com/user-attachments/assets/0eeccc03-5489-4667-9fb2-7988d2c7bbe2)
