### ISSUE TITLE
[워크샵] 레전드 그리모어 합성 성공 시 1주년 그리모어가 지급되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6581]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows

### detailed device info

Windows 10

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
레전드 그리모어 합성 성공 시 1주년 그리모어가 지급되는 현상
- 레전드 아우라 합성 / 신성 아우라 합성 / 신성 그리모어 합성에서도 출력될 것으로 예상됩니다.
- Windows 환경에서 발생 확인했습니다.
- Android, iOS 환경 확인 중입니다.

![Image](https://github.com/user-attachments/assets/85cb3413-740b-4014-9930-f756a75b1a5c)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 레전드 그리모어 합성 선택하여 진행
3. 합성 성공 시 1주년 그리모어가 지급되는 현상 확인

[Should be]
레전드 그리모어 합성 성공 시 1주년 그리모어가 지급되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
합성이 성공한 케이스에서 아이템별 등장 확률이 제대로 적용되지 않던 문제가 있었습니다. 해당 내용 수정하여 260.0.1에서부터 적용됩니다. @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
합성 테스트 진행 시 하기 아이템은 획득되지 않아 이슈 종료하겠습니다.
- 로드 아우라 3종
- 1주년 아우라
- 1주년 그리모어

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)
