### ISSUE TITLE
[워크샵] 합성 화면에서 AP 포션 사용 후 합성 시도 시 AP 부족 출력

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6584]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성 화면에서 AP 포션 사용 후 합성 시도 시 AP 부족 출력
- 합성 화면을 벗어난 뒤 재 진입 시 합성이 가능합니다.
- 공헌도 AP 충전 시에도 동일한 현상 발생했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/a4d96c9a-cfba-4ecd-a30f-a91b9c7a899b

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. AP 0 상태로 진입
3. 합성 재료 선택 후 등록 진행
4. AP 영역 클릭하여 AP 포션 사용
5. AP 충전 완료
6. 합성 버튼 클릭 시 AP 부족 출력 확인

[Should be]
합성 UI에서 AP 포션 사용 후 합성이 가능해야 합니다.

### Relevant log output

```shell

```

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)

https://github.com/user-attachments/assets/aa4f28a4-c83e-4579-8d61-5333431fadab
