### ISSUE TITLE
[워크샵] 합성 화면에서 AP 포션 사용 시 상단 UI 내 AP 포션 수량이 감소하지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6585]
### APV version info

v200260

### Client version info

v260.0.0

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성 화면에서 AP 포션 사용 시 상단 UI 내 AP 포션 수량이 감소하지 않는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/f0029575-cdf4-4e29-9e7a-3153c919c9c0

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. AP 0 상태로 진입
3. 합성 재료 선택 후 등록 진행
4. AP 영역 클릭하여 AP 포션 사용
5. AP 충전 완료
6. 합성 화면 상단 UI 내 AP 포션 수량이 감소하지 않는 현상 확인

[Should be]
합성 화면에서 AP 포션 사용 시 상단 UI 내 AP 포션 수량이 감소해야 합니다.

### Relevant log output

```shell

```

**Comment by QgamesJeongWonChoe** [comment]
현재 합성 버튼 클릭 시 출력되는 AP 부족 팝업을 통해 AP 포션 사용 시 상단 UI 내 AP 포션 수량이 감소되지 않는 현상이 발생하고 있습니다. 확인 부탁 드립니다.

[테스트 환경]
Windows.v200260-260.0.1
Android.v200260-260.0.1
iOS.v260.0.1(136)

https://github.com/user-attachments/assets/08529487-9d90-44e1-91af-8eb8fa426a70

**Comment by eugene-doobu** [comment]
아래 PR에서 수정하였습니다. 260.0.2에서 확인 부탁드립니다
https://github.com/planetarium/NineChronicles/pull/6597
