### ISSUE TITLE
[워크샵] 합성 재료 등록 화면에서 스크롤 방향이 실제와 반대로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6594]
### APV version info

v200260

### Client version info

v260.0.1

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성 재료 등록 화면에서 스크롤 방향이 실제와 반대로 출력되는 현상
- 스크롤를 내릴 경우 올라가는 형태로 출력되고 있습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/861c6457-5e94-4e24-b747-0be050db57f4

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 합성 가능한 등급의 선택 버튼 클릭
3. 재료 아이콘 영역 스크롤 시도
4. 스크롤 방향이 실제와 반대로 출력되는 현상 확인

[Should be]
합성 재료 등록 화면의 스크롤 방향이 실제와 동일해야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 PR에서 수정하였습니다. 260.0.2에서 확인 부탁드립니다
https://github.com/planetarium/NineChronicles/pull/6597

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.2
Android.v200260-260.0.2
iOS.v260.0.2(137)

https://github.com/user-attachments/assets/5bae2eaf-a410-4f70-a5d8-cae97a751049
