### ISSUE TITLE
[워크샵] 합성에서 획득되지 않는 장비가 미리보기에 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6595]
### APV version info

v200260

### Client version info

v260.0.1

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성에서 획득되지 않는 장비가 미리보기에 출력되는 현상
- 합성 화면 / 합성 진행 창 내 말풍선 내에서 확인했습니다.
- 로드 아우라 / 1주년 아우라 / 1주년 그리모어가 출력됩니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/4f82d692-d9bd-47c1-9e08-84f33f0bd234)

![Image](https://github.com/user-attachments/assets/fc71ca28-e749-4aa1-9bde-ede494b9c8c5)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 신성 등급 그리모어 합성 선택 후 재료 등록
3. 합성 화면 내 미리보기에서 1주년 그리모어 출력 확인
4. 합성 진행
5. 합성 진행 창 말풍선 내 미리보기에서 1주년 그리모어 출력 확인

[Should be]
합성 미리보기에서 획득 불가능한 장비가 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 PR에서 수정하였습니다. 260.0.2에서 확인 부탁드립니다
https://github.com/planetarium/NineChronicles/pull/6597

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.2
Android.v200260-260.0.2
iOS.v260.0.2(137)

https://github.com/user-attachments/assets/acbba9b3-a7a6-4087-912c-8a3fd0b49efa
