### ISSUE TITLE
[워크샵] 합성 화면에서 비활성화된 선택 버튼 클릭 시 재료 부족 메세지가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6596]
### APV version info

v200260

### Client version info

v260.0.1

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 8, iOS 17

### Planet

Heimdall

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
합성 화면에서 비활성화된 선택 버튼 클릭 시 '해당 희귀도의 재료가 부족합니다. 재료를 좀 더 확보하고 시도해주세요.' 메세지가 출력되지 않는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/1954a613-314f-4ac0-af35-170a9073a695

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 좌측 재료 등급 목록에서 비활성화된 선택 버튼 클릭
3. 재료 부족 메세지가 출력되지 않는 것을 확인

[Should be]
합성 화면에서 비활성화된 선택 버튼 클릭 시 재료 부족 메세지가 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
아래 PR에서 수정하였습니다. 260.0.2에서 확인 부탁드립니다
https://github.com/planetarium/NineChronicles/pull/6597

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.2
Android.v200260-260.0.2
iOS.v260.0.2(137)

![Image](https://github.com/user-attachments/assets/0935acc7-da34-4d0b-a3b7-98c2f3585af4)
