### ISSUE TITLE
이벤트 던전 UI 이슈

### ISSUE THREAD

**Issue by eugene-doobu** [planetarium/NineChronicles#6599]
https://planetariumhq.slack.com/archives/C011716SDTM/p1734067855438299

1. 로브 좌측 토스트 바에 이벤트 요리 아이콘이 표시되지 않음
2. 월드 인포메이션에서 이벤트던전 입장 버튼 찌부
3. 이벤트던전 스테이지 아이콘 크기비교? 아이콘 스프라이트?

**Comment by jonny-jeahyunchoi** [comment]
1. 요리 아이콘 '900113'세팅
2. 원본 이미지 사이즈로 조절
3. 기존아이콘과 동일 수정x
