### ISSUE TITLE
[월드보스] PC 환경에서 헤임달 체인의 월드보스 시작 버튼이 동작하지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6608]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Windows

### detailed device info

Windows 10

### Planet

Heimdall

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
PC 환경에서 헤임달 체인의 월드보스 시작 버튼이 동작하지 않는 현상
- Windows 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/f0c8bcbd-c5cc-40c5-82a7-d7c00ae12bc6

### How to reproduce the issue

[재현 스텝]
1. 헤임달 체인에서 메인 화면 - 월드 보스 진입
2. 월드 보스 화면에서 입장 버튼 클릭
3. 전투 준비 화면에서 시작 버튼 클릭 시 동작하지 않는 것을 확인

[Should be]
PC 환경에서 헤임달 체인의 월드보스 시작 버튼이 정상적으로 동작해야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
#6607 과 중복으로 보입니다.
