### ISSUE TITLE
[이벤트] 이벤트 아이템 제작하기 퀘스트 바로가기 아이콘이 흰색 이미지로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6609]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
이벤트 아이템 제작하기 퀘스트 바로가기 아이콘이 흰색 이미지로 출력되는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/e12fbca3-11a2-43df-a8aa-8b7365631ac5)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 퀘스트 바로가기 확인
2. 이벤트 아이템 제작하기 퀘스트 확인
3. 퀘스트 바로가기 아이콘이 흰색 이미지로 출력되는 현상 확인

[Should be]
이벤트 퀘스트 바로가기의 아이콘이 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
수정되었습니다 다음버전에서 확인부탁드립니다~!

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.3
Android.v200260-260.0.3
iOS.v260.0.3(138)

![Image](https://github.com/user-attachments/assets/4e197c4e-2a3a-46e9-8559-4b081f632a49)
