### ISSUE TITLE
[시즌패스] 시즌패스 업데이트가 반영되지 않은 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6610]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Android (9c K), iOS (9c M)

### detailed device info

Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
시즌패스 업데이트가 반영되지 않은 현상
- 용기패스 프리미엄 보상 확인시 용기 마스터가 출력되고 있습니다.
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/a15af294-46fb-48c3-97f4-1df891017424)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 시즌패스 클릭
2. 용기패스 프리미엄 해제하기 버튼 클릭
3. 이전 시즌 칭호인 용기 마스터가 보상으로 출력되는 현상 확인

[Should be]
용기 패스 프리미엄 구매 시 '소원 청취자' 칭호가 보상으로 지급되어야 합니다.

### Relevant log output

```shell

```

**Comment by U-lis** [comment]
@jaeho0103  현재 internal 에서 `COURAGEPASS13Premium` (12월 시즌) 상품을 팔고 있고, 이 상품은 49900026 칭호를 지급하고 있습니다.
아직 1월 상품 세팅이 되어 있지 않아서 시즌패스도 다음 시즌으로 넘어가지 않았습니다. "소원 청취자" 가 내년 1월 상품에 대한 칭호일까요?

**Comment by U-lis** [comment]
@QgamesGeonPyoNoh 
확인 결과 1월 시즌 상품은 아직 세팅되지 않은 상태입니다. 이는 금일 중으로 전달주실 예정이어서 전달받는대로 업데이트 예정입니다.

**Comment by U-lis** [comment]
시즌패스 1월 패스로 업데이트 및 상품 설정 완료했습니다. 
월드 클리어 패스를 제외한 용기패스, 어드벤처 보스 패스가 초기화되어 있으면 정상입니다.
경험치 및 결제 확인 부탁드립니다 🙏

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Android.v200260-260.0.4
iOS.v260.0.4(139)

![Image](https://github.com/user-attachments/assets/6db36472-9b9c-436c-bb10-9f1b6cc9041d)
