### ISSUE TITLE
[마켓] 상품 팝업 내 텍스트 출력 이상 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6611]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Android (9c K), iOS (9c M)

### detailed device info

Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
상품 팝업 내 텍스트 출력 이상 현상
- 상품 이름 텍스트가 팝업 테두리 / 상품 아이콘과 겹쳐지는 부분이 있습니다.
- 기간 제한이 없는 상품에 {0}-{1} 텍스트가 출력되고 있습니다.
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/b4ddb1fd-74bf-49b0-a56b-8908ccb9a3b0)
![Image](https://github.com/user-attachments/assets/7562bc18-5d7a-436e-9305-35b87ef0fdaf)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경 - 메인 로비 - 마켓 클릭
2. 마켓 내 임의의 패키지 클릭
3. 상품 이름 텍스트가 팝업 테두리 / 상품 아이콘과 일부 겹쳐지는 현상 확인
4, 마켓 내 기간 제한이 없는 상품 클릭
5. 기간 영역에 {0}-{1} 텍스트가 출력되는 현상 확인

[Should be]
상품 이름 텍스트가 다른 UI와 겹쳐지지 않아야 합니다.
기간 제한이 없는 상품에 {0}-{1} 텍스트가 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu  줄바꿈을 두번할필요없이 한번만해도 될것같습니다~!

**Comment by QgamesGeonPyoNoh** [comment]
현재 마일리지 샵 상품에 {0}-{1} 출력되고 있습니다.

![Image](https://github.com/user-attachments/assets/20dd2bd0-a7ca-43a5-bb28-38d1dc396f92)

그리고 일부 패키지의 이름이 실제 패키지 이름과 일치하지 않는 현상 발생했습니다.

https://github.com/user-attachments/assets/4494ef79-9f2a-4700-ad81-60ee24a9a620

확인 부탁드립니다.

[테스트 환경]
Android.v200260-260.0.3
iOS.v260.0.3(138)

**Comment by jonny-jeahyunchoi** [comment]
@NineSyu 체크 부탁드립니다

**Comment by NineSyu** [comment]
L10n 수정하여 상품 이름과 내용물이 일치하게 변경했습니다.
재접속 후 확인하시면 정상적으로 표시될 것입니다.

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
K.Android.v200260-260.0.3
iOS.v260.0.3(138)

https://github.com/user-attachments/assets/59e3dcf0-9dbb-40de-8067-b76524064fe4
