### ISSUE TITLE
[워크샵] 합성 재료 등록 팝업 닫은 뒤 선택 버튼 클릭 시 리셋 안내 팝업 출력 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6612]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
합성 재료 등록 팝업 닫은 뒤 선택 버튼 클릭 시 리셋 안내 팝업 출력 현상
- 재료 등록 팝업을 닫아 등록한 재료가 없는 상태이나 리셋 안내 팝업이 출력됩니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/9308542c-3f74-4483-94f5-2f8ae89c77ea

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 진입
2. 임의의 재료-등급 선택 버튼 클릭
3. 합성 재료 등록 팝업 출력 - 닫기 버튼 클릭
4. 임의의 재료-등급 선택 버튼 클릭
5. 등록된 재료가 없으나 리셋 안내 팝업 출력 확인

[Should be]
등록된 재료가 없을 경우 리셋 안내 팝업이 출력되지 않아야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
해당 내용 수정되어 다음 빌드에서 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.4
Android.v200260-260.0.4
iOS.v260.0.4(139)

https://github.com/user-attachments/assets/83738b86-4e3b-4566-866c-9634740dad76
