### ISSUE TITLE
[아레나] 오딘에서 아레나 공격 대상이 일부만 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6613]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 8, iOS 17

### Planet

Odin

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
오딘에서 아레나 공격 대상이 일부만 출력되는 현상
- 헤임달에서는 공격 대상이 정상 출력되는 것을 확인했습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/072f624b-346a-47f3-b108-dcf2666cdefc)

### How to reproduce the issue

[재현 스텝]
1. 오딘 체인에서 메인 로비 - 아레나 진입
2. 아레나 공격 대상이 일부만 출력되는 것을 확인

[Should be]
오딘에서 아레나 공격 대상이 정상 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
서비스 설정 문제가 있었던걸로 확인됐습니다. 다시 확인 부탁드립니다.

**Comment by QgamesJeongWonChoe** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.2
Android.v200260-260.0.2
iOS.v260.0.2(137)

![Image](https://github.com/user-attachments/assets/aff5632a-3dcd-475d-a1cf-4b0ecf84b92f)
