### ISSUE TITLE
[랭킹] 오딘에서 랭킹 버튼 클릭 시 에러 팝업이 출력되는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6614]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 8, iOS 17

### Planet

Odin

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
오딘에서 랭킹 버튼 클릭 시 에러 팝업이 출력되는 현상
- 헤임달, 토르 체인에서는 랭킹 팝업이 정상 출력되는 것을 확인했습니다,
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/0ff8f243-802b-488c-bce2-9e39d892e93c

### How to reproduce the issue

[재현 스텝]
1. 오딘 체인에서 메인 로비 상단의 랭킹 버튼 클릭
2. 빈 랭킹 리스트가 출력되는 것을 확인
3. 랭킹 팝업을 닫을 시 에러 팝업이 출력되는 것을 확인

[Should be]
오딘에서 랭킹 버튼 클릭 시 랭킹 팝업이 정상 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
랭킹서비스에서 리스트를 가져오는데 실패했을때 뜨는 에러입니다. 현재는 오딘인터널 리스트 잘받아오는것으로 보입니다~!
![image](https://github.com/user-attachments/assets/7b504c16-bf26-41ba-bf84-ef0621dc5902)
