### ISSUE TITLE
[랭킹] 헤임달, 토르 체인에서 어빌리티 랭킹 리스트가 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6615]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 8, iOS 17

### Planet

Heimdall

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
헤임달, 토르 체인에서 어빌리티 랭킹 리스트가 출력되지 않는 현상
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/bde55519-e536-4e09-9476-b080a03643a6

### How to reproduce the issue

[재현 스텝]
1. 헤임달 체인에서 메일 로비 상단의 랭킹 버튼 클릭
2. 출력된 랭킹 팝업에서 어빌리티 탭 클릭
3. 어빌리티 랭킹 리스트가 출력되지 않는 것을 확인

[Should be]
헤임달, 토르 체인에서 어빌리티 랭킹 리스트가 정상 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
인터널에서 procedure가 안돌아서 안나오는 문제로 보임

**Comment by U-lis** [comment]
@area363  님 확인 결과 internal heimdall, thor 에 procedure > cronjob 변경점 설정을 하지 않아서 그런 것으로 확인

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.5
Android.v200260-260.0.5
iOS.v260.0.5(140)

![Image](https://github.com/user-attachments/assets/013a4e0f-c701-4a71-9ccc-5c32a098f4b9)
