### ISSUE TITLE
[상점] iOS 환경에서 상품 구매가 진행되지 않는 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6616]
### APV version info

v200260

### Client version info

v260.0.2

### Device

iOS (9c M)

### detailed device info

iOS 17

### Planet

Odin

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
iOS 환경에서 상품 구매가 진행되지 않는 현상
- Android 환경에서는 상품 정상 구매 확인했습니다.
- iOS 환경에서 상품 구매 시 구매 완료 팝업이 출력되지 않는 것을 확인했습니다.

https://github.com/user-attachments/assets/3cb6e26e-a008-46a1-953a-2d1711e7f5e9

해당 현상 발생 당시 에러 로그 공유 드립니다.
[2024-12-17 02:07:35] [IDetailedStoreListener PurchaseFail] reason: Unknown, Product: AP 포션 75
Nekoyume.IAPStore.IAPStoreManager:UnityEngine.Purchasing.IDetailedStoreListener.OnPurchaseFailed(Product, PurchaseFailureDescription)
UnityEngine.Purchasing.Extension.UnityUtil:Update()

### How to reproduce the issue

[재현 스텝]
1. iOS 환경에서 메인 로비 - 상점 진입
2. 상점 화면에서 단일 패키지 탭 클릭
3. AP 포션 75개 구매 버튼 클릭
4. iOS구매 팝업에서 구입 버튼 클릭
5. 상품 구매가 진행되지 않는 것을 확인

[Should be]
iOS 환경에서 상품 구매가 정상 진행되어야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
@U-lis @Atralupus 이거 상품 sku가 꼬여있는것같습니다 골든더스트 100 구매에 실패했는데 로그는 [AP 포션 75] 가 실패한것으로 나오는것같아요

**Comment by QgamesJeongWonChoe** [comment]
@jonny-jeahyunchoi 에러 로그는 최초 이슈 발생 시의 로그입니다. 영상은 이후 다른 상품을 구매하며 해당 이슈를 재현하던 중 촬영한 것이므로 영상과 로그는 동일한 시점이 아닙니다. 혼선을 드려서 죄송합니다.

**Comment by jonny-jeahyunchoi** [comment]
@QgamesJeongWonChoe 앗 그렇군요 확인 및 공유 감사합니다~!

**Comment by jonny-jeahyunchoi** [comment]
@QgamesJeongWonChoe 앱스토어 계정연결문제일가능성도 있어보이는데 앱스토어 계정 로그아웃 및 재로그인하시고 시도부탁드립니다~!

**Comment by jonny-jeahyunchoi** [comment]
테스터분 로컬문제인지 다른분들께 확인요청

**Comment by jonny-jeahyunchoi** [comment]
추가 인원들까지 체크했을때 전부 구매 성공
애플 서비스 장애 이슈인것으로 예상되어 이슈는 닫도록 하겠습니다.
