### ISSUE TITLE
[이벤트] 라글렌피딕 99년 산의 설명 텍스트가 'O_O?!' 로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6618]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
라글렌피딕 99년 산의 설명 텍스트가 'O_O?!' 로 출력되는 현상
- 라그나 데낄라 / 짭쪼름한 엘릭서는 텍스트 형태로 출력됩니다.
- 의도하신 설명 텍스트가 맞는지 확인 부탁드립니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/cfff9be1-771a-4951-aa20-5e6e155800a4)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 인벤토리 버튼 클릭
2. 음식 탭 내 라글렌피딕 99년 산 클릭
3. 라글렌피딕 99년 산 팝업 내 설명 텍스트 확인
4. 설명 텍스트가 'O_O?!' 로 출력되는 현상 확인

[Should be]
라글렌피딕 99년 산 설명 텍스트가 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by NineSyu** [comment]
의도한 아이템 설명이 맞습니다! cc@jaeho0103

**Comment by QgamesGeonPyoNoh** [comment]
기획 의도인 부분으로 확인하여 이슈 종료하겠습니다.

[테스트 환경]
Windows.v200260-260.0.3
Android.v200260-260.0.3
iOS.v260.0.3(138)
