### ISSUE TITLE
[런쳐] 오딘 - 토르 간 NCG 전송이 불가능한 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6620]
### APV version info

v200260

### Client version info

v260.0.2

### Device

Windows

### detailed device info

Windows 10

### Planet

Odin

### account address info

0x3A73d8bC927D66fB6a6dFd8adB414EB0f34F3c72

### What happened?

[내용]
오딘 - 토르 간 NCG 전송이 불가능한 현상
- Windows 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/39ddd54f-5471-4e80-8dab-a113f769996d

- 해당 현상 발생 당시 Log 파일 공유드립니다.

[Log.zip](https://github.com/user-attachments/files/18161287/Log.zip)

### How to reproduce the issue

[재현 스텝]
1. PC 환경 런쳐 실행
2. 오딘 Planet 진입
3. Send NCG 버튼 클릭
4. 대상 Planet 토르 선택
5. NCG 전송 진행 시 전송되지 않는 현상 확인

[Should be]
오딘 - 토르 체인 간 NCG 전송이 가능해야 합니다.

### Relevant log output

```shell

```

**Comment by Atralupus** [comment]
Bridge가 네트워크에 붙지 못해 죽어있던 문제였으며 지금은 해결되었습니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.5

https://github.com/user-attachments/assets/8381aff0-5143-4bb2-bcac-b827a86c353b
