### ISSUE TITLE
[워크샵] 합성 튜토리얼이 출력되지 않는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6623]
### APV version info

v200260

### Client version info

v260.0.3

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 12, iOS 17

### Planet

Odin

### account address info

0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544

### What happened?

[내용]
합성 튜토리얼이 출력되지 않는 현상
- 합성 화면에 최초 진입 시에도 튜토리얼이 출력되지 않았습니다.
- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/da827043-137f-4864-ae16-109c59e21754

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 워크샵 - 합성 클릭
2. 합성 화면 최초 진입
3. 합성 튜토리얼이 출력되지 않는 현상 확인

[Should be]
합성 화면 최초 진입 시 합성 튜토리얼이 출력되어야 합니다.

### Relevant log output

```shell

```

**Comment by eugene-doobu** [comment]
해당 내용 수정되어 다음 빌드에서 확인 부탁드립니다

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.4

https://github.com/user-attachments/assets/a647e685-5738-424b-8363-f7962442aff8

**Comment by QgamesGeonPyoNoh** [comment]
기존에 151 스테이지를 클리어한 캐릭터에서는 튜토리얼이 출력되지 않고 있습니다.
해당 부분 확인 부탁드립니다.

[테스트 환경]
Windows.v200260-260.0.4
Android.v200260-260.0.4
iOS.v260.0.4(139)

**Comment by eugene-doobu** [comment]
@QgamesGeonPyoNoh 혹시 해당 캐릭터가 마지막으로 클리어했던 스테이지 번호를 알 수 있을까요?

**Comment by eugene-doobu** [comment]
말씀주신 두 케이스가 추가 처리가 되어있는걸로 보입니다. 다른 튜토리얼들은 마지막 클리어 스테이지를 조회하고 해당 스테이지를 클리어 한 직후 로비로 왔을때 수행되는게 기본 구현입니다. 혹시 관련해서 추가 작업 필요할까요? @jaeho0103 

```
룬 레벨 보너스가 1 이상이면서 튜토리얼을 안 본 경우 튜토리얼 실행
커스텀크래프트 친밀도가 0이면서 튜토리얼을 안 본 경우 튜토리얼 실행
```

**Comment by eugene-doobu** [comment]
로컬기기에서 특정 아바타로 합성 튜토리얼 안 본 상태로 합성 UI에 진입하면 튜토리얼 나오도록 기능 수정하였습니다. 관련 내용 260.0.5 버전에서 확인 부탁드립니다 @QgamesGeonPyoNoh

**Comment by QgamesGeonPyoNoh** [comment]
수정 내용 확인 완료되었습니다.

[테스트 환경]
Windows.v200260-260.0.5
Android.v200260-260.0.5
iOS.v260.0.5(140)

https://github.com/user-attachments/assets/a8d0676c-7d41-4da5-b8bc-6cdbe82a6cd4
