### ISSUE TITLE
[시즌패스] 어드벤쳐 보스 패스 프리미엄 구매 시 지급된 스크롤이 인벤토리 내에서 기존 스크롤과 별도로 출력되는 현상

### ISSUE THREAD

**Issue by QgamesGeonPyoNoh** [planetarium/NineChronicles#6626]
### APV version info

v200260

### Client version info

v260.0.3

### Device

Android (9c K), iOS (9c M)

### detailed device info

Android 12, iOS 17

### Planet

Heimdall

### account address info

0x3146FE0E47A1998e14cd8a33640e3648A5A90276

### What happened?

[내용]
어드벤쳐 보스 패스 프리미엄 구매 시 지급된 스크롤이 인벤토리 내에서 기존 스크롤과 별도로 출력되는 현상
- Android, iOS 환경에서 발생 확인했습니다.

![Image](https://github.com/user-attachments/assets/36949e3a-ea1b-4455-83da-f82d7ff53fdc)

### How to reproduce the issue

[재현 스텝]
1. 모바일 환경
2. 메인 로비 - 시즌 패스 - 어드벤쳐 보스 패스 클릭
3. 프리미엄 구매 진행
4. 스크롤 500개 획득 확인
5. 인벤토리 확인 시 지급받은 스크롤이 기존 스크롤과 별도로 출력되는 현상 확인

[Should be]
어드벤쳐 보스 패스 프리미엄 구매 시 지급된 스크롤이 기존 스크롤과 인벤토리 내에서 합쳐져야 합니다.

### Relevant log output

```shell

```

**Comment by ipdae** [comment]
스크롤의 NT, T 상태 확인 필요(메인넷 포함)

**Comment by U-lis** [comment]
기존에 NT 로 되어 있던 것들이 있어서 두개가 따로 보이고 있었습니다.
DB 에서 지급 상품 T 로 변경했습니다. 이건 이후 T 로 쭉 나갈건데, 예전에 상품을 구매하거나 한 분들은 T, NT 두개를 가지고 있을 수 있습니다.
lib9c custom craft action 확인 결과 NT 로 지급된 것이 action 에 영향을 주거나 하지는 않을 것으로 확인했습니다.
