### ISSUE TITLE
[토르 체인] 커스텀 장비 제작 시 소요되는 블럭이 기존 체인과 동일한 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6627]
### APV version info

v200260

### Client version info

v260.0.4

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 8, iOS 17

### Planet

Thor

### account address info

0x2a848B90f0A17370610915A99C7153ceE8b96013

### What happened?

[내용]
커스텀 장비 제작 시 소요되는 블럭이 기존 체인과 동일한 현상
- 오딘, 헤임달, 토르 체인에서 모두 커스텀 제작 시 21600 블럭이 소요되는 것을 확인했습니다.
- 일반 장비 제작 시 토르 체인에서는 기존 체인의 1/5 블럭이 소요되는 것을 확인했습니다.
- Windows, Android, iOS 환경에서 확인했습니다.

https://github.com/user-attachments/assets/c9240860-2cc6-4cff-b28c-566a4cc12346

### How to reproduce the issue

[재현 스텝]
1. 토르 체인에서 메인 로비 - 워크샵 - 커스텀 제작 진입
2. 커스텀 제작 화면에서 장비 선택
3. 제작 정보에 소요되는 블럭이 21600으로 표기된 것을 확인
4. 커스텀 제작 진행 시 오딘과 동일하게 21600 블럭이 소요되는 것을 확인

[Should be]
토르 체인에서 커스텀 장비 제작 시 소요되는 블럭이 기존 체인의 1/5로 감소되어야 합니다.

### Relevant log output

```shell

```

**Comment by NineSyu** [comment]
안녕하세요! 커스틈 장비는 오딘, 헤임달과 동일한 제작블록을 가지는 것이 정상스펙인 것으로 확인됩니다!
체크해주셔서 감사드립니다! 위에 이슈는 정상스펙 처리해주시면 감사드립니다!

**Comment by QgamesGeonPyoNoh** [comment]
기획 의도인 것으로 확인하여 이슈 종료하겠습니다.

[테스트 환경]
Windows.v200260-260.0.4
Android.v200260-260.0.4
iOS.v260.0.4(139)
