### ISSUE TITLE
[시즌패스] 월드 클리어 패스에 표기된 경험치와 실제 스테이지 진행도가 상이한 현상

### ISSUE THREAD

**Issue by QgamesJeongWonChoe** [planetarium/NineChronicles#6629]
### APV version info

v200260

### Client version info

v260.0.4

### Device

Windows, Android (9c M), iOS (9c M)

### detailed device info

Windows 10, Android 8, iOS 17

### Planet

Odin

### account address info

0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9

### What happened?

[내용]
월드 클리어 패스에 표기된 경험치와 실제 스테이지 진행도가 상이한 현상
- 일부 계정에서 경험치가 실제 클리어한 스테이지보다 더 높게 출력되는 현상이 발생합니다.
헤임달 / 0xaCd3f7B53C3E3fA8A21C49995A9a890eEeDd02C9 / 캐릭터명 Yrsk
23 스테이지 클리어 / 경험치 29

- 일부 계정에서 경험지가 실제 클리어한 스테이지보다 더 낮게 출력되는 현상이 발생합니다.
오딘 / 0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544 / 캐릭터명 qkr
151 스테이지 클리어 / 경험치 150

- 일부 계정에서 경험치가 음수로 출력되는 현상이 발생합니다.
오딘 / 0x7F1312E1fF4d7b9721b0bB364369AfDB03bde544 / 캐릭터명 tester123

- Windows, Android, iOS 환경에서 발생 확인했습니다.

https://github.com/user-attachments/assets/3d760c02-0bbb-477c-8a2c-08b5428fe1fe

https://github.com/user-attachments/assets/d415ee9e-b5a0-4fc7-8e87-f8c2652603b8

![Image](https://github.com/user-attachments/assets/342f12b2-cff1-450c-898d-a83691306b7d)

### How to reproduce the issue

[재현 스텝]
1. 메인 로비 - 시즌 패스 버튼 클릭
2. 시즌 패스 화면에서 월드 클리어 패스 탭 클릭
3. 월드 클리어 패스 경험치 확인
4. 어드벤쳐 - 월드맵 - 스테이지 진입
5. 월드 클리어 패스에 표기된 경험치와 실제 스테이지 진행도가 상이한 것을 확인

[Should be]
월드 클리어 패스에 표기된 경험치와 실제 스테이지 진행도가 동일해야 합니다.

### Relevant log output

```shell

```

**Comment by jonny-jeahyunchoi** [comment]
@jaeho0103 @Atralupus @U-lis
체크 부탁드립니다~!
1번이슈 : 체크필요
2번이슈 : 단순히 갱신이 늦은것일수도있을것같음
3번이슈 : 경험치 테이블과 유저 경험치보유량 이 어긋난듯해보입니다.

**Comment by jaeho0103** [comment]
일단 저는 지난번 시즌과 동일한 데이터를 요청드려서 체크할게 없어보이고,
@U-lis @Atralupus 님이 서비스 상태를 체크해봐주셔야 할 것 같습니다.

**Comment by U-lis** [comment]
@QgamesJeongWonChoe 
1. 실제보다 DB 의 값이 높은 것은 snapshot reset 의 영향일 수 있을 것 같습니다. 예전에 internal 에서 29 스테이지까지 진행했는데 snapshot reset 이 되면서 23 스테이지까지만 깬 상태로 돌아왔다면 이렇게 보일 수 있습니다.
    - 이 부분은 앞으로 snapshot reset 을 하면 world clear pass 도 초기화해 문제가 없도록 하겠습니다.
2. 실제보다 낮게 보이는 현상은 확인해보겠습니다.
    - 만일 해당 계정이 QA 시작 후 한번도 스테이지를 진행하지 않은 상태라면 chain 과 DB 의 상태가 싱크되지 않아 이렇게 보일 수 있습니다. 현재 스테이지 진행/sweep 을 하지 않으면 월드 클리어 패스가 갱신되지 않습니다.
3. 음수로 보이는 계정은 확인해보니 월드 클리어 패스 극초기 테스트 이후 변경이 없던 계정으로 보입니다.
    - 이때는 제가 임의의 값을 넣어서 최종 값과 경험치-레벨 조합이 맞지 않을 수 있습니다. 경우에 따라 경험치보다 레벨이 높게 설정되었을 수 있으며, 이 경우 음수 경험치가 보일 수 있습니다.
    
===
1, 3번 케이스의 경우는 mainnet 에서는 발생하지 않는 이슈들 (snapshot reset || test data)이기 때문에 무시해도 될 것으로 보이고, 2번에 대해서는 좀 더 체크해보고 말씀드리겠습니다.
2번의 경우에도 snapshot reset + 스테이지 진행 안함 상태라면 mainnet 에서는 발생할 일 없기는 합니다. << 이 계정은 아무 스테이지나 한번 진행하고 확인해주시면 좋을 것 같습니다.

**Comment by QgamesGeonPyoNoh** [comment]
말씀해주신 상황 확인했습니다.
2번 케이스의 경우 클리어한 스테이지 다시 클리어 시 실제 수치와 동일하게 변경되었습니다.

[테스트 환경]
Windows.v200260-260.0.5
Android.v200260-260.0.5
iOS.v260.0.5(140)

https://github.com/user-attachments/assets/a672ebdc-1009-4f2a-b232-7c1b15356337
