### ISSUE TITLE
Missing AP potion from purchase

### ISSUE THREAD

**Issue by PoohVz** [planetarium/NineChronicles#773]
S1mpleMan#6382 reported that he bought some AP potion in v100075, at first, it didn't seem to go through so he bought few times.
After v100077, he saw his NCG decreased and there are few mails about the AP potion purchase but it's not enough.

Address: 0x6DaD7a3C3Cce31d81B252f12c495B6c255529d69 
![image](https://user-images.githubusercontent.com/13524523/133095214-30b57298-88df-4a9c-80ab-c7ac3ca89de2.png)
![image](https://user-images.githubusercontent.com/13524523/133095234-149bb827-bb66-4afe-957b-c7531f3aaf6d.png)

Tx:

>  {

            "actions": [
              {
                "inspection": "{\n  \"type_id\": \"buy10\",\n  \"values\": {\n    \"ba\": b\"\\xa7\\x3d\\x91\\x8d\\xa6\\xb0\\xfa\\xa5\\xfe\\x0c\\xd9\\xa4\\x74\\x44\\x41\\x53\\xf1\\x3a\\x76\\x29\",\n    \"id\": b\"\\x22\\xdd\\xc7\\x41\\x51\\x5c\\x7b\\x41\\xb6\\x33\\xe6\\x39\\xcb\\x97\\xef\\x2f\",\n    \"pis\": [\n      {\n        \"ist\": \"ApStone\",\n        \"oi\": b\"\\xc9\\xf6\\xbe\\x19\\xc1\\x4b\\x41\\x4f\\xba\\x8f\\x07\\x1c\\x7d\\x5e\\xc7\\x81\",\n        \"p\": [\n          {\n            \"decimalPlaces\": b\"\\x02\",\n            \"minters\": [b\"\\x47\\xd0\\x82\\xa1\\x15\\xc6\\x3e\\x7b\\x58\\xb1\\x53\\x2d\\x20\\xe6\\x31\\x53\\x8e\\xaf\\xad\\xde\"],\n            \"ticker\": \"NCG\"\n          },\n          1000\n        ],\n        \"sga\": b\"\\xd7\\xc7\\xb9\\xc2\\xaf\\x56\\x9a\\x24\\x90\\x7e\\xfd\\xfa\\x6f\\x38\\xe6\\xa2\\x8a\\x08\\x00\\x7b\",\n        \"sva\": b\"\\x35\\x37\\xdd\\x42\\x50\\x87\\x5c\\x5c\\xaa\\xe4\\x62\\x8e\\x4e\\x1a\\xe0\\x15\\xec\\x4a\\x9d\\x8b\",\n        \"ti\": b\"\\xbd\\x88\\x05\\xcb\\x20\\x1c\\x60\\x5b\\x82\\x11\\xc6\\xe4\\xf5\\xb8\\xa0\\x71\"\n      }\n    ]\n  }\n}"
              }
            ],
            "timestamp": "2021-09-13T02:44:58.370905+00:00",
            "id": "4f28dd666e356c017bfafd76710e5be27802de5c90835908823245dac13d24cd"
          },
          {
            "actions": [
              {
                "inspection": "{\n  \"type_id\": \"buy10\",\n  \"values\": {\n    \"ba\": b\"\\xa7\\x3d\\x91\\x8d\\xa6\\xb0\\xfa\\xa5\\xfe\\x0c\\xd9\\xa4\\x74\\x44\\x41\\x53\\xf1\\x3a\\x76\\x29\",\n    \"id\": b\"\\x02\\x6c\\x0f\\xa2\\xd2\\xf3\\x3d\\x4e\\x9f\\xa7\\x1c\\x91\\x3e\\xe1\\x93\\xa7\",\n    \"pis\": [\n      {\n        \"ist\": \"ApStone\",\n        \"oi\": b\"\\xa5\\xeb\\xad\\xb1\\xca\\x78\\x05\\x4d\\xa6\\x59\\xa0\\x95\\x94\\x40\\xf4\\x47\",\n        \"p\": [\n          {\n            \"decimalPlaces\": b\"\\x02\",\n            \"minters\": [b\"\\x47\\xd0\\x82\\xa1\\x15\\xc6\\x3e\\x7b\\x58\\xb1\\x53\\x2d\\x20\\xe6\\x31\\x53\\x8e\\xaf\\xad\\xde\"],\n            \"ticker\": \"NCG\"\n          },\n          10000\n        ],\n        \"sga\": b\"\\xaa\\x6b\\x08\\xf0\\xc3\\x4f\\xc8\\xc2\\xe5\\x94\\x1e\\x23\\x41\\x6d\\x2d\\x48\\xe1\\x4f\\x58\\x34\",\n        \"sva\": b\"\\x70\\x9e\\x5b\\xf0\\x82\\x3d\\xf4\\xdd\\xff\\x76\\xa1\\x1a\\x65\\x85\\xd1\\x46\\x3e\\x9d\\xc9\\xf8\",\n        \"ti\": b\"\\xbd\\x88\\x05\\xcb\\x20\\x1c\\x60\\x5b\\x82\\x11\\xc6\\xe4\\xf5\\xb8\\xa0\\x71\"\n      }\n    ]\n  }\n}"
              }
            ],
            "timestamp": "2021-09-13T02:44:39.722731+00:00",
            "id": "8687758d2f0abcb067d0b9b85c96ab637fa585555052f273c355093e8567db24"
          },
          {
            "actions": [
              {
                "inspection": "{\n  \"type_id\": \"buy10\",\n  \"values\": {\n    \"ba\": b\"\\xa7\\x3d\\x91\\x8d\\xa6\\xb0\\xfa\\xa5\\xfe\\x0c\\xd9\\xa4\\x74\\x44\\x41\\x53\\xf1\\x3a\\x76\\x29\",\n    \"id\": b\"\\xf4\\x3a\\x51\\xf3\\x29\\xe8\\x5a\\x46\\x86\\x62\\x9c\\x6d\\x5b\\x47\\x1b\\x27\",\n    \"pis\": [\n      {\n        \"ist\": \"ApStone\",\n        \"oi\": b\"\\xe8\\xec\\xe1\\xc2\\x71\\x39\\xe2\\x4e\\x8b\\xe9\\x70\\x0f\\xfc\\x52\\x88\\xbe\",\n        \"p\": [\n          {\n            \"decimalPlaces\": b\"\\x02\",\n            \"minters\": [b\"\\x47\\xd0\\x82\\xa1\\x15\\xc6\\x3e\\x7b\\x58\\xb1\\x53\\x2d\\x20\\xe6\\x31\\x53\\x8e\\xaf\\xad\\xde\"],\n            \"ticker\": \"NCG\"\n          },\n          10000\n        ],\n        \"sga\": b\"\\xaa\\x6b\\x08\\xf0\\xc3\\x4f\\xc8\\xc2\\xe5\\x94\\x1e\\x23\\x41\\x6d\\x2d\\x48\\xe1\\x4f\\x58\\x34\",\n        \"sva\": b\"\\x70\\x9e\\x5b\\xf0\\x82\\x3d\\xf4\\xdd\\xff\\x76\\xa1\\x1a\\x65\\x85\\xd1\\x46\\x3e\\x9d\\xc9\\xf8\",\n        \"ti\": b\"\\xbd\\x88\\x05\\xcb\\x20\\x1c\\x60\\x5b\\x82\\x11\\xc6\\xe4\\xf5\\xb8\\xa0\\x71\"\n      }\n    ]\n  }\n}"
              }
            ],
            "timestamp": "2021-09-13T02:44:34.936344+00:00",
            "id": "492bcc18543cfdaee707cae7577a7cd234b4c32a65d8f56752265097713122e3"
          },
          {
            "actions": [
              {
                "inspection": "{\n  \"type_id\": \"buy10\",\n  \"values\": {\n    \"ba\": b\"\\xa7\\x3d\\x91\\x8d\\xa6\\xb0\\xfa\\xa5\\xfe\\x0c\\xd9\\xa4\\x74\\x44\\x41\\x53\\xf1\\x3a\\x76\\x29\",\n    \"id\": b\"\\x27\\xd9\\x1c\\x52\\x8a\\x21\\xce\\x4c\\x88\\xbd\\xd7\\x89\\x01\\x3c\\xef\\x07\",\n    \"pis\": [\n      {\n        \"ist\": \"ApStone\",\n        \"oi\": b\"\\x0e\\xbb\\x5d\\x5d\\x61\\x28\\xff\\x42\\x9f\\xfe\\xcb\\x5c\\x19\\x9b\\x66\\xf7\",\n        \"p\": [\n          {\n            \"decimalPlaces\": b\"\\x02\",\n            \"minters\": [b\"\\x47\\xd0\\x82\\xa1\\x15\\xc6\\x3e\\x7b\\x58\\xb1\\x53\\x2d\\x20\\xe6\\x31\\x53\\x8e\\xaf\\xad\\xde\"],\n            \"ticker\": \"NCG\"\n          },\n          1000\n        ],\n        \"sga\": b\"\\xd7\\xc7\\xb9\\xc2\\xaf\\x56\\x9a\\x24\\x90\\x7e\\xfd\\xfa\\x6f\\x38\\xe6\\xa2\\x8a\\x08\\x00\\x7b\",\n        \"sva\": b\"\\x35\\x37\\xdd\\x42\\x50\\x87\\x5c\\x5c\\xaa\\xe4\\x62\\x8e\\x4e\\x1a\\xe0\\x15\\xec\\x4a\\x9d\\x8b\",\n        \"ti\": b\"\\xbd\\x88\\x05\\xcb\\x20\\x1c\\x60\\x5b\\x82\\x11\\xc6\\xe4\\xf5\\xb8\\xa0\\x71\"\n      }\n    ]\n  }\n}"
              }
            ],
            "timestamp": "2021-09-13T02:44:30.364901+00:00",
            "id": "2270e10acd092eb6ade07ef5e165657936123e15b56a2d176581baea0fef9595"
          },
          {
            "actions": [
              {
                "inspection": "{\n  \"type_id\": \"buy10\",\n  \"values\": {\n    \"ba\": b\"\\xa7\\x3d\\x91\\x8d\\xa6\\xb0\\xfa\\xa5\\xfe\\x0c\\xd9\\xa4\\x74\\x44\\x41\\x53\\xf1\\x3a\\x76\\x29\",\n    \"id\": b\"\\xaf\\x7b\\xe3\\x36\\xc7\\xc3\\x7d\\x4b\\xa8\\x40\\x41\\x3d\\x00\\x99\\xdb\\x39\",\n    \"pis\": [\n      {\n        \"ist\": \"ApStone\",\n        \"oi\": b\"\\x3c\\x07\\xbb\\x80\\xb7\\x44\\xe9\\x40\\xb8\\x38\\x7f\\x03\\x99\\xc4\\x4a\\xe1\",\n        \"p\": [\n          {\n            \"decimalPlaces\": b\"\\x02\",\n            \"minters\": [b\"\\x47\\xd0\\x82\\xa1\\x15\\xc6\\x3e\\x7b\\x58\\xb1\\x53\\x2d\\x20\\xe6\\x31\\x53\\x8e\\xaf\\xad\\xde\"],\n            \"ticker\": \"NCG\"\n          },\n          3500\n        ],\n        \"sga\": b\"\\xbb\\x2e\\x97\\x52\\xc6\\x6b\\x90\\x9a\\x31\\xca\\x8d\\xb1\\x99\\x27\\xe0\\x27\\x49\\xd4\\x51\\x57\",\n        \"sva\": b\"\\xb4\\xf6\\xc2\\xd6\\x29\\xd2\\x87\\xd0\\xee\\x8a\\xb8\\x47\\xb5\\xee\\x57\\x61\\xec\\x53\\x0e\\x4d\",\n        \"ti\": b\"\\xbd\\x88\\x05\\xcb\\x20\\x1c\\x60\\x5b\\x82\\x11\\xc6\\xe4\\xf5\\xb8\\xa0\\x71\"\n      }\n    ]\n  }\n}"
              }
            ],
            "timestamp": "2021-09-13T02:44:19.455137+00:00",
            "id": "43f0c152a2c3d2947b955760d790344f3e80758f9148e2883724e50180b95914"
          },
          {
            "actions": [
              {
                "inspection": "{\n  \"type_id\": \"buy10\",\n  \"values\": {\n    \"ba\": b\"\\xa7\\x3d\\x91\\x8d\\xa6\\xb0\\xfa\\xa5\\xfe\\x0c\\xd9\\xa4\\x74\\x44\\x41\\x53\\xf1\\x3a\\x76\\x29\",\n    \"id\": b\"\\x7e\\xae\\x3a\\x0a\\x4f\\x88\\xb5\\x4c\\x96\\xba\\xd5\\x4c\\xda\\x82\\xf0\\xde\",\n    \"pis\": [\n      {\n        \"ist\": \"ApStone\",\n        \"oi\": b\"\\x65\\x75\\x5f\\x9b\\xbb\\xf9\\x71\\x45\\x88\\x75\\xd8\\x29\\x15\\x6e\\x83\\xa9\",\n        \"p\": [\n          {\n            \"decimalPlaces\": b\"\\x02\",\n            \"minters\": [b\"\\x47\\xd0\\x82\\xa1\\x15\\xc6\\x3e\\x7b\\x58\\xb1\\x53\\x2d\\x20\\xe6\\x31\\x53\\x8e\\xaf\\xad\\xde\"],\n            \"ticker\": \"NCG\"\n          },\n          3500\n        ],\n        \"sga\": b\"\\xbb\\x2e\\x97\\x52\\xc6\\x6b\\x90\\x9a\\x31\\xca\\x8d\\xb1\\x99\\x27\\xe0\\x27\\x49\\xd4\\x51\\x57\",\n        \"sva\": b\"\\xb4\\xf6\\xc2\\xd6\\x29\\xd2\\x87\\xd0\\xee\\x8a\\xb8\\x47\\xb5\\xee\\x57\\x61\\xec\\x53\\x0e\\x4d\",\n        \"ti\": b\"\\xbd\\x88\\x05\\xcb\\x20\\x1c\\x60\\x5b\\x82\\x11\\xc6\\xe4\\xf5\\xb8\\xa0\\x71\"\n      }\n    ]\n  }\n}"
              }
            ],
            "timestamp": "2021-09-13T02:44:04.671806+00:00",
            "id": "ed23f9e0366a6eef3e47d33b3991e98b6f7b5203291b2703c10070076eb3e020"
          }
        ]
      }
    }
  },

**Comment by Namyujeong** [comment]
@PoohVz Transaction investigation completed.

It's true that only 3 out of 6 were purchased.
However, gold was deducted only for 3 cases. There was no gold deduction for failed purchases. (100NCG 1, 10 NCG 2, total 120 NCG)

Two of the three failed purchases were because someone else bought the potion first.
In the other case, the cause is not precisely understood, but the gold was not deducted either.
There is a possibility that you have already tried to purchase while the previous gold has not been deducted at the time when you already have about 50NCG left.
(In the previous build, there were frequent errors about total gold and AP, so we implemented a patch that removed the local layer processing.)

We show this to the player with a one-line popup when a purchase fails.
However, users may overlook this.
We plan to improve this in the future with the transaction history feature.

![image](https://user-images.githubusercontent.com/41294407/133380122-b04376f8-d713-4d72-8eec-f39b0b5dfc99.png)
![image](https://user-images.githubusercontent.com/41294407/133380138-d45b13f8-c956-4819-9942-5e6f204ff62d.png)

**Comment by PoohVz** [comment]
Thanks @Namyujeong , I will let him know
