### ISSUE TITLE
Missing characters/account reset

### ISSUE THREAD

**Issue by PoohVz** [planetarium/NineChronicles#777]
There are reports after the update, characters go missing or accounts completely reset. NCG is still there but nothing else.
![image](https://user-images.githubusercontent.com/13524523/133127265-ff2b7fe9-8ca5-4432-a54c-7d9592e496e6.png)

bozz | FACINGS#7725
Address: 0x16B1974640544eF8a1E3e86530a1A61930bD5901
https://cdn.discordapp.com/attachments/582156664283594753/887022740509437972/ncg.zip

**Comment by PoohVz** [comment]
Trihkal0#2812
0x3CB3AB32109AcA06BC9470d8774B91887EAABb82
https://cdn.discordapp.com/attachments/653951482395361301/887025434003406878/logs.rar

**Comment by longfin** [comment]
```graphql
query
{
  stateQuery
  {
    agent(address: "0x16B1974640544eF8a1E3e86530a1A61930bD5901")
    {
      avatarStates
      {
        name
        level
        inventory
        {
          equipments
          {
            id
          }
        }
      }
    }
  }
}
```

it relates to https://github.com/planetarium/lib9c/pull/618

**Comment by PoohVz** [comment]
Is it 2 different query?
![image](https://user-images.githubusercontent.com/13524523/133365244-dcf9895d-cf1b-4518-b2ad-423561863208.png)

**Comment by PoohVz** [comment]
BlackFeign#4853
0x9d03941Dee022B1C4EA8cE86b8B2c6102F02c8Fb
https://cdn.discordapp.com/attachments/653951482395361301/887579890344427580/New_WinRAR_ZIP_archive.zip

**Comment by longfin** [comment]
We should send a recovery transaction. I'll send it within this week.

**Comment by longfin** [comment]
Recovery tx had been applied.

0x3CB3AB32109AcA06BC9470d8774B91887EAABb82
![image](https://user-images.githubusercontent.com/128436/137483292-554e278f-172d-446a-a049-08f41ccfe6f1.png)

0x16B1974640544eF8a1E3e86530a1A61930bD5901
![image](https://user-images.githubusercontent.com/128436/137483352-c6a76d95-7515-4362-a0ce-a44cd43e966b.png)
