### ISSUE TITLE
GraphQL hackandslash

### ISSUE THREAD

**Issue by NicuTheodorAlexandru** [planetarium/NineChronicles#816]
The hackandslash graphql api action mutation doesn't accept a rankingMapAddress argument and the api backend seems to send an address filled with 0s instead of getting the correct rankingMapAddress from the avatar address.

**Comment by longfin** [comment]
@NicuTheodorAlexandru Thanks for reporting. this issue has been addressed by https://github.com/planetarium/NineChronicles.Headless/pull/725 and it will be released as v100079.
