### ISSUE TITLE
Getting Buyer State by providing OrderID

### ISSUE THREAD

**Issue by osamadeep** [planetarium/NineChronicles#867]
i notice that you can see the player who bought your item when it happens, but is there anyway to reach the buyer address by providing only the OrderId?

**Comment by osamadeep** [comment]
thank you @boscohyun for reply, I try to use it but there is a lot of missing reference, can you please describe how to use?

**Comment by boscohyun** [comment]
Can I get the list of missing references?
Maybe the `Agent.GetState()` is to be `Game.Game.instance.Agent.GetState()`.

**Comment by osamadeep** [comment]
[Showing info in mail](https://im.ge/i/oN4Xjq)
I am trying to get the buyer name in mail system, 
https://github.com/planetarium/NineChronicles/blob/development/nekoyume/Assets/_Scripts/Extension/LocalizationExtension.cs#L119

`                
case OrderBuyerMail orderBuyerMail:
                    var buyerItemName = Util.GetItemNameByOrdierId(orderBuyerMail.OrderId, true);
                    //|||||||||||||| PANDORA START CODE |||||||||||||||||||
                    string x1 = "";
                    var order1 = Util.GetOrder(orderBuyerMail.OrderId);
                    if (States.TryGetAvatarState(order1.SellerAvatarAddress, out var avatarState1))
                    {
                        x1 = $"[<color=green><size=70%>{orderBuyerMail.blockIndex}</size></color>] Spent <color=red>-{order1.Price}</color> for {buyerItemName}" +
                            $" from {avatarState1.NameWithHash}";
                        return x1;
                    }//|||||||||||||| PANDORA  END  CODE |||||||||||||||||||
                    else
                        return string.Format(L10nManager.Localize("UI_BUYER_MAIL_FORMAT"),
                        buyerItemName);

                case OrderSellerMail orderSellerMail:
                    var order = Util.GetOrder(orderSellerMail.OrderId);
                    var sellerItemName = Util.GetItemNameByOrdierId(orderSellerMail.OrderId, true);
                    var taxedPrice = order.Price - order.GetTax();
                    //|||||||||||||| PANDORA START CODE |||||||||||||||||||
                    string x = "";

                    if (States.TryGetAvatarState(order.SellerAvatarAddress, out var avatarState))
                    {
                        x = $"[<color=green><size=70%>{orderSellerMail.blockIndex}</size></color>] Got <color=green>+{taxedPrice}</color> for your {sellerItemName}";
                        return x;
                    }//|||||||||||||| PANDORA  END  CODE |||||||||||||||||||
                    else
                        return string.Format(L10nManager.Localize("UI_SELLER_MAIL_FORMAT"), taxedPrice, sellerItemName);
`

putting TryGetBuyerAvatarAddress in this file give me almost 10 reference check
