### ISSUE TITLE
Game crashes when shutdown

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles#987]
# Environment
- v100087
- in RPC mode

# Steps to reproduce
- Launch the game through the game launcher
- Execute battle(`HackAndSlash`) once (or more?)
- Close 9c.exe

# Excpected behavior
- 9c.exe should be turned off without any error

# Actual behavior
![image](https://user-images.githubusercontent.com/128436/143173406-890768ce-52d1-4662-9d43-2d9847fb8e53.png)

[Player.log](https://github.com/planetarium/NineChronicles/files/7592666/Player.log)

**Comment by ipdae** [comment]
https://github.com/Cysharp/MagicOnion#grpc-channel-management-integration-for-unity

**Comment by ipdae** [comment]
I think we found a hit for solving the problem. in test, crash was not reproduced when disable [RankLoadingTask](https://github.com/planetarium/NineChronicles/blob/rc-v100089/nekoyume/Assets/_Scripts/UI/Widget/Popup/RankPopup.cs#L40). this task calls GetStateAsync internally, and this is may occur crash when dispose rpc client.
